Repository ocaml/opam-repository, pull requests merged in 2018-06, with the labels that each got.

#12084 herdtools7.7.50 - via opam-publish
  packages/herdtools7/herdtools7.7.50/descr
  packages/herdtools7/herdtools7.7.50/opam
  packages/herdtools7/herdtools7.7.50/url
Labels: consider for merge, question

#12094 Frama-C 17 Chlorine 20180501
  packages/frama-c/frama-c.20180501/descr
  packages/frama-c/frama-c.20180501/files/run_autoconf_if_needed.sh
  packages/frama-c/frama-c.20180501/opam
  packages/frama-c/frama-c.20180501/url
  packages/pilat/pilat.1.1/opam
Labels: needs reporter action

#12093 added packages/acpc/acpc.1.2.3
  packages/acpc/acpc.1.2.3/descr
  packages/acpc/acpc.1.2.3/opam
  packages/acpc/acpc.1.2.3/url
Labels: needs reporter action

#12118 Package glicko2.1.0.0
  packages/glicko2/glicko2.1.0.0/descr
  packages/glicko2/glicko2.1.0.0/opam
  packages/glicko2/glicko2.1.0.0/url
Labels: needs reporter action

#12116 Package ocaml-monadic.0.4.0
  packages/jhupllib/jhupllib.0.1.1/url
  packages/jhupllib/jhupllib.0.1/url
  packages/ocaml-monadic/ocaml-monadic.0.4.0/descr
  packages/ocaml-monadic/ocaml-monadic.0.4.0/opam
  packages/ocaml-monadic/ocaml-monadic.0.4.0/url
  packages/pds-reachability/pds-reachability.0.2.1/opam
  packages/pds-reachability/pds-reachability.0.2.1/url
Labels: needs reporter action

#12096 Package pilat.1.2
  packages/pilat/pilat.1.2/descr
  packages/pilat/pilat.1.2/opam
  packages/pilat/pilat.1.2/url
Labels: consider for merge, question

#12130 Package ocaml-r.0.1.0
  packages/ocaml-r/ocaml-r.0.1.0/descr
  packages/ocaml-r/ocaml-r.0.1.0/opam
  packages/ocaml-r/ocaml-r.0.1.0/url
Labels: needs reporter action

#12143 [new release] irmin (1.4.0)
  packages/datakit/datakit.0.11.0/opam
  packages/datakit/datakit.0.12.0/opam
  packages/irmin-git/irmin-git.1.1.0/opam
  packages/irmin-git/irmin-git.1.2.0/opam
  packages/irmin/irmin.1.4.0/descr
  packages/irmin/irmin.1.4.0/opam
  packages/irmin/irmin.1.4.0/url
Labels: needs reporter action

#12063 Add Vimebac 0.0.0
  packages/vimebac/vimebac.0.0.0/descr
  packages/vimebac/vimebac.0.0.0/opam
  packages/vimebac/vimebac.0.0.0/url
Labels: needs reporter action

#12115 New minor release of the web programming language Links, version 0.7.3.
  packages/links-postgresql/links-postgresql.0.7.3/descr
  packages/links-postgresql/links-postgresql.0.7.3/opam
  packages/links-postgresql/links-postgresql.0.7.3/url
  packages/links/links.0.7.3/descr
  packages/links/links.0.7.3/opam
  packages/links/links.0.7.3/url
Labels: question

#12092 added acpc.1.1.1
  packages/acpc/acpc.1.1.1/descr
  packages/acpc/acpc.1.1.1/opam
  packages/acpc/acpc.1.1.1/url
Labels: needs reporter action

#12217 Heptagon version 1.05.00
  packages/heptagon/heptagon.1.05.00/url
Labels: question

#12223 Package omod.0.0.2
  packages/omod/omod.0.0.2/descr
  packages/omod/omod.0.0.2/opam
  packages/omod/omod.0.0.2/url
Labels: needs admin action

#12233 Add irc-client.0.6.0
  packages/calculon/calculon.0.1/opam
  packages/calculon/calculon.0.2/opam
  packages/irc-client-lwt/irc-client-lwt.0.6.0/descr
  packages/irc-client-lwt/irc-client-lwt.0.6.0/opam
  packages/irc-client-lwt/irc-client-lwt.0.6.0/url
  packages/irc-client-tls/irc-client-tls.0.6.0/descr
  packages/irc-client-tls/irc-client-tls.0.6.0/opam
  packages/irc-client-tls/irc-client-tls.0.6.0/url
  packages/irc-client-unix/irc-client-unix.0.6.0/descr
  packages/irc-client-unix/irc-client-unix.0.6.0/opam
  packages/irc-client-unix/irc-client-unix.0.6.0/url
  packages/irc-client/irc-client.0.6.0/descr
  packages/irc-client/irc-client.0.6.0/opam
  packages/irc-client/irc-client.0.6.0/url
Labels: needs reporter action

#12229 merlin v3.1.0
  packages/merlin/merlin.3.1.0/descr
  packages/merlin/merlin.3.1.0/opam
  packages/merlin/merlin.3.1.0/url
Labels: needs reporter action
