Repository ocaml/opam-repository, pull requests merged in 2018-09, with the labels that each got.

#12553 [frama-c] blacklist incompatible why3 version
  packages/frama-c/frama-c.20171101/opam
  packages/frama-c/frama-c.20180501/opam
  packages/frama-c/frama-c.20180502/opam
Labels: needs reporter action

#12551 Add mkaudio.1.1.0
  packages/mkaudio/mkaudio.1.1.0/descr
  packages/mkaudio/mkaudio.1.1.0/opam
  packages/mkaudio/mkaudio.1.1.0/url
Labels: consider for merge

#12528 Package orpie.1.6.0
  packages/orpie/orpie.1.6.0/descr
  packages/orpie/orpie.1.6.0/opam
  packages/orpie/orpie.1.6.0/url
Labels: consider for merge

#12533 wcs-ocaml version 2017-05-26.05
  packages/wcs-lib/wcs-lib.2017-05-26.05/descr
  packages/wcs-lib/wcs-lib.2017-05-26.05/opam
  packages/wcs-lib/wcs-lib.2017-05-26.05/url
  packages/wcs/wcs.2017-05-26.05/descr
  packages/wcs/wcs.2017-05-26.05/opam
  packages/wcs/wcs.2017-05-26.05/url
Labels: needs reporter action

#12547 [ppx-import] Release supporting OCaml 4.07.0
  packages/ppx_import/ppx_import.1.5/descr
  packages/ppx_import/ppx_import.1.5/opam
  packages/ppx_import/ppx_import.1.5/url
Labels: needs maintainer action

#12583 Add bitstring v3.1.0
  packages/bitstring/bitstring.3.1.0/descr
  packages/bitstring/bitstring.3.1.0/opam
  packages/bitstring/bitstring.3.1.0/url
Labels: needs reporter action

#12581 ocamlbuild: constraint ocaml-version to 4.07
  packages/ocamlbuild/ocamlbuild.0.11.0/opam
  packages/ocamlbuild/ocamlbuild.0.12.0/opam
  packages/ocamlbuild/ocamlbuild.0.9.1/opam
  packages/ocamlbuild/ocamlbuild.0.9.2/opam
  packages/ocamlbuild/ocamlbuild.0.9.3/opam
Labels: needs reporter action

#12602 Add (safe-string compatible) ledit 2.04 and make ledit 2.03 explicitly not safe string
  packages/ledit/ledit.2.03/opam
  packages/ledit/ledit.2.04/descr
  packages/ledit/ledit.2.04/files/ledit.install
  packages/ledit/ledit.2.04/opam
  packages/ledit/ledit.2.04/url
Labels: needs reporter action

#12604 [new release] core (v0.11.3)
  packages/async_extra/async_extra.v0.11.0/opam
  packages/core/core.v0.11.3/descr
  packages/core/core.v0.11.3/opam
  packages/core/core.v0.11.3/url
  packages/email_message/email_message.v0.11.0/opam
Labels: needs reporter action

#12622 [new release] dune (1.2.0)
  packages/dune/dune.1.2.0/descr
  packages/dune/dune.1.2.0/opam
  packages/dune/dune.1.2.0/url
Labels: needs reporter action

#12641 [new release] dune (1.2.1)
  packages/dune/dune.1.2.1/descr
  packages/dune/dune.1.2.1/opam
  packages/dune/dune.1.2.1/url
Labels: consider for merge

#12637 releases: tcpip.3.5.0 mirage-qubes{-ipv4}.0.6 charrua{-core,-client,-client-lwt,-client-mirage,-unix}.0.10
  packages/charrua-client-lwt/charrua-client-lwt.0.10/descr
  packages/charrua-client-lwt/charrua-client-lwt.0.10/opam
  packages/charrua-client-lwt/charrua-client-lwt.0.10/url
  packages/charrua-client-mirage/charrua-client-mirage.0.10/descr
  packages/charrua-client-mirage/charrua-client-mirage.0.10/opam
  packages/charrua-client-mirage/charrua-client-mirage.0.10/url
  packages/charrua-client/charrua-client.0.10/descr
  packages/charrua-client/charrua-client.0.10/opam
  packages/charrua-client/charrua-client.0.10/url
  packages/charrua-core/charrua-core.0.10/descr
  packages/charrua-core/charrua-core.0.10/opam
  packages/charrua-core/charrua-core.0.10/url
  packages/charrua-unix/charrua-unix.0.10/descr
  packages/charrua-unix/charrua-unix.0.10/opam
  packages/charrua-unix/charrua-unix.0.10/url
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.6/descr
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.6/opam
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.6/url
  packages/mirage-qubes/mirage-qubes.0.6/descr
  packages/mirage-qubes/mirage-qubes.0.6/opam
  packages/mirage-qubes/mirage-qubes.0.6/url
  packages/tcpip/tcpip.3.5.0/descr
  packages/tcpip/tcpip.3.5.0/opam
  packages/tcpip/tcpip.3.5.0/url
Labels: needs reporter action

#12626 Release Links 0.8 (Merchiston)
  packages/links-postgresql/links-postgresql.0.8/descr
  packages/links-postgresql/links-postgresql.0.8/opam
  packages/links-postgresql/links-postgresql.0.8/url
  packages/links/links.0.8/descr
  packages/links/links.0.8/opam
  packages/links/links.0.8/url
Labels: consider for merge, question

#12613 Package teash.0.1.0
  packages/teash/teash.0.1.0/descr
  packages/teash/teash.0.1.0/opam
  packages/teash/teash.0.1.0/url
Labels: question

#12627 +Tuareg 2.2.0
  packages/tuareg/tuareg.2.2.0/opam
Labels: needs reporter action

#12594 [new release] ppxlib (0.3.1)
  packages/ppxlib/ppxlib.0.3.1/descr
  packages/ppxlib/ppxlib.0.3.1/opam
  packages/ppxlib/ppxlib.0.3.1/url
Labels: needs reporter action

#12518 Release caqti.1.0.0
  packages/caqti-async/caqti-async.1.0.0/opam
  packages/caqti-driver-mariadb/caqti-driver-mariadb.1.0.0/opam
  packages/caqti-driver-postgresql/caqti-driver-postgresql.1.0.0/opam
  packages/caqti-driver-sqlite3/caqti-driver-sqlite3.1.0.0/opam
  packages/caqti-dynload/caqti-dynload.1.0.0/opam
  packages/caqti-lwt/caqti-lwt.1.0.0/opam
  packages/caqti-type-calendar/caqti-type-calendar.1.0.0/opam
  packages/caqti/caqti.1.0.0/opam
Labels: needs reporter action

#12663 Package morbig.0.9
  packages/morbig/morbig.0.9/opam
Labels: question

#12645 4 packages from c-cube/qcheck at 0.9
  packages/qcheck-alcotest/qcheck-alcotest.0.9/opam
  packages/qcheck-core/qcheck-core.0.9/opam
  packages/qcheck-ounit/qcheck-ounit.0.9/opam
  packages/qcheck/qcheck.0.9/opam
Labels: consider for merge

#12669 3.07+1 and 3.07+2 were official releases
  packages/ocaml-base-compiler/ocaml-base-compiler.3.07+1/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.3.07+2/opam
  packages/ocaml-system/ocaml-system.3.07+1/files/gen_ocaml_config.ml.in
  packages/ocaml-system/ocaml-system.3.07+1/opam
  packages/ocaml-system/ocaml-system.3.07+2/files/gen_ocaml_config.ml.in
  packages/ocaml-system/ocaml-system.3.07+2/opam
  packages/ocaml/ocaml.3.07+1/files/gen_ocaml_config.ml.in
  packages/ocaml/ocaml.3.07+1/opam
  packages/ocaml/ocaml.3.07+2/files/gen_ocaml_config.ml.in
  packages/ocaml/ocaml.3.07+2/opam
Labels: consider for merge

#12687 [new release] mdx (1.0.0)
  packages/mdx/mdx.1.0.0/opam
Labels: needs reporter action

#12671 add compiler packages for ocaml 4.07.1+rc1
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1+32bit/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1+afl/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1+default-unsafe-string/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1+flambda+no-flat-float-array/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1+force-safe-string/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1+fp+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1+fp/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+rc1/opam
  packages/ocaml/ocaml.4.07.1/files/gen_ocaml_config.ml.in
  packages/ocaml/ocaml.4.07.1/opam
Labels: needs reporter action

#12665 added packages/conf-g++/conf-g++.1.0
  packages/conf-g++/conf-g++.1.0/opam
Labels: question

#12675 Adding ppx_relit 0.1 and relit_helper 0.1
  packages/ppx_relit/ppx_relit.0.1/opam
  packages/relit-reason/relit-reason.0.0.1/opam
  packages/relit_helper/relit_helper.0.1/opam
Labels: needs reporter action

#12666 added packages/oranger/oranger.0.9.11
  packages/oranger/oranger.0.9.11/files/compile_ranger.sh
  packages/oranger/oranger.0.9.11/opam
Labels: needs reporter action

#12702 open 0.2.2
  packages/open/open.0.2.2/opam
Labels: needs reporter action

#12610 Add piqilib-0.6.14 and piqi-0.7.6
  packages/piqi/piqi.0.7.6/opam
  packages/piqilib/piqilib.0.6.14/opam
Labels: needs reporter action

#12404 Eliom: do not allow js_of_ocaml-lwt.3.2.0 (buggy)
  packages/eliom/eliom.6.3.0/opam
Labels: needs reporter action
