Repository ocaml/opam-repository, pull requests merged in 2018-11, with the labels that each got.

#12891 Package tldr.0.1
  packages/tldr/tldr.0.1/opam
Labels: needs reporter action

#12920 add +spacetime switches for 4.07.*
  packages/ocaml-variants/ocaml-variants.4.07.0+spacetime/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+spacetime/opam
Labels: consider for merge

#12903 3 packages from cyrus-/relit at 0.2.0
  packages/ppx_relit/ppx_relit.0.2.0/opam
  packages/relit-reason/relit-reason.0.0.2/opam
  packages/relit_helper/relit_helper.0.2.0/opam
Labels: needs reporter action

#12911 [new release] electrod (0.2.1)
  packages/electrod/electrod.0.2.1/opam
Labels: needs reporter action

#12922 [new release] bwrap (0.1)
  packages/bwrap/bwrap.0.1/opam
Labels: consider for merge

#12933 omd.2.0.0.alpha
  packages/omd/omd.2.0.0~alpha
Labels: needs reporter action

#12918 cohttp-lwt{,-jsoo}: add missing sexplib dependency
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.1.1.1/opam
  packages/cohttp-lwt/cohttp-lwt.1.1.1/opam
Labels: consider for merge

#12950 Solo5: Release 0.4.1, various Mirage/Solo5 updates
  packages/mirage-block-solo5/mirage-block-solo5.0.4.0/opam
  packages/mirage-net-solo5/mirage-net-solo5.0.4.0/opam
  packages/mirage-solo5/mirage-solo5.0.5.0/opam
  packages/ocaml-freestanding/ocaml-freestanding.0.4.2/opam
  packages/solo5-bindings-genode/solo5-bindings-genode.0.4.1/opam
  packages/solo5-bindings-hvt/solo5-bindings-hvt.0.4.1/opam
  packages/solo5-bindings-muen/solo5-bindings-muen.0.4.1/opam
  packages/solo5-bindings-virtio/solo5-bindings-virtio.0.4.1/opam
Labels: needs reporter action

#12962 [new release] ocal (0.2.2)
  packages/ocal/ocal.0.2.2/opam
Labels: consider for merge

#12972 Package ppx_fast_pipe.0.0.1
  packages/ppx_fast_pipe/ppx_fast_pipe.0.0.1/opam
Labels: consider for merge

#12997 [new release] mdx (1.1.0)
  packages/mdx/mdx.1.1.0/opam
Labels: consider for merge

#13020 Fix error 31
  packages/amqp-client/amqp-client.1.0.1/opam
  packages/frenetic/frenetic.2.0.0/opam
  packages/frenetic/frenetic.3.0.0/opam
  packages/frenetic/frenetic.3.1.0/opam
  packages/libres3/libres3.0.2/opam
  packages/libres3/libres3.0.3/opam
  packages/ocamlnet/ocamlnet.3.5.1/opam
Labels: question

#13009 added packages/orsvm_e1071/orsvm_e1071.3.0.1
  packages/orsvm_e1071/orsvm_e1071.3.0.1/opam
Labels: needs reporter action

#13021 Package javalib.3.0
  packages/javalib/javalib.3.0/opam
Labels: needs reporter action

#13058 +flowtype.0.87.0
  packages/flowtype/flowtype.0.87.0/opam
Labels: needs reporter action

#13055 Package obeam.0.1.0
  packages/obeam/obeam.0.1.0/opam
Labels: needs reporter action

#13037 + ubpf 0.1
  packages/ubpf/ubpf.0.1/opam
Labels: needs reporter action
