Repository ocaml/opam-repository, pull requests merged in 2018-10, with the labels that each got.

#12728 [opam2 cleanup] merge descr and url files into opam files
  packages/base-bigarray/base-bigarray.base/descr
  packages/base-bigarray/base-bigarray.base/opam
  packages/base-threads/base-threads.base/descr
  packages/base-threads/base-threads.base/opam
  packages/base-unix/base-unix.base/descr
  packages/base-unix/base-unix.base/opam
  packages/color/color.0.2.0/descr
  packages/color/color.0.2.0/opam
  packages/color/color.0.2.0/url
  packages/jingoo/jingoo.1.2.19/descr
  packages/jingoo/jingoo.1.2.19/opam
  packages/jingoo/jingoo.1.2.20/descr
  packages/jingoo/jingoo.1.2.20/opam
  packages/json_decoder/json_decoder.0.1.1/descr
  packages/json_decoder/json_decoder.0.1.1/opam
  packages/json_decoder/json_decoder.0.1.1/url
  packages/ocaml-migrate-parsetree/ocaml-migrate-parsetree.1.1.0/descr
  packages/ocaml-migrate-parsetree/ocaml-migrate-parsetree.1.1.0/opam
  packages/ocaml-migrate-parsetree/ocaml-migrate-parsetree.1.1.0/url
  packages/ppxlib/ppxlib.0.3.1/descr
  packages/ppxlib/ppxlib.0.3.1/opam
  packages/ppxlib/ppxlib.0.3.1/url
  packages/zeit/zeit.0.1.0/descr
  packages/zeit/zeit.0.1.0/opam
  packages/zeit/zeit.0.1.0/url
Labels: consider for merge

#12746 Package oseq.0.2
  packages/oseq/oseq.0.2/opam
Labels: needs reporter action

#12748 Add diet.0.2
  packages/diet/diet.0.2/opam
Labels: question

#12730 Fix `with-test` filter on depends field
  packages/jingoo/jingoo.1.2.19/opam
  packages/jingoo/jingoo.1.2.20/opam
  packages/oranger/oranger.0.9.11/opam
  packages/piqi/piqi.0.7.6/opam
  packages/ppx_relit/ppx_relit.0.1/opam
  packages/tree_layout/tree_layout.0.1.0/opam
Labels: needs maintainer action

#12706 [new release] eigen 0.0.6 - opam2 compatibility
  packages/eigen/eigen.0.0.6/files/eigen.install
  packages/eigen/eigen.0.0.6/opam
  packages/owl/owl.0.2.2/opam
  packages/owl/owl.0.2.3/opam
  packages/owl/owl.0.2.4/opam
  packages/owl/owl.0.2.5/opam
  packages/owl/owl.0.2.6/opam
Labels: consider for merge

#12750 [camlp5] Support for 4.07.1.
  packages/camlp5/camlp5.7.06.10-g84ce6cc4/files/camlp5.install
  packages/camlp5/camlp5.7.06.10-g84ce6cc4/opam
Labels: consider for merge

#12701 added packages/lbvs_consent/lbvs_consent.2.0.0
  packages/lbvs_consent/lbvs_consent.2.0.0/opam
Labels: needs reporter action

#12771 Package ocamlformat.0.8
  packages/ocamlformat/ocamlformat.0.8/opam
Labels: needs reporter action

#12770 [new release] merlin (3.2.2)
  packages/merlin/merlin.3.2.2/opam
Labels: needs reporter action

#12788 osx-cf: add a missing conflict with lwt
  packages/osx-cf/osx-cf.0.1.0/opam
  packages/osx-cf/osx-cf.0.1.1/opam
Labels: consider for merge

#12786 [new release] docker-api (0.2)
  packages/docker-api/docker-api.0.2/opam
Labels: consider for merge

#12787 Release OCaml Jupyter kernel 2.3.4
  packages/jupyter/jupyter.2.3.4/opam
Labels: consider for merge

#12760 Package rresult.0.6.0
  packages/rresult/rresult.0.6.0/opam
Labels: needs reporter action

#12812 [new release] decompress and rfc1951 (0.8.1)
  packages/decompress/decompress.0.8.1/opam
  packages/rfc1951/rfc1951.0.8.1/opam
Labels: needs reporter action

#12823 New ACGtk releases
  packages/acgtk/acgtk.1.4.0/opam
  packages/acgtk/acgtk.1.5.0/opam
Labels: needs reporter action

#12842 cohttp-async: add missing uri dependency and bounds
  packages/cohttp-async/cohttp-async.0.99.0/opam
  packages/cohttp-async/cohttp-async.1.0.0/opam
  packages/cohttp-async/cohttp-async.1.0.2/opam
  packages/cohttp-async/cohttp-async.1.1.1/opam
  packages/cohttp-async/cohttp-async.1.2.0/opam
Labels: consider for merge

#12736 Support ndbm, bugfix for omake
  packages/conf-dbm/conf-dbm.1.0.0/files/test_gdbm.c
  packages/conf-dbm/conf-dbm.1.0.0/files/test_ndbm.c
  packages/conf-dbm/conf-dbm.1.0.0/opam
  packages/omake/omake.0.10.3/files/lib_build_OCaml.om.diff
  packages/omake/omake.0.10.3/opam
  packages/sequence/sequence.1.1/opam
Labels: question

#12846 Package gg.0.9.3
  packages/gg/gg.0.9.3/opam
Labels: consider for merge

#12889 Package tensorboard.0.0.1
  packages/tensorboard/tensorboard.0.0.1/opam
Labels: needs reporter action

#12810 3 packages from ryanslade/influxdb-ocaml at 0.2.0
  packages/influxdb-async/influxdb-async.0.2.0/opam
  packages/influxdb-lwt/influxdb-lwt.0.2.0/opam
  packages/influxdb/influxdb.0.2.0/opam
Labels: needs reporter action

#12884 [jingoo] release version 1.2.21
  packages/jingoo/jingoo.1.2.21/opam
Labels: needs maintainer action, needs reporter action

#12861 rename all frama-c versions
  packages/frama-c-base/frama-c-base.11.0/opam
  packages/frama-c-base/frama-c-base.12.1/files/wp-ocaml-403.patch
  packages/frama-c-base/frama-c-base.12.1/opam
  packages/frama-c-base/frama-c-base.13.1/files/run_autoconf_if_needed.sh
  packages/frama-c-base/frama-c-base.13.1/opam
  packages/frama-c-base/frama-c-base.14.0/files/4.05-support.patch
  packages/frama-c-base/frama-c-base.14.0/files/run_autoconf_if_needed.sh
  packages/frama-c-base/frama-c-base.14.0/opam
  packages/frama-c-base/frama-c-base.15.0/files/run_autoconf_if_needed.sh
  packages/frama-c-base/frama-c-base.15.0/opam
  packages/frama-c-e-acsl/frama-c-e-acsl.0.5/opam
  packages/frama-c/frama-c.10.0/files/0004-Port-to-OCamlgraph-1.8.5.patch
  packages/frama-c/frama-c.10.0/opam
  packages/frama-c/frama-c.11.0/opam
  packages/frama-c/frama-c.12.1/opam
  packages/frama-c/frama-c.13.1/opam
  packages/frama-c/frama-c.14.0/opam
  packages/frama-c/frama-c.15.0/opam
  packages/frama-c/frama-c.16.0/files/run_autoconf_if_needed.sh
  packages/frama-c/frama-c.16.0/opam
  packages/frama-c/frama-c.17.0/files/run_autoconf_if_needed.sh
  packages/frama-c/frama-c.17.0/opam
  packages/frama-c/frama-c.17.1/files/run_autoconf_if_needed.sh
  packages/frama-c/frama-c.17.1/opam
  packages/frama-c/frama-c.7.0/files/frama-c.install
  packages/frama-c/frama-c.7.0/opam
  packages/frama-c/frama-c.8.0/files/frama-c.install
  packages/frama-c/frama-c.8.0/opam
  packages/frama-c/frama-c.9.0/files/frama-c.install
  packages/frama-c/frama-c.9.0/opam
  packages/frama-c/frama-c.9.1/files/4.01-compat.patch
  packages/frama-c/frama-c.9.1/files/frama-c.install
  packages/frama-c/frama-c.9.1/opam
  packages/pilat/pilat.1.1/opam
  packages/pilat/pilat.1.2/opam
  packages/why/why.2.32/opam
  packages/why/why.2.33/opam
  packages/why/why.2.34/opam
  packages/why/why.2.35/opam
  packages/why/why.2.36/opam
  packages/why/why.2.37/opam
  packages/why/why.2.38/opam
  packages/why/why.2.39/opam
  packages/why/why.2.40/opam
  packages/why/why.2.41/opam
Labels: consider for merge

#12888 ocaml-lua.1.6
  packages/ocaml-lua/ocaml-lua.1.7/opam
Labels: consider for merge

#12853 Package swagger.0.2.0
  packages/swagger/swagger.0.2.0/opam
Labels: needs reporter action
