Repository ocaml/opam-repository, pull requests merged in 2018-12, with the labels that each got.

#13054 jsoo.3.3.0
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.3.3.0/opam
  packages/js_of_ocaml-lwt/js_of_ocaml-lwt.3.3.0/opam
  packages/js_of_ocaml-ppx/js_of_ocaml-ppx.3.3.0/opam
  packages/js_of_ocaml-ppx_deriving_json/js_of_ocaml-ppx_deriving_json.3.3.0/opam
  packages/js_of_ocaml-toplevel/js_of_ocaml-toplevel.3.3.0/opam
  packages/js_of_ocaml-tyxml/js_of_ocaml-tyxml.3.3.0/opam
  packages/js_of_ocaml/js_of_ocaml.3.3.0/opam
  packages/opam2web/opam2web.1.5.0/opam
Labels: help wanted

#13082 charInfo_width 1.1.0
  packages/charInfo_width/charInfo_width.1.1.0/opam
Labels: help wanted, needs reporter action

#13096 Lablgtk3.0.beta1
  packages/conf-gtk3/conf-gtk3.18/opam
  packages/conf-gtksourceview3/conf-gtksourceview3.0/opam
  packages/lablgtk3/lablgtk3.0.beta1/files/lablgtk.install
  packages/lablgtk3/lablgtk3.0.beta1/opam
Labels: needs reporter action

#13046 Add the conf-tensorflow package.
  packages/libtensorflow/libtensorflow.0.1/opam
Labels: help wanted

#13112 +angstrom.0.11.0
  packages/angstrom-async/angstrom-async.0.11.0/opam
  packages/angstrom-lwt-unix/angstrom-lwt-unix.0.11.0/opam
  packages/angstrom-unix/angstrom-unix.0.11.0/opam
  packages/angstrom/angstrom.0.11.0/opam
Labels: needs reporter action

#13127 added packages/minicli/minicli.5.0.0
  packages/minicli/minicli.5.0.0/opam
Labels: consider for merge

#13122 stdcompat.8
  packages/stdcompat/stdcompat.8/opam
Labels: consider for merge

#13119 added packages/bst/bst.6.0.0
  packages/bst/bst.6.0.0/opam
Labels: consider for merge

#13116 [new release] landmarks (1.3)
  packages/landmarks/landmarks.1.3/opam
Labels: consider for merge

#13128 Fix some broken revdeps adding some upper bounds
  packages/angstrom-async/angstrom-async.0.10.0/opam
  packages/angstrom-async/angstrom-async.0.9.0/opam
  packages/angstrom-unix/angstrom-unix.0.10.0/opam
  packages/angstrom-unix/angstrom-unix.0.6.0/opam
  packages/angstrom-unix/angstrom-unix.0.7.0/opam
  packages/angstrom-unix/angstrom-unix.0.8.0/opam
  packages/angstrom-unix/angstrom-unix.0.8.1/opam
  packages/angstrom-unix/angstrom-unix.0.9.0/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.1.0.0/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.1.0.2/opam
  packages/electrod/electrod.0.2.1/opam
  packages/hts_shrink/hts_shrink.1.0.0/opam
Labels: consider for merge

#13139 Package biocaml.0.9.0
  packages/biocaml/biocaml.0.9.0/opam
Labels: consider for merge

#13140 [new release] vchan, vchan-xen and vchan-unix (4.0.0)
  packages/vchan-unix/vchan-unix.4.0.0/opam
  packages/vchan-xen/vchan-xen.4.0.0/opam
  packages/vchan/vchan.4.0.0/opam
Labels: consider for merge

#13135 Add support for Nix openssl package on macOS
  packages/conf-openssl/conf-openssl.1/files/osx-build.sh
  packages/conf-openssl/conf-openssl.1/opam
Labels: needs reporter action

#13144 [new release] decoders, decoders-ezjsonm and decoders-yojson (0.1.1)
  packages/decoders-ezjsonm/decoders-ezjsonm.0.1.1/opam
  packages/decoders-yojson/decoders-yojson.0.1.1/opam
  packages/decoders/decoders.0.1.1/opam
Labels: needs reporter action

#13149 [new release] earlybird (0.1.3)
  packages/earlybird/earlybird.0.1.3/opam
Labels: consider for merge

#13110 Packages: tidy(tidy-html5) & conf-tidy
  packages/conf-tidy/conf-tidy.1/files/test.c
  packages/conf-tidy/conf-tidy.1/opam
  packages/tidy/tidy.5-0.2/opam
Labels: question

#13080 Frama-C 18.0 (Argon) for opam 1.2
  packages/frama-c/frama-c.20181101/descr
  packages/frama-c/frama-c.20181101/opam
  packages/frama-c/frama-c.20181101/url
Labels: question

#13083 Remove mesh 0.7.4, mindstorm 0.5.3 & 0.5.4, etc.
  packages/conf-gfortran/conf-gfortran.0/opam
  packages/mesh/mesh.0.7.4/opam
  packages/mindstorm/mindstorm.0.5.3/opam
  packages/mindstorm/mindstorm.0.5.4/opam
  packages/oasis2opam/oasis2opam.0.3.3/opam
  packages/oasis2opam/oasis2opam.0.4.0/opam
  packages/odepack/odepack.0.6.2/opam
  packages/odepack/odepack.0.6.3/opam
  packages/odepack/odepack.0.6.5/opam
  packages/odepack/odepack.0.6.6/opam
  packages/odepack/odepack.0.6.7/opam
  packages/odepack/odepack.0.6.8/opam
  packages/odepack/odepack.0.6.9/opam
Labels: consider for merge, question

#13166 Package ocaml-http.0.1.6
  packages/ocaml-http/ocaml-http.0.1.6/opam
Labels: needs reporter action

#13170 Added cloudi.1.7.5
  packages/cloudi/cloudi.1.7.5/opam
Labels: consider for merge

#13173 Package eliom.6.4.0
  packages/eliom/eliom.6.4.0/opam
Labels: question

#13133 [new release] ahrocksdb (0.2.1)
  packages/ahrocksdb/ahrocksdb.0.2.1/opam
Labels: needs reporter action

#13205 [new release] vmnet (1.3.2)
  packages/vmnet/vmnet.1.3.2/opam
Labels: consider for merge, question

#13198 + devkit 0.7
  packages/devkit/devkit.0.7/opam
Labels: needs reporter action

#13199 Added liquidsoap 1.3.5 and gd.1.0a5
  packages/conf-gd/conf-gd.1/opam
  packages/gd/gd.1.0a5/opam
  packages/liquidsoap/liquidsoap.1.3.5/opam
Labels: consider for merge, question
