Repository ocaml/opam-repository, pull requests merged in 2019-08, with the labels that each got.

#14628 Package fmt.0.8.8
  packages/fmt/fmt.0.8.8/opam
Labels: consider for merge

#14631 Add portia.1.3
  packages/portia/portia.1.3/opam
Labels: consider for merge, needs reporter action

#14624 ppxlib.0.9.0
  packages/ppxlib/ppxlib.0.9.0/opam
Labels: consider for merge, needs reporter action

#14614 [new release] merlin-extend (0.5)
  packages/merlin-extend/merlin-extend.0.5/opam
Labels: consider for merge, needs reporter action

#14632 [new release] facteur (0.1.0)
  packages/conf-libmagic/conf-libmagic.1/opam
  packages/facteur/facteur.0.1.0/opam
Labels: needs reporter action

#14640 Added rel 5.7.08 of camlp5.
  packages/camlp5/camlp5.7.08/files/camlp5.install
  packages/camlp5/camlp5.7.08/opam
Labels: consider for merge, needs reporter action

#14636 Package nocoiner.1.0.0
  packages/nocoiner/nocoiner.1.0.0/opam
Labels: consider for merge, needs reporter action

#14634 Package taglib.0.3.6
  packages/taglib/taglib.0.3.6/opam
Labels: consider for merge, needs reporter action

#14641 Package lwt-pipeline.0.1
  packages/lwt-pipeline/lwt-pipeline.0.1/opam
Labels: needs reporter action

#14638 Package ocamlformat.0.11.0
  packages/ocamlformat/ocamlformat.0.11.0/opam
Labels: consider for merge, needs reporter action

#14672 [new release] tcpip (3.7.8)
  packages/tcpip/tcpip.3.7.8/opam
Labels: consider for merge, needs reporter action

#14601 +bigstringaf.0.5.3
  packages/bigstringaf/bigstringaf.0.5.3/opam
Labels: needs reporter action

#14660 Package logs.0.7.0
  packages/logs/logs.0.7.0/opam
Labels: consider for merge

#14656 New version of statverif added
  packages/statverif/statverif.1.97pl1.2/opam
Labels: needs reporter action

#14588 added packages/bytearray/bytearray.1.0.0
  packages/bytearray/bytearray.1.0.0/opam
Labels: needs reporter action

#14602 added packages/setcore/setcore.1.0.0
  packages/setcore/setcore.1.0.1/opam
Labels: needs reporter action

#14652 Release Links 0.9 (Burghmuirhead).
  packages/links-postgresql/links-postgresql.0.9/opam
  packages/links-sqlite3/links-sqlite3.0.9/opam
  packages/links/links.0.9/opam
Labels: needs reporter action

#14390 Package bnfgen.2.0
  packages/bnfgen/bnfgen.2.0/opam
Labels: consider for merge

#14403 Deprecate cfgen, since it was renamed to bnfgen
  packages/cfgen/cfgen.1.0/opam
Labels: needs reporter action

#14678 otf v0.1 submission.
  packages/otf/otf.0.1/opam
Labels: needs reporter action

#14568 Fix dune version for sedlex.2.1
  packages/sedlex/sedlex.2.1/opam
Labels: question

#14691 [new release] lascar (0.6-alpha)
  packages/lascar/lascar.0.6-alpha/opam
Labels: consider for merge

#14692 [new release] yaml (2.0.1)
  packages/yaml/yaml.2.0.1/opam
Labels: consider for merge

#14607 added packages/parany/parany.7.0.0
  packages/parany/parany.7.0.0/opam
Labels: needs reporter action

#14693 [new release] cohttp-lwt-jsoo, cohttp-mirage, cohttp-lwt, cohttp-async, cohttp-top, cohttp-lwt-unix and cohttp (2.3.0)
  packages/cohttp-async/cohttp-async.2.3.0/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.2.3.0/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.2.3.0/opam
  packages/cohttp-lwt/cohttp-lwt.2.3.0/opam
  packages/cohttp-mirage/cohttp-mirage.2.3.0/opam
  packages/cohttp-top/cohttp-top.2.3.0/opam
  packages/cohttp/cohttp.2.3.0/opam
  packages/websocket-lwt-unix/websocket-lwt-unix.2.13/opam
Labels: needs reporter action

#14698 lablqml 0.6.2 for ocaml >= 4.08
  packages/conf-qt/conf-qt.5.2.1/opam
  packages/lablqml/lablqml.0.6.2/opam
  packages/qocamlbrowser/qocamlbrowser.0.2.11/opam
Labels: needs reporter action

#14703 simplify constraints on the mmap package
  packages/mmap/mmap.1.1.0/opam
Labels: question

#14708 Camlp5 logger syntax extension 0.4.2
  packages/logger-p5/logger-p5.0.4.2/opam
Labels: needs reporter action

#14724 Get the lastest version of verimag packages (camlp4 free)
  packages/lustre-v6/lustre-v6.1.737/opam
  packages/lustre-v6/lustre-v6.6.101.7/opam
  packages/lutils/lutils.1.49.5/opam
  packages/lutin/lutin.2.56/opam
  packages/lutin/lutin.2.70.4/opam
  packages/rdbg/rdbg.1.184.1/opam
Labels: needs reporter action

#14626 Speed up re-configuring OCaml sources
  packages/ocaml-base-compiler/ocaml-base-compiler.4.08.0/files/ocaml-base-compiler.install
  packages/ocaml-base-compiler/ocaml-base-compiler.4.08.0/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.08.1/files/ocaml-base-compiler.install
  packages/ocaml-base-compiler/ocaml-base-compiler.4.08.1/opam
Labels: consider for merge

#14715 Attempt to package augeas
  packages/augeas/augeas.0.6/opam
Labels: consider for merge

#14731 [new release] owl-ode-odepack, owl-ode-base, owl-ode-sundials and owl-ode (0.2.0)
  packages/owl-ode-base/owl-ode-base.0.2.0/opam
  packages/owl-ode-odepack/owl-ode-odepack.0.2.0/opam
  packages/owl-ode-sundials/owl-ode-sundials.0.2.0/opam
  packages/owl-ode/owl-ode.0.2.0/opam
Labels: consider for merge

#14741 Package mariadb.1.1.4
  packages/mariadb/mariadb.1.1.4/opam
Labels: consider for merge

#14739 Package fileutils.0.6.0
  packages/fileutils/fileutils.0.6.0/opam
Labels: consider for merge

#14713 Package cmarker.0.3.0
  packages/cmarker/cmarker.0.3.0/opam
Labels: consider for merge

#14746 Package unionFind.20190827
  packages/unionFind/unionFind.20190827/opam
Labels: needs reporter action

#14751 Package oseq.0.3
  packages/oseq/oseq.0.3/opam
Labels: needs reporter action
