Repository ocaml/opam-repository, pull requests merged in 2019-01, with the labels that each got.

#13207 [new release] mirage-clock, mirage-clock-freestanding, mirage-clock-lwt and mirage-clock-unix (2.0.0)
  packages/dns-forward-lwt-unix/dns-forward-lwt-unix.0.9.0/opam
  packages/mirage-clock-freestanding/mirage-clock-freestanding.2.0.0/opam
  packages/mirage-clock-lwt/mirage-clock-lwt.2.0.0/opam
  packages/mirage-clock-unix/mirage-clock-unix.2.0.0/opam
  packages/mirage-clock/mirage-clock.2.0.0/opam
Labels: needs reporter action

#13200 Update Travis to Ubuntu 16.04
  .travis.yml
Labels: consider for merge, needs maintainer action, question

#13240 mirage-net-lwt: restrict to ipaddr <3.0.0 (requires Macaddr.t which i…
  packages/mirage-net-lwt/mirage-net-lwt.1.0.0/opam
  packages/mirage-net-lwt/mirage-net-lwt.1.1.0/opam
Labels: needs reporter action

#13246 add mirage-net{-lwt}.1.2.0
  packages/mirage-net-lwt/mirage-net-lwt.1.2.0/opam
  packages/mirage-net/mirage-net.1.2.0/opam
Labels: needs reporter action

#13239 [new release] decoders, decoders-ezjsonm and decoders-yojson (0.1.2)
  packages/decoders-ezjsonm/decoders-ezjsonm.0.1.2/opam
  packages/decoders-yojson/decoders-yojson.0.1.2/opam
  packages/decoders/decoders.0.1.2/opam
Labels: needs reporter action

#13254 2 packages from dozzman/interface-prime at dev
  packages/interface-prime-lwt/interface-prime-lwt.0.1/opam
  packages/interface-prime/interface-prime.0.1/opam
Labels: needs maintainer action

#13261 Package msat.0.7
  packages/msat/msat.0.7/opam
Labels: question

#13255 Package ws.0.1
  packages/ws/ws.0.1/opam
Labels: needs reporter action

#13283 +mirage-qubes-ipv4.0.6.1
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.6.1/opam
Labels: consider for merge, question

#13286 release of psmt2-frontend 0.2
  packages/psmt2-frontend/psmt2-frontend.0.2/opam
Labels: consider for merge

#13292 ocamlcodoc.1
  packages/ocamlcodoc/ocamlcodoc.1.0.0/opam
Labels: needs reporter action

#13291 Package obeam.0.1.3
  packages/obeam/obeam.0.1.3/opam
Labels: question

#13280 Package eliom.6.6.0
  packages/eliom/eliom.6.6.0/opam
Labels: consider for merge, question

#13301 Configuration package for zstd
  packages/conf-zstd/conf-zstd.0.1/opam
Labels: consider for merge

#13300 Package tablecloth-native.0.0.2
  packages/tablecloth-native/tablecloth-native.0.0.2/opam
Labels: needs reporter action

#13310 Package ocp-browser.1.1.8
  packages/ocp-browser/ocp-browser.1.1.8/opam
Labels: needs reporter action

#13305 5 packages from zshipko/resp at 0.9
  packages/resp-client/resp-client.0.9/opam
  packages/resp-mirage/resp-mirage.0.9/opam
  packages/resp-server/resp-server.0.9/opam
  packages/resp-unix/resp-unix.0.9/opam
  packages/resp/resp.0.9/opam
Labels: needs reporter action

#13288 [new release] datakit-github, datakit-bridge-local-git, datakit-client-git, datakit-client, datakit, datakit-bridge-github, datakit-server-9p, datakit-client-9p, datakit-ci and datakit-server (0.12.2)
  packages/datakit-bridge-github/datakit-bridge-github.0.12.2/opam
  packages/datakit-bridge-local-git/datakit-bridge-local-git.0.12.2/opam
  packages/datakit-ci/datakit-ci.0.12.2/opam
  packages/datakit-client-9p/datakit-client-9p.0.12.2/opam
  packages/datakit-client-git/datakit-client-git.0.12.2/opam
  packages/datakit-client/datakit-client.0.12.2/opam
  packages/datakit-github/datakit-github.0.12.2/opam
  packages/datakit-server-9p/datakit-server-9p.0.12.2/opam
  packages/datakit-server/datakit-server.0.12.2/opam
  packages/datakit/datakit.0.12.2/opam
Labels: needs reporter action

#13316 Package morsmall.0.1
  packages/morsmall/morsmall.0.1/opam
Labels: needs reporter action

#13311 flac.0.1.4
  packages/flac/flac.0.1.4/opam
Labels: needs reporter action

#13315 nlopt-ocaml: remove ocaml-version upper bound
  packages/nlopt-ocaml/nlopt-ocaml.0.5.1/opam
Labels: consider for merge

#13320 Package opam-ed.0.3
  packages/opam-ed/opam-ed.0.3/opam
Labels: consider for merge

#13319 added packages/lbvs_consent/lbvs_consent.2.0.1
  packages/lbvs_consent/lbvs_consent.2.0.1/opam
Labels: needs reporter action

#13329 Package headache.1.04
  packages/headache/headache.1.04/opam
Labels: consider for merge

#13338 Hts shrink 210
  packages/hts_shrink/hts_shrink.2.1.0/opam
Labels: consider for merge

#13345 [new release] pkcs11-driver, pkcs11-cli, pkcs11-rev and pkcs11 (0.18.0)
  packages/pkcs11-cli/pkcs11-cli.0.18.0/opam
  packages/pkcs11-driver/pkcs11-driver.0.18.0/opam
  packages/pkcs11-rev/pkcs11-rev.0.18.0/opam
  packages/pkcs11/pkcs11.0.18.0/opam
Labels: consider for merge
