Repository ocaml/opam-repository, pull requests merged in 2019-07, with the labels that each got.

#14415 added packages/pardi/pardi.1.0.0/opam
  packages/pardi/pardi.1.0.0/opam
Labels: needs reporter action

#14389 added packages/dokeysto/dokeysto.3.0.1
  packages/dokeysto/dokeysto.3.0.1/opam
  packages/dokeysto_camltc/dokeysto_camltc.3.0.1/opam
  packages/dokeysto_lz4/dokeysto_lz4.3.0.1/opam
Labels: question

#14380 Package lo.0.1.2
  packages/lo/lo.0.1.2/opam
Labels: needs reporter action

#14422 Package fdkaac.0.3.0
  packages/fdkaac/fdkaac.0.3.0/opam
Labels: needs reporter action

#14330 camlzip version 1.08
  packages/camlzip/camlzip.1.08/opam
Labels: needs reporter action

#14434 Add bounds on camlzip < 1.08 and other upper bounds
  packages/alt-ergo-free/alt-ergo-free.2.0.0/opam
  packages/alt-ergo/alt-ergo.1.30/opam
  packages/alt-ergo/alt-ergo.2.0.0/opam
  packages/alt-ergo/alt-ergo.2.1.0/opam
  packages/alt-ergo/alt-ergo.2.2.0/opam
  packages/altgr-ergo/altgr-ergo.1.30/opam
  packages/decompress/decompress.0.8.1/opam
  packages/decompress/decompress.0.8/opam
Labels: needs reporter action

#14447 vchan: older versions cannot use mirage-xen>4
  packages/vchan/vchan.2.0.0/opam
  packages/vchan/vchan.2.0.1/opam
  packages/vchan/vchan.2.0.2/opam
  packages/vchan/vchan.2.0.3/opam
  packages/vchan/vchan.2.1.0/opam
  packages/vchan/vchan.2.2.0/opam
  packages/vchan/vchan.2.3.0/opam
  packages/vchan/vchan.2.3.1/opam
Labels: consider for merge

#14473 [new release] uri and uri-sexp (3.0.0)
  packages/async_js/async_js.v0.12.0/opam
  packages/cohttp-async/cohttp-async.1.2.0/opam
  packages/cohttp-async/cohttp-async.2.0.0/opam
  packages/cohttp-async/cohttp-async.2.1.1/opam
  packages/cohttp/cohttp.1.2.0/opam
  packages/cohttp/cohttp.2.0.0/opam
  packages/cohttp/cohttp.2.1.2/opam
  packages/mechaml/mechaml.0.1/opam
  packages/mechaml/mechaml.1.0.0/opam
  packages/mechaml/mechaml.1.1.0/opam
  packages/satyrographos/satyrographos.0.0.1.4/opam
  packages/satyrographos/satyrographos.0.0.1.5/opam
  packages/satyrographos/satyrographos.0.0.1.7/opam
  packages/uri-sexp/uri-sexp.3.0.0/opam
  packages/uri/uri.3.0.0/opam
Labels: needs reporter action

#14472 Package ocsigenserver.2.12.0
  packages/ocsigenserver/ocsigenserver.2.12.0/opam
Labels: consider for merge

#14476 New version of visitors.
  packages/visitors/visitors.20190711/opam
Labels: consider for merge

#14479 [new release] mirage, mirage-runtime, mirage-types-lwt and mirage-types (3.5.1)
  packages/mirage-runtime/mirage-runtime.3.5.1/opam
  packages/mirage-types-lwt/mirage-types-lwt.3.5.1/opam
  packages/mirage-types/mirage-types.3.5.1/opam
  packages/mirage/mirage.3.5.1/opam
Labels: consider for merge

#14471 Markup.ml 0.8.1: standards-compliant HTML5 parser
  packages/markup/markup.0.8.1/opam
Labels: needs admin action

#14490 [new release] datakit-github, datakit-bridge-local-git, datakit-client-git, datakit-client, datakit, datakit-bridge-github, datakit-server-9p, datakit-client-9p, datakit-ci and datakit-server (1.0.0)
  packages/datakit-bridge-github/datakit-bridge-github.1.0.0/opam
  packages/datakit-bridge-local-git/datakit-bridge-local-git.1.0.0/opam
  packages/datakit-ci/datakit-ci.1.0.0/opam
  packages/datakit-client-9p/datakit-client-9p.1.0.0/opam
  packages/datakit-client-git/datakit-client-git.1.0.0/opam
  packages/datakit-client/datakit-client.1.0.0/opam
  packages/datakit-github/datakit-github.1.0.0/opam
  packages/datakit-server-9p/datakit-server-9p.1.0.0/opam
  packages/datakit-server/datakit-server.1.0.0/opam
  packages/datakit/datakit.1.0.0/opam
Labels: needs reporter action

#14500 Package ppx_cstubs.0.2.0
  packages/ppx_cstubs/ppx_cstubs.0.2.0/opam
Labels: needs reporter action

#14449 2 packages from sapristi/easy_logging at 0.5
  packages/easy_logging/easy_logging.0.5/opam
  packages/easy_logging_yojson/easy_logging_yojson.0.5/opam
Labels: needs reporter action

#14510 [new release] merlin (3.3.2)
  packages/merlin/merlin.3.3.2/opam
Labels: needs reporter action

#14481 8 packages from ocaml/opam at 2.0.5
  packages/opam-client/opam-client.2.0.5/opam
  packages/opam-core/opam-core.2.0.5/opam
  packages/opam-devel/opam-devel.2.0.5/opam
  packages/opam-format/opam-format.2.0.5/opam
  packages/opam-installer/opam-installer.2.0.5/opam
  packages/opam-repository/opam-repository.2.0.5/opam
  packages/opam-solver/opam-solver.2.0.5/opam
  packages/opam-state/opam-state.2.0.5/opam
Labels: needs reporter action

#14509 Package herdtools7.7.54
  packages/herdtools7/herdtools7.7.54/files/chatouille.patch
  packages/herdtools7/herdtools7.7.54/opam
Labels: needs reporter action

#14524 Flac conflicts with old Liquidsoap versions.
  packages/flac/flac.0.1.5/opam
Labels: question

#14521 [new release] routes (0.5.1)
  packages/routes/routes.0.5.1/opam
Labels: needs reporter action

#14502 4 packages from c-cube/qcheck at 0.10
  packages/qcheck-alcotest/qcheck-alcotest.0.10/opam
  packages/qcheck-core/qcheck-core.0.10/opam
  packages/qcheck-ounit/qcheck-ounit.0.10/opam
  packages/qcheck/qcheck.0.10/opam
Labels: needs reporter action

#14523 Reason 3.5.0
  packages/reason/reason.3.5.0/opam
  packages/rtop/rtop.3.5.0/opam
Labels: consider for merge

#14527 Fix qcheck bounds
  packages/nunchaku/nunchaku.0.5.1/opam
  packages/oasis2opam/oasis2opam.0.6.1/opam
  packages/oasis2opam/oasis2opam.0.6.2/opam
  packages/oasis2opam/oasis2opam.0.7/opam
  packages/oasis2opam/oasis2opam.0.8/opam
  packages/stringext/stringext.1.4.0/opam
  packages/stringext/stringext.1.4.1/opam
  packages/stringext/stringext.1.4.2/opam
  packages/syslog-message/syslog-message.0.0.1/opam
  packages/syslog-message/syslog-message.0.0.2/opam
Labels: consider for merge

#14535 [new release] tcpip (3.7.7)
  packages/tcpip/tcpip.3.7.7/opam
Labels: needs reporter action

#14539 Package ocsigen-start.2.2.2
  packages/ocsigen-start/ocsigen-start.2.2.2/opam
Labels: question

#14540 5 packages from owlbarn/owl at 0.6.0
  packages/owl-base/owl-base.0.6.0/opam
  packages/owl-plplot/owl-plplot.0.6.0/opam
  packages/owl-top/owl-top.0.6.0/opam
  packages/owl-zoo/owl-zoo.0.6.0/opam
  packages/owl/owl.0.6.0/opam
Labels: consider for merge

#14552 owl-ode, owl-ode-sundials: release 0.1.0
  packages/owl-ode-sundials/owl-ode-sundials.0.1.0/opam
  packages/owl-ode/owl-ode.0.1.0/opam
  packages/sundialsml/sundialsml.3.1.1p0-1/opam
Labels: consider for merge

#14559 Add ppx_tools.5.3+4.08.0
  packages/ppx_tools/ppx_tools.5.3+4.08.0/opam
Labels: consider for merge

#14555 Package topkg.1.0.1
  packages/topkg/topkg.1.0.1/opam
Labels: consider for merge

#14558 Package mtime.1.2.0
  packages/mtime/mtime.1.2.0/opam
Labels: consider for merge

#14557 Package tsdl.0.9.7
  packages/tsdl/tsdl.0.9.7/opam
Labels: consider for merge

#14526 Genprint 0.1
  packages/genprint/genprint.0.1/opam
Labels: needs reporter action

#14564 Package fmt.0.8.7
  packages/fmt/fmt.0.8.7/opam
Labels: consider for merge

#14545 [new release] ppxlib (0.8.1)
  packages/ppxlib/ppxlib.0.8.1/opam
Labels: needs reporter action

#14531 Package bogue.20190717
  packages/bogue/bogue.20190717/opam
Labels: needs reporter action

#14560 Add ctypes 0.15.0
  packages/ctypes/ctypes.0.15.0/opam
Labels: needs reporter action

#14556 Package mccs.1.1+10
  packages/mccs/mccs.1.1+10/opam
Labels: question

#14584 [new release] emile (0.5)
  packages/emile/emile.0.5/opam
Labels: consider for merge

#14585 Add ctypes 0.15.1.
  packages/ctypes/ctypes.0.15.1/opam
Labels: consider for merge

#14581 Release x509 0.7.0
  packages/certify/certify.0.1/opam
  packages/certify/certify.0.2/opam
  packages/conex-nocrypto/conex-nocrypto.0.10.0/opam
  packages/conex-nocrypto/conex-nocrypto.0.10.1/opam
  packages/conex/conex.0.9.2/opam
  packages/logs-syslog/logs-syslog.0.0.1/opam
  packages/logs-syslog/logs-syslog.0.0.2/opam
  packages/logs-syslog/logs-syslog.0.1.0/opam
  packages/logs-syslog/logs-syslog.0.1.1/opam
  packages/logs-syslog/logs-syslog.0.2.0/opam
  packages/logs-syslog/logs-syslog.0.2.1/opam
  packages/tls/tls.0.10.1/opam
  packages/tls/tls.0.10.2/opam
  packages/tls/tls.0.9.0/opam
  packages/tls/tls.0.9.1/opam
  packages/tls/tls.0.9.2/opam
  packages/tls/tls.0.9.3/opam
  packages/tlstunnel/tlstunnel.0.2.0/opam
  packages/x509/x509.0.7.0/opam
Labels: consider for merge

#14534 Package gremlin.0.1.1
  packages/gremlin/gremlin.0.1.1/opam
Labels: consider for merge

#14592 +tls 0.10.3
  packages/capnp-rpc-lwt/capnp-rpc-lwt.0.3.2/opam
  packages/tls/tls.0.10.3/opam
Labels: consider for merge

#14589 [new release] mrmime (0.1.0)
  packages/mrmime/mrmime.0.1.0/opam
Labels: needs reporter action

#14594 Package nice_parser.1.0.0
  packages/nice_parser/nice_parser.1.0.0/opam
Labels: needs reporter action

#14597 Package psyche.0.0.1
  packages/psyche/psyche.0.0.1/opam
Labels: needs reporter action

#14591 [new release] certify (0.3.0)
  packages/certify/certify.0.3.0/opam
Labels: consider for merge, needs reporter action

#14610 Lwt_log 1.1.1
  packages/lwt_log/lwt_log.1.1.1/opam
Labels: needs reporter action

#14608 [new release] sendmail-lwt, colombe and sendmail (0.1.0)
  packages/colombe/colombe.0.1.0/opam
  packages/sendmail-lwt/sendmail-lwt.0.1.0/opam
  packages/sendmail/sendmail.0.1.0/opam
Labels: needs reporter action

#14616 pythonlib.v0.12.0
  packages/pythonlib/pythonlib.v0.12.0/opam
Labels: consider for merge, needs reporter action
