Repository ocaml/opam-repository, pull requests merged in 2019-02, with the labels that each got.

#13344 Add upper bounds to reverse dependencies of Jane Street packages
  packages/ahrocksdb/ahrocksdb.0.2.0/opam
  packages/alcotest-async/alcotest-async.0.8.5/opam
  packages/angstrom-async/angstrom-async.0.11.0/opam
  packages/biocaml/biocaml.0.9.0/opam
  packages/camelsnakekebab/camelsnakekebab.0.4/opam
  packages/charrua-core/charrua-core.0.11.1/opam
  packages/conduit-async/conduit-async.1.4.0/opam
  packages/conduit-lwt-unix/conduit-lwt-unix.1.4.0/opam
  packages/conduit-lwt/conduit-lwt.1.4.0/opam
  packages/conduit/conduit.1.4.0/opam
  packages/coq-serapi/coq-serapi.8.9.0+0.6.0/opam
  packages/datakit-ci/datakit-ci.0.12.2/opam
  packages/datakit-server-9p/datakit-server-9p.0.12.2/opam
  packages/dns-async/dns-async.1.1.0/opam
  packages/gemini/gemini.0.1/opam
  packages/graphql-async/graphql-async.0.8.0/opam
  packages/httpaf-async/httpaf-async.0.5.0/opam
  packages/ipaddr/ipaddr.2.9.0/opam
  packages/ipaddr/ipaddr.3.0.0/opam
  packages/lacaml/lacaml.11.0.3/opam
  packages/logs-async-reporter/logs-async-reporter.1.0/opam
  packages/logs-async/logs-async.1.0/opam
  packages/macaddr/macaddr.3.0.0/opam
  packages/mirage-conduit/mirage-conduit.3.1.0/opam
  packages/mssql/mssql.1.1/opam
  packages/netchannel/netchannel.1.8.1/opam
  packages/obeam/obeam.0.1.2/opam
  packages/obeam/obeam.0.1.3/opam
  packages/opium/opium.0.17.0/opam
  packages/opium_kernel/opium_kernel.0.17.0/opam
  packages/ppxlib/ppxlib.0.4.0/opam
  packages/ppxlib/ppxlib.0.5.0/opam
  packages/range/range.0.5/opam
  packages/tablecloth-native/tablecloth-native.0.0.2/opam
  packages/tensorflow/tensorflow.0.0.11/opam
  packages/tidy/tidy.5-0.2/opam
  packages/tls/tls.0.9.3/opam
  packages/torch/torch.0.1/opam
  packages/torch/torch.0.2/opam
  packages/torch/torch.0.3/opam
  packages/travesty/travesty.0.1.2/opam
  packages/travesty/travesty.0.1.3/opam
  packages/travesty/travesty.0.2.0/opam
  packages/uri/uri.2.1.0/opam
  packages/vchan-unix/vchan-unix.4.0.0/opam
  packages/vchan-xen/vchan-xen.4.0.0/opam
  packages/vchan/vchan.4.0.0/opam
  packages/vmnet/vmnet.1.3.2/opam
  packages/vmnet/vmnet.1.3.3/opam
Labels: needs reporter action

#13371 [new release] xenstore (2.1.0)
  packages/xenstore/xenstore.2.1.0/opam
Labels: consider for merge

#13367 [new release] arp and arp-mirage (1.0.0)
  packages/arp-mirage/arp-mirage.1.0.0/opam
  packages/arp/arp.1.0.0/opam
Labels: consider for merge

#13375 [new release] tar-mirage, tar and tar-unix (1.0.0)
  packages/tar-mirage/tar-mirage.1.0.0/opam
  packages/tar-unix/tar-unix.1.0.0/opam
  packages/tar/tar.1.0.0/opam
Labels: consider for merge

#13400 Package uutf.1.0.2
  packages/uutf/uutf.1.0.2/opam
Labels: consider for merge

#13349 New package: conf-libclang
  packages/conf-libclang/conf-libclang.1.0.0/files/configure.sh
  packages/conf-libclang/conf-libclang.1.0.0/opam
Labels: help wanted

#13407 Package eigen.0.1.0
  packages/eigen/eigen.0.1.0/opam
  packages/owl/owl.0.2.5/opam
  packages/owl/owl.0.2.6/opam
  packages/owl/owl.0.2.9/opam
  packages/owl/owl.0.3.0/opam
  packages/owl/owl.0.3.7/opam
  packages/owl/owl.0.3.8/opam
  packages/owl/owl.0.4.0/opam
Labels: needs reporter action

#13405 added packages/lbvs_consent/lbvs_consent.2.1.0
  packages/lbvs_consent/lbvs_consent.2.1.0/opam
Labels: needs reporter action

#13356 Restrict ppx_deriving_yojson dependency to yojson < 1.6
  packages/ppx_deriving_yojson/ppx_deriving_yojson.1.0/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.1.1/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.2.0/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.2.1/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.2.2/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.2.3/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.2.4/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.3.0/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.3.1/opam
  packages/ppx_deriving_yojson/ppx_deriving_yojson.3.3/opam
Labels: consider for merge

#13420 3 packages from OCamlPro/ocplib-json-typed at 0.7
  packages/ocplib-json-typed-browser/ocplib-json-typed-browser.0.7/opam
  packages/ocplib-json-typed-bson/ocplib-json-typed-bson.0.7/opam
  packages/ocplib-json-typed/ocplib-json-typed.0.7/opam
Labels: needs reporter action

#13351 add conf-rust.2018
  packages/conf-rust-2018/conf-rust-2018.1/files/test.rs
  packages/conf-rust-2018/conf-rust-2018.1/opam
Labels: help wanted

#13446 Add upper bounds to reverse dependencies of Jane Street packages
  packages/charrua-core/charrua-core.0.11.2/opam
  packages/cohttp-async/cohttp-async.2.0.0/opam
  packages/cohttp-lwt/cohttp-lwt.2.0.0/opam
  packages/cohttp/cohttp.2.0.0/opam
  packages/dns-async/dns-async.1.1.1/opam
  packages/dockerfile-cmd/dockerfile-cmd.6.1.0/opam
  packages/dockerfile/dockerfile.6.1.0/opam
  packages/ezjsonm-lwt/ezjsonm-lwt.1.0.0/opam
  packages/ezjsonm/ezjsonm.1.0.0/opam
  packages/faraday-async/faraday-async.0.7.0/opam
  packages/gemini/gemini.0.2.0/opam
  packages/mirage-block-unix/mirage-block-unix.2.11.0/opam
  packages/mirage-net-macosx/mirage-net-macosx.1.5.0/opam
  packages/netchannel/netchannel.1.9.0/opam
  packages/pcre/pcre.7.4.0/opam
  packages/pkcs11/pkcs11.0.18.0/opam
  packages/protocol-9p-unix/protocol-9p-unix.1.0.0/opam
  packages/protocol-9p-unix/protocol-9p-unix.1.0.1/opam
  packages/protocol-9p/protocol-9p.1.0.0/opam
  packages/protocol-9p/protocol-9p.1.0.1/opam
  packages/satyrographos/satyrographos.0.0.1.4/opam
  packages/tensorflow/tensorflow.0.0.11/opam
  packages/uri/uri.2.2.0/opam
  packages/vchan-unix/vchan-unix.4.0.1/opam
  packages/vchan-xen/vchan-xen.4.0.1/opam
  packages/vchan/vchan.4.0.1/opam
Labels: consider for merge

#13465 ocp-index does not build with dune >=1.7
  packages/ocp-index/ocp-index.1.1.6/opam
  packages/ocp-index/ocp-index.1.1.7/opam
Labels: consider for merge

#13440 why3 1.2.0
  packages/why3-coq/why3-coq.1.2.0/opam
  packages/why3-ide/why3-ide.1.2.0/opam
  packages/why3/why3.1.2.0/opam
Labels: needs reporter action

#13284 conf-openssl: macos: look for openssl until it is found
  packages/conf-openssl/conf-openssl.1/files/osx-build.sh
  packages/conf-openssl/conf-openssl.1/opam
Labels: needs reporter action

#13434 New clangml release: 4.0.0beta1
  packages/clangml-transforms/clangml-transforms.0.19/opam
  packages/clangml-transforms/clangml-transforms.0.20/opam
  packages/clangml-transforms/clangml-transforms.0.21/opam
  packages/clangml-transforms/clangml-transforms.0.23/opam
  packages/clangml/clangml.3.9.1.2/opam
  packages/clangml/clangml.4.0.0beta1/opam
  packages/conf-libclang/conf-libclang.1.0.0/opam
Labels: needs reporter action

#13466 Package nsq.0.4.0
  packages/nsq/nsq.0.4.0/opam
Labels: needs reporter action

#13489 [new release] stdlib-shims (0.1.0)
  packages/stdlib-shims/stdlib-shims.0.1.0/opam
Labels: needs reporter action

#13500 datakit-ci needs uri>=2.0
  packages/datakit-ci/datakit-ci.0.12.2/opam
Labels: needs reporter action

#13495 +mirage-platform.3.3.0
  packages/mirage-xen-ocaml/mirage-xen-ocaml.3.3.0/opam
  packages/mirage-xen-posix/mirage-xen-posix.3.3.0/opam
Labels: consider for merge

#13507 release of OCamlbuild 0.14.0
  packages/ocamlbuild/ocamlbuild.0.14.0/opam
Labels: consider for merge

#13506 Package eigen.0.1.1
  packages/eigen/eigen.0.1.1/opam
Labels: consider for merge

#13508 2 packages from c-cube/calculon at 0.4
  packages/calculon-web/calculon-web.0.2/opam
  packages/calculon-web/calculon-web.0.3/opam
  packages/calculon-web/calculon-web.0.4/opam
  packages/calculon/calculon.0.4/opam
Labels: needs reporter action

#13514 base-unsafe-string
  packages/base-unsafe-string/base-unsafe-string.base/opam
Labels: consider for merge

#13530 conf-openblas: fix switches
  packages/conf-openblas/conf-openblas.0.2.0/opam
Labels: consider for merge

#13553 release tls 0.10.1
  packages/tls/tls.0.10.1/opam
Labels: consider for merge

#13549 Release crunch 3.0.0
  packages/crunch/crunch.3.0.0/opam
  packages/datakit-ci/datakit-ci.0.12.1/opam
  packages/datakit-ci/datakit-ci.0.12.2/opam
  packages/mirage-www/mirage-www.1.1.0/opam
  packages/mirage/mirage.2.0.0/opam
  packages/mirage/mirage.2.0.1/opam
  packages/mirage/mirage.2.1.0/opam
  packages/mirage/mirage.2.1.1/opam
  packages/mirage/mirage.2.2.0/opam
  packages/mirage/mirage.2.2.1/opam
  packages/mirage/mirage.2.3.0/opam
Labels: consider for merge

#13548 mirage-kv-lwt 2.0.0 requires at leastt mirage-kv 2.0.0
  packages/mirage-kv-lwt/mirage-kv-lwt.2.0.0/opam
Labels: consider for merge

#13546 [new release] mirage-dns (3.1.2)
  packages/mirage-dns/mirage-dns.3.1.1/opam
  packages/mirage-dns/mirage-dns.3.1.2/opam
Labels: consider for merge

#13545 [new release] mirage-fs-lwt and mirage-fs (2.0.0)
  packages/mirage-fs-lwt/mirage-fs-lwt.2.0.0/opam
  packages/mirage-fs/mirage-fs.2.0.0/opam
Labels: consider for merge
