Repository ocaml/opam-repository, pull requests merged in 2019-10, with the labels that each got.

#14959 Package unidecode.0.1.0
  packages/unidecode/unidecode.0.1.0/opam
Labels: needs reporter action

#14956 Package hacl.0.1
  packages/hacl/hacl.0.1/opam
Labels: needs reporter action

#14911 new Frama-C version 19.1
  packages/frama-c/frama-c.19.1/opam
Labels: needs reporter action

#14981 Add camlidl 1.07 package
  packages/camlidl/camlidl.1.07/files/META
  packages/camlidl/camlidl.1.07/files/camlidl.install
  packages/camlidl/camlidl.1.07/files/disable-fatal-warn-31.diff
  packages/camlidl/camlidl.1.07/opam
Labels: needs reporter action

#14972 4 packages from c-cube/qcheck at 0.11
  packages/qcheck-alcotest/qcheck-alcotest.0.11/opam
  packages/qcheck-core/qcheck-core.0.11/opam
  packages/qcheck-ounit/qcheck-ounit.0.11/opam
  packages/qcheck/qcheck.0.11/opam
Labels: needs reporter action

#14966 Package liquidsoap.1.4.0
  packages/liquidsoap/liquidsoap.1.4.0/opam
Labels: needs reporter action

#14976 added packages/conf-liblinear-tools/conf-liblinear-tools.1.0.0
  packages/conf-liblinear-tools/conf-liblinear-tools.1.0.0/opam
Labels: needs reporter action

#14973 added packages/parmap/parmap.1.0-rc11
  packages/parmap/parmap.1.0-rc11/opam
Labels: needs reporter action

#14987 [new release] ounit2-lwt, ounit2, ounit-lwt and ounit (2.2.1)
  packages/ounit-lwt/ounit-lwt.2.2.1/opam
  packages/ounit/ounit.2.2.1/opam
  packages/ounit2-lwt/ounit2-lwt.2.2.1/opam
  packages/ounit2/ounit2.2.2.1/opam
Labels: needs reporter action

#14988 added packages/lz4_chans/lz4_chans.3.0.0
  packages/lz4_chans/lz4_chans.3.0.0/opam
Labels: needs reporter action

#14986 Release clangml.4.0.1
  packages/clangml/clangml.4.0.1/opam
Labels: needs reporter action

#14992 [new release] protocell (1.0.0)
  packages/protocell/protocell.1.0.0/opam
Labels: needs reporter action

#14995 Package blake2.0.2
  packages/blake2/blake2.0.2/opam
Labels: consider for merge

#15004 [new release] plotkicadsch and kicadsch (0.5.2)
  packages/kicadsch/kicadsch.0.5.2/opam
  packages/plotkicadsch/plotkicadsch.0.5.2/opam
Labels: needs reporter action

#15005 Package lwt-watcher.0.1
  packages/lwt-watcher/lwt-watcher.0.1/opam
Labels: needs reporter action

#15024 mlcuddidl.3.0.5
  packages/mlcuddidl/mlcuddidl.3.0.5/opam
Labels: needs reporter action

#15013 [new release] decompress and rfc1951 (0.9.1)
  packages/decompress/decompress.0.9.1/opam
  packages/rfc1951/rfc1951.0.9.1/opam
Labels: needs reporter action

#15008 added packages/linwrap/linwrap.0.0.1
  packages/linwrap/linwrap.0.0.1/opam
Labels: needs reporter action

#15038 Package resource-pooling.0.8
  packages/resource-pooling/resource-pooling.0.8/opam
Labels: consider for merge

#15036 Package ldap.2.4.1
  packages/ldap/ldap.2.4.1/opam
Labels: consider for merge

#15048 ocaml-protoc-plugin.1.0.0 and conf-protoc.1.0.0
  packages/conf-protoc/conf-protoc.1.0.0/opam
  packages/ocaml-protoc-plugin/ocaml-protoc-plugin.1.0.0/opam
Labels: consider for merge

#14935 added packages/molenc/molenc.5.0.0
  packages/conf-rdkit/conf-rdkit.0.1/opam
  packages/molenc/molenc.5.0.0/opam
Labels: consider for merge, question

#15017 [new release] Add coq.8.10.0 and coqide.8.10.0
  packages/conf-findutils/conf-findutils.1/opam
  packages/conf-gtksourceview3/conf-gtksourceview3.0+1/opam
  packages/coq/coq.8.10.0/files/coq.install
  packages/coq/coq.8.10.0/opam
  packages/coqide/coqide.8.10.0/files/coqide.install
  packages/coqide/coqide.8.10.0/opam
Labels: question

#15046 Add piqi-0.7.7
  packages/piqi/piqi.0.7.7/opam
Labels: needs reporter action

#15040 [new release] gsl (1.24.1)
  packages/gsl/gsl.1.24.1/opam
Labels: needs reporter action

#15000 Release clangml-transforms.0.24
  packages/clangml-transforms/clangml-transforms.0.24/opam
  packages/memcad/memcad.1.0.0/opam
Labels: needs reporter action

#15052 Package data-encoding.0.1.1
  packages/data-encoding/data-encoding.0.1.1/opam
Labels: needs reporter action

#15064 [jingoo] Release version v1.3.1
  packages/jingoo/jingoo.1.3.1/opam
Labels: needs reporter action

#15053 Package resource-pooling.1.1
  packages/resource-pooling/resource-pooling.1.1/opam
Labels: consider for merge

#15058 Package lwt-canceler.0.1
  packages/lwt-canceler/lwt-canceler.0.1/opam
Labels: needs reporter action

#15059 Package lwt-canceler.0.2
  packages/lwt-canceler/lwt-canceler.0.2/opam
Labels: needs reporter action

#15042 [new release] pcre (7.4.2)
  packages/pcre/pcre.7.4.2/opam
Labels: needs reporter action

#15043 [new release] postgresql (4.5.1)
  packages/postgresql/postgresql.4.5.1/opam
Labels: needs reporter action

#15080 session <= 3.2: add upper bound on lwt
  packages/session/session.0.1.0/opam
  packages/session/session.0.2.0/opam
  packages/session/session.0.3.0/opam
  packages/session/session.0.3.2/opam
Labels: consider for merge

#15092 [new release] mirage-clock, mirage-clock-unix and mirage-clock-freestanding (3.0.0)
  packages/mirage-clock-freestanding/mirage-clock-freestanding.3.0.0/opam
  packages/mirage-clock-unix/mirage-clock-unix.3.0.0/opam
  packages/mirage-clock/mirage-clock.3.0.0/opam
  packages/mirage-fs-unix/mirage-fs-unix.1.4.1/opam
  packages/mirage-fs-unix/mirage-fs-unix.1.5.0/opam
  packages/mirage-fs-unix/mirage-fs-unix.1.6.0/opam
  packages/mirage-kv-unix/mirage-kv-unix.2.0.0/opam
Labels: needs reporter action

#15100 camlzip version 1.09
  packages/camlzip/camlzip.1.09/opam
Labels: needs reporter action

#15089 Package ocp-indent.1.8.1
  packages/ocp-indent/ocp-indent.1.8.1/opam
Labels: needs reporter action

#15087 z3 opam package update
  packages/z3/z3.4.8.6/opam
Labels: needs reporter action

#15086 Package ocaml-protoc-plugin.2.0.0
  packages/conf-protoc/conf-protoc.0.9/opam
  packages/conf-protoc/conf-protoc.1.0.0/opam
  packages/ocaml-protoc-plugin/ocaml-protoc-plugin.2.0.0/opam
Labels: question

#15077 Patch JS packages for upcoming dune 2
  packages/patdiff/patdiff.v0.12.1/opam
  packages/re2/re2.v0.12.1/opam
  packages/zstandard/zstandard.v0.12.1/opam
Labels: consider for merge, question

#15099 [new release] functoria-runtime and functoria (3.0.1)
  packages/functoria-runtime/functoria-runtime.3.0.1/opam
  packages/functoria/functoria.3.0.1/opam
Labels: needs reporter action

#15116 Package unidecode.0.3.0
  packages/unidecode/unidecode.0.3.0/opam
Labels: needs reporter action

#15117 [new release] duration (0.1.3)
  packages/duration/duration.0.1.3/opam
Labels: needs reporter action

#15118 Package ocaml-lua.1.8
  packages/ocaml-lua/ocaml-lua.1.8/opam
Labels: needs reporter action

#15115 Package unidecode.0.2.0
  packages/unidecode/unidecode.0.2.0/opam
Labels: needs reporter action

#15111 Update mlmpfr package releases
  packages/mlmpfr/mlmpfr.3.1.6/files/test.c
  packages/mlmpfr/mlmpfr.3.1.6/opam
  packages/mlmpfr/mlmpfr.4.0.0/files/test.c
  packages/mlmpfr/mlmpfr.4.0.0/opam
  packages/mlmpfr/mlmpfr.4.0.1/files/test.c
  packages/mlmpfr/mlmpfr.4.0.1/opam
  packages/mlmpfr/mlmpfr.4.0.2/files/test.c
  packages/mlmpfr/mlmpfr.4.0.2/opam
Labels: needs reporter action

#15109 [new release] alg_structs_qcheck and alg_structs (0.1.2)
  packages/alg_structs/alg_structs.0.1.3/opam
  packages/alg_structs_qcheck/alg_structs_qcheck.0.1.3/opam
Labels: needs reporter action

#15137 Package pfff.0.39.1
  packages/pfff/pfff.0.39.1/opam
Labels: needs reporter action

#15131 [new release] elpi (1.8.0)
  packages/elpi/elpi.1.8.0/files/0001-Makefile-pass-DUNE_OPTS-to-dune.patch
  packages/elpi/elpi.1.8.0/opam
Labels: needs reporter action

#15141 Package glfw-ocaml (3.2.1-3)
  packages/glfw-ocaml/glfw-ocaml.3.2.1-3/opam
Labels: consider for merge
