Repository ocaml/opam-repository, pull requests merged in 2019-09, with the labels that each got.

#14768 mlgmpidl.1.2.11
  packages/mlgmpidl/mlgmpidl.1.2.11/opam
Labels: needs reporter action

#14767 Package dolmen.0.4.1
  packages/dolmen/dolmen.0.4.1/opam
Labels: needs reporter action

#14771 Sawja.1.5.7
  packages/sawja/sawja.1.5.7/opam
Labels: needs reporter action

#14772 [new release] elpi (1.7.0)
  packages/elpi/elpi.1.7.0/opam
Labels: needs reporter action

#14777 Add General.0.7.0
  packages/General/General.0.7.0/opam
Labels: needs reporter action

#14766 Add package pxp version 1.2.9
  packages/pxp/pxp.1.2.9/files/408.patch
  packages/pxp/pxp.1.2.9/opam
Labels: needs reporter action

#14763 Add package glMLite version 0.03.52
  packages/conf-libjpeg/conf-libjpeg.1/opam
  packages/glMLite/glMLite.0.03.51/opam
  packages/glMLite/glMLite.0.03.52/opam
  packages/glMLite/glMLite.0.03.53/opam
Labels: needs reporter action

#14765 Add package irrlicht version 0.0.4
  packages/irrlicht/irrlicht.0.0.3/opam
  packages/irrlicht/irrlicht.0.0.5/opam
Labels: needs reporter action

#14764 Add package ocaml-sfml version 0.08
  packages/conf-sfml2/conf-sfml2.1/opam
  packages/sfml/sfml.0.08.2/opam
  packages/sfml/sfml.0.08/opam
Labels: needs reporter action

#14791 Package containers.2.6.1
  packages/containers/containers.2.6.1/opam
Labels: needs reporter action

#14795 Package ocsigen-start.2.4.0
  packages/ocsigen-start/ocsigen-start.2.4.0/opam
Labels: consider for merge

#14814 [new release] dropbox_lwt_unix and dropbox (0.2)
  packages/dropbox/dropbox.0.2/opam
  packages/dropbox_lwt_unix/dropbox_lwt_unix.0.2/opam
Labels: needs reporter action

#14816 i3ipc 0.3
  packages/i3ipc/i3ipc.0.3/opam
Labels: needs reporter action

#14817 Package ISO8601.0.2.6
  packages/ISO8601/ISO8601.0.2.6/opam
Labels: needs reporter action

#14818 [new release] fileutils (0.6.1)
  packages/fileutils/fileutils.0.6.1/opam
Labels: needs reporter action

#14824 [new release] integration1d (0.5.1)
  packages/integration1d/integration1d.0.5.1/opam
Labels: needs reporter action

#14831 Package srt.0.1.0
  packages/srt/srt.0.1.0/opam
Labels: needs reporter action

#14839 [new release] fftw3 (0.8.3)
  packages/fftw3/fftw3.0.8.3/opam
Labels: needs reporter action

#14833 rfsm: add upper bound on lascar
  packages/rfsm/rfsm.1.0/opam
  packages/rfsm/rfsm.1.4.2/opam
  packages/rfsm/rfsm.1.5/opam
  packages/rfsm/rfsm.1.6-alpha-3/opam
Labels: needs reporter action

#14837 Package ocp-indent.1.8.0
  packages/ocp-indent/ocp-indent.1.8.0/opam
Labels: needs reporter action

#14827 [new release] lascar (0.6.0)
  packages/lascar/lascar.0.6.0/opam
Labels: needs reporter action

#14842 Release of OCaml 4.09.0
  packages/ocaml-base-compiler/ocaml-base-compiler.4.09.0/files/ocaml-base-compiler.install
  packages/ocaml-base-compiler/ocaml-base-compiler.4.09.0/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+32bit/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+afl/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+bytecode-only/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+default-unsafe-string/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+flambda+no-flat-float-array/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+force-safe-string/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+fp+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+fp/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+musl+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+musl+static+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+no-flat-float-array/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+spacetime/opam
Labels: needs admin action

#14859 Package archetype.0.1.3
  packages/archetype/archetype.0.1.3/opam
Labels: needs reporter action

#14847 [new release] rfsm (1.6.0)
  packages/rfsm/rfsm.1.6.0/opam
Labels: needs reporter action

#14867 Adds CPDF v2.3
  packages/cpdf/cpdf.2.3/files/cpdf.install
  packages/cpdf/cpdf.2.3/opam
Labels: needs reporter action

#14870 [new release] digestif (0.8.0)
  packages/digestif/digestif.0.8.0/opam
Labels: needs reporter action

#14875 Add Unison 2.48.15
  packages/unison/unison.2.48.15v4/files/ocaml48.patch
  packages/unison/unison.2.48.15v4/files/unison.install
  packages/unison/unison.2.48.15v4/opam
Labels: needs reporter action

#14871 [new release] checkseum (0.1.1)
  packages/checkseum/checkseum.0.1.1/opam
Labels: needs reporter action

#14890 Fix package that fail after OUnit has transitioned to dune.
  packages/debian-formats/debian-formats.0.1.1/opam
  packages/lens/lens.1.1.0/opam
  packages/lens/lens.1.2.0/opam
  packages/qcheck/qcheck.0.5.2/opam
  packages/qcheck/qcheck.0.5.3.1/opam
  packages/qcheck/qcheck.0.5.3/opam
  packages/qcheck/qcheck.0.6/opam
  packages/qcheck/qcheck.0.7/opam
  packages/qmp/qmp.0.9.0/opam
  packages/qmp/qmp.0.9.1/opam
Labels: consider for merge

#14884 Package fdkaac.0.3.1
  packages/fdkaac/fdkaac.0.3.1/opam
Labels: question

#14883 Add irc-client.0.6.2
  packages/irc-client-lwt-ssl/irc-client-lwt-ssl.0.6.2/opam
  packages/irc-client-lwt/irc-client-lwt.0.6.2/opam
  packages/irc-client-tls/irc-client-tls.0.6.2/opam
  packages/irc-client-unix/irc-client-unix.0.6.2/opam
  packages/irc-client/irc-client.0.6.2/opam
Labels: needs reporter action

#14928 Some older versions of ocurl assume unsafe strings
  packages/ocurl/ocurl.0.7.6/opam
  packages/ocurl/ocurl.0.7.7/opam
  packages/ocurl/ocurl.0.7.8/opam
  packages/ocurl/ocurl.0.7.9/opam
Labels: needs reporter action

#14929 pgx_lwt: don't run tests, they call getlogin
  packages/pgx_lwt/pgx_lwt.0.1/opam
Labels: consider for merge

#14930 Restrict zmq-async minimal OCaml/JST version
  packages/zmq-async/zmq-async.5.1.0/opam
Labels: needs reporter action

#14925 release camels version 0.0.3
  packages/camels/camels.0.0.3/opam
Labels: needs reporter action

#14908 2 packages from issuu/ocaml-protoc-plugin at 0.9
  packages/conf-protoc/conf-protoc.0.9/opam
  packages/ocaml-protoc-plugin/ocaml-protoc-plugin.0.9/opam
Labels: question

#14907 [new release] ounit2-lwt, ounit2, ounit-lwt and ounit (2.2.0)
  packages/ounit-lwt/ounit-lwt.2.2.0/opam
  packages/ounit/ounit.2.2.0/opam
  packages/ounit2-lwt/ounit2-lwt.2.2.0/opam
  packages/ounit2/ounit2.2.2.0/opam
Labels: consider for merge, needs reporter action

#14939 Package pfff.0.37.6
  packages/pfff/pfff.0.37.6/opam
Labels: consider for merge

#14927 Package ffmpeg.0.4.1
  packages/ffmpeg/ffmpeg.0.4.1/opam
Labels: consider for merge

#14912 Fix other packages affected by triple-quoting opam bug
  packages/clangml/clangml.3.9.1.2/opam
  packages/clangml/clangml.3.9.1/opam
  packages/libtensorflow/libtensorflow.0.1/opam
  packages/libtorch/libtorch.1.0.0/opam
  packages/libtorch/libtorch.1.0.1/opam
  packages/libtorch/libtorch.1.1.0/opam
  packages/libtorch/libtorch.1.2.0/opam
Labels: needs reporter action

#14937 added packages/daft/daft.0.0.3
  packages/daft/daft.0.0.3/opam
Labels: needs reporter action

#14936 added packages/dokeysto/dokeysto.3.0.2
  packages/dokeysto/dokeysto.3.0.2/opam
Labels: consider for merge
