Repository ocaml/opam-repository, pull requests merged in 2019-12, with the labels that each got.

#15427 jbuilder 1.0+beta20.1
  packages/jbuilder/jbuilder.1.0+beta20.1/opam
Labels: consider for merge

#15415 [new release] mdx (1.5.0)
  packages/containers/containers.2.6.1/opam
  packages/containers/containers.2.6/opam
  packages/mdx/mdx.1.5.0/opam
  packages/routes/routes.0.5.2/opam
Labels: consider for merge, needs reporter action

#15423 Package lua-ml.0.9
  packages/lua-ml/lua-ml.0.9/opam
Labels: consider for merge, needs reporter action

#15431 Blacklist lablgtk3 3.0.beta7 also from Coq 8.10.{0,1}
  packages/coqide/coqide.8.10.0/opam
  packages/coqide/coqide.8.10.1/opam
  packages/coqide/coqide.8.10.2/opam
Labels: question

#15435 sqlite3: add missing dune-configurator dependency
  packages/sqlite3/sqlite3.5.0.1/opam
Labels: consider for merge

#15429 Package soupault.1.6
  packages/soupault/soupault.1.6/opam
Labels: needs reporter action

#15438 Package zmq.5.1.3
  packages/zmq-async/zmq-async.5.1.3/opam
  packages/zmq-lwt/zmq-lwt.5.1.3/opam
  packages/zmq/zmq.5.1.3/opam
Labels: consider for merge

#15434 [new release] pb-plugin and pb (1.0.0)
  packages/pb-plugin/pb-plugin.1.0.0/opam
  packages/pb/pb.1.0.0/opam
Labels: needs reporter action

#15445 Fix rpclib's dependencies
  packages/ppx_deriving_rpc/ppx_deriving_rpc.5.9.0/opam
  packages/ppx_deriving_rpc/ppx_deriving_rpc.6.0.0/opam
  packages/rpclib-async/rpclib-async.5.9.0/opam
  packages/rpclib-async/rpclib-async.6.0.0/opam
  packages/rpclib-lwt/rpclib-lwt.5.9.0/opam
  packages/rpclib-lwt/rpclib-lwt.6.0.0/opam
Labels: consider for merge

#15443 Update conf-mariadb to work with recent alpine releases
  packages/conf-mariadb/conf-mariadb.2/opam
Labels: needs reporter action

#15440 [new release] minicaml (0.1)
  packages/minicaml/minicaml.0.1/opam
Labels: needs reporter action

#15446 [new release] nuscr (1.0.0)
  packages/nuscr/nuscr.1.0.0/opam
Labels: consider for merge, needs reporter action

#15457 GT.0.2.0
  packages/GT/GT.0.2.0/opam
Labels: consider for merge

#15466 [new release] rpclib, rpclib-lwt, rpclib-async, rpclib-html, rpclib-js and ppx_deriving_rpc (7.0.0)
  packages/ppx_deriving_rpc/ppx_deriving_rpc.7.0.0/opam
  packages/rpclib-async/rpclib-async.7.0.0/opam
  packages/rpclib-html/rpclib-html.7.0.0/opam
  packages/rpclib-js/rpclib-js.7.0.0/opam
  packages/rpclib-lwt/rpclib-lwt.7.0.0/opam
  packages/rpclib/rpclib.7.0.0/opam
Labels: consider for merge

#15464 [new release] rpclib, rpclib-lwt, rpclib-async, rpclib-html, rpclib-js and ppx_deriving_rpc (6.1.0)
  packages/ppx_deriving_rpc/ppx_deriving_rpc.6.1.0/opam
  packages/rpclib-async/rpclib-async.6.1.0/opam
  packages/rpclib-html/rpclib-html.6.1.0/opam
  packages/rpclib-js/rpclib-js.6.1.0/opam
  packages/rpclib-lwt/rpclib-lwt.6.1.0/opam
  packages/rpclib/rpclib.6.1.0/opam
Labels: consider for merge

#15467 [new release] owl-zoo, owl-top, owl-base, owl and owl-plplot (0.7.2)
  packages/owl-base/owl-base.0.7.2/opam
  packages/owl-plplot/owl-plplot.0.7.2/opam
  packages/owl-top/owl-top.0.7.2/opam
  packages/owl-zoo/owl-zoo.0.7.2/opam
  packages/owl/owl.0.7.2/opam
Labels: consider for merge

#15479 [new release] idds (0.2)
  packages/idds/idds.0.2/opam
Labels: needs reporter action

#15463 Package remu_ts.0.1
  packages/remu_ts/remu_ts.0.1/opam
Labels: needs reporter action

#15480 Package ppx_string_interpolation.1.0.0
  packages/ppx_string_interpolation/ppx_string_interpolation.1.0.0/opam
Labels: needs reporter action

#15366 Package pixel_pusher.1.0
  packages/pixel_pusher/pixel_pusher.1.0/opam
Labels: needs reporter action

#15461 added packages/conf-haveged/conf-havaged.1.0.0
  packages/conf-haveged/conf-haveged.1.0.0/opam
Labels: needs reporter action

#15488 [new release] curve-sampling and curve-sampling-cairo (0.2)
  packages/curve-sampling/curve-sampling.0.2/opam
Labels: needs reporter action

#15482 Add the tqdm package.
  packages/tqdm/tqdm.0.1/opam
Labels: needs reporter action

#15490 [new release] csv, csvtool and csv-lwt (2.4)
  packages/csv-lwt/csv-lwt.2.4/opam
  packages/csv/csv.2.4/opam
  packages/csvtool/csvtool.2.4/opam
Labels: needs reporter action

#15489 [new release] color-brewery (0.1)
  packages/color-brewery/color-brewery.0.1/opam
Labels: needs reporter action

#15455 [new release] graphics (5.1.0)
  packages/graphics/graphics.5.1.0/opam
Labels: needs reporter action

#15497 Markup.ml 0.8.2 - standards-compliant HTML parser
  packages/markup/markup.0.8.2/opam
Labels: needs reporter action

#15506 Install Stog binaries
  packages/stog/stog.0.18.0-1/opam
Labels: needs reporter action

#15510 [jingoo] Release version 1.3.2
  packages/jingoo/jingoo.1.3.2/opam
Labels: question

#15507 [new release] emile (0.6)
  packages/emile/emile.0.6/opam
Labels: needs reporter action

#15525 [new release] minicaml (0.2.1)
  packages/minicaml/minicaml.0.2.1/opam
Labels: needs reporter action

#15520 Package eigen.0.1.6
  packages/eigen/eigen.0.1.6/opam
Labels: consider for merge

#15514 Add upper bounds on bencode
  packages/cconv-ppx/cconv-ppx.0.5/opam
  packages/cconv/cconv.0.1/opam
  packages/cconv/cconv.0.2/opam
  packages/cconv/cconv.0.3.1/opam
  packages/cconv/cconv.0.3/opam
  packages/cconv/cconv.0.4/opam
  packages/cconv/cconv.0.5/opam
  packages/decoders-bencode/decoders-bencode.0.3.0/opam
Labels: needs maintainer action

#15516 + cbor 0.3
  packages/cbor/cbor.0.3/opam
Labels: needs reporter action

#15505 2 packages from darioteixeira/pgocaml at 4.2
  packages/pgocaml/pgocaml.4.2/opam
  packages/pgocaml_ppx/pgocaml_ppx.4.2/opam
Labels: needs reporter action

#15528 [new release] ppx_factory (0.1.0)
  packages/ppx_factory/ppx_factory.0.1.0/opam
Labels: needs reporter action

#15532 [new release] js_of_ocaml, js_of_ocaml-ocamlbuild, js_of_ocaml-ppx_deriving_json, js_of_ocaml-tyxml, js_of_ocaml-ppx, js_of_ocaml-lwt, js_of_ocaml-compiler and js_of_ocaml-toplevel (3.5.2)
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.3.5.2/opam
  packages/js_of_ocaml-lwt/js_of_ocaml-lwt.3.5.2/opam
  packages/js_of_ocaml-ocamlbuild/js_of_ocaml-ocamlbuild.3.5.2/opam
  packages/js_of_ocaml-ppx/js_of_ocaml-ppx.3.5.2/opam
  packages/js_of_ocaml-ppx_deriving_json/js_of_ocaml-ppx_deriving_json.3.5.2/opam
  packages/js_of_ocaml-toplevel/js_of_ocaml-toplevel.3.5.2/opam
  packages/js_of_ocaml-tyxml/js_of_ocaml-tyxml.3.5.2/opam
  packages/js_of_ocaml/js_of_ocaml.3.5.2/opam
Labels: consider for merge

#15527 Package radare2.0.0.3
  packages/radare2/radare2.0.0.3/opam
Labels: needs reporter action

#15535 Package containers.2.8
  packages/containers/containers.2.8/opam
  packages/msat/msat.0.8/opam
Labels: question

#15537 Package pacomb.0.1
  packages/pacomb/pacomb.1.0/opam
Labels: needs reporter action

#15502 Package fadbadml.0.1
  packages/fadbadml/fadbadml.0.1/opam
Labels: needs reporter action

#15562 restrict to core<0.13.0 for packages that use polymorphic comparison
  packages/horned_worm/horned_worm.0.3.1/opam
  packages/horned_worm/horned_worm.0.3.2/opam
  packages/horned_worm/horned_worm.0.3.3/opam
  packages/horned_worm/horned_worm.0.3.4/opam
  packages/horned_worm/horned_worm.0.3.5/opam
  packages/websocket-async/websocket-async.2.10/opam
  packages/websocket-async/websocket-async.2.11/opam
  packages/websocket-async/websocket-async.2.12/opam
  packages/websocket-async/websocket-async.2.13/opam
Labels: needs reporter action

#15509 Fix jingoo build under opam sandbox
  packages/jingoo/jingoo.1.3.0-1/opam
  packages/jingoo/jingoo.1.3.1-1/opam
Labels: needs reporter action, question

#15563 wcs: use jbuilder to build
  packages/wcs-api/wcs-api.2017-05-26.01/opam
  packages/wcs-api/wcs-api.2017-05-26.02/opam
  packages/wcs-api/wcs-api.2017-05-26.03/opam
  packages/wcs-api/wcs-api.2017-05-26.04/opam
  packages/wcs-lib/wcs-lib.2017-05-26.00/opam
  packages/wcs-lib/wcs-lib.2017-05-26.01/opam
  packages/wcs-lib/wcs-lib.2017-05-26.02/opam
  packages/wcs-lib/wcs-lib.2017-05-26.03/opam
  packages/wcs-lib/wcs-lib.2017-05-26.04/opam
  packages/wcs-lib/wcs-lib.2017-05-26.05/opam
Labels: consider for merge

#15572 [new release] mirage-nat (2.0.0)
  packages/mirage-nat/mirage-nat.2.0.0/opam
Labels: question

#15565 [new release] routes (0.6.0)
  packages/routes/routes.0.6.0/opam
Labels: needs reporter action

#15574 Release ppx_compose.0.1.0.
  packages/ppx_compose/ppx_compose.0.1.0/opam
Labels: needs reporter action

#15587 [new release] Package ppx_rapper.0.9.2
  packages/ppx_rapper/ppx_rapper.0.9.2/opam
Labels: needs reporter action

#15595 Package ppx_wideopen.0.0.1
  packages/ppx_wideopen/ppx_wideopen.0.0.1/opam
Labels: needs reporter action

#15615 [new release] fftw3 (0.8.4)
  packages/fftw3/fftw3.0.8.4/opam
Labels: needs reporter action

#15617 Package lambda-term.2.0.3
  packages/lambda-term/lambda-term.2.0.3/opam
Labels: needs reporter action

#15610 Package gobject-introspection.0.2
  packages/gobject-introspection/gobject-introspection.0.2/opam
Labels: needs reporter action

#15619 Mark various package as incompatible with OCaml 4.10
  packages/links/links.0.9/opam
  packages/ppxlib/ppxlib.0.7.0/opam
  packages/ppxlib/ppxlib.0.8.0/opam
  packages/ppxlib/ppxlib.0.8.1/opam
Labels: consider for merge
