Repository ocaml/opam-repository, pull requests merged in 2019-03, with the labels that each got.

#13554 Package mariadb.1.1.2
  packages/mariadb/mariadb.1.1.2/opam
Labels: consider for merge

#13165 switch objsize to backup copy since upstream is gone
  packages/objsize/objsize.0.17/opam
  packages/objsize/objsize.0.18/opam
Labels: needs reporter action

#13560 Package cohttp-mirage.2.1.0
  packages/cohttp-mirage/cohttp-mirage.2.1.0/opam
Labels: consider for merge

#13561 Package eigen.0.1.2
  packages/eigen/eigen.0.1.2/opam
Labels: consider for merge

#13563 tar-mirage implements mirage-kv: needs to conflict with mirage-kv 2.0.0
  packages/tar-mirage/tar-mirage.0.8.0/opam
  packages/tar-mirage/tar-mirage.0.9.0/opam
  packages/tar-mirage/tar-mirage.1.0.0/opam
  packages/tar-mirage/tar-mirage.1.0.1/opam
  packages/tar/tar.0.8.0/opam
Labels: consider for merge

#13580 Added the initial release of the mmdb package
  packages/mmdb/mmdb.0.1.0/opam
Labels: question

#13593 Package py.1.2
  packages/py/py.1.2/opam
Labels: needs reporter action

#13582 Package eigen.0.1.3
  packages/eigen/eigen.0.1.3/opam
Labels: consider for merge

#13585 owl: add upper bounds
  packages/owl-zoo/owl-zoo.0.3.7/opam
  packages/owl/owl.0.3.7/opam
  packages/owl/owl.0.3.8/opam
  packages/owl/owl.0.4.0/opam
Labels: consider for merge

#13584 [new release] owl-zoo, owl-top, owl-base, owl and owl-plplot (0.5.0)
  packages/owl-base/owl-base.0.5.0/opam
  packages/owl-plplot/owl-plplot.0.5.0/opam
  packages/owl-top/owl-top.0.5.0/opam
  packages/owl-zoo/owl-zoo.0.5.0/opam
  packages/owl/owl.0.5.0/opam
Labels: consider for merge

#13509 Package fluent-logger.1.1.0
  packages/fluent-logger/fluent-logger.1.1.0/opam
Labels: needs reporter action

#13556 bddapron.2.2.5
  packages/bddapron/bddapron.2.2.5/opam
Labels: needs reporter action

#13591 [new release] sedlex (v2.0)
  packages/ccss/ccss.1.6/opam
  packages/flow_parser/flow_parser.0.46.0/opam
  packages/flow_parser/flow_parser.0.47.0/opam
  packages/flow_parser/flow_parser.0.52.0/opam
  packages/flow_parser/flow_parser.0.62.0/opam
  packages/flow_parser/flow_parser.0.80.0/opam
  packages/flowtype/flowtype.0.62.0/opam
  packages/flowtype/flowtype.0.64.0/opam
  packages/flowtype/flowtype.0.72.0/opam
  packages/flowtype/flowtype.0.78.0/opam
  packages/flowtype/flowtype.0.79.0/opam
  packages/flowtype/flowtype.0.79.1/opam
  packages/flowtype/flowtype.0.80.0/opam
  packages/frenetic/frenetic.5.0.3/opam
  packages/iri/iri.0.4.0/opam
  packages/minimal/minimal.1.1.0/opam
  packages/rdf/rdf.0.11.0/opam
  packages/sedlex/sedlex.2.0/opam
  packages/sgf/sgf.1.0/opam
  packages/snabela/snabela.1.0/opam
  packages/xtmpl/xtmpl.0.17.0/opam
Labels: needs reporter action

#13600 2 packages from owlbarn/owl_ode at 0.0.7
  packages/owl-ode-sundials/owl-ode-sundials.0.0.7/opam
  packages/owl-ode/owl-ode.0.0.7/opam
Labels: consider for merge

#13605 [new release] dune (1.8.0)
  packages/dune/dune.1.8.0/opam
Labels: consider for merge

#13592 [new release] combinat (1.0)
  packages/combinat/combinat.1.0/opam
Labels: needs reporter action

#13416 added packages/ancient/ancient.0.9.1
  packages/ancient/ancient.0.9.1/opam
Labels: consider for merge

#13606 The great Iter migration.
  packages/sequence/sequence.0.1/opam
  packages/sequence/sequence.0.10/opam
  packages/sequence/sequence.0.11/opam
  packages/sequence/sequence.0.2/opam
  packages/sequence/sequence.0.3.1/opam
  packages/sequence/sequence.0.3.2/opam
  packages/sequence/sequence.0.3.3/opam
  packages/sequence/sequence.0.3.4/opam
  packages/sequence/sequence.0.3.5/opam
  packages/sequence/sequence.0.3.6.1/opam
  packages/sequence/sequence.0.3.6/opam
  packages/sequence/sequence.0.3.7/opam
  packages/sequence/sequence.0.3/opam
  packages/sequence/sequence.0.4.1/opam
  packages/sequence/sequence.0.4/opam
  packages/sequence/sequence.0.5.1/opam
  packages/sequence/sequence.0.5.2/opam
  packages/sequence/sequence.0.5.3/opam
  packages/sequence/sequence.0.5.4/opam
  packages/sequence/sequence.0.5.5/opam
  packages/sequence/sequence.0.5/opam
  packages/sequence/sequence.0.6/opam
  packages/sequence/sequence.0.7/opam
  packages/sequence/sequence.0.8/opam
  packages/sequence/sequence.0.9/opam
  packages/sequence/sequence.1.0/opam
  packages/sequence/sequence.1.1/opam
Labels: needs reporter action

#13568 +session.0.4.1
  packages/session-cohttp-async/session-cohttp-async.0.4.1/opam
  packages/session-cohttp-lwt/session-cohttp-lwt.0.4.1/opam
  packages/session-cohttp/session-cohttp.0.4.1/opam
  packages/session-postgresql-async/session-postgresql-async.0.4.1/opam
  packages/session-postgresql-lwt/session-postgresql-lwt.0.4.1/opam
  packages/session-postgresql/session-postgresql.0.4.1/opam
  packages/session-redis-lwt/session-redis-lwt.0.4.1/opam
  packages/session-webmachine/session-webmachine.0.4.1/opam
  packages/session/session.0.4.1/opam
Labels: question

#13569 +angstrom.0.11.1
  packages/angstrom-async/angstrom-async.0.11.1/opam
  packages/angstrom-lwt-unix/angstrom-lwt-unix.0.11.1/opam
  packages/angstrom-unix/angstrom-unix.0.11.1/opam
  packages/angstrom/angstrom.0.11.1/opam
Labels: question

#13613 Package bitcoinml.0.4.1
  packages/bitcoinml/bitcoinml.0.4.1/opam
Labels: consider for merge

#13619 Package uuidm.0.9.7
  packages/uuidm/uuidm.0.9.7/opam
Labels: consider for merge

#13626 [new release] iter (1.2)
  packages/iter/iter.1.2/opam
Labels: consider for merge

#13620 [new release] dune (1.8.1)
  packages/dune/dune.1.8.1/opam
Labels: question

#13661 Package stdcompat.9
  packages/ocamlcodoc/ocamlcodoc.1.0.0/opam
  packages/stdcompat/stdcompat.9/opam
Labels: needs reporter action

#13672 added packages/hack_parallel/hack_parallel.0.1.1
  packages/hack_parallel/hack_parallel.0.1.1/opam
Labels: needs reporter action

#13677 re-remove upper bounds on sexplib <v0.12.0
  packages/cstruct-async/cstruct-async.3.3.0/opam
  packages/cstruct-async/cstruct-async.3.4.0/opam
  packages/cstruct-async/cstruct-async.3.5.0/opam
  packages/cstruct/cstruct.3.3.0/opam
  packages/cstruct/cstruct.3.4.0/opam
  packages/cstruct/cstruct.3.5.0/opam
  packages/nocrypto/nocrypto.0.5.4-1/opam
Labels: consider for merge

#13694 Package textrazor.0.1
  packages/textrazor/textrazor.0.1/opam
Labels: needs reporter action

#13685 Patch ocamlfind to elimitate the check for awk
  packages/ocamlfind/ocamlfind.1.3.1/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.3.1/opam
  packages/ocamlfind/ocamlfind.1.3.2/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.3.2/opam
  packages/ocamlfind/ocamlfind.1.3.3/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.3.3/opam
  packages/ocamlfind/ocamlfind.1.4.0/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.4.0/opam
  packages/ocamlfind/ocamlfind.1.4.1/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.4.1/opam
  packages/ocamlfind/ocamlfind.1.5.1/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.5.1/opam
  packages/ocamlfind/ocamlfind.1.5.2/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.5.2/opam
  packages/ocamlfind/ocamlfind.1.5.3/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.5.3/opam
  packages/ocamlfind/ocamlfind.1.5.4/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.5.4/opam
  packages/ocamlfind/ocamlfind.1.5.5/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.5.5/opam
  packages/ocamlfind/ocamlfind.1.5.6/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.5.6/opam
  packages/ocamlfind/ocamlfind.1.6.1/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.6.1/opam
  packages/ocamlfind/ocamlfind.1.6.2/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.6.2/opam
  packages/ocamlfind/ocamlfind.1.7.1/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.7.1/opam
  packages/ocamlfind/ocamlfind.1.7.2/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.7.2/opam
  packages/ocamlfind/ocamlfind.1.7.3-1/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.7.3-1/opam
  packages/ocamlfind/ocamlfind.1.7.3/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.7.3/opam
  packages/ocamlfind/ocamlfind.1.8.0/files/no-awk-check.patch
  packages/ocamlfind/ocamlfind.1.8.0/opam
Labels: help wanted, question

#13703 + qfs 0.9
  packages/qfs/qfs.0.9/opam
Labels: needs reporter action

#13700 Package easy_logging.0.1
  packages/easy_logging/easy_logging.0.1/opam
Labels: needs reporter action

#13713 + devkit 1.0
  packages/devkit/devkit.1.0/opam
  packages/elasticsearch-cli/elasticsearch-cli.0.1/opam
  packages/elasticsearch-cli/elasticsearch-cli.0.2/opam
  packages/elasticsearch-cli/elasticsearch-cli.0.3/opam
  packages/elasticsearch-cli/elasticsearch-cli.0.4/opam
Labels: question

#13721 libevent: add suse depexts
  packages/libevent/libevent.0.8.1/opam
Labels: consider for merge

#13720 Package owl-ode.0.0.8
  packages/owl-ode/owl-ode.0.0.8/opam
Labels: consider for merge

#13714 The gcc in OpenBSD base is too old(compilation fails), default to cc (aka clang)
  packages/zarith-freestanding/zarith-freestanding.1.7-2/files/mirage-build.sh
  packages/zarith-freestanding/zarith-freestanding.1.7-2/files/mirage-install.sh
  packages/zarith-freestanding/zarith-freestanding.1.7-2/files/mirage-uninstall.sh
  packages/zarith-freestanding/zarith-freestanding.1.7-2/files/no-dynlink.patch
  packages/zarith-freestanding/zarith-freestanding.1.7-2/opam
Labels: help wanted

#13732 Package spelll.0.3
  packages/archsat/archsat.1.0/opam
  packages/spelll/spelll.0.3/opam
Labels: consider for merge

#13729 cohttp: add conditional bounds
  packages/cohttp-lwt-unix/cohttp-lwt-unix.1.0.0/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.1.1.1/opam
Labels: needs admin action

#13730 containers: fix deps in with-test mode
  packages/containers/containers.2.2/opam
  packages/containers/containers.2.3/opam
  packages/containers/containers.2.4.1/opam
  packages/containers/containers.2.4/opam
  packages/containers/containers.2.5/opam
Labels: consider for merge

#13742 Bisect_ppx 1.4.1: code coverage for OCaml
  packages/bisect_ppx/bisect_ppx.1.4.1/opam
Labels: question

#13739 New package iso639.0.0.4
  packages/iso639/iso639.0.0.4/opam
Labels: needs reporter action

#13706 [new release] cairo2, cairo2-pango and cairo2-gtk (0.6.1)
  packages/cairo2-gtk/cairo2-gtk.0.6.1/opam
  packages/cairo2-pango/cairo2-pango.0.6.1/opam
  packages/cairo2/cairo2.0.6.1/opam
Labels: question

#13707 Package pgocaml.3.0
  packages/pgocaml/pgocaml.3.0/opam
Labels: needs reporter action

#13701 Package lascar.0.5
  packages/lascar/lascar.0.5/opam
  packages/rfsm/rfsm.1.0/opam
Labels: needs reporter action

#13752 Package bigarray-compat.1.0.0
  packages/bigarray-compat/bigarray-compat.1.0.0/opam
Labels: needs reporter action

#13754 opam-publish.0.3.5: base64 module conflict stops this from linking
  packages/opam-publish/opam-publish.0.3.5/opam
Labels: needs reporter action

#13765 [new release] hpack, h2-mirage, h2-lwt, h2 and h2-lwt-unix (0.1.0)
  packages/h2-lwt-unix/h2-lwt-unix.0.1.0/opam
  packages/h2-lwt/h2-lwt.0.1.0/opam
  packages/h2-mirage/h2-mirage.0.1.0/opam
  packages/h2/h2.0.1.0/opam
  packages/hpack/hpack.0.1.0/opam
Labels: needs reporter action
