Repository ocaml/opam-repository, pull requests merged in 2020-07, with the labels that each got.

#16739 Package jhupllib.0.2.2
  packages/jhupllib/jhupllib.0.2.2/opam
Labels: consider for merge

#16736 Package bogue.20200630
  packages/bogue/bogue.20200630/opam
Labels: needs reporter action

#16766 + mldonkey 3.1.7-2
  packages/mldonkey/mldonkey.3.1.7-2/files/mldonkey.install
  packages/mldonkey/mldonkey.3.1.7-2/opam
Labels: needs reporter action

#16767 Package letters.0.1.0
  packages/letters/letters.0.1.0/opam
Labels: needs reporter action

#16781 [new release] current_web, current_github, current_docker, current, current_git, current_slack, current_ansi, current_rpc, current_incr and current_examples (0.3)
  packages/current/current.0.3/opam
  packages/current_ansi/current_ansi.0.3/opam
  packages/current_docker/current_docker.0.3/opam
  packages/current_examples/current_examples.0.3/opam
  packages/current_git/current_git.0.3/opam
  packages/current_github/current_github.0.3/opam
  packages/current_incr/current_incr.0.3/opam
  packages/current_rpc/current_rpc.0.3/opam
  packages/current_slack/current_slack.0.3/opam
  packages/current_web/current_web.0.3/opam
Labels: consider for merge

#16795 Release slap v4.1.1
  packages/slap/slap.4.1.1/opam
Labels: consider for merge

#16787 Package camlp5.8.00~alpha01
  packages/camlp5/camlp5.8.00~alpha01/opam
  packages/elpi/elpi.1.0.5/opam
  packages/elpi/elpi.1.1.0/opam
  packages/elpi/elpi.1.1.1/opam
  packages/elpi/elpi.1.10.0/opam
  packages/elpi/elpi.1.10.1/opam
  packages/elpi/elpi.1.10.2/opam
  packages/elpi/elpi.1.11.0/opam
  packages/elpi/elpi.1.11.1/opam
  packages/elpi/elpi.1.11.2/opam
  packages/elpi/elpi.1.2.0/opam
  packages/elpi/elpi.1.3.1/opam
  packages/elpi/elpi.1.4.0/opam
  packages/elpi/elpi.1.4.1/opam
  packages/elpi/elpi.1.5.2/opam
  packages/elpi/elpi.1.6.0/opam
  packages/elpi/elpi.1.7.0/opam
  packages/elpi/elpi.1.8.0/opam
  packages/elpi/elpi.1.9.0/opam
  packages/elpi/elpi.1.9.1/opam
  packages/ledit/ledit.2.03/opam
  packages/ledit/ledit.2.04/opam
  packages/ulex-camlp5/ulex-camlp5.1.2/opam
Labels: consider for merge

#16789 Package yices2_bindings.0.1
  packages/yices2_bindings/yices2_bindings.0.1/opam
Labels: consider for merge

#16810 [new release] dune-release (1.4.0)
  packages/dune-release/dune-release.1.4.0/opam
Labels: consider for merge

#16814 Fix camlp5 also for coq < 8.8
  packages/coq/coq.8.3/opam
  packages/coq/coq.8.4.5/opam
  packages/coq/coq.8.4.6/opam
  packages/coq/coq.8.4.6~camlp4/opam
  packages/coq/coq.8.4pl1/opam
  packages/coq/coq.8.4pl2/opam
  packages/coq/coq.8.4pl4/opam
  packages/coq/coq.8.5.0/opam
  packages/coq/coq.8.5.1/opam
  packages/coq/coq.8.5.2/opam
  packages/coq/coq.8.5.3/opam
  packages/coq/coq.8.6.1/opam
  packages/coq/coq.8.6/opam
  packages/coq/coq.8.7.0/opam
  packages/coq/coq.8.7.1+1/opam
  packages/coq/coq.8.7.1+2/opam
  packages/coq/coq.8.7.1/opam
  packages/coq/coq.8.7.2/opam
Labels: consider for merge

#16807 new file: packages/pardi/pardi.3.1.1/opam
  packages/pardi/pardi.3.1.1/opam
Labels: needs reporter action

#16818 [new release] alcotest-lwt, alcotest, alcotest-async and alcotest-mirage (1.2.1)
  packages/alcotest-async/alcotest-async.1.2.1/opam
  packages/alcotest-lwt/alcotest-lwt.1.2.1/opam
  packages/alcotest-mirage/alcotest-mirage.1.2.1/opam
  packages/alcotest/alcotest.1.2.1/opam
  packages/current/current.0.2/opam
  packages/current/current.0.3/opam
Labels: consider for merge

#16824 Add bitmasks.1.2.0
  packages/bitmasks/bitmasks.1.2.0/opam
Labels: needs reporter action

#16821 Package wikitext.1.0.0
  packages/wikitext/wikitext.1.0.0/opam
Labels: consider for merge

#16836 Package ubase.0.03
  packages/ubase/ubase.0.03/opam
Labels: consider for merge

#16805 Luv 0.5.4
  packages/luv/luv.0.5.4/opam
Labels: needs reporter action

#16830 package "funfields" version 0.04
  packages/funbits/funbits.0.0.0/opam
  packages/funbits/funbits.0.02/opam
  packages/funfields/funfields.0.02/opam
  packages/funfields/funfields.0.03/opam
  packages/funfields/funfields.0.04/opam
Labels: needs reporter action

#16621 Package scipy.sp1.4-0.3.0
  packages/scipy/scipy.sp1.4-0.3.0/opam
Labels: consider for merge

#16849 [new release] cohttp-lwt-jsoo, cohttp, cohttp-lwt, cohttp-lwt-unix, cohttp-top, cohttp-async and cohttp-mirage (2.5.4)
  packages/cohttp-async/cohttp-async.2.5.4/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.2.5.4/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.2.5.4/opam
  packages/cohttp-lwt/cohttp-lwt.2.5.4/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.4/opam
  packages/cohttp-top/cohttp-top.2.5.4/opam
  packages/cohttp/cohttp.2.5.4/opam
Labels: consider for merge

#16835 Package pa_ppx.0.01
  packages/pa_ppx/pa_ppx.0.01/opam
Labels: question

#16870 [new release] reparse (1.0.0)
  packages/reparse/reparse.1.0.0/opam
Labels: consider for merge

#16883 Package ppx_cstubs.0.4.3
  packages/ppx_cstubs/ppx_cstubs.0.4.3/opam
Labels: needs reporter action

#16894 Update systemverilog repo information
  packages/systemverilog/systemverilog.0.0.1/opam
  packages/systemverilog/systemverilog.0.0.2/opam
Labels: consider for merge

#16901 Update NetML URL
  packages/netml/netml.0.1.0/opam
Labels: consider for merge

#16910 2 packages from OCamlPro/ocp-index at 1.2.1
  packages/ocp-browser/ocp-browser.1.2.1/opam
  packages/ocp-index/ocp-index.1.2.1/opam
Labels: consider for merge

#16900 [new release] ezjsonm-lwt and ezjsonm (1.2.0)
  packages/ezjsonm-lwt/ezjsonm-lwt.1.2.0/opam
  packages/ezjsonm/ezjsonm.1.2.0/opam
  packages/mirage-tc/mirage-tc.0.3.0/opam
  packages/mustache/mustache.2.0.0/opam
  packages/opium_kernel/opium_kernel.0.16.0/opam
  packages/opium_kernel/opium_kernel.0.17.0/opam
  packages/opium_kernel/opium_kernel.0.17.1/opam
Labels: consider for merge
