Repository ocaml/opam-repository, pull requests merged in 2020-12, with the labels that each got.

#17732 Add ez_cmdliner.0.2.0
  packages/ez_cmdliner/ez_cmdliner.0.2.0/opam
Labels: needs reporter action

#17736 [new release] logs-syslog (0.3.0)
  packages/logs-syslog/logs-syslog.0.3.0/opam
Labels: consider for merge

#17704 Package gmp.6.2.1
  packages/gmp/gmp.6.2.1/opam
Labels: needs reporter action, question

#17703 [new release] conf-libclang.11
  packages/conf-libclang/conf-libclang.11/files/configure.sh
  packages/conf-libclang/conf-libclang.11/opam
Labels: consider for merge, question

#17749 [new release] mirage, mirage-runtime, mirage-types-lwt and mirage-types (3.10.0)
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.8.0/opam
  packages/mirage-runtime/mirage-runtime.3.10.0/opam
  packages/mirage-types-lwt/mirage-types-lwt.3.10.0/opam
  packages/mirage-types/mirage-types.3.10.0/opam
  packages/mirage/mirage.3.10.0/opam
Labels: consider for merge

#17752 [new release] dap (1.0.0)
  packages/dap/dap.1.0.0/opam
Labels: consider for merge

#17754 [new release] key-parsers (1.0.0)
  packages/key-parsers/key-parsers.1.0.0/opam
  packages/pkcs11/pkcs11.0.9.0/opam
Labels: consider for merge

#17772 [new release] dap (1.0.1)
  packages/dap/dap.1.0.1/opam
Labels: consider for merge

#17766 package Frama-C plugin MetAcsl
  packages/conf-swi-prolog/conf-swi-prolog.1/opam
  packages/frama-c-metacsl/frama-c-metacsl.0.1/opam
Labels: consider for merge

#17690 Packaging coq-native
  packages/coq-native/coq-native.1/opam
  packages/coq/coq.8.10.0/opam
  packages/coq/coq.8.10.1/opam
  packages/coq/coq.8.10.2/opam
  packages/coq/coq.8.11.0/opam
  packages/coq/coq.8.11.1/opam
  packages/coq/coq.8.11.2/opam
  packages/coq/coq.8.12.0/opam
  packages/coq/coq.8.12.1/opam
  packages/coq/coq.8.5.0/opam
  packages/coq/coq.8.5.0~camlp4/opam
  packages/coq/coq.8.5.1/opam
  packages/coq/coq.8.5.2/opam
  packages/coq/coq.8.5.2~camlp4/opam
  packages/coq/coq.8.5.3/opam
  packages/coq/coq.8.6.1/opam
  packages/coq/coq.8.6/opam
  packages/coq/coq.8.7.0/opam
  packages/coq/coq.8.7.1+1/opam
  packages/coq/coq.8.7.1+2/opam
  packages/coq/coq.8.7.1/opam
  packages/coq/coq.8.7.2/opam
  packages/coq/coq.8.8.0/opam
  packages/coq/coq.8.8.1/opam
  packages/coq/coq.8.8.2/opam
  packages/coq/coq.8.9.0/opam
  packages/coq/coq.8.9.1/opam
Labels: consider for merge

#17776 Add the wasmtime package
  packages/libwasmtime/libwasmtime.0.21.0+linux-x86_64/opam
  packages/libwasmtime/libwasmtime.0.21.0+macos-x86_64/opam
  packages/wasmtime/wasmtime.0.0.1/opam
Labels: consider for merge

#17743 +httpaf.0.7.0
  packages/httpaf-async/httpaf-async.0.7.0/opam
  packages/httpaf-lwt-unix/httpaf-lwt-unix.0.7.0/opam
  packages/httpaf/httpaf.0.7.0/opam
Labels: needs reporter action

#17802 macOS 11 / XCode 12 fix for remake (used by gappa)
  packages/gappa/gappa.1.3.5/files/remake.patch
Labels: needs reporter action

#17817 Update bitstring and ppx_bitstring to 4.1.0
  packages/bitstring/bitstring.4.1.0/opam
  packages/ppx_bitstring/ppx_bitstring.4.1.0/opam
Labels: consider for merge

#17824 Package pulseaudio.0.1.4
  packages/conf-pulseaudio/conf-pulseaudio.1/opam
  packages/pulseaudio/pulseaudio.0.1.4/opam
Labels: consider for merge

#17827 +tezos-rust-libs.1.0
  packages/tezos-rust-libs/tezos-rust-libs.1.0/opam
Labels: consider for merge

#17801 Update conf-zmq
  packages/conf-zmq/conf-zmq.0.1/opam
Labels: consider for merge

#17800 Add feather 0.1.0 and feather async 0.1.0
  packages/feather/feather.0.1.0/opam
  packages/feather_async/feather_async.0.1.0/opam
Labels: needs reporter action

#17840 Package ppx_deriving_jsoo.0.2
  packages/ppx_deriving_jsoo/ppx_deriving_jsoo.0.2/opam
Labels: needs reporter action

#17820 2 packages from leviroth/ocaml-reddit-api at 0.1.0
  packages/reddit_api_async/reddit_api_async.0.1.0/opam
  packages/reddit_api_kernel/reddit_api_kernel.0.1.0/opam
Labels: needs reporter action

#17810 Import new versions for packages in xapi-project/xs-opam
  packages/cdrom/cdrom.0.9.4/opam
  packages/crc/crc.2.1.0/opam
  packages/dlm/dlm.0.3.1/opam
  packages/ezxenstore/ezxenstore.0.4.1/opam
  packages/fd-send-recv/fd-send-recv.2.0.1/opam
  packages/nbd/nbd.4.0.3/opam
  packages/netlink/netlink.0.3.4/opam
  packages/xapi-backtrace/xapi-backtrace.0.7/opam
  packages/xapi-inventory/xapi-inventory.1.2.1/opam
  packages/xapi-rrd/xapi-rrd.1.8.2/opam
  packages/xapi-stdext-pervasives/xapi-stdext-pervasives.4.14.0/opam
  packages/xapi-stdext-std/xapi-stdext-std.4.14.0/opam
  packages/xapi-stdext-threads/xapi-stdext-threads.4.14.0/opam
  packages/xapi-stdext-unix/xapi-stdext-unix.4.14.0/opam
Labels: consider for merge

#17844 [new release] sihl-web, sihl-email, sihl-persistence, sihl-type, sihl-contract, sihl-core, sihl-queue, sihl-user, sihl-storage and sihl (0.2.2)
  packages/sihl-contract/sihl-contract.0.2.2/opam
  packages/sihl-core/sihl-core.0.2.2/opam
  packages/sihl-email/sihl-email.0.2.2/opam
  packages/sihl-persistence/sihl-persistence.0.2.2/opam
  packages/sihl-queue/sihl-queue.0.2.2/opam
  packages/sihl-storage/sihl-storage.0.2.2/opam
  packages/sihl-type/sihl-type.0.2.2/opam
  packages/sihl-user/sihl-user.0.2.2/opam
  packages/sihl-web/sihl-web.0.2.2/opam
  packages/sihl/sihl.0.2.2/opam
Labels: consider for merge

#17847 Add package ocamlsdl2-ttf version 0.01
  packages/ocamlsdl2-ttf/ocamlsdl2-ttf.0.01/opam
  packages/ocamlsdl2-ttf/ocamlsdl2-ttf.0.02/opam
Labels: needs reporter action

#17910 GT.0.4.0
  packages/GT/GT.0.4.0/opam
Labels: consider for merge
