Repository ocaml/opam-repository, pull requests merged in 2020-05, with the labels that each got.

#16357 add ocaml.4.10.0+nnpcheck to dynamically check for naked pointers
  packages/ocaml-variants/ocaml-variants.4.10.0+nnpcheck/opam
Labels: needs reporter action

#16361 Package batch_jaro_winkler.0.1.0
  packages/batch_jaro_winkler/batch_jaro_winkler.0.1.0/opam
Labels: question

#16368 ocaml-freestanding 0.6.0
  packages/ocaml-freestanding/ocaml-freestanding.0.6.0/opam
Labels: consider for merge

#16377 [new release] bigarray-overlap (0.2.0)
  packages/bigarray-overlap/bigarray-overlap.0.2.0/opam
Labels: needs reporter action, question

#16382 [new release] archi-lwt, archi-async and archi (0.1.0)
  packages/archi-async/archi-async.0.1.0/opam
  packages/archi-lwt/archi-lwt.0.1.0/opam
  packages/archi/archi.0.1.0/opam
Labels: question

#16371 Tezos node.7.0
  packages/tezos-base/tezos-base.7.0/opam
  packages/tezos-clic/tezos-clic.7.0/opam
  packages/tezos-crypto/tezos-crypto.7.0/opam
  packages/tezos-embedded-protocol-000-Ps9mPmXa/tezos-embedded-protocol-000-Ps9mPmXa.7.0/opam
  packages/tezos-embedded-protocol-001-PtCJ7pwo/tezos-embedded-protocol-001-PtCJ7pwo.7.0/opam
  packages/tezos-embedded-protocol-002-PsYLVpVv/tezos-embedded-protocol-002-PsYLVpVv.7.0/opam
  packages/tezos-embedded-protocol-003-PsddFKi3/tezos-embedded-protocol-003-PsddFKi3.7.0/opam
  packages/tezos-embedded-protocol-004-Pt24m4xi/tezos-embedded-protocol-004-Pt24m4xi.7.0/opam
  packages/tezos-embedded-protocol-005-PsBABY5H/tezos-embedded-protocol-005-PsBABY5H.7.0/opam
  packages/tezos-embedded-protocol-005-PsBabyM1/tezos-embedded-protocol-005-PsBabyM1.7.0/opam
  packages/tezos-embedded-protocol-006-PsCARTHA/tezos-embedded-protocol-006-PsCARTHA.7.0/opam
  packages/tezos-embedded-protocol-genesis-carthagenet/tezos-embedded-protocol-genesis-carthagenet.7.0/opam
  packages/tezos-error-monad/tezos-error-monad.7.0/opam
  packages/tezos-event-logging/tezos-event-logging.7.0/opam
  packages/tezos-lmdb/tezos-lmdb.7.0/opam
  packages/tezos-mempool-006-PsCARTHA/tezos-mempool-006-PsCARTHA.7.0/opam
  packages/tezos-micheline/tezos-micheline.7.0/opam
  packages/tezos-node/tezos-node.7.0/opam
  packages/tezos-p2p-services/tezos-p2p-services.7.0/opam
  packages/tezos-p2p/tezos-p2p.7.0/opam
  packages/tezos-protocol-000-Ps9mPmXa/tezos-protocol-000-Ps9mPmXa.7.0/opam
  packages/tezos-protocol-001-PtCJ7pwo/tezos-protocol-001-PtCJ7pwo.7.0/opam
  packages/tezos-protocol-002-PsYLVpVv/tezos-protocol-002-PsYLVpVv.7.0/opam
  packages/tezos-protocol-003-PsddFKi3/tezos-protocol-003-PsddFKi3.7.0/opam
  packages/tezos-protocol-004-Pt24m4xi/tezos-protocol-004-Pt24m4xi.7.0/opam
  packages/tezos-protocol-005-PsBABY5H/tezos-protocol-005-PsBABY5H.7.0/opam
  packages/tezos-protocol-005-PsBabyM1/tezos-protocol-005-PsBabyM1.7.0/opam
  packages/tezos-protocol-006-PsCARTHA/tezos-protocol-006-PsCARTHA.7.0/opam
  packages/tezos-protocol-compiler/tezos-protocol-compiler.7.0/opam
  packages/tezos-protocol-environment-sigs/tezos-protocol-environment-sigs.7.0/opam
  packages/tezos-protocol-environment/tezos-protocol-environment.7.0/opam
  packages/tezos-protocol-genesis-carthagenet/tezos-protocol-genesis-carthagenet.7.0/opam
  packages/tezos-protocol-updater/tezos-protocol-updater.7.0/opam
  packages/tezos-requester/tezos-requester.7.0/opam
  packages/tezos-rpc-http-server/tezos-rpc-http-server.7.0/opam
  packages/tezos-rpc-http/tezos-rpc-http.7.0/opam
  packages/tezos-rpc/tezos-rpc.7.0/opam
  packages/tezos-shell-context/tezos-shell-context.7.0/opam
  packages/tezos-shell-services/tezos-shell-services.7.0/opam
  packages/tezos-shell/tezos-shell.7.0/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.7.0/opam
  packages/tezos-stdlib/tezos-stdlib.7.0/opam
  packages/tezos-storage/tezos-storage.7.0/opam
  packages/tezos-tooling/tezos-tooling.7.0/opam
  packages/tezos-validation/tezos-validation.7.0/opam
  packages/tezos-validator/tezos-validator.7.0/opam
  packages/tezos-version/tezos-version.7.0/opam
  packages/tezos-workers/tezos-workers.7.0/opam
Labels: consider for merge

#16246 fix for unmagic.1.0.4
  packages/unmagic/unmagic.1.0.4/opam
Labels: needs reporter action

#16349 crowbar.0.2
  packages/crowbar/crowbar.0.2/opam
Labels: needs reporter action

#16243 2 packages from project-everest/hacl-star at 0.1
  packages/hacl-star-raw/hacl-star-raw.0.1/opam
  packages/hacl-star/hacl-star.0.1/opam
Labels: needs reporter action

#16443 Solo5 0.6.5
  packages/solo5-bindings-hvt/solo5-bindings-hvt.0.6.5/opam
  packages/solo5-bindings-muen/solo5-bindings-muen.0.6.5/opam
  packages/solo5-bindings-spt/solo5-bindings-spt.0.6.5/opam
  packages/solo5-bindings-virtio/solo5-bindings-virtio.0.6.5/opam
Labels: needs reporter action

#16455 Update torch.
  packages/torch/torch.0.9/opam
Labels: needs reporter action

#16464 Fix musl+static switches for Alpine
  packages/ocaml-variants/ocaml-variants.4.01.0+musl+static/opam
  packages/ocaml-variants/ocaml-variants.4.02.1+musl+static/opam
  packages/ocaml-variants/ocaml-variants.4.02.3+musl+static/opam
  packages/ocaml-variants/ocaml-variants.4.05.0+musl+static+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.06.0+musl+static+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.06.1+musl+static+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.07.1+musl+static+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.08.0+musl+static+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.08.1+musl+static+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.09.0+musl+static+flambda/opam
  packages/ocaml-variants/ocaml-variants.4.09.1+musl+static+flambda/opam
Labels: needs reporter action

#16452 new file: packages/parany/parany.11.0.2/opam
  packages/hts_shrink/hts_shrink.2.1.1/opam
  packages/molenc/molenc.7.0.1/opam
  packages/molenc/molenc.8.0.2/opam
  packages/oplsr/oplsr.5.0.1/opam
  packages/parany/parany.11.0.2/opam
  packages/pardi/pardi.2.0.4/opam
Labels: question

#16461 Add webtest.2.0.0 and webtest-js.2.0.0
  packages/webtest-js/webtest-js.2.0.0/opam
  packages/webtest/webtest.2.0.0/opam
Labels: needs reporter action

#16471 Package loga.0.0.5
  packages/loga/loga.0.0.5/opam
Labels: needs reporter action

#16473 Added ppx_test.1.7.0
  packages/ppx_test/ppx_test.1.7.0/opam
Labels: needs reporter action

#16495 + sqlgg 20200521
  packages/sqlgg/sqlgg.20200521/opam
Labels: needs reporter action

#16536 Deprecate configurator
  packages/configurator/configurator.v0.10.0/opam
  packages/configurator/configurator.v0.11.0/opam
  packages/configurator/configurator.v0.9.0/opam
  packages/configurator/configurator.v0.9.1/opam
Labels: consider for merge

#16519 Package ocaml-vdom.0.2
  packages/ocaml-vdom/ocaml-vdom.0.2/opam
Labels: question

#16450 Package asli.0.2.0
  packages/asli/asli.0.2.0/opam
Labels: needs reporter action

#16510 Package lp.0.2.0
  packages/lp-glpk/lp-glpk.0.2.0/opam
  packages/lp-gurobi/lp-gurobi.0.2.0/opam
  packages/lp/lp.0.2.0/opam
Labels: needs reporter action

#16547 [new release] ppx_factory (0.1.1)
  packages/ppx_factory/ppx_factory.0.1.1/opam
Labels: question
