Repository ocaml/opam-repository, pull requests merged in 2020-10, with the labels that each got.

#17303 pa_ppx Version 0.03
  packages/pa_ppx/pa_ppx.0.03/opam
Labels: needs reporter action

#17351 [new release] inquire (0.2.1)
  packages/inquire/inquire.0.2.1/opam
Labels: consider for merge

#17347 Package vec.0.1.0
  packages/vec/vec.0.1.0/opam
Labels: consider for merge

#17338 Harness some Liquidsoap upcoming version conflicts.
  packages/liquidsoap/liquidsoap.1.3.4/opam
  packages/liquidsoap/liquidsoap.1.3.5/opam
  packages/liquidsoap/liquidsoap.1.3.6/opam
  packages/liquidsoap/liquidsoap.1.3.7/opam
  packages/liquidsoap/liquidsoap.1.4.0/opam
  packages/liquidsoap/liquidsoap.1.4.1-1/opam
  packages/liquidsoap/liquidsoap.1.4.1-2/opam
  packages/liquidsoap/liquidsoap.1.4.1/opam
  packages/liquidsoap/liquidsoap.1.4.2/opam
  packages/liquidsoap/liquidsoap.1.4.3/opam
  packages/sdl-liquidsoap/sdl-liquidsoap.2/opam
Labels: question

#17349 [new release] cviode (0.0.4)
  packages/cviode/cviode.0.0.4/opam
Labels: consider for merge

#17348 [new release] rpclib-html, rpclib-async, rpclib, rpc, rpclib-lwt, ppx_deriving_rpc and rpclib-js (8.0.0)
  packages/ppx_deriving_rpc/ppx_deriving_rpc.8.0.0/opam
  packages/rpc/rpc.8.0.0/opam
  packages/rpclib-async/rpclib-async.8.0.0/opam
  packages/rpclib-html/rpclib-html.8.0.0/opam
  packages/rpclib-js/rpclib-js.8.0.0/opam
  packages/rpclib-lwt/rpclib-lwt.8.0.0/opam
  packages/rpclib/rpclib.8.0.0/opam
Labels: consider for merge

#17344 [new release] ocamlgraph_gtk and ocamlgraph (2.0.0)
  packages/dose3/dose3.5.0.1/opam
  packages/llvmgraph/llvmgraph.0.2/opam
  packages/not-ocamlfind/not-ocamlfind.0.07/opam
  packages/ocamlgraph/ocamlgraph.2.0.0/opam
  packages/ocamlgraph_gtk/ocamlgraph_gtk.2.0.0/opam
  packages/opam-lib/opam-lib.1.3.1/opam
  packages/why3/why3.1.2.1/opam
Labels: consider for merge

#17357 [new release] spin (0.7.0)
  packages/spin/spin.0.7.0/opam
Labels: needs reporter action

#17260 Package opam-publish.2.0.2
  packages/opam-publish/opam-publish.2.0.2/opam
Labels: consider for merge

#17360 [new release] ppxlib (0.18.0)
  packages/clim-ppx/clim-ppx.0.3.0/opam
  packages/hardcaml/hardcaml.v0.14.0/opam
  packages/metapp/metapp.0.3.0/opam
  packages/metaquot/metaquot.0.3.0/opam
  packages/mlt_parser/mlt_parser.v0.14.0/opam
  packages/ppx_bitstring/ppx_bitstring.4.0.0/opam
  packages/ppx_const/ppx_const.2.0/opam
  packages/ppx_custom_printf/ppx_custom_printf.v0.13.0/opam
  packages/ppx_custom_printf/ppx_custom_printf.v0.14.0/opam
  packages/ppx_deriving_rpc/ppx_deriving_rpc.7.2.0/opam
  packages/ppx_deriving_rpc/ppx_deriving_rpc.8.0.0/opam
  packages/ppx_expect/ppx_expect.v0.14.0/opam
  packages/ppx_fields_conv/ppx_fields_conv.v0.14.1/opam
  packages/ppx_getenv/ppx_getenv.2.0/opam
  packages/ppx_irmin/ppx_irmin.2.2.0/opam
  packages/ppx_optcomp/ppx_optcomp.v0.13.0/opam
  packages/ppx_optcomp/ppx_optcomp.v0.14.0/opam
  packages/ppx_protocol_conv/ppx_protocol_conv.5.1.3/opam
  packages/ppx_python/ppx_python.v0.13.0/opam
  packages/ppx_sexp_conv/ppx_sexp_conv.v0.14.1/opam
  packages/ppx_sexp_message/ppx_sexp_message.v0.13.0/opam
  packages/ppx_sexp_message/ppx_sexp_message.v0.14.0/opam
  packages/ppx_yojson/ppx_yojson.1.0.0/opam
  packages/ppxlib/ppxlib.0.18.0/opam
Labels: needs reporter action

#17356 Package ocsigen-start.2.19.2
  packages/ocsigen-start/ocsigen-start.2.19.2/opam
Labels: needs reporter action

#17386 Fix configure options for BER MetaOCaml N111
  packages/ocaml-variants/ocaml-variants.4.11.1+BER/opam
Labels: consider for merge

#17393 Package mm.0.6.0
  packages/liquidsoap/liquidsoap.1.4.0/opam
  packages/liquidsoap/liquidsoap.1.4.1-1/opam
  packages/liquidsoap/liquidsoap.1.4.1-2/opam
  packages/liquidsoap/liquidsoap.1.4.1/opam
  packages/mkaudio/mkaudio.1.0.0/opam
  packages/mkaudio/mkaudio.1.0.1/opam
  packages/mkaudio/mkaudio.1.1.0/opam
  packages/mm/mm.0.6.0/opam
Labels: consider for merge

#17407 Package brr.0.0.1
  packages/brr/brr.0.0.1/opam
Labels: consider for merge

#17408 2 packages from project-everest/hacl-star at 0.3.0
  packages/hacl-star-raw/hacl-star-raw.0.3.0/opam
  packages/hacl-star/hacl-star.0.3.0/opam
Labels: consider for merge

#17392 [new release] sihl-email, sihl-queue, sihl-storage and sihl (0.1.5)
  packages/sihl-email/sihl-email.0.1.5/opam
  packages/sihl-queue/sihl-queue.0.1.5/opam
  packages/sihl-storage/sihl-storage.0.1.5/opam
  packages/sihl/sihl.0.1.5/opam
Labels: needs reporter action

#17413 [new release] ocaml-lsp-server and lsp (1.1.0)
  packages/lsp/lsp.1.1.0/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.1.0/opam
Labels: consider for merge

#17398 Package cryptoverif.2.03pl1
  packages/cryptoverif/cryptoverif.2.03pl1/opam
Labels: needs reporter action, question

#17418 Release Camlp5 Version 8.00-alpha06
  packages/camlp5/camlp5.8.00~alpha06/opam
Labels: consider for merge

#17282 Update lablgtk3.3.0.beta5 (still required for Windows compatibility)
  packages/lablgtk3/lablgtk3.3.0.beta5/opam
Labels: needs reporter action

#17279 Added an existence check to conf-gnome-icon-theme3
  packages/conf-adwaita-icon-theme/conf-adwaita-icon-theme.1/opam
  packages/conf-gnome-icon-theme3/conf-gnome-icon-theme3.0/opam
Labels: consider for merge

#17415 [new release] ocaml-r (0.4.0)
  packages/ocaml-r/ocaml-r.0.4.0/opam
Labels: consider for merge

#17432 Promise 1.1.2: native version of a JS promise binding
  packages/promise/promise.1.1.2/opam
Labels: needs reporter action

#17429 Fix tezos compatibility with uri 4.0
  packages/tezos-base/tezos-base.7.4/opam
  packages/tezos-clic/tezos-clic.7.4/files/with-re.patch
  packages/tezos-clic/tezos-clic.7.4/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.7.4/files/with-re.patch
  packages/tezos-stdlib-unix/tezos-stdlib-unix.7.4/opam
Labels: consider for merge

#17424 Speex updates
  packages/conf-libspeex/conf-libspeex.1/opam
  packages/speex/speex.0.2.2/opam
  packages/speex/speex.0.3.0/opam
Labels: consider for merge

#17443 Package ogg.0.6.1
  packages/conf-libogg/conf-libogg.1/opam
  packages/ogg/ogg.0.6.1/opam
Labels: consider for merge

#17435 Package opam-depext.1.1.4
  packages/opam-depext/opam-depext.1.1.4/opam
Labels: consider for merge

#17441 [new release] coq-serapi (8.10.0+0.7.2)
  packages/coq-serapi/coq-serapi.8.10.0+0.7.2/opam
Labels: needs reporter action

#16737 [missing release] z3 (4.8.5)
  packages/z3/z3.4.8.5/files/4468.patch
  packages/z3/z3.4.8.5/opam
Labels: consider for merge

#17446 [new release] daypack-lib.0.0.6
  packages/daypack-lib/daypack-lib.0.0.6/opam
Labels: consider for merge

#17451 [new release] ppx_yojson (1.1.0)
  packages/ppx_yojson/ppx_yojson.1.1.0/opam
Labels: consider for merge

#17453 [new release] js_of_ocaml-ocamlbuild, js_of_ocaml-compiler, js_of_ocaml-ppx, js_of_ocaml-lwt, js_of_ocaml-toplevel, js_of_ocaml-tyxml, js_of_ocaml and js_of_ocaml-ppx_deriving_json (3.8.0)
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.3.8.0/opam
  packages/js_of_ocaml-lwt/js_of_ocaml-lwt.3.8.0/opam
  packages/js_of_ocaml-ocamlbuild/js_of_ocaml-ocamlbuild.3.8.0/opam
  packages/js_of_ocaml-ppx/js_of_ocaml-ppx.3.8.0/opam
  packages/js_of_ocaml-ppx_deriving_json/js_of_ocaml-ppx_deriving_json.3.8.0/opam
  packages/js_of_ocaml-toplevel/js_of_ocaml-toplevel.3.8.0/opam
  packages/js_of_ocaml-tyxml/js_of_ocaml-tyxml.3.8.0/opam
  packages/js_of_ocaml/js_of_ocaml.3.8.0/opam
Labels: consider for merge

#17463 Changed GTK icon theme to adwaita in all GTK3 based CoqIDE packages
  packages/coqide/coqide.8.10.0/opam
  packages/coqide/coqide.8.10.1/opam
  packages/coqide/coqide.8.10.2/opam
  packages/coqide/coqide.8.11.0/opam
  packages/coqide/coqide.8.11.1/opam
  packages/coqide/coqide.8.11.2/opam
  packages/coqide/coqide.8.12.0/opam
Labels: needs reporter action

#17449 Package fsml.0.2.1
  packages/fsml/fsml.0.2.1/opam
Labels: needs reporter action

#17465 [new release] eigen (0.3.0)
  packages/eigen/eigen.0.3.0/opam
Labels: consider for merge

#17462 [new release] ocaml-migrate-parsetree (2.1.0)
  packages/ocaml-migrate-parsetree/ocaml-migrate-parsetree.2.1.0/opam
Labels: consider for merge

#17355 Declare package cache in git-controlled repo file
  repo
Labels: needs admin action

#17472 Package qrc.0.1.0
  packages/qrc/qrc.0.1.0/opam
Labels: consider for merge

#17466 [WIP] Add ocp-build 1.99.21 for all ocaml versions
  packages/ocp-build/ocp-build.1.99.21/opam
  packages/opam-core/opam-core.2.0.0~beta/opam
  packages/opam-core/opam-core.2.0.0~beta3.1/opam
  packages/opam-core/opam-core.2.0.0~beta3/opam
  packages/opam-core/opam-core.2.0~alpha5/opam
  packages/typerex-clibs/typerex-clibs.1.0/opam
  packages/typerex-system/typerex-system.1.0/opam
Labels: consider for merge

#17476 [new release] ppxlib (0.19.0)
  packages/ppxlib/ppxlib.0.19.0/opam
Labels: consider for merge

#17474 [new release] telltime.0.0.3
  packages/telltime/telltime.0.0.3/opam
Labels: consider for merge

#17469 [new release] flex-array (1.0.0)
  packages/flex-array/flex-array.1.0.0/opam
Labels: consider for merge

#17479 Package fadbadml.0.1.2
  packages/fadbadml/fadbadml.0.1.2/opam
Labels: needs reporter action

#17501 Package mpg123.0.1
  packages/mpg123/mpg123.0.1/opam
Labels: needs reporter action

#17507 Package ezjs_extension.0.1
  packages/ezjs_extension/ezjs_extension.0.1/opam
Labels: needs reporter action

#17543 upgrade Jane Street ppx libraries to use ppxlib 0.18.0
  packages/ppx_expect/ppx_expect.v0.14.1/opam
  packages/ppx_fields_conv/ppx_fields_conv.v0.14.2/opam
  packages/ppx_optcomp/ppx_optcomp.v0.14.1/opam
  packages/ppx_sexp_conv/ppx_sexp_conv.v0.14.2/opam
  packages/ppx_sexp_message/ppx_sexp_message.v0.14.1/opam
Labels: consider for merge, needs maintainer action
