Repository ocaml/opam-repository, pull requests merged in 2020-06, with the labels that each got.

#16505 add conf-mbedtls
  packages/conf-mbedtls/conf-mbedtls.1/files/test.c
  packages/conf-mbedtls/conf-mbedtls.1/opam
Labels: needs reporter action

#16577 0install-solver: require dune 2.5 to fix installation
  packages/0install-solver/0install-solver.2.17/opam
Labels: consider for merge

#16567 Package lem.2020-06-03
  packages/lem/lem.2020-06-03/opam
Labels: consider for merge

#16521 3 packages from gitlab.inria.fr/fpottier/menhir/repository/20200525/archive.tar.gz
  packages/menhir/menhir.20200525/opam
  packages/menhirLib/menhirLib.20200525/opam
  packages/menhirSdk/menhirSdk.20200525/opam
Labels: consider for merge

#16585 [new release] dune-build-info, dune, dune-configurator, dune-action-plugin, dune-private-libs and dune-glob (2.6.0)
  packages/dune-action-plugin/dune-action-plugin.2.6.0/opam
  packages/dune-build-info/dune-build-info.2.6.0/opam
  packages/dune-configurator/dune-configurator.2.6.0/opam
  packages/dune-glob/dune-glob.2.6.0/opam
  packages/dune-private-libs/dune-private-libs.2.6.0/opam
  packages/dune/dune.2.6.0/opam
Labels: consider for merge, question

#16562 Fix accessor*, higher_kinded, and ppx_accessor packages.
  packages/accessor/accessor.v0.14.1/opam
  packages/accessor_async/accessor_async.v0.14.1/opam
  packages/accessor_base/accessor_base.v0.14.1/opam
  packages/accessor_core/accessor_core.v0.14.1/opam
  packages/higher_kinded/higher_kinded.v0.14.1/opam
  packages/ppx_accessor/ppx_accessor.v0.14.1/opam
Labels: do not merge

#16574 Package linksem.0.7
  packages/linksem/linksem.0.7/opam
Labels: needs reporter action

#16582 Package sedlex.2.2
  packages/sedlex/sedlex.2.2/opam
Labels: question

#16602 Add version 0.0.2 of systemverilog package
  packages/systemverilog/systemverilog.0.0.2/opam
Labels: needs reporter action

#16646 ipaddr 5.0.0 reverse dependencies: charrua, mirage-nat (test), tcpip (test), tuntap
  packages/charrua-server/charrua-server.1.1.0/opam
  packages/charrua-server/charrua-server.1.2.0/opam
  packages/charrua-server/charrua-server.1.2.1/opam
  packages/charrua/charrua.1.1.0/opam
  packages/charrua/charrua.1.2.0/opam
  packages/charrua/charrua.1.2.1/opam
  packages/mirage-nat/mirage-nat.1.2.0/opam
  packages/mirage-nat/mirage-nat.2.0.0/opam
  packages/mirage-nat/mirage-nat.2.1.0/opam
  packages/mirage-nat/mirage-nat.2.2.0/opam
  packages/mirage-nat/mirage-nat.2.2.1/opam
  packages/tcpip/tcpip.4.0.0/opam
  packages/tcpip/tcpip.4.1.0/opam
  packages/tuntap/tuntap.1.8.1/opam
Labels: consider for merge

#16644 [new release] ipaddr-cstruct, macaddr, macaddr-sexp, ipaddr, ipaddr-sexp and macaddr-cstruct (5.0.0)
  packages/ipaddr-cstruct/ipaddr-cstruct.5.0.0/opam
  packages/ipaddr-sexp/ipaddr-sexp.5.0.0/opam
  packages/ipaddr/ipaddr.5.0.0/opam
  packages/macaddr-cstruct/macaddr-cstruct.5.0.0/opam
  packages/macaddr-sexp/macaddr-sexp.5.0.0/opam
  packages/macaddr/macaddr.5.0.0/opam
Labels: consider for merge

#16656 Update asli upper bound on ott
  packages/asli/asli.0.1/opam
  packages/asli/asli.0.2.0/opam
Labels: consider for merge

#16651 added camlimages.5.0.3
  packages/camlimages/camlimages.5.0.3/opam
Labels: needs reporter action

#16666 Package astring.0.8.4
  packages/astring/astring.0.8.4/opam
Labels: consider for merge

#16676 Package tsdl.0.9.8
  packages/tsdl/tsdl.0.9.8/opam
Labels: consider for merge

#16620 Package np.np1.18-0.3.0
  packages/np/np.np1.18-0.3.0/opam
Labels: consider for merge

#16679 [new release] tcpip (5.0.0)
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.6.0/opam
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.7.0/opam
  packages/charrua/charrua.1.0.0/opam
  packages/charrua/charrua.1.1.0/opam
  packages/charrua/charrua.1.2.0/opam
  packages/charrua/charrua.1.2.1/opam
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.6.1/opam
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.6/opam
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.7.0/opam
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.8.0/opam
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.8.1/opam
  packages/mirage-qubes-ipv4/mirage-qubes-ipv4.0.8.2/opam
  packages/tcpip/tcpip.5.0.0/opam
Labels: consider for merge

#16607 added scaml.1.2.0pre7
  packages/scaml/scaml.1.2.0~pre7/opam
Labels: needs reporter action

#16412 Luv 0.5.3: libuv binding
  packages/luv/luv.0.5.3/opam
Labels: needs reporter action

#16667 Promise 1.1.0 - native version of a JS Promise binding
  packages/promise/promise.1.1.0/opam
Labels: needs reporter action

#16693 new file: packages/hts_shrink/hts_shrink.2.1.2/opam
  packages/hts_shrink/hts_shrink.2.1.2/opam
Labels: needs reporter action

#16710 2 packages from gitlab.com/nomadic-labs/ringo/-/archive/v0.5/ringo-v0.5.tar.gz
  packages/ringo-lwt/ringo-lwt.0.5/opam
  packages/ringo/ringo.0.5/opam
Labels: consider for merge

#16637 Package binaryen.0.1.0
  packages/binaryen/binaryen.0.1.0/opam
Labels: consider for merge, question

#16719 Package biocaml.0.11.0
  packages/biocaml/biocaml.0.11.0/opam
Labels: needs reporter action

#16655 [new release] rpclib-html, rpclib-async, rpclib, rpc, rpclib-lwt, ppx_deriving_rpc and rpclib-js (7.1.0)
  packages/camldm/camldm.0.1.0/opam
  packages/ppx_deriving_rpc/ppx_deriving_rpc.7.1.0/opam
  packages/rpc/rpc.7.1.0/opam
  packages/rpclib-async/rpclib-async.7.1.0/opam
  packages/rpclib-html/rpclib-html.7.1.0/opam
  packages/rpclib-js/rpclib-js.7.1.0/opam
  packages/rpclib-lwt/rpclib-lwt.7.1.0/opam
  packages/rpclib/rpclib.7.1.0/opam
  packages/xapi-backtrace/xapi-backtrace.0.4/opam
  packages/xapi-backtrace/xapi-backtrace.0.5/opam
  packages/xapi-rrd/xapi-rrd.0.10.1/opam
  packages/xapi-rrd/xapi-rrd.0.12.0/opam
  packages/xapi-rrd/xapi-rrd.1.0.0/opam
  packages/xapi-rrd/xapi-rrd.1.0.1/opam
  packages/xen-api-client/xen-api-client.0.9.10/opam
  packages/xen-api-client/xen-api-client.0.9.8/opam
Labels: consider for merge

#16721 [new release] ppx_irmin, irmin, irmin-test, irmin-mem, irmin-pack and irmin-graphql (2.2.0)
  packages/irmin-chunk/irmin-chunk.2.2.0/opam
  packages/irmin-fs/irmin-fs.2.2.0/opam
  packages/irmin-git/irmin-git.2.2.0/opam
  packages/irmin-graphql/irmin-graphql.2.2.0/opam
  packages/irmin-http/irmin-http.2.2.0/opam
  packages/irmin-mem/irmin-mem.2.2.0/opam
  packages/irmin-mirage-git/irmin-mirage-git.2.2.0/opam
  packages/irmin-mirage-graphql/irmin-mirage-graphql.2.2.0/opam
  packages/irmin-mirage/irmin-mirage.2.2.0/opam
  packages/irmin-pack/irmin-pack.2.2.0/opam
  packages/irmin-test/irmin-test.2.2.0/opam
  packages/irmin-unix/irmin-unix.2.2.0/opam
  packages/irmin/irmin.2.2.0/opam
  packages/ppx_irmin/ppx_irmin.2.2.0/opam
Labels: needs reporter action

#16725 [new release] cohttp-lwt-jsoo, cohttp, cohttp-lwt, cohttp-lwt-unix, cohttp-top, cohttp-async and cohttp-mirage (2.5.2)
  packages/cohttp-async/cohttp-async.2.5.2/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.2.5.2/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.2.5.2/opam
  packages/cohttp-lwt/cohttp-lwt.2.5.2/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.2/opam
  packages/cohttp-top/cohttp-top.2.5.2/opam
  packages/cohttp/cohttp.2.5.2/opam
Labels: consider for merge

#16726 [new release] cohttp-lwt-jsoo, cohttp, cohttp-lwt, cohttp-lwt-unix, cohttp-top, cohttp-async and cohttp-mirage (2.5.3)
  packages/cohttp-async/cohttp-async.2.5.3/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.2.5.3/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.2.5.3/opam
  packages/cohttp-lwt/cohttp-lwt.2.5.3/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.3/opam
  packages/cohttp-top/cohttp-top.2.5.3/opam
  packages/cohttp/cohttp.2.5.3/opam
Labels: consider for merge

#16727 Package tdigest.0.1.0
  packages/tdigest/tdigest.0.1.0/opam
Labels: needs reporter action

#16673 new file: packages/odnnr/odnnr.2.0.0/opam
  packages/odnnr/odnnr.2.0.0/files/install_keras.r
  packages/odnnr/odnnr.2.0.0/opam
Labels: needs reporter action

#16664 Package embedded_ocaml_templates.0.1.4
  packages/embedded_ocaml_templates/embedded_ocaml_templates.0.1.4/opam
Labels: question

#16733 Package SZXX.0.1.0
  packages/SZXX/SZXX.0.1.0/opam
Labels: question
