Repository ocaml/opam-repository, pull requests merged in 2020-09, with the labels that each got.

#17090 [new release] mirage-stack (2.1.0)
  packages/mirage-stack/mirage-stack.2.1.0/opam
Labels: consider for merge

#17087 Release orsetto 1.0.3.
  packages/orsetto/orsetto.1.0.3/opam
Labels: question

#17103 add mpp 0.3.4
  packages/mpp/mpp.0.3.4/opam
Labels: consider for merge

#17127 [new release] bheap (2.0.0)
  packages/bheap/bheap.2.0.0/opam
  packages/mirage-solo5/mirage-solo5.0.6.0/opam
  packages/mirage-solo5/mirage-solo5.0.6.1/opam
  packages/mirage-solo5/mirage-solo5.0.6.2/opam
Labels: question

#17124 Package promise_jsoo.0.1.0
  packages/promise_jsoo/promise_jsoo.0.1.0/opam
Labels: consider for merge

#17141 Publish telltime.0.0.1
  packages/telltime/telltime.0.0.1/opam
Labels: consider for merge

#17097 +faraday.0.7.2
  packages/faraday-async/faraday-async.0.7.2/opam
  packages/faraday-lwt-unix/faraday-lwt-unix.0.7.2/opam
  packages/faraday-lwt/faraday-lwt.0.7.2/opam
  packages/faraday/faraday.0.7.2/opam
  packages/gluten-async/gluten-async.0.2.1/opam
  packages/h2-async/h2-async.0.6.1/opam
  packages/httpaf-async/httpaf-async.0.4.1/opam
  packages/httpaf-async/httpaf-async.0.5.0/opam
  packages/httpaf-async/httpaf-async.0.6.0/opam
  packages/httpaf-async/httpaf-async.0.6.5/opam
  packages/httpaf-async/httpaf-async.0.6.6/opam
Labels: consider for merge

#17149 [new release] curly (0.2.0)
  packages/curly/curly.0.2.0/opam
Labels: consider for merge

#17150 ocamlmpi 1.05 (support for bigarrays)
  packages/mpi/mpi.1.05/files/post105.patch
  packages/mpi/mpi.1.05/opam
Labels: consider for merge

#17157 [new release] memtrace (0.1)
  packages/memtrace/memtrace.0.1/opam
Labels: consider for merge

#17132 Opam publish camlp5 7.13
  packages/camlp5/camlp5.7.13/opam
Labels: consider for merge

#16622 Package sklearn.sk0.22-0.3.0
  packages/sklearn/sklearn.sk0.22-0.3.0/opam
Labels: consider for merge

#17172 conf-libev depends on ocaml
  packages/conf-libev/conf-libev.4-11/opam
Labels: consider for merge

#17162 Package apronext.1.0
  packages/apronext/apronext.1.0/opam
Labels: consider for merge

#17190 [new release] prom (0.3)
  packages/prom/prom.0.3/opam
Labels: consider for merge

#17192 [new release] multipart_form (0.1.0)
  packages/multipart_form/multipart_form.0.1.0/opam
Labels: needs reporter action

#17197 new package: zarith-freestanding 1.10
  packages/zarith-freestanding/zarith-freestanding.1.10/files/mirage-build.sh
  packages/zarith-freestanding/zarith-freestanding.1.10/files/mirage-install.sh
  packages/zarith-freestanding/zarith-freestanding.1.10/files/mirage-uninstall.sh
  packages/zarith-freestanding/zarith-freestanding.1.10/files/no-dynlink.patch
  packages/zarith-freestanding/zarith-freestanding.1.10/opam
Labels: consider for merge, question

#17203 conf-cmake: Use /bin/sh instead of bash
  packages/conf-cmake/conf-cmake.1/files/configure.sh
  packages/conf-cmake/conf-cmake.1/opam
Labels: needs reporter action

#17195 Package ocsigen-i18n.3.6.0
  packages/ocsigen-i18n/ocsigen-i18n.3.6.0/opam
Labels: needs reporter action

#17196 Add opam-bin.0.9.5
  packages/opam-bin/opam-bin.0.9.5/opam
  packages/opam_bin_lib/opam_bin_lib.0.9.5/opam
Labels: needs reporter action

#17229 Package order-i3-xfce.0.1
  packages/order-i3-xfce/order-i3-xfce.0.1/opam
Labels: needs reporter action

#17207 Memtrace viewer (with dependencies)
  packages/memtrace_viewer/memtrace_viewer.v0.14.0/opam
Labels: consider for merge

#17263 Add clim clim ppx.0.3.0 and finally remove ezcmdliner.
  packages/clim-ppx/clim-ppx.0.3.0/opam
  packages/clim/clim.0.3.0/opam
  packages/ezcmdliner/ezcmdliner.0.1.1/opam
Labels: consider for merge

#17268 [new release] rml (1.09.06)
  packages/rml/rml.1.09.06/opam
Labels: needs reporter action

#17288 [new release] odepack (0.7.1)
  packages/odepack/odepack.0.7.1/opam
Labels: question

#17275 Camlp5 8.00 alpha05 release
  packages/camlp5/camlp5.8.00~alpha05/opam
Labels: needs reporter action

#17276 Package vue-jsoo.0.2
  packages/vue-jsoo/vue-jsoo.0.2/opam
Labels: consider for merge

#17294 Package clap.0.1.0
  packages/clap/clap.0.1.0/opam
Labels: consider for merge

#17302 mirage-types & tcpip: prepare for API-breaking mirage-protocols release
  packages/mirage-types/mirage-types.3.7.1/opam
  packages/mirage-types/mirage-types.3.7.5/opam
  packages/mirage-types/mirage-types.3.7.6/opam
  packages/mirage-types/mirage-types.3.8.0/opam
  packages/mirage-types/mirage-types.3.8.1/opam
  packages/tcpip/tcpip.4.0.0/opam
  packages/tcpip/tcpip.4.1.0/opam
  packages/tcpip/tcpip.5.0.0/opam
  packages/tcpip/tcpip.5.0.1/opam
Labels: consider for merge
