Repository ocaml/opam-repository, pull requests merged in 2020-04, with the labels that each got.

#16113 [new release] ocaml-print-intf (1.2.0)
  packages/ocaml-print-intf/ocaml-print-intf.1.2.0/opam
Labels: consider for merge

#16111 Lwt: dune exec: use --no-config
  packages/lwt/lwt.5.1.2/opam
  packages/lwt/lwt.5.2.0/opam
Labels: question

#16104 apero-core.0.4.7
  packages/apero-core/apero-core.0.4.7/opam
Labels: needs reporter action

#16117 Update META for metaocaml package
  packages/base-metaocaml-ocamlfind/base-metaocaml-ocamlfind.base/files/META
Labels: consider for merge

#16131 Package oraft.0.1.0
  packages/oraft/oraft.0.1.0/opam
Labels: needs reporter action

#16136 [new release] let-if (0.2.0)
  packages/let-if/let-if.0.2.0/opam
Labels: needs reporter action

#16153 Bisect_ppx 2.3.0 - now with dark theme
  packages/bisect_ppx/bisect_ppx.2.3.0/opam
Labels: consider for merge

#16154 [new release] anthill (0.1)
  packages/anthill/anthill.0.1/opam
Labels: consider for merge

#16162 fixed camlimages.5.0.1 for migration from BitBucket Mercurial to GitLab
  packages/camlimages/camlimages.5.0.1/opam
Labels: consider for merge

#16160 3 packages from ryanslade/influxdb-ocaml at 0.3.0
  packages/influxdb-async/influxdb-async.0.3.0/opam
  packages/influxdb-lwt/influxdb-lwt.0.3.0/opam
  packages/influxdb/influxdb.0.3.0/opam
Labels: question

#16197 Mew,mew vi
  packages/mew/mew.0.1.0/opam
  packages/mew_vi/mew_vi.0.1.0/opam
Labels: question

#16188 fdkaac.0.3.2: Add conflict on liquidsoap < 1.4.0
  packages/liquidsoap/liquidsoap.1.3.0/opam
  packages/liquidsoap/liquidsoap.1.3.1/opam
  packages/liquidsoap/liquidsoap.1.3.2/opam
  packages/liquidsoap/liquidsoap.1.3.3-1/opam
  packages/liquidsoap/liquidsoap.1.3.3/opam
  packages/liquidsoap/liquidsoap.1.3.4/opam
  packages/liquidsoap/liquidsoap.1.3.5/opam
  packages/liquidsoap/liquidsoap.1.3.6/opam
  packages/liquidsoap/liquidsoap.1.3.7/opam
Labels: needs reporter action

#16209 [new release] ledgerwallet and ledgerwallet-tezos (0.1.0)
  packages/ledgerwallet-tezos/ledgerwallet-tezos.0.1.0/opam
  packages/ledgerwallet/ledgerwallet.0.1.0/opam
Labels: needs reporter action, question

#16208 new file: packages/oranger/oranger.2.0.2
  packages/oranger/oranger.2.0.2/files/compile_ranger.sh
  packages/oranger/oranger.2.0.2/opam
Labels: needs reporter action, question

#16185 Add llvm.10.0.0 and conf-llvm.10.0.0
  packages/conf-llvm/conf-llvm.10.0.0/files/configure.sh
  packages/conf-llvm/conf-llvm.10.0.0/opam
  packages/llvm/llvm.10.0.0/files/META.patch
  packages/llvm/llvm.10.0.0/files/fix-shared.patch
  packages/llvm/llvm.10.0.0/files/install.sh
  packages/llvm/llvm.10.0.0/files/link-META.patch
  packages/llvm/llvm.10.0.0/opam
Labels: needs maintainer action

#16231 Genprint v0.4
  packages/genprint/genprint.0.4/opam
Labels: needs reporter action

#16288 +angstrom.0.14.0
  packages/angstrom-async/angstrom-async.0.14.0/opam
  packages/angstrom-lwt-unix/angstrom-lwt-unix.0.14.0/opam
  packages/angstrom-unix/angstrom-unix.0.14.0/opam
  packages/angstrom/angstrom.0.14.0/opam
Labels: needs reporter action, question

#16319 [new release] dotenv (0.0.3)
  packages/dotenv/dotenv.0.0.3/opam
Labels: needs reporter action
