Repository ocaml/opam-repository, pull requests merged in 2020-02, with the labels that each got.

#15755 Package herdtools7.7.55
  packages/herdtools7/herdtools7.7.55/opam
Labels: needs reporter action

#15747 Package azure-cosmos-db.0.1.2
  packages/azure-cosmos-db/azure-cosmos-db.0.1.2/opam
Labels: needs reporter action

#15767 Luv: binding to libuv — cross-platform async I/O and other system calls
  packages/luv/luv.0.5.0/opam
Labels: needs reporter action

#15776 Package ppx_rapper.1.0.1
  packages/ppx_rapper/ppx_rapper.1.0.1/opam
Labels: question

#15793 [new release] parmap (1.1.1)
  packages/parmap/parmap.1.1.1/opam
Labels: needs reporter action

#15780 Package multipart-form-data.0.3.0
  packages/multipart-form-data/multipart-form-data.0.3.0/opam
Labels: consider for merge

#15791 Package ocp-indent-nlfork.1.5.4
  packages/ocp-indent-nlfork/ocp-indent-nlfork.1.5.4/opam
Labels: consider for merge

#15779 [new release] elpi (1.10.0)
  packages/elpi/elpi.1.10.0/opam
Labels: needs reporter action

#15787 [new release] obus (1.2.2)
  packages/obus/obus.1.2.2/opam
Labels: consider for merge

#15799 [new release] prom (0.1)
  packages/prom/prom.0.1/opam
Labels: needs reporter action

#15796 Opam publish camlp5.7.11
  packages/camlp5/camlp5.7.11/opam
Labels: needs reporter action

#15814 Release stdcompat.12
  packages/stdcompat/stdcompat.12/opam
Labels: needs reporter action

#15811 Links version 0.9.1
  packages/links-postgresql/links-postgresql.0.9.1/opam
  packages/links-sqlite3/links-sqlite3.0.9.1/opam
  packages/links/links.0.9.1/opam
Labels: consider for merge

#15669 [new release] alcotest-lwt, alcotest and alcotest-async (1.0.0)
  packages/alcotest-async/alcotest-async.1.0.0/opam
  packages/alcotest-lwt/alcotest-lwt.1.0.0/opam
  packages/alcotest/alcotest.1.0.0/opam
  packages/base64/base64.3.2.0/opam
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.3.1/opam
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.3.2/opam
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.3.3/opam
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.3/opam
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.4.0/opam
  packages/capnp-rpc-mirage/capnp-rpc-mirage.0.5.0/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.0.3.2/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.0.3.3/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.0.4.0/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.0.5.0/opam
  packages/current/current.0.1/opam
  packages/digestif/digestif.0.7.1/opam
  packages/digestif/digestif.0.7.2/opam
  packages/digestif/digestif.0.7.3/opam
  packages/digestif/digestif.0.7.4/opam
  packages/digestif/digestif.0.7/opam
  packages/digestif/digestif.0.8.0/opam
  packages/graphql_parser/graphql_parser.0.11.0/opam
  packages/icalendar/icalendar.0.1.0/opam
  packages/icalendar/icalendar.0.1.1/opam
  packages/icalendar/icalendar.0.1.2/opam
  packages/icalendar/icalendar.0.1.3/opam
  packages/irmin-chunk/irmin-chunk.1.3.0/opam
  packages/irmin-fs/irmin-fs.1.3.0/opam
  packages/irmin-mem/irmin-mem.1.3.0/opam
  packages/logtk/logtk.1.5.1/opam
  packages/minicaml/minicaml.0.3.3/opam
  packages/owl/owl.0.3.7/opam
  packages/owl/owl.0.3.8/opam
  packages/owl/owl.0.4.0/opam
  packages/owl/owl.0.5.0/opam
  packages/resp-unix/resp-unix.0.9.1/opam
  packages/resp-unix/resp-unix.0.9/opam
  packages/rpclib/rpclib.5.9.0/opam
  packages/rpclib/rpclib.6.0.0/opam
  packages/rpclib/rpclib.6.1.0/opam
  packages/rpclib/rpclib.7.0.0/opam
  packages/yuscii/yuscii.0.2.0/opam
  packages/yuscii/yuscii.0.2.1/opam
Labels: needs reporter action

#15694 simplify cudf install/uninstall command
  packages/cudf/cudf.0.9-1/opam
Labels: needs reporter action

#15822 Package jupyter-kernel.0.6
  packages/jupyter-kernel/jupyter-kernel.0.6/opam
Labels: consider for merge

#15800 2 packages from cryptosense/ocaml-mock at 0.1.1
  packages/mock-ounit/mock-ounit.0.1.1/opam
  packages/mock/mock.0.1.1/opam
Labels: needs reporter action

#15818 added packages/rankers/rankers.2.0.0
  packages/rankers/rankers.2.0.1/opam
Labels: needs reporter action

#15821 ocaml-migrate-parsetree 1.6.0
  packages/ocaml-migrate-parsetree/ocaml-migrate-parsetree.1.6.0/opam
Labels: needs reporter action

#15830 [new release] ppxfind (1.4)
  packages/ppxfind/ppxfind.1.4/opam
Labels: needs reporter action

#15833 [new release] alcotest-lwt, alcotest and alcotest-async (1.0.1)
  packages/alcotest-async/alcotest-async.1.0.1/opam
  packages/alcotest-lwt/alcotest-lwt.1.0.1/opam
  packages/alcotest/alcotest.1.0.1/opam
Labels: consider for merge, question

#15843 [new release] owl-symbolic (0.2.0)
  packages/owl-symbolic/owl-symbolic.0.2.0/opam
Labels: consider for merge

#15845 [new release] dune-build-info, dune, dune-configurator, dune-action-plugin, dune-private-libs and dune-glob (2.3.0)
  packages/dune-action-plugin/dune-action-plugin.2.3.0/opam
  packages/dune-build-info/dune-build-info.2.3.0/opam
  packages/dune-configurator/dune-configurator.2.3.0/opam
  packages/dune-glob/dune-glob.2.3.0/opam
  packages/dune-private-libs/dune-private-libs.2.3.0/opam
  packages/dune/dune.2.3.0/opam
Labels: needs reporter action

#15794 Add Unison 2.51.2
  packages/unison/unison.2.51.2/files/ocaml48.patch
  packages/unison/unison.2.51.2/files/unison.install
  packages/unison/unison.2.51.2/opam
Labels: consider for merge, question

#15839 [new release] inquire (0.1.0)
  packages/inquire/inquire.0.1.0/opam
Labels: needs reporter action

#15877 Add {learn-ocaml, learn-ocaml-client} 0.12
  packages/learn-ocaml-client/learn-ocaml-client.0.12/opam
  packages/learn-ocaml/learn-ocaml.0.12/opam
Labels: needs reporter action, question

#15860 Release Alt-Ergo 2.3.1 (all packages)
  packages/alt-ergo-lib/alt-ergo-lib.2.3.1/opam
  packages/alt-ergo-parsers/alt-ergo-parsers.2.3.1/opam
  packages/alt-ergo/alt-ergo.2.3.1/opam
  packages/altgr-ergo/altgr-ergo.2.3.1/opam
Labels: needs reporter action

#15878 [new release] dune-build-info, dune, dune-configurator, dune-action-plugin, dune-private-libs and dune-glob (2.3.1)
  packages/dune-action-plugin/dune-action-plugin.2.3.1/opam
  packages/dune-build-info/dune-build-info.2.3.1/opam
  packages/dune-configurator/dune-configurator.2.3.1/opam
  packages/dune-glob/dune-glob.2.3.1/opam
  packages/dune-private-libs/dune-private-libs.2.3.1/opam
  packages/dune/dune.2.3.1/opam
Labels: needs reporter action

#15853 Result 1.5 - improved 4.08 compatibility
  packages/result/result.1.5/opam
Labels: consider for merge

#15770 Add pkg libdash
  packages/libdash/libdash.0.1/opam
Labels: needs reporter action

#15903 Package oplot.0.50
  packages/oplot/oplot.0.50/opam
Labels: consider for merge

#15899 2 packages from Gbury/mSAT at 0.8.2
  packages/msat-bin/msat-bin.0.8.2/opam
  packages/msat/msat.0.8.2/opam
Labels: needs reporter action
