Repository ocaml/opam-repository, pull requests merged in 2020-11, with the labels that each got.

#17551 [new release] ocaml-protoc-plugin (4.1.0)
  packages/ocaml-protoc-plugin/ocaml-protoc-plugin.4.1.0/opam
Labels: consider for merge

#17555 [new release] ocamlformat (0.15.1)
  packages/ocamlformat/ocamlformat.0.15.1/opam
Labels: consider for merge

#17562 Package azure-cosmos-db.0.1.5
  packages/azure-cosmos-db/azure-cosmos-db.0.1.5/opam
Labels: consider for merge

#17569 [new release] mirage-crypto-pk, mirage-crypto, mirage-crypto-rng and mirage-crypto-rng-mirage (0.8.7)
  packages/mirage-crypto-pk/mirage-crypto-pk.0.8.7/opam
  packages/mirage-crypto-rng-mirage/mirage-crypto-rng-mirage.0.8.7/opam
  packages/mirage-crypto-rng/mirage-crypto-rng.0.8.7/opam
  packages/mirage-crypto/mirage-crypto.0.8.7/opam
Labels: consider for merge

#17566 [new release] checkseum (0.3.0)
  packages/checkseum/checkseum.0.3.0/opam
Labels: question

#17563 add pkg guacaml-0.02
  packages/GuaCaml/GuaCaml.0.02/opam
Labels: needs reporter action

#17574 Various fixes (OCaml 4.12 edition)
  packages/asn1-combinators/asn1-combinators.0.2.0-1/opam
  packages/asn1-combinators/asn1-combinators.0.2.0/opam
  packages/asn1-combinators/asn1-combinators.0.2.2/opam
  packages/asn1-combinators/asn1-combinators.0.2.3/opam
  packages/core/core.113.24.00/opam
  packages/core/core.113.24.01/opam
  packages/core/core.113.24.02/opam
  packages/core/core.113.33.00+4.03/opam
  packages/core/core.113.33.01+4.03/opam
  packages/core/core.113.33.02+4.03/opam
  packages/core/core.v0.10.0/opam
  packages/core/core.v0.11.2/opam
  packages/core/core.v0.11.3/opam
  packages/core/core.v0.12.2/opam
  packages/core/core.v0.12.3/opam
  packages/core/core.v0.12.4/opam
  packages/core/core.v0.13.0/opam
  packages/core/core.v0.14.0/opam
  packages/core/core.v0.9.2/opam
  packages/core_kernel/core_kernel.113.24.00/opam
  packages/core_kernel/core_kernel.113.33.01+4.03/opam
  packages/core_kernel/core_kernel.113.33.02+4.03/opam
  packages/core_kernel/core_kernel.v0.10.0/opam
  packages/core_kernel/core_kernel.v0.11.1/opam
  packages/core_kernel/core_kernel.v0.12.2/opam
  packages/core_kernel/core_kernel.v0.12.3/opam
  packages/core_kernel/core_kernel.v0.13.1/opam
  packages/core_kernel/core_kernel.v0.14.0/opam
  packages/core_kernel/core_kernel.v0.9.1/opam
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.3.7.0/opam
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.3.7.1/opam
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.3.8.0/opam
  packages/mdx/mdx.1.7.0/opam
  packages/ocp-index/ocp-index.1.2.1/opam
  packages/topkg/topkg.0.7.5/opam
  packages/topkg/topkg.0.7.6/opam
  packages/topkg/topkg.0.7.7/opam
  packages/topkg/topkg.0.7.8/opam
  packages/topkg/topkg.0.7.9/opam
  packages/topkg/topkg.0.8.0/opam
  packages/topkg/topkg.0.8.1/opam
  packages/topkg/topkg.0.9.0/opam
  packages/topkg/topkg.0.9.1/opam
  packages/topkg/topkg.1.0.0/opam
  packages/topkg/topkg.1.0.1/opam
  packages/topkg/topkg.1.0.2/opam
Labels: consider for merge

#17577 Fix revdeps from #17571
  packages/azblob-async/azblob-async.0.1.0/opam
  packages/cohttp-lwt/cohttp-lwt.2.0.0/opam
  packages/cohttp-lwt/cohttp-lwt.2.1.3/opam
  packages/cohttp-mirage/cohttp-mirage.2.2.0/opam
  packages/cohttp-mirage/cohttp-mirage.2.3.0/opam
  packages/cohttp-mirage/cohttp-mirage.2.4.0/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.0/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.1/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.2-1/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.2/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.3/opam
  packages/cohttp-mirage/cohttp-mirage.2.5.4/opam
  packages/curly/curly.0.1.0/opam
  packages/curly/curly.0.2.0/opam
  packages/current_github/current_github.0.2/opam
  packages/current_github/current_github.0.3/opam
  packages/current_web/current_web.0.1/opam
  packages/current_web/current_web.0.2/opam
  packages/current_web/current_web.0.3/opam
  packages/git-http/git-http.2.0.0/opam
  packages/git-http/git-http.2.1.0/opam
  packages/git-http/git-http.2.1.1/opam
  packages/git-http/git-http.2.1.2/opam
  packages/git-http/git-http.2.1.3/opam
  packages/git-unix/git-unix.2.0.0/opam
  packages/git-unix/git-unix.2.1.0/opam
  packages/git-unix/git-unix.2.1.1/opam
  packages/git-unix/git-unix.2.1.2/opam
  packages/git-unix/git-unix.2.1.3/opam
  packages/github-jsoo/github-jsoo.3.0.1/opam
  packages/github-jsoo/github-jsoo.3.1.0/opam
  packages/github-jsoo/github-jsoo.4.0.0/opam
  packages/github-jsoo/github-jsoo.4.3.0/opam
  packages/github-jsoo/github-jsoo.4.3.1/opam
  packages/github-jsoo/github-jsoo.4.3.2/opam
  packages/kappa-server/kappa-server.4.1.0/opam
  packages/letsencrypt/letsencrypt.0.1.0/opam
  packages/letsencrypt/letsencrypt.0.1.1/opam
  packages/ocsigen-start/ocsigen-start.2.18.0/opam
  packages/opium/opium.0.17.0/opam
  packages/opium/opium.0.17.1/opam
  packages/opium/opium.0.18.0/opam
  packages/oraft/oraft.0.1.0/opam
  packages/prof_spacetime/prof_spacetime.0.3.0/opam
  packages/prometheus-app/prometheus-app.0.5/opam
  packages/prometheus-app/prometheus-app.0.6/opam
  packages/prometheus-app/prometheus-app.0.7/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.2/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.3/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.4/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.5/opam
  packages/sihl/sihl.0.1.4/opam
  packages/sihl/sihl.0.1.5/opam
  packages/sihl/sihl.0.1.6/opam
  packages/sihl/sihl.0.1.7/opam
Labels: consider for merge

#17565 [new release] digestif (1.0.0)
  packages/digestif/digestif.1.0.0/opam
  packages/git/git.2.0.0/opam
  packages/git/git.2.1.0/opam
  packages/git/git.2.1.1/opam
  packages/git/git.2.1.2/opam
  packages/git/git.2.1.3/opam
Labels: consider for merge

#17603 Package num.1.4
  packages/num/num.1.4/opam
Labels: consider for merge

#17601 [new release] ppx_factory (0.2.0)
  packages/ppx_factory/ppx_factory.0.2.0/opam
Labels: question

#17599 new file: packages/batteries/batteries.3.2.0/opam
  packages/batteries/batteries.3.2.0/opam
Labels: consider for merge

#17596 Package satyrographos.0.0.2.8
  packages/satyrographos/satyrographos.0.0.2.8/opam
Labels: consider for merge

#17607 [new release] owl-zoo, owl-top, owl-base, owl and owl-plplot (1.0.0)
  packages/owl-base/owl-base.1.0.0/opam
  packages/owl-plplot/owl-plplot.1.0.0/opam
  packages/owl-top/owl-top.1.0.0/opam
  packages/owl-zoo/owl-zoo.1.0.0/opam
  packages/owl/owl.1.0.0/opam
Labels: question

#17611 Add hvsock.2.0.0
  packages/hvsock/hvsock.2.0.0/opam
Labels: consider for merge

#17594 Package oraft.0.1.1
  packages/oraft/oraft.0.1.1/opam
Labels: needs reporter action

#17635 PARTIALLD not set for ocaml-option-32bit
  packages/ocaml-variants/ocaml-variants.4.12.0+trunk/opam
  packages/ocaml-variants/ocaml-variants.4.12.0~alpha1+options/opam
Labels: consider for merge

#17640 Package opam-file-format.2.1.1
  packages/opam-file-format/opam-file-format.2.1.1/opam
Labels: consider for merge

#17641 [new release] ocaml-lsp-server, lsp and jsonrpc (1.2.0)
  packages/jsonrpc/jsonrpc.1.2.0/opam
  packages/lsp/lsp.1.2.0/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.2.0/opam
Labels: needs reporter action, question

#17672 [new release] decimal (0.1.1)
  packages/decimal/decimal.0.1.1/opam
Labels: consider for merge

#17670 Frama-C: new release (22.0)
  packages/frama-c/frama-c.22.0/files/01-tests-cpp-m32.patch
  packages/frama-c/frama-c.22.0/files/02-tests-flamegraph.patch
  packages/frama-c/frama-c.22.0/opam
Labels: question

#17625 Package samplerate.0.1.5
  packages/conf-libsamplerate/conf-libsamplerate.1/opam
  packages/samplerate/samplerate.0.1.5/opam
Labels: consider for merge

#17693 3 packages from gitlab.com/dannywillems/ocaml-ff/-/archive/0.5.0/ocaml-ff-0.5.0.tar.gz
  packages/ff-pbt/ff-pbt.0.5.0/opam
  packages/ff-sig/ff-sig.0.5.0/opam
  packages/ff/ff.0.5.0/opam
Labels: needs reporter action

#17694 Package blake3.0.1
  packages/blake3/blake3.0.1/opam
Labels: needs reporter action

#17689 [new release] ocaml-lsp-server, lsp and jsonrpc (1.3.0)
  packages/jsonrpc/jsonrpc.1.3.0/opam
  packages/lsp/lsp.1.3.0/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.3.0/opam
Labels: needs reporter action

#17708 [new release] mirage-protocols (5.0.0)
  packages/mirage-protocols/mirage-protocols.5.0.0/opam
Labels: consider for merge

#17719 Added cloudi.2.0.1
  packages/cloudi/cloudi.2.0.1/opam
Labels: consider for merge

#17725 [new release] reparse and reparse-unix (2.0.0)
  packages/reparse-unix/reparse-unix.2.0.0/opam
  packages/reparse/reparse.2.0.0/opam
Labels: consider for merge

#17720 [new release] sendmail, sendmail-lwt, received and colombe (0.4.0)
  packages/colombe/colombe.0.4.0/opam
  packages/letters/letters.0.1.1/opam
  packages/letters/letters.0.2.0/opam
  packages/received/received.0.4.0/opam
  packages/sendmail-lwt/sendmail-lwt.0.4.0/opam
  packages/sendmail/sendmail.0.4.0/opam
Labels: consider for merge
