Repository ocaml/opam-repository, pull requests merged in 2021-05, with the labels that each got.

#18633 Relinquish Caravan maintainership
  packages/caravan/caravan.0.0.2/opam
Labels: consider for merge

#18651 2 packages from jobjo/popper at 0.1.1
  packages/popper/popper.0.1.1/opam
  packages/ppx_deriving_popper/ppx_deriving_popper.0.1.1/opam
Labels: consider for merge

#18659 Package xmldiff.0.6.0
  packages/crowbar/crowbar.0.1/opam
  packages/xmldiff/xmldiff.0.6.0/opam
Labels: consider for merge

#18678 [new release] shared-block-ring (3.0.0)
  packages/shared-block-ring/shared-block-ring.3.0.0/opam
Labels: consider for merge

#18709 [new release] ocaml-lsp-server, lsp and jsonrpc (1.6.1)
  packages/jsonrpc/jsonrpc.1.6.1/opam
  packages/lsp/lsp.1.6.1/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.6.1/opam
Labels: consider for merge

#18715 Package httph.0.1
  packages/httph/httph.0.1/opam
Labels: needs reporter action

#18751 Added cloudi.2.0.2
  packages/cloudi/cloudi.2.0.2/opam
Labels: needs reporter action

#18756 Package testu01.1.2.3-0.1
  packages/testu01/testu01.1.2.3-0.1/opam
Labels: question
