Repository ocaml/opam-repository, pull requests merged in 2021-06, with the labels that each got.

#18723 [new release] jsonxt (1.0.0)
  packages/jsonxt/jsonxt.1.0.0/opam
Labels: needs reporter action

#18760 mirage-crypto: Add missing lower-bound constraint
  packages/mirage-crypto/mirage-crypto.0.6.0/opam
  packages/mirage-crypto/mirage-crypto.0.6.1/opam
  packages/mirage-crypto/mirage-crypto.0.6.2/opam
Labels: consider for merge

#18769 [new release] ca-certs-nss (3.66)
  packages/ca-certs-nss/ca-certs-nss.3.66/opam
Labels: consider for merge

#18828 Add a version constraint on ppxlib in the previous release of visitors.
  packages/visitors/visitors.20210316/opam
Labels: consider for merge

#18827 Package visitors.20210608
  packages/visitors/visitors.20210608/opam
Labels: consider for merge

#18702 Package goblint-cil.1.8.0
  packages/goblint-cil/goblint-cil.1.8.0/opam
Labels: needs reporter action

#18680 Package mkocaml.1.2
  packages/mkocaml/mkocaml.1.2/opam
Labels: consider for merge

#18837 vhd-format is not compatible with OCaml 4.13
  packages/vhd-format/vhd-format.0.12.0/opam
  packages/vhd-format/vhd-format.0.12.1/opam
Labels: consider for merge

#18204 Added tutorial to submit first package to opam.ocaml.org
  CONTRIBUTING.md
Labels: consider for merge, needs maintainer action, question

#18785 8 packages from savonet/ocaml-ffmpeg at 1.0.0-beta1
  packages/conf-ffmpeg/conf-ffmpeg.1/opam
  packages/ffmpeg-av/ffmpeg-av.1.0.0~beta1/opam
  packages/ffmpeg-avcodec/ffmpeg-avcodec.1.0.0~beta1/opam
  packages/ffmpeg-avdevice/ffmpeg-avdevice.1.0.0~beta1/opam
  packages/ffmpeg-avfilter/ffmpeg-avfilter.1.0.0~beta1/opam
  packages/ffmpeg-avutil/ffmpeg-avutil.1.0.0~beta1/opam
  packages/ffmpeg-swresample/ffmpeg-swresample.1.0.0~beta1/opam
  packages/ffmpeg-swscale/ffmpeg-swscale.1.0.0~beta1/opam
  packages/ffmpeg/ffmpeg.1.0.0~beta1/opam
  packages/mastodon-archive-viewer/mastodon-archive-viewer.0.2/opam
  packages/mastodon-archive-viewer/mastodon-archive-viewer.0.3/opam
Labels: consider for merge

#18740 Package feather_async.0.2.0
  packages/feather_async/feather_async.0.2.0/opam
Labels: question

#18722 [new release] bitwuzla and bitwuzla-bin (0.0.0)
  packages/bitwuzla-bin/bitwuzla-bin.0.0.0/opam
  packages/bitwuzla/bitwuzla.0.0.1/opam
Labels: consider for merge

#18895 [new release] mula (0.1.0)
  packages/mula/mula.0.1.0/opam
Labels: consider for merge

#18886 bump dolog version constraint in oplsr.8.0.1
  packages/oplsr/oplsr.8.0.1/opam
Labels: consider for merge

#18897 Adds CamlPDF v2.4
  packages/camlpdf/camlpdf.2.4/opam
Labels: consider for merge

#18870 2 packages from INRIA/zelus at 2.2
  packages/zelus-gtk/zelus-gtk.2.2/opam
  packages/zelus/zelus.2.2/opam
Labels: consider for merge

#18901 Adds cpdf v2.4
  packages/cpdf/cpdf.2.4/files/cpdf.install
  packages/cpdf/cpdf.2.4/opam
Labels: consider for merge

#18893 Package srt.0.2.0
  packages/conf-srt/conf-srt.1/opam
  packages/liquidsoap/liquidsoap.1.4.0/opam
  packages/liquidsoap/liquidsoap.1.4.1-1/opam
  packages/liquidsoap/liquidsoap.1.4.1-2/opam
  packages/liquidsoap/liquidsoap.1.4.1/opam
  packages/liquidsoap/liquidsoap.1.4.2/opam
  packages/liquidsoap/liquidsoap.1.4.3/opam
  packages/srt/srt.0.2.0/opam
Labels: consider for merge

#18925 [new release] omd (2.0.0.alpha2)
  packages/omd/omd.2.0.0~alpha2/opam
Labels: consider for merge

#18932 update graphql_parser lower bounds on dune
  packages/graphql_parser/graphql_parser.0.11.0/opam
  packages/graphql_parser/graphql_parser.0.12.2/opam
  packages/graphql_parser/graphql_parser.0.13.0/opam
  packages/graphql_parser/graphql_parser.0.9.0/opam
Labels: consider for merge

#18968 [new release] ocaml-lsp-server, lsp and jsonrpc (1.7.0)
  packages/jsonrpc/jsonrpc.1.7.0/opam
  packages/lsp/lsp.1.7.0/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.7.0/opam
Labels: consider for merge

#18974 [new release] reparse, reparse-lwt and reparse-lwt-unix (3.0.1)
  packages/reparse-lwt-unix/reparse-lwt-unix.3.0.1/opam
  packages/reparse-lwt/reparse-lwt.3.0.1/opam
  packages/reparse/reparse.3.0.1/opam
Labels: consider for merge

#18981 [new release] ppx_distr_guards (0.3)
  packages/ppx_distr_guards/ppx_distr_guards.0.3/opam
Labels: consider for merge
