Repository ocaml/opam-repository, pull requests merged in 2021-08, with the labels that each got.

#19038 add virtual package conf-librsvg2
  packages/conf-librsvg2/conf-librsvg2.0/opam
Labels: question

#19213 [new release] preface (0.1.0)
  packages/preface/preface.0.1.0/opam
Labels: consider for merge

#19211 [new release] jekyll-format (0.3.0)
  packages/jekyll-format/jekyll-format.0.3.0/opam
  packages/yaml-sexp/yaml-sexp.3.0.0/opam
Labels: consider for merge

#19177 Package ppx_pbt.0.2.0
  packages/ppx_pbt/ppx_pbt.0.2.1/opam
Labels: consider for merge

#19215 Luv 0.5.10 - binding to libuv, the core of Node.js
  packages/luv/luv.0.5.10/opam
Labels: consider for merge

#19195 Package salsa20.1.2.0
  packages/salsa20-core/salsa20-core.0.2.0/opam
  packages/salsa20-core/salsa20-core.0.3.0/opam
  packages/salsa20/salsa20.1.2.0/opam
Labels: consider for merge

#19197 Package scrypt-kdf.1.2.0
  packages/scrypt-kdf/scrypt-kdf.1.2.0/opam
Labels: consider for merge

#19263 [new release] um-abt (0.1.3)
  packages/um-abt/um-abt.0.1.3/opam
Labels: needs reporter action
