Repository ocaml/opam-repository, pull requests merged in 2021-02, with the labels that each got.

#18060 Prepare for dose3.6.0
  packages/conf-dpkg/conf-dpkg.1/opam
  packages/conf-python-3/conf-python-3.1.0.0/opam
  packages/conf-python3-yaml/conf-python3-yaml.1/opam
  packages/opam-lib/opam-lib.1.3.0/opam
  packages/opam-lib/opam-lib.1.3.1/opam
  packages/opam-solver/opam-solver.2.0.0/opam
  packages/opam-solver/opam-solver.2.0.0~beta/opam
  packages/opam-solver/opam-solver.2.0.0~beta3.1/opam
  packages/opam-solver/opam-solver.2.0.0~beta3/opam
  packages/opam-solver/opam-solver.2.0.0~beta5/opam
  packages/opam-solver/opam-solver.2.0.0~rc/opam
  packages/opam-solver/opam-solver.2.0.0~rc2/opam
  packages/opam-solver/opam-solver.2.0.0~rc3/opam
  packages/opam-solver/opam-solver.2.0.1/opam
  packages/opam-solver/opam-solver.2.0.2/opam
  packages/opam-solver/opam-solver.2.0.3/opam
  packages/opam-solver/opam-solver.2.0.4/opam
  packages/opam-solver/opam-solver.2.0.5/opam
  packages/opam-solver/opam-solver.2.0.6/opam
  packages/opam-solver/opam-solver.2.0.7/opam
  packages/opam-solver/opam-solver.2.0~alpha5/opam
  packages/opam-solver/opam-solver.2.1.0~beta2/opam
  packages/opam-solver/opam-solver.2.1.0~beta4/opam
Labels: consider for merge

#18073 Tezos-crypto should depend on 0.3.15, not 0.3.14.
  packages/bls12-381/bls12-381.0.3.15/opam
  packages/tezos-crypto/tezos-crypto.8.0/opam
  packages/tezos-crypto/tezos-crypto.8.1/opam
Labels: consider for merge

#18013 [new release] stdlib-shims (0.3.0)
  packages/stdlib-shims/stdlib-shims.0.3.0/opam
Labels: needs maintainer action

#18067 Package ocaml-protoc-plugin.4.2.0
  packages/conf-protoc/conf-protoc.1.0.0/opam
  packages/ocaml-protoc-plugin/ocaml-protoc-plugin.4.2.0/opam
Labels: consider for merge

#18077 [new release] irmin et al. (2.4.0)
  packages/irmin-bench/irmin-bench.2.4.0/opam
  packages/irmin-chunk/irmin-chunk.2.4.0/opam
  packages/irmin-containers/irmin-containers.2.4.0/opam
  packages/irmin-fs/irmin-fs.2.4.0/opam
  packages/irmin-git/irmin-git.2.4.0/opam
  packages/irmin-graphql/irmin-graphql.2.4.0/opam
  packages/irmin-http/irmin-http.2.4.0/opam
  packages/irmin-layers/irmin-layers.2.4.0/opam
  packages/irmin-mirage-git/irmin-mirage-git.2.4.0/opam
  packages/irmin-mirage-graphql/irmin-mirage-graphql.2.4.0/opam
  packages/irmin-mirage/irmin-mirage.2.4.0/opam
  packages/irmin-pack/irmin-pack.2.4.0/opam
  packages/irmin-test/irmin-test.2.4.0/opam
  packages/irmin-unix/irmin-unix.2.4.0/opam
  packages/irmin/irmin.2.4.0/opam
  packages/ppx_irmin/ppx_irmin.2.4.0/opam
Labels: needs reporter action

#18084 Package tezos-rust-libs.1.1
  packages/tezos-rust-libs/tezos-rust-libs.1.1/opam
Labels: needs reporter action

#18065 Update source hash code for gappa
  packages/gappa/gappa.1.3.5/opam
Labels: consider for merge

#18135 [new release] travesty (0.7.0)
  packages/travesty/travesty.0.7.0/opam
Labels: consider for merge

#18112 5 packages from gitlab.com/dannywillems/ocaml-bls12-381/-/archive/0.4.1/ocaml-bls12-381-0.4.1.tar.bz2
  packages/bls12-381-gen/bls12-381-gen.0.4.1/opam
  packages/bls12-381-js-gen/bls12-381-js-gen.0.4.1/opam
  packages/bls12-381-js/bls12-381-js.0.4.1/opam
  packages/bls12-381-unix/bls12-381-unix.0.4.1/opam
  packages/bls12-381/bls12-381.0.4.1/opam
Labels: consider for merge

#18144 [new release] postgresql (5.0.0)
  packages/postgresql/postgresql.5.0.0/opam
Labels: consider for merge

#18146 [new release] ppx_import (1.8.0)
  packages/ppx_import/ppx_import.1.8.0/opam
Labels: consider for merge

#18163 added packages/ocamlscript/ocamlscript.3.0.0
  packages/ocamlscript/ocamlscript.3.0.0/files/ocamlscript.install
  packages/ocamlscript/ocamlscript.3.0.0/opam
Labels: consider for merge

#18159 [new release] opasswd (1.3.1)
  packages/opasswd/opasswd.1.3.1/opam
Labels: consider for merge

#18171 Package bnfgen.3.0.0
  packages/bnfgen/bnfgen.3.0.0/opam
Labels: consider for merge

#18168 [new release] irmin et al. (2.5.0)
  packages/irmin-bench/irmin-bench.2.5.0/opam
  packages/irmin-chunk/irmin-chunk.2.5.0/opam
  packages/irmin-containers/irmin-containers.2.5.0/opam
  packages/irmin-fs/irmin-fs.2.5.0/opam
  packages/irmin-git/irmin-git.2.5.0/opam
  packages/irmin-graphql/irmin-graphql.2.5.0/opam
  packages/irmin-http/irmin-http.2.5.0/opam
  packages/irmin-layers/irmin-layers.2.5.0/opam
  packages/irmin-mirage-git/irmin-mirage-git.2.5.0/opam
  packages/irmin-mirage-graphql/irmin-mirage-graphql.2.5.0/opam
  packages/irmin-mirage/irmin-mirage.2.5.0/opam
  packages/irmin-pack/irmin-pack.2.5.0/opam
  packages/irmin-test/irmin-test.2.5.0/opam
  packages/irmin-unix/irmin-unix.2.5.0/opam
  packages/irmin/irmin.2.5.0/opam
  packages/ppx_irmin/ppx_irmin.2.5.0/opam
Labels: consider for merge, question

#18176 [new release] rungen (0.0.1)
  packages/rungen/rungen.0.0.1/opam
Labels: consider for merge

#18202 Fmlib Release 0.1.0
  packages/fmlib/fmlib.0.1.0/opam
Labels: consider for merge, question

#18200 [new release] optint (0.0.5)
  packages/checkseum/checkseum.0.0.1/opam
  packages/checkseum/checkseum.0.0.2/opam
  packages/checkseum/checkseum.0.0.3/opam
  packages/checkseum/checkseum.0.0.9/opam
  packages/checkseum/checkseum.0.1.0/opam
  packages/checkseum/checkseum.0.1.1-1/opam
  packages/checkseum/checkseum.0.1.1/opam
  packages/checkseum/checkseum.0.2.0/opam
  packages/checkseum/checkseum.0.2.1/opam
  packages/checkseum/checkseum.0.3.0/opam
  packages/decompress/decompress.0.9.0/opam
  packages/decompress/decompress.0.9.1/opam
  packages/optint/optint.0.0.5/opam
  packages/rfc1951/rfc1951.0.9.0/opam
  packages/rfc1951/rfc1951.0.9.1/opam
Labels: needs reporter action

#18209 Add coq-of-ocaml version 2.4.0
  packages/coq-of-ocaml/coq-of-ocaml.2.4.0/opam
Labels: question

#18237 relax ppxlib constraint on hack_parallel.1.0.1
  packages/hack_parallel/hack_parallel.1.0.1/opam
Labels: consider for merge
