Repository ocaml/opam-repository, pull requests merged in 2021-01, with the labels that each got.

#17911 OCanren
  packages/OCanren-ppx/OCanren-ppx.0.1.0/opam
  packages/OCanren/OCanren.0.1.0/opam
Labels: question

#17921 [new release] opam-monorepo (0.2.0)
  packages/opam-monorepo/opam-monorepo.0.2.0/opam
Labels: question

#17729 Package gobba.0.4.2
  packages/gobba/gobba.0.4.2/opam
Labels: question

#17925 Add conf-libfuse
  packages/conf-libfuse/conf-libfuse.1/opam
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs/opam
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs2/opam
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs3/opam
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs4/opam
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs5/opam
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs6/opam
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs7/opam
Labels: needs maintainer action

#17928 [new release] pratter (0.1.1)
  packages/pratter/pratter.0.1.1/opam
Labels: consider for merge

#17933 Coq 8.13.0
  packages/conf-gtksourceview3/conf-gtksourceview3.0+2/opam
  packages/coq/coq.8.13.0/files/coq.install
  packages/coq/coq.8.13.0/opam
  packages/coqide/coqide.8.13.0/files/coqide.install
  packages/coqide/coqide.8.13.0/opam
Labels: consider for merge

#17909 conf-rdkit: handle newer distributions
  packages/conf-rdkit/conf-rdkit.1/files/test.cpp
  packages/conf-rdkit/conf-rdkit.1/opam
Labels: consider for merge

#17946 [new release] sihl-web, sihl-session, sihl-email, sihl-persistence, sihl-contract, sihl-token, sihl-core, sihl-queue, sihl-user, sihl-storage, sihl-facade and sihl (0.3.0-rc1)
  packages/sihl-contract/sihl-contract.0.3.0~rc1/opam
  packages/sihl-core/sihl-core.0.3.0~rc1/opam
  packages/sihl-email/sihl-email.0.3.0~rc1/opam
  packages/sihl-facade/sihl-facade.0.3.0~rc1/opam
  packages/sihl-persistence/sihl-persistence.0.3.0~rc1/opam
  packages/sihl-queue/sihl-queue.0.3.0~rc1/opam
  packages/sihl-session/sihl-session.0.3.0~rc1/opam
  packages/sihl-storage/sihl-storage.0.3.0~rc1/opam
  packages/sihl-token/sihl-token.0.3.0~rc1/opam
  packages/sihl-user/sihl-user.0.3.0~rc1/opam
  packages/sihl-web/sihl-web.0.3.0~rc1/opam
  packages/sihl/sihl.0.3.0~rc1/opam
Labels: needs reporter action

#17960 [new release] irmin et al. (2.3.0)
  packages/irmin-bench/irmin-bench.2.3.0/opam
  packages/irmin-chunk/irmin-chunk.2.3.0/opam
  packages/irmin-containers/irmin-containers.2.3.0/opam
  packages/irmin-fs/irmin-fs.2.3.0/opam
  packages/irmin-git/irmin-git.2.3.0/opam
  packages/irmin-graphql/irmin-graphql.2.3.0/opam
  packages/irmin-http/irmin-http.2.3.0/opam
  packages/irmin-layers/irmin-layers.2.3.0/opam
  packages/irmin-mem/irmin-mem.2.3.0/opam
  packages/irmin-mirage-git/irmin-mirage-git.2.3.0/opam
  packages/irmin-mirage-graphql/irmin-mirage-graphql.2.3.0/opam
  packages/irmin-mirage/irmin-mirage.2.3.0/opam
  packages/irmin-pack/irmin-pack.2.3.0/opam
  packages/irmin-test/irmin-test.2.3.0/opam
  packages/irmin-unix/irmin-unix.2.3.0/opam
  packages/irmin/irmin.2.3.0/opam
  packages/ppx_irmin/ppx_irmin.2.3.0/opam
  packages/tezos-storage/tezos-storage.8.0/opam
Labels: needs reporter action

#17942 Add zelus and zelus-gtk 2.1 packages
  packages/zelus-gtk/zelus-gtk.2.1/opam
  packages/zelus/zelus.2.1/opam
Labels: question

#17964 Package opam-publish.2.0.3
  packages/opam-publish/opam-publish.2.0.3/opam
Labels: consider for merge

#17956 [new release] qbf (0.3)
  packages/qbf/qbf.0.3/opam
  packages/touist/touist.3.4.0/opam
  packages/touist/touist.3.4.1/opam
Labels: consider for merge

#17948 Add libwasmtime 0.22
  packages/libwasmtime/libwasmtime.0.22.0+linux-x86_64/opam
  packages/libwasmtime/libwasmtime.0.22.0+macos-x86_64/opam
Labels: question

#17966 [new release] git, git-cohttp, git-cohttp-mirage, git-cohttp-unix, git-unix and git-mirage (3.1.0)
  packages/git-cohttp-mirage/git-cohttp-mirage.3.1.0/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.1.0/opam
  packages/git-cohttp/git-cohttp.3.1.0/opam
  packages/git-mirage/git-mirage.3.1.0/opam
  packages/git-unix/git-unix.3.1.0/opam
  packages/git/git.3.1.0/opam
Labels: consider for merge

#17990 camlbz2: upgrade to 0.7.0
  packages/camlbz2/camlbz2.0.7.0/opam
Labels: needs reporter action

#17882 Package ocsigenserver.2.17.0
  packages/ocsigenserver/ocsigenserver.2.17.0/opam
Labels: needs reporter action

#18001 Package ocsigenserver.2.18.0
  packages/conf-dbm/conf-dbm.1.0.0/opam
  packages/ocsigenserver/ocsigenserver.2.18.0/opam
Labels: consider for merge

#18000 + devkit 1.20210120
  packages/conf-libevent/conf-libevent.1/opam
  packages/devkit/devkit.1.20210120/opam
  packages/libevent/libevent.0.7.0/opam
  packages/libevent/libevent.0.8.0/opam
  packages/libevent/libevent.0.8.1/opam
Labels: consider for merge

#18006 Add google-drive-ocamlfuse 0.7.25
  packages/google-drive-ocamlfuse/google-drive-ocamlfuse.0.7.25/opam
Labels: needs reporter action

#18009 hacl-star-raw: fails on powerpc, so disable
  packages/hacl-star-raw/hacl-star-raw.0.1.1/opam
  packages/hacl-star-raw/hacl-star-raw.0.1/opam
  packages/hacl-star-raw/hacl-star-raw.0.2.0/opam
  packages/hacl-star-raw/hacl-star-raw.0.2.1/opam
  packages/hacl-star-raw/hacl-star-raw.0.2.2/opam
  packages/hacl-star-raw/hacl-star-raw.0.3.0/opam
  packages/tezos-crypto/tezos-crypto.8.0/opam
  packages/tezos-crypto/tezos-crypto.8.1/opam
Labels: consider for merge

#18016 Import metadata from repository in xapi-project/xs-opam
  packages/netlink/netlink.0.3.4/opam
  packages/xapi-stdext-pervasives/xapi-stdext-pervasives.4.16.0/opam
  packages/xapi-stdext-std/xapi-stdext-std.4.16.0/opam
  packages/xapi-stdext-threads/xapi-stdext-threads.4.16.0/opam
  packages/xapi-stdext-unix/xapi-stdext-unix.4.16.0/opam
  packages/xenstore_transport/xenstore_transport.1.3.0/opam
Labels: needs reporter action, question

#18025 [new release] art (0.1.0)
  packages/art/art.0.1.0/opam
Labels: consider for merge

#18040 Package apronext.1.0.3
  packages/apronext/apronext.1.0.3/opam
  packages/conf-mpfr/conf-mpfr.2/opam
  packages/picasso/picasso.0.1/opam
Labels: consider for merge

#18045 Publish timere.0.1.3
  packages/timere/timere.0.1.3/opam
Labels: consider for merge

#18015 Release Alt-Ergo 2.4.0 (all packages)
  packages/alt-ergo-lib/alt-ergo-lib.2.4.0/opam
  packages/alt-ergo-parsers/alt-ergo-parsers.2.4.0/opam
  packages/alt-ergo/alt-ergo.2.4.0/opam
  packages/altgr-ergo/altgr-ergo.2.4.0/opam
Labels: consider for merge

#18051 [new release] paf (0.0.1)
  packages/paf/paf.0.0.1/opam
Labels: consider for merge

#18053 Abella 2.0.7
  packages/abella/abella.2.0.7/opam
Labels: question

#18059 Create symlink for conf-bison and conf-flex in Mac homebrew
  packages/conf-bison/conf-bison.2/opam
  packages/conf-flex/conf-flex.2/opam
Labels: consider for merge, needs maintainer action
