Repository ocaml/opam-repository, pull requests merged in 2021-03, with the labels that each got.

#18242 new file: packages/batteries/batteries.3.3.0/opam
  packages/batteries/batteries.3.3.0/opam
Labels: consider for merge

#18261 camlp4.system: remove brew depext
  packages/camlp4/camlp4.4.04+system/opam
  packages/camlp4/camlp4.4.05+system/opam
  packages/camlp4/camlp4.4.06+system/opam
  packages/camlp4/camlp4.4.07+system/opam
  packages/camlp4/camlp4.4.08+system/opam
  packages/camlp4/camlp4.4.09+system/opam
  packages/camlp4/camlp4.4.10+system/opam
  packages/camlp4/camlp4.4.11+system/opam
  packages/camlp4/camlp4.4.12+system/opam
Labels: question

#18269 Publish timere-parse.0.0.1
  packages/timere-parse/timere-parse.0.0.1/opam
Labels: consider for merge

#18245 Restore ARM64 support for 4.02-4.05
  packages/ocaml-base-compiler/ocaml-base-compiler.4.02.0/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.02.0/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.02.1/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.02.1/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.02.2/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.02.2/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.02.3/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.02.3/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.03.0/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.03.0/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.04.0/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.04.0/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.04.1/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.04.1/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.04.2/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.04.2/opam
  packages/ocaml-base-compiler/ocaml-base-compiler.4.05.0/files/gpr1330.patch
  packages/ocaml-base-compiler/ocaml-base-compiler.4.05.0/opam
Labels: consider for merge

#18298 [new release] bag (1.0.0)
  packages/bag/bag.1.0.0/opam
Labels: consider for merge

#18305 Package archetype.1.2.2
  packages/archetype/archetype.1.2.2/opam
Labels: consider for merge

#18291 [new release] omd (2.0.0~alpha1)
  packages/md2mld/md2mld.0.2.0/opam
  packages/md2mld/md2mld.0.3.0/opam
  packages/ocp_reveal/ocp_reveal.0.1/opam
  packages/omd/omd.2.0.0~alpha1/opam
  packages/sail/sail.0.13/opam
  packages/sail/sail.0.14/opam
Labels: consider for merge

#18293 Package speex.0.4.0
  packages/speex/speex.0.4.0/opam
Labels: consider for merge

#18294 Package vorbis.0.8.0
  packages/conf-libvorbis/conf-libvorbis.1/opam
  packages/vorbis/vorbis.0.8.0/opam
Labels: consider for merge

#18301 +mparser.1.3, +mparser-re.1.3, +mparser-pcre.1.3
  packages/anthill/anthill.0.1/opam
  packages/mparser-pcre/mparser-pcre.1.3/opam
  packages/mparser-re/mparser-re.1.3/opam
  packages/mparser/mparser.1.3/opam
  packages/netkat/netkat.0.1/opam
Labels: consider for merge

#18303 Package flac.0.3.0
  packages/flac/flac.0.3.0/opam
Labels: consider for merge

#18302 Package opus.0.2.0
  packages/conf-libopus/conf-libopus.1/opam
  packages/opus/opus.0.2.0/opam
Labels: consider for merge

#18300 Add the libtorch 1.8 packages.
  packages/libtorch/libtorch.1.8.0+linux-x86_64/opam
  packages/libtorch/libtorch.1.8.0+macos-x86_64/opam
Labels: consider for merge

#18309 7 packages from oxidizing/sihl at 0.3.0-rc2
  packages/sihl-cache/sihl-cache.0.3.0~rc2/opam
  packages/sihl-email/sihl-email.0.3.0~rc2/opam
  packages/sihl-queue/sihl-queue.0.3.0~rc2/opam
  packages/sihl-storage/sihl-storage.0.3.0~rc2/opam
  packages/sihl-token/sihl-token.0.3.0~rc2/opam
  packages/sihl-user/sihl-user.0.3.0~rc2/opam
  packages/sihl/sihl.0.3.0~rc2/opam
Labels: needs reporter action

#18311 Package fsml.0.3.0
  packages/fsml/fsml.0.3.0/opam
Labels: consider for merge

#18312 Fix licenses for some conf packages
  packages/conf-alsa/conf-alsa.1/opam
  packages/conf-ao/conf-ao.1/opam
  packages/conf-dssi/conf-dssi.1/opam
  packages/conf-gstreamer/conf-gstreamer.1/opam
  packages/conf-jack/conf-jack.1/opam
  packages/conf-ladspa/conf-ladspa.1/opam
  packages/conf-libflac/conf-libflac.1/opam
  packages/conf-libogg/conf-libogg.1/opam
  packages/conf-libopus/conf-libopus.1/opam
  packages/conf-libsamplerate/conf-libsamplerate.1/opam
  packages/conf-libspeex/conf-libspeex.1/opam
  packages/conf-libtheora/conf-libtheora.1/opam
  packages/conf-libvorbis/conf-libvorbis.1/opam
  packages/conf-portaudio/conf-portaudio.1/opam
  packages/conf-pulseaudio/conf-pulseaudio.1/opam
  packages/conf-soundtouch/conf-soundtouch.1/opam
Labels: consider for merge

#18321 7 packages from oxidizing/sihl at 0.3.0
  packages/sihl-cache/sihl-cache.0.3.0/opam
  packages/sihl-email/sihl-email.0.3.0/opam
  packages/sihl-queue/sihl-queue.0.3.0/opam
  packages/sihl-storage/sihl-storage.0.3.0/opam
  packages/sihl-token/sihl-token.0.3.0/opam
  packages/sihl-user/sihl-user.0.3.0/opam
  packages/sihl/sihl.0.3.0/opam
Labels: consider for merge, question

#18328 toml.7.0.0 and toml_cconv.7.0.0
  packages/dirsift/dirsift.0.0.3/opam
  packages/toml/toml.7.0.0/opam
  packages/toml_cconv/toml_cconv.7.0.0/opam
Labels: consider for merge

#18355 [new release] ocaml-lsp-server, lsp and jsonrpc (1.4.1)
  packages/jsonrpc/jsonrpc.1.4.1/opam
  packages/lsp/lsp.1.4.1/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.4.1/opam
Labels: consider for merge

#18110 2 packages from LexiFi/gen_js_api at 1.0.7
  packages/conf-npm/conf-npm.1/opam
  packages/cordova-plugin-background-mode/cordova-plugin-background-mode.1.0/opam
  packages/cordova-plugin-battery-status/cordova-plugin-battery-status.1.0/opam
  packages/cordova-plugin-local-notifications/cordova-plugin-local-notifications.1.0/opam
  packages/cordova-plugin-sim-card/cordova-plugin-sim-card.1.0/opam
  packages/cordova/cordova.1.0/opam
  packages/gen_js_api/gen_js_api.1.0.7/opam
  packages/ocaml-js-stdlib/ocaml-js-stdlib.1.0/opam
  packages/ojs/ojs.1.0.7/opam
Labels: needs reporter action

#18324 [new release] decoders-yojson, decoders-cbor, decoders, decoders-jsonm, decoders-ezjsonm, decoders-sexplib, decoders-bencode and decoders-msgpck (0.6.0)
  packages/decoders-bencode/decoders-bencode.0.6.0/opam
  packages/decoders-cbor/decoders-cbor.0.6.0/opam
  packages/decoders-ezjsonm/decoders-ezjsonm.0.6.0/opam
  packages/decoders-jsonm/decoders-jsonm.0.6.0/opam
  packages/decoders-msgpck/decoders-msgpck.0.6.0/opam
  packages/decoders-sexplib/decoders-sexplib.0.6.0/opam
  packages/decoders-yojson/decoders-yojson.0.6.0/opam
  packages/decoders/decoders.0.6.0/opam
Labels: needs reporter action

#18327 Why3 1.4.0
  packages/frama-c/frama-c.19.0/opam
  packages/frama-c/frama-c.19.1/opam
  packages/frama-c/frama-c.21.0/opam
  packages/frama-c/frama-c.21.1/opam
  packages/frama-c/frama-c.22.0/opam
  packages/why3-coq/why3-coq.1.4.0/opam
  packages/why3-ide/why3-ide.1.4.0/opam
  packages/why3/why3.1.4.0/opam
Labels: needs reporter action

#18367 Package comby.1.3.0
  packages/comby/comby.1.3.0/opam
Labels: needs reporter action

#18368 Add Polly 0.2.2 bindings for the Linux epoll system call
  packages/polly/polly.0.2.2/opam
Labels: consider for merge

#18369 [new release] msgpck and msgpck-repr (1.6)
  packages/msgpck-repr/msgpck-repr.1.6/opam
  packages/msgpck/msgpck.1.6/opam
Labels: consider for merge

#18372 [new release] git, git-cohttp, git-cohttp-mirage, git-cohttp-unix, git-mirage and git-unix (3.3.3)
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.3/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.3.3/opam
  packages/git-cohttp/git-cohttp.3.3.3/opam
  packages/git-mirage/git-mirage.3.3.3/opam
  packages/git-unix/git-unix.3.3.3/opam
  packages/git/git.3.3.3/opam
Labels: consider for merge

#18366 [new release] doi2bib (0.3.0)
  packages/doi2bib/doi2bib.0.3.0/opam
Labels: consider for merge

#18371 17 packages from inhabitedtype/ocaml-aws at 1.2
  packages/aws-async/aws-async.1.2/opam
  packages/aws-autoscaling/aws-autoscaling.0.1.0/opam
  packages/aws-autoscaling/aws-autoscaling.1.2/opam
  packages/aws-cloudformation/aws-cloudformation.0.1.0/opam
  packages/aws-cloudformation/aws-cloudformation.1.2/opam
  packages/aws-cloudtrail/aws-cloudtrail.0.1.0/opam
  packages/aws-cloudtrail/aws-cloudtrail.1.2/opam
  packages/aws-cloudwatch/aws-cloudwatch.1.2/opam
  packages/aws-ec2/aws-ec2.0.1.0/opam
  packages/aws-ec2/aws-ec2.1.2/opam
  packages/aws-elasticache/aws-elasticache.1.2/opam
  packages/aws-elasticloadbalancing/aws-elasticloadbalancing.0.1.0/opam
  packages/aws-elasticloadbalancing/aws-elasticloadbalancing.1.2/opam
  packages/aws-lwt/aws-lwt.1.2/opam
  packages/aws-rds/aws-rds.1.2/opam
  packages/aws-route53/aws-route53.1.2/opam
  packages/aws-sdb/aws-sdb.0.1.0/opam
  packages/aws-sdb/aws-sdb.1.2/opam
  packages/aws-sqs/aws-sqs.1.2/opam
  packages/aws-ssm/aws-ssm.0.1.0/opam
  packages/aws-ssm/aws-ssm.1.2/opam
  packages/aws-sts/aws-sts.0.1.0/opam
  packages/aws-sts/aws-sts.1.2/opam
  packages/aws/aws.1.2/opam
Labels: consider for merge

#18382 Various fixes
  packages/angstrom/angstrom.0.1.0/opam
  packages/angstrom/angstrom.0.1.1/opam
  packages/angstrom/angstrom.0.2.0/opam
  packages/angstrom/angstrom.0.3.0/opam
  packages/angstrom/angstrom.0.4.0/opam
  packages/angstrom/angstrom.0.5.0/opam
  packages/angstrom/angstrom.0.5.1/opam
  packages/cfstream/cfstream.1.2.1/opam
  packages/cfstream/cfstream.1.2.2/opam
  packages/cfstream/cfstream.1.2.3/opam
  packages/cfstream/cfstream.1.3.0/opam
  packages/cstruct/cstruct.2.0.0/opam
  packages/cstruct/cstruct.2.1.0/opam
  packages/cstruct/cstruct.2.2.0/opam
  packages/cstruct/cstruct.2.3.0/opam
  packages/edn/edn.0.1.1/opam
  packages/jsonm/jsonm.1.0.0/opam
  packages/mirage-solo5/mirage-solo5.0.1.1/opam
  packages/text/text.0.6/opam
  packages/text/text.0.7.1/opam
  packages/text/text.0.7/opam
  packages/toml/toml.1.0.0/opam
  packages/toml/toml.2.0.0/opam
  packages/toml/toml.2.1.0/opam
  packages/toml/toml.2.2.0/opam
  packages/toml/toml.2.2.1/opam
  packages/toml/toml.3.0.0/opam
  packages/toml/toml.4.0.0/opam
  packages/toml/toml.5.0.0/opam
  packages/toml/toml.7.0.0/opam
  packages/toml_cconv/toml_cconv.7.0.0/opam
  packages/uint/uint.1.0.2/opam
  packages/uint/uint.1.0.3/opam
  packages/uint/uint.1.1.0/opam
  packages/uint/uint.1.1.1/opam
  packages/uint/uint.1.1.4/opam
  packages/uri/uri.1.9.4/opam
Labels: consider for merge

#18388 [new release] rpclib-html, rpclib-async, rpclib, rpc, rpclib-lwt, ppx_deriving_rpc and rpclib-js (8.1.0)
  packages/ppx_deriving_rpc/ppx_deriving_rpc.8.1.0/opam
  packages/rpc/rpc.8.1.0/opam
  packages/rpclib-async/rpclib-async.8.1.0/opam
  packages/rpclib-html/rpclib-html.8.1.0/opam
  packages/rpclib-js/rpclib-js.8.1.0/opam
  packages/rpclib-lwt/rpclib-lwt.8.1.0/opam
  packages/rpclib/rpclib.8.1.0/opam
Labels: consider for merge

#18392 Partly revert #17577
  packages/azblob-async/azblob-async.0.1.0/opam
  packages/comby/comby.1.2.2/opam
  packages/comby/comby.1.3.0/opam
  packages/curly/curly.0.1.0/opam
  packages/curly/curly.0.2.0/opam
  packages/current_github/current_github.0.2/opam
  packages/current_github/current_github.0.3/opam
  packages/current_github/current_github.0.4/opam
  packages/current_web/current_web.0.1/opam
  packages/current_web/current_web.0.2/opam
  packages/current_web/current_web.0.3/opam
  packages/current_web/current_web.0.4/opam
  packages/git-http/git-http.2.0.0/opam
  packages/git-http/git-http.2.1.0/opam
  packages/git-http/git-http.2.1.1/opam
  packages/git-http/git-http.2.1.2/opam
  packages/git-http/git-http.2.1.3/opam
  packages/git-unix/git-unix.2.1.1/opam
  packages/git-unix/git-unix.2.1.2/opam
  packages/git-unix/git-unix.2.1.3/opam
  packages/kappa-server/kappa-server.4.1.0/opam
  packages/letsencrypt/letsencrypt.0.1.0/opam
  packages/letsencrypt/letsencrypt.0.1.1/opam
  packages/ocsigen-start/ocsigen-start.2.18.0/opam
  packages/ocsigenserver/ocsigenserver.2.18.0/opam
  packages/opium/opium.0.17.0/opam
  packages/opium/opium.0.17.1/opam
  packages/opium/opium.0.18.0/opam
  packages/oraft/oraft.0.1.0/opam
  packages/oraft/oraft.0.1.1/opam
  packages/prometheus-app/prometheus-app.0.6/opam
  packages/prometheus-app/prometheus-app.0.7/opam
  packages/prometheus-app/prometheus-app.1.0/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.2/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.3/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.4/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.5/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.6.1/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.6/opam
  packages/sihl/sihl.0.1.10/opam
  packages/sihl/sihl.0.1.8/opam
  packages/sihl/sihl.0.1.9/opam
  packages/sihl/sihl.0.2.0/opam
  packages/sihl/sihl.0.2.1/opam
  packages/sihl/sihl.0.2.2/opam
Labels: consider for merge

#18399 [new release] dolmen_type, dolmen_bin, dolmen_loop, dolmen_lsp and dolmen (0.5)
  packages/archsat/archsat.1.1/opam
  packages/dolmen/dolmen.0.5/opam
  packages/dolmen_bin/dolmen_bin.0.5/opam
  packages/dolmen_loop/dolmen_loop.0.5/opam
  packages/dolmen_lsp/dolmen_lsp.0.5/opam
  packages/dolmen_type/dolmen_type.0.5/opam
  packages/msat/msat.0.7/opam
Labels: consider for merge

#18400 Two minor tweaks
  packages/ocaml-base-compiler/ocaml-base-compiler.3.12.0/opam
  packages/ocamlfind/ocamlfind.1.3.1/opam
Labels: consider for merge

#18385 [new release] cohttp-lwt-jsoo, cohttp, cohttp-lwt, cohttp-lwt-unix, cohttp-top, cohttp-async and cohttp-mirage (4.0.0)
  packages/cohttp-async/cohttp-async.4.0.0/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.4.0.0/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.4.0.0/opam
  packages/cohttp-lwt/cohttp-lwt.4.0.0/opam
  packages/cohttp-mirage/cohttp-mirage.4.0.0/opam
  packages/cohttp-top/cohttp-top.4.0.0/opam
  packages/cohttp/cohttp.4.0.0/opam
  packages/comby/comby.1.2.2/opam
  packages/doi2bib/doi2bib.0.3.0/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.2.0/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.0/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.1/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.2/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.3/opam
  packages/git-http/git-http.2.0.0/opam
  packages/git-http/git-http.2.1.0/opam
  packages/git-http/git-http.2.1.1/opam
  packages/git-http/git-http.2.1.2/opam
  packages/git-http/git-http.2.1.3/opam
Labels: consider for merge

#18153 initial cca
  packages/cca/cca.0.1/files/cca.install
  packages/cca/cca.0.1/opam
  packages/volt/volt.1.4/opam
Labels: consider for merge

#18410 [new release] optint (0.1.0)
  packages/optint/optint.0.1.0/opam
Labels: consider for merge

#18409 [new release] grenier (0.12)
  packages/grenier/grenier.0.12/opam
Labels: consider for merge

#18422 Package ez_api.0.1.0
  packages/ez_api/ez_api.0.1.0/opam
Labels: consider for merge

#18423 [new release] pp (1.1.2)
  packages/pp/pp.1.1.2/opam
Labels: needs reporter action

#18427 [new release] csexp (1.5.1)
  packages/csexp/csexp.1.5.1/opam
Labels: consider for merge, question
