Repository ocaml/opam-repository, pull requests merged in 2021-09, with the labels that each got.

#19390 [new release] links, links-postgresql, links-sqlite3 and links-mysql (0.9.4)
  packages/links-mysql/links-mysql.0.9.4/opam
  packages/links-postgresql/links-postgresql.0.9.4/opam
  packages/links-sqlite3/links-sqlite3.0.9.4/opam
  packages/links/links.0.9.4/opam
Labels: consider for merge

#19307 Package osnap.0.1.1
  packages/osnap/osnap.0.1.1/opam
Labels: consider for merge

#19401 Package prbnmcn-gnuplot.0.0.1
  packages/prbnmcn-gnuplot/prbnmcn-gnuplot.0.0.1/opam
Labels: consider for merge

#19279 4 packages from sneeuwballen/zipperposition at 2.1
  packages/libzipperposition/libzipperposition.2.1/opam
  packages/logtk/logtk.2.1/opam
  packages/zipperposition-tools/zipperposition-tools.2.1/opam
  packages/zipperposition/zipperposition.2.1/opam
Labels: consider for merge

#19207 4 packages from c-cube/qcheck at 0.18
  packages/alg_structs_qcheck/alg_structs_qcheck.0.1.3/opam
  packages/fadbadml/fadbadml.0.1.2/opam
  packages/preface/preface.0.1.0/opam
  packages/qcheck-alcotest/qcheck-alcotest.0.18/opam
  packages/qcheck-core/qcheck-core.0.18/opam
  packages/qcheck-ounit/qcheck-ounit.0.18/opam
  packages/qcheck/qcheck.0.18/opam
Labels: needs reporter action

#19408 Add the OCaml 4.13 preview of Merlin
  packages/merlin/merlin.4.3.2~4.13preview/opam
Labels: consider for merge

#19280 [new release] unix-errno (0.6.0)
  packages/dlm/dlm.0.3.0/opam
  packages/dlm/dlm.0.3.1/opam
  packages/unix-errno/unix-errno.0.6.0/opam
  packages/unix-sys-resource/unix-sys-resource.0.1.2/opam
  packages/unix-sys-stat/unix-sys-stat.0.5.0/opam
  packages/unix-sys-stat/unix-sys-stat.0.5.1/opam
  packages/unix-sys-stat/unix-sys-stat.0.5.2/opam
  packages/unix-time/unix-time.0.1.0/opam
Labels: consider for merge

#18883 conf-gnomecanvas.2: add required libart for pkg-config gnomecanvas
  packages/conf-gnomecanvas/conf-gnomecanvas.2/opam
Labels: needs reporter action

#19172 Octagon Domain Support with ELINA
  packages/elina/elina.1.3/opam
Labels: consider for merge

#19396 Package ocsigen-toolkit.2.13.0
  packages/ocsigen-toolkit/ocsigen-toolkit.2.13.0/opam
Labels: needs reporter action

#19318 Add gapi-ocaml 0.4.2, google-drive-ocamlfuse 0.7.27
  packages/gapi-ocaml/gapi-ocaml.0.4.2/opam
  packages/google-drive-ocamlfuse/google-drive-ocamlfuse.0.7.27/opam
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs6/opam
Labels: consider for merge

#19437 Hide dune.2.9.0 as much as possible (generates broken dune files)
  packages/dune/dune.2.9.0/opam
Labels: consider for merge

#19450 +flow_parser.0.159.0
  packages/flow_parser/flow_parser.0.159.0/opam
Labels: consider for merge

#19473 [new release] ppx_defer (0.5.0)
  packages/ppx_defer/ppx_defer.0.5.0/opam
Labels: consider for merge

#19475 [new release] llvm (12.0.1)
  packages/conf-llvm/conf-llvm.12.0.1/files/configure.sh
  packages/conf-llvm/conf-llvm.12.0.1/opam
  packages/llvm/llvm.12.0.1/files/META.patch
  packages/llvm/llvm.12.0.1/files/fix-shared.patch
  packages/llvm/llvm.12.0.1/files/install.sh
  packages/llvm/llvm.12.0.1/files/link-META.patch
  packages/llvm/llvm.12.0.1/opam
Labels: consider for merge

#19286 [new release] ocaml-lsp-server, lsp and jsonrpc (1.8.0)
  packages/jsonrpc/jsonrpc.1.8.0/opam
  packages/lsp/lsp.1.8.0/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.8.0/opam
Labels: consider for merge

#19497 fix url.src for camlimages
  packages/camlimages/camlimages.4.0.1/opam
  packages/camlimages/camlimages.4.0.2/opam
  packages/camlimages/camlimages.4.1.0/opam
  packages/camlimages/camlimages.4.1.1/opam
  packages/camlimages/camlimages.4.1.2/opam
  packages/camlimages/camlimages.4.2.0/opam
  packages/camlimages/camlimages.4.2.1/opam
  packages/camlimages/camlimages.4.2.2/opam
  packages/camlimages/camlimages.4.2.3/opam
  packages/camlimages/camlimages.4.2.4/opam
  packages/camlimages/camlimages.4.2.5/opam
  packages/camlimages/camlimages.4.2.6/opam
  packages/camlimages/camlimages.5.0.0/opam
Labels: consider for merge

#19480 Package tsdl-ttf.0.3
  packages/tsdl-ttf/tsdl-ttf.0.3/opam
Labels: consider for merge

#19394 Update some of zoggy's packages urls
  packages/chamo/chamo.2.01/opam
  packages/chamo/chamo.2.02/opam
  packages/chamo/chamo.2.03/opam
Labels: consider for merge

#19534 Package liquidsoap.2.0.0~rc1
  packages/liquidsoap/liquidsoap.2.0.0~rc1/opam
Labels: consider for merge

#19532 Package letters.0.3.0
  packages/letters/letters.0.3.0/opam
Labels: needs reporter action

#19521 Elina version 1.3.1
  packages/elina/elina.1.3.1/opam
Labels: needs reporter action

#19601 labltk-8.06.11 with ocamlbrowser-4.13.0
  packages/labltk/labltk.8.06.11/opam
  packages/ocamlbrowser/ocamlbrowser.4.13.0/opam
Labels: consider for merge

#19599 Add: uucd.14.0.0, uucp.14.0.0, uunf.14.0.0, uuseg.14.0.0
  packages/uucd/uucd.14.0.0/opam
  packages/uucp/uucp.14.0.0/opam
  packages/uunf/uunf.14.0.0/opam
  packages/uuseg/uuseg.14.0.0/opam
Labels: consider for merge

#19518 [new release] re (1.10.3)
  packages/re/re.1.10.3/opam
Labels: question

#19607 [new release] dirsift.0.0.4
  packages/dirsift/dirsift.0.0.4/opam
Labels: consider for merge

#19609 OCaml 4.13 preview for ocaml-lsp-server
  packages/ocaml-lsp-server/ocaml-lsp-server.1.9.0~4.13preview/opam
Labels: consider for merge

#19623 Add: brr.0.0.2
  packages/brr/brr.0.0.2/opam
Labels: consider for merge
