Repository ocaml/opam-repository, pull requests merged in 2022-04, with the labels that each got.

#21099 fix(coq-serapi): cmdliner<1.1.0
  packages/coq-serapi/coq-serapi.8.7.1+0.4.1/opam
  packages/coq-serapi/coq-serapi.8.7.1+0.4.12/opam
  packages/coq-serapi/coq-serapi.8.7.1+0.4.2/opam
  packages/coq-serapi/coq-serapi.8.7.1+0.4.8/opam
  packages/coq-serapi/coq-serapi.8.7.1+0.4/opam
  packages/coq-serapi/coq-serapi.8.7.2+0.4.13/opam
  packages/coq-serapi/coq-serapi.8.8.0+0.5.1/opam
  packages/coq-serapi/coq-serapi.8.8.0+0.5.2/opam
  packages/coq-serapi/coq-serapi.8.8.0+0.5.3/opam
  packages/coq-serapi/coq-serapi.8.8.0+0.5.4/opam
  packages/coq-serapi/coq-serapi.8.8.0+0.5.5/opam
  packages/coq-serapi/coq-serapi.8.8.0+0.5.6/opam
  packages/ppx_deriving/ppx_deriving.4.4.1/opam
  packages/ppx_deriving/ppx_deriving.4.4/opam
Labels: consider for merge

#20645 Add a post-message for num's known install failure
  packages/num/num.1.0/opam
  packages/num/num.1.1/opam
  packages/num/num.1.2/opam
  packages/num/num.1.3/opam
  packages/num/num.1.4/opam
Labels: consider for merge

#21082 Package chamo.3.0
  packages/chamo/chamo.3.0/opam
Labels: consider for merge

#21145 +bigstringaf.0.9.0
  packages/bigstringaf/bigstringaf.0.9.0/opam
Labels: consider for merge

#21152 [new release] optint (0.2.0)
  packages/optint/optint.0.2.0/opam
Labels: consider for merge

#21163 Prepare the release of decompress.1.4.3 which remove the bigarray-compat dependency
  packages/carton/carton.0.3.0/opam
  packages/carton/carton.0.4.0/opam
  packages/carton/carton.0.4.1/opam
  packages/carton/carton.0.4.2/opam
  packages/carton/carton.0.4.3/opam
Labels: consider for merge

#21160 [new release] digestif (1.1.2)
  packages/digestif/digestif.1.1.2/opam
Labels: consider for merge

#21161 [new release] checkseum (0.3.3)
  packages/checkseum/checkseum.0.3.3/opam
Labels: consider for merge

#21155 [new release] rfc1951 and decompress (1.4.3)
  packages/decompress/decompress.1.4.3/opam
  packages/git/git.3.4.0/opam
  packages/git/git.3.5.0/opam
  packages/git/git.3.6.0/opam
  packages/git/git.3.7.0/opam
  packages/git/git.3.7.1/opam
  packages/git/git.3.8.0/opam
  packages/git/git.3.9.0/opam
  packages/rfc1951/rfc1951.1.4.3/opam
Labels: consider for merge

#21178 [new release] carton, carton-lwt and carton-git (carton-v0.4.4)
  packages/carton-git/carton-git.0.4.4/opam
  packages/carton-lwt/carton-lwt.0.4.4/opam
  packages/carton/carton.0.4.4/opam
Labels: consider for merge

#21187 Package ez_api.1.1.1
  packages/ez_api/ez_api.1.1.1/opam
Labels: needs reporter action

#21242 3 packages from andersfugmann/aws-s3 at 4.7.0
  packages/aws-s3-async/aws-s3-async.4.7.0/opam
  packages/aws-s3-lwt/aws-s3-lwt.4.7.0/opam
  packages/aws-s3/aws-s3.4.7.0/opam
Labels: question

#21274 [new release] atdts, atds, atdpy, atdj, atdgen, atdgen-runtime, atdgen-codec-runtime and atd (2.5.0)
  packages/atd/atd.2.5.0/opam
  packages/atdgen-codec-runtime/atdgen-codec-runtime.2.5.0/opam
  packages/atdgen-runtime/atdgen-runtime.2.5.0/opam
  packages/atdgen/atdgen.2.5.0/opam
  packages/atdj/atdj.2.5.0/opam
  packages/atdpy/atdpy.2.5.0/opam
  packages/atds/atds.2.5.0/opam
  packages/atdts/atdts.2.5.0/opam
Labels: needs reporter action

#21278 misuja: update url, the old one is no longer accessible
  packages/misuja/misuja.0.0.0/opam
Labels: consider for merge
