Repository ocaml/opam-repository, pull requests merged in 2022-11, with the labels that each got.

#22407 Package monomorphic.2.1.0
  packages/monomorphic/monomorphic.2.1.0/opam
Labels: consider for merge

#22416 Add camlpdf.2.5.3
  packages/camlpdf/camlpdf.2.5.3/opam
Labels: consider for merge

#22424 Package stdint-literals.1.0
  packages/stdint-literals/stdint-literals.1.0/opam
Labels: consider for merge

#22386 Package spotlib.4.3.0
  packages/spotlib/spotlib.4.3.0/opam
Labels: consider for merge

#22426 Add libtorch 1.13.
  packages/libtorch/libtorch.1.13.0+linux-x86_64/opam
  packages/libtorch/libtorch.1.13.0+macos-x86_64/opam
Labels: consider for merge

#22429 [new release] zmq, zmq-lwt and zmq-async (5.2.1)
  packages/zmq-async/zmq-async.5.2.1/opam
  packages/zmq-lwt/zmq-lwt.5.2.1/opam
  packages/zmq/zmq.5.2.1/opam
Labels: consider for merge

#22428 pfff needs older Menhir
  packages/pfff/pfff.0.25.1/opam
  packages/pfff/pfff.0.27.1/opam
  packages/pfff/pfff.0.27.3/opam
  packages/pfff/pfff.0.29/opam
  packages/pfff/pfff.0.37.1/opam
  packages/pfff/pfff.0.37.4/opam
  packages/pfff/pfff.0.37.6/opam
  packages/pfff/pfff.0.39.1/opam
  packages/pfff/pfff.0.39.3/opam
  packages/pfff/pfff.0.39.4/opam
  packages/pfff/pfff.0.39.5/opam
  packages/pfff/pfff.0.40.4/opam
Labels: consider for merge

#22425 Add cubicle.1.2.0
  packages/cubicle/cubicle.1.2.0/files/cubicle.install
  packages/cubicle/cubicle.1.2.0/opam
Labels: consider for merge

#22427 LablTk 8.06.13 and OCamlBrowser 5.0.0
  packages/labltk/labltk.8.06.13/opam
  packages/ocamlbrowser/ocamlbrowser.5.0.0/opam
Labels: consider for merge

#22228 Update conf-libfontconfig
  packages/conf-libfontconfig/conf-libfontconfig.1/opam
Labels: question, do not merge

#22224 Update conf-xkbcommon
  packages/conf-xkbcommon/conf-xkbcommon.1/opam
Labels: consider for merge

#22433 [new release] git-kv (0.0.1)
  packages/git-kv/git-kv.0.0.1/opam
Labels: consider for merge

#22225 Update conf-libpng
  packages/conf-libpng/conf-libpng.1/opam
Labels: consider for merge

#22444 Followup to dose3 fix
  packages/dose3/dose3.5.0.1-2/opam
Labels: consider for merge

#22448 sihl.0.1.1 conflicts with the new http package
  packages/sihl/sihl.0.1.1/opam
Labels: consider for merge

#22443 Remove unnecessary upper bounds for camyll
  packages/camyll/camyll.0.4.0/opam
  packages/camyll/camyll.0.4.1/opam
Labels: consider for merge

#22432 Frama-C: new release (26.0~beta-Iron)
  packages/frama-c/frama-c.26.0~beta/opam
Labels: question, consider for merge

#22458 New release of Solo5 (v0.7.4)
  packages/solo5-cross-aarch64/solo5-cross-aarch64.0.7.4/opam
  packages/solo5/solo5.0.7.4/opam
Labels: consider for merge

#22465 Package unison.2.53.0
  packages/unison/unison.2.53.0/opam
Labels: consider for merge

#21902 add ocaml-sat-solvers v0.7
  packages/ocaml-sat-solvers/ocaml-sat-solvers.0.7/opam
  packages/pgsolver/pgsolver.4.1/opam
Labels: consider for merge

#22497 Package data-encoding.0.7.1
  packages/data-encoding/data-encoding.0.7.1/opam
Labels: consider for merge

#22353 [new release] http, cohttp, cohttp-top, cohttp-server-lwt-unix, cohttp-mirage, cohttp-lwt, cohttp-lwt-unix, cohttp-lwt-jsoo, cohttp-eio, cohttp-curl, cohttp-curl-lwt, cohttp-curl-async and cohttp-async (6.0.0~alpha0)
  packages/cohttp-async/cohttp-async.6.0.0~alpha0/opam
  packages/cohttp-curl-async/cohttp-curl-async.6.0.0~alpha0/opam
  packages/cohttp-curl-lwt/cohttp-curl-lwt.6.0.0~alpha0/opam
  packages/cohttp-curl/cohttp-curl.6.0.0~alpha0/opam
  packages/cohttp-eio/cohttp-eio.6.0.0~alpha0/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.6.0.0~alpha0/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.6.0.0~alpha0/opam
  packages/cohttp-lwt/cohttp-lwt.6.0.0~alpha0/opam
  packages/cohttp-mirage/cohttp-mirage.6.0.0~alpha0/opam
  packages/cohttp-server-lwt-unix/cohttp-server-lwt-unix.6.0.0~alpha0/opam
  packages/cohttp-top/cohttp-top.6.0.0~alpha0/opam
  packages/cohttp/cohttp.6.0.0~alpha0/opam
  packages/http/http.6.0.0~alpha0/opam
Labels: consider for merge

#22522 +uecc.0.4
  packages/uecc/uecc.0.4/opam
Labels: consider for merge

#22520 [new release] dockerfile, dockerfile-opam and dockerfile-cmd (8.1.0)
  packages/dockerfile-cmd/dockerfile-cmd.8.1.0/opam
  packages/dockerfile-opam/dockerfile-opam.8.1.0/opam
  packages/dockerfile/dockerfile.8.1.0/opam
Labels: question

#22547 [new release] ISO3166 (0.1.0)
  packages/ISO3166/ISO3166.0.1.0/opam
Labels: consider for merge

#22540 Package simlog.0.0.3
  packages/simlog/simlog.0.0.3/opam
Labels: consider for merge

#22562 guardian: Remove restrictive constraints
  packages/guardian/guardian.0.0.4/opam
Labels: question

#22550 Package ocaml-canvas.1.0.0
  packages/ocaml-canvas/ocaml-canvas.1.0.0/opam
Labels: consider for merge

#22527 +ledgerwallet.0.3.0
  packages/ledgerwallet-tezos/ledgerwallet-tezos.0.3.0/opam
  packages/ledgerwallet/ledgerwallet.0.3.0/opam
  packages/tezos-signer-backends/tezos-signer-backends.12.0/opam
  packages/tezos-signer-backends/tezos-signer-backends.12.3/opam
  packages/tezos-signer-backends/tezos-signer-backends.13.0/opam
  packages/tezos-signer-backends/tezos-signer-backends.14.0/opam
  packages/tezos-signer-backends/tezos-signer-backends.15.0/opam
Labels: consider for merge

#22536 ocaml-systemd 1.3
  packages/ocaml-systemd/ocaml-systemd.1.3/opam
Labels: consider for merge

#22576 Package parmap.1.2.5
  packages/parmap/parmap.1.2.5/opam
Labels: consider for merge

#22573 Package SZXX.3.0.0
  packages/SZXX/SZXX.3.0.0/opam
Labels: consider for merge

#22572 Package tdigest.2.0.0
  packages/tdigest/tdigest.2.0.0/opam
Labels: consider for merge

#22571 Package fuzzy_compare.2.0.0
  packages/fuzzy_compare/fuzzy_compare.2.0.0/opam
Labels: consider for merge

#22523 [new release] xapi-stdext, xapi-stdext-zerocheck, xapi-stdext-unix, xapi-stdext-threads, xapi-stdext-std, xapi-stdext-pervasives, xapi-stdext-encodings and xapi-stdext-date (4.20.0)
  packages/xapi-stdext-date/xapi-stdext-date.4.20.0/opam
  packages/xapi-stdext-encodings/xapi-stdext-encodings.4.20.0/opam
  packages/xapi-stdext-pervasives/xapi-stdext-pervasives.4.20.0/opam
  packages/xapi-stdext-std/xapi-stdext-std.4.20.0/opam
  packages/xapi-stdext-threads/xapi-stdext-threads.4.20.0/opam
  packages/xapi-stdext-unix/xapi-stdext-unix.4.20.0/opam
  packages/xapi-stdext-zerocheck/xapi-stdext-zerocheck.4.20.0/opam
Labels: question

#22590 [new release] colombe, sendmail and sendmail-lwt (0.7.0)
  packages/colombe/colombe.0.7.0/opam
  packages/sendmail-lwt/sendmail-lwt.0.7.0/opam
  packages/sendmail/sendmail.0.7.0/opam
Labels: consider for merge

#22579 [new release] mimic and mimic-happy-eyeballs (0.0.6)
  packages/mimic-happy-eyeballs/mimic-happy-eyeballs.0.0.6/opam
  packages/mimic/mimic.0.0.6/opam
Labels: consider for merge
