Repository ocaml/opam-repository, pull requests merged in 2022-02, with the labels that each got.

#20605 [new release] mirage-unix (5.0.0)
  packages/mirage-unix/mirage-unix.5.0.0/opam
Labels: consider for merge

#20606 [new release] mirage-block-solo5 (0.7.0)
  packages/mirage-block-solo5/mirage-block-solo5.0.7.0/opam
Labels: consider for merge

#20607 [new release] mirage-net-solo5 (0.7.0)
  packages/mirage-net-solo5/mirage-net-solo5.0.7.0/opam
Labels: consider for merge

#20608 [new release] mirage-console-solo5 (0.7.0)
  packages/mirage-console-solo5/mirage-console-solo5.0.7.0/opam
Labels: consider for merge

#20609 [new release] mirage-block-xen (2.1.0)
  packages/mirage-block-xen/mirage-block-xen.2.1.0/opam
Labels: consider for merge

#20610 [new release] mirage-net-xen and netchannel (2.1.0)
  packages/mirage-net-xen/mirage-net-xen.2.1.0/opam
  packages/netchannel/netchannel.2.1.0/opam
Labels: consider for merge

#20611 [new release] mirage-clock, mirage-clock-unix and mirage-clock-freestanding (4.1.0)
  packages/mirage-clock-freestanding/mirage-clock-freestanding.4.1.0/opam
  packages/mirage-clock-unix/mirage-clock-unix.4.1.0/opam
  packages/mirage-clock/mirage-clock.4.1.0/opam
Labels: consider for merge

#20613 [new release] rpclib, rpclib-lwt, rpclib-js, rpclib-html, rpclib-async, rpc and ppx_deriving_rpc (8.1.2)
  packages/ppx_deriving_rpc/ppx_deriving_rpc.8.1.2/opam
  packages/rpc/rpc.8.1.2/opam
  packages/rpclib-async/rpclib-async.8.1.2/opam
  packages/rpclib-html/rpclib-html.8.1.2/opam
  packages/rpclib-js/rpclib-js.8.1.2/opam
  packages/rpclib-lwt/rpclib-lwt.8.1.2/opam
  packages/rpclib/rpclib.8.1.2/opam
Labels: consider for merge

#20612 [new release] mirage-console, mirage-console-xen, mirage-console-xen-proto, mirage-console-xen-backend and mirage-console-unix (5.1.0)
  packages/mirage-console-unix/mirage-console-unix.5.1.0/opam
  packages/mirage-console-xen-backend/mirage-console-xen-backend.5.1.0/opam
  packages/mirage-console-xen-proto/mirage-console-xen-proto.5.1.0/opam
  packages/mirage-console-xen/mirage-console-xen.5.1.0/opam
  packages/mirage-console/mirage-console.5.1.0/opam
Labels: consider for merge

#20622 Patch world breaking gitlab-unix.0.1.0 installation
  packages/gitlab-unix/gitlab-unix.0.1.0/files/no-diff-installed.patch
  packages/gitlab-unix/gitlab-unix.0.1.0/opam
Labels: consider for merge

#20624 Bisect_ppx 2.7.1: OCaml coverage tool
  packages/bisect_ppx/bisect_ppx.2.7.1/opam
Labels: consider for merge

#20489 Add KreMLin 1.0.0
  packages/kremlin/kremlin.1.0.0/opam
Labels: do not merge

#20632 Fix constraints about mirage and docteur-{unix,solo5}
  packages/docteur-solo5/docteur-solo5.0.0.2/opam
  packages/docteur-unix/docteur-unix.0.0.2/opam
Labels: consider for merge

#20639 [new release] git, git-unix, git-mirage and git-paf (3.8.0)
  packages/git-mirage/git-mirage.3.8.0/opam
  packages/git-paf/git-paf.3.8.0/opam
  packages/git-unix/git-unix.3.8.0/opam
  packages/git/git.3.8.0/opam
Labels: consider for merge

#20636 4 packages from c-cube/qcheck at 0.18.1
  packages/qcheck-alcotest/qcheck-alcotest.0.18.1/opam
  packages/qcheck-core/qcheck-core.0.18.1/opam
  packages/qcheck-ounit/qcheck-ounit.0.18.1/opam
  packages/qcheck/qcheck.0.18.1/opam
Labels: consider for merge

#20638 [new release] doi2bib (0.6.1)
  packages/doi2bib/doi2bib.0.6.1/opam
Labels: consider for merge

#20641 Add: uutf.1.0.3
  packages/uutf/uutf.1.0.3/opam
Labels: consider for merge

#20630 Package pyml_bindgen.0.2.0
  packages/pyml_bindgen/pyml_bindgen.0.2.0/opam
Labels: needs reporter action

#20649 [new release] extunix (0.4.0)
  packages/devkit/devkit.1.0/opam
  packages/devkit/devkit.1.2/opam
  packages/devkit/devkit.1.20210120/opam
  packages/devkit/devkit.1.3/opam
  packages/extunix/extunix.0.4.0/opam
Labels: consider for merge

#20654 rpclib < 6.1.0 implicitly used the result package
  packages/rpclib/rpclib.5.9.0/opam
  packages/rpclib/rpclib.6.0.0/opam
Labels: consider for merge

#20653 tezos-stdlib-unix < 8.0 will not be compatible with Lwt 5.6.0
  packages/tezos-stdlib-unix/tezos-stdlib-unix.7.0/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.7.1/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.7.2/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.7.3/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.7.4/opam
Labels: question

#20675 Package searchTree.0.1
  packages/searchTree/searchTree.0.1/opam
Labels: needs reporter action

#20681 [new release] docteur, docteur-unix and docteur-solo5 (0.0.3)
  packages/docteur-solo5/docteur-solo5.0.0.3/opam
  packages/docteur-unix/docteur-unix.0.0.3/opam
  packages/docteur/docteur.0.0.3/opam
Labels: consider for merge

#20698 Add: b0.0.0.4, odig.0.0.8
  packages/b0/b0.0.0.4/opam
  packages/odig/odig.0.0.8/opam
Labels: consider for merge

#20696 Switch bls12-381 tarball sources to tags/releases instead of commits
  packages/bls12-381-unix/bls12-381-unix.1.1.1/opam
  packages/bls12-381-unix/bls12-381-unix.2.0.0/opam
  packages/bls12-381/bls12-381.1.1.1/opam
  packages/bls12-381/bls12-381.2.0.0/opam
Labels: consider for merge

#20689 Package sifun.1.0.0
  packages/sifun/sifun.1.0.0/opam
Labels: needs reporter action

#20727 Package liquidsoap.2.0.3
  packages/liquidsoap/liquidsoap.2.0.3/opam
Labels: needs reporter action

#20730 Hyper: Web client that composes well with Dream
  packages/hyper/hyper.1.0.0~alpha1/opam
Labels: consider for merge

#20711 New OSDP version 1.1.0
  packages/conf-csdp/conf-csdp.1/opam
  packages/osdp/osdp.1.1.0/opam
Labels: consider for merge

#20736 Add: omod.0.0.3
  packages/omod/omod.0.0.3/opam
Labels: consider for merge

#20738 Add: gg.1.0.0
  packages/gg/gg.1.0.0/opam
Labels: consider for merge

#20735 2 packages from gitlab.com/dannywillems/ocaml-bls12-381/-/archive/2.0.1/ocaml-bls12-381-2.0.1.tar.bz2
  packages/bls12-381-unix/bls12-381-unix.2.0.1/opam
  packages/bls12-381/bls12-381.2.0.1/opam
Labels: consider for merge

#20739 [new release] x509 (0.16.0)
  packages/x509/x509.0.16.0/opam
Labels: consider for merge

#20743 Fix constraint in OCanren-ppx (repair #20720)
  packages/OCanren-ppx/OCanren-ppx.0.3.0~alpha1/opam
  packages/noCanren/noCanren.0.3.0~alpha1/opam
Labels: consider for merge

#20746 [new release] equinoxe, equinoxe-hlc and equinoxe-cohttp (0.2.0)
  packages/equinoxe-cohttp/equinoxe-cohttp.0.2.0/opam
  packages/equinoxe-hlc/equinoxe-hlc.0.2.0/opam
  packages/equinoxe/equinoxe.0.2.0/opam
Labels: consider for merge

#20762 Why3 1.4.1
  packages/why3-coq/why3-coq.1.4.1/opam
  packages/why3-ide/why3-ide.1.4.1/opam
  packages/why3/why3.1.4.1/opam
Labels: consider for merge

#20776 Package lwt-watcher.0.2
  packages/lwt-watcher/lwt-watcher.0.2/opam
Labels: consider for merge

#20810 [new release] mirage-kv (4.0.1)
  packages/mirage-kv/mirage-kv.4.0.1/opam
Labels: consider for merge
