Repository ocaml/opam-repository, pull requests merged in 2022-01, with the labels that each got.

#20367 [new release] coin (0.1.4)
  packages/coin/coin.0.1.4/opam
Labels: consider for merge

#20377 [new release] received (0.5.1)
  packages/received/received.0.5.1/opam
Labels: consider for merge

#20371 Package sqlite3_utils.0.5
  packages/sqlite3_utils/sqlite3_utils.0.5/opam
Labels: consider for merge

#20373 piaf.0.1.0 requires at least bigstringaf.0.8.0 and stdlib-shims
  packages/piaf/piaf.0.1.0/opam
Labels: consider for merge

#20372 [new release] paf, paf-cohttp and paf-le (0.0.8)
  packages/paf-cohttp/paf-cohttp.0.0.8/opam
  packages/paf-le/paf-le.0.0.8/opam
  packages/paf/paf.0.0.8/opam
Labels: consider for merge

#20246 [new release] cohttp, cohttp-top, cohttp-mirage, cohttp-lwt, cohttp-lwt-unix, cohttp-lwt-jsoo and cohttp-async (5.0.0)
  packages/cohttp-async/cohttp-async.5.0.0/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.5.0.0/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.5.0.0/opam
  packages/cohttp-lwt/cohttp-lwt.5.0.0/opam
  packages/cohttp-mirage/cohttp-mirage.5.0.0/opam
  packages/cohttp-top/cohttp-top.5.0.0/opam
  packages/cohttp/cohttp.5.0.0/opam
  packages/h1_parser/h1_parser.0.0.2/opam
  packages/zeit/zeit.0.1.0/opam
Labels: consider for merge

#20366 new release ocaml-freestanding.0.7.0
  packages/gmp-freestanding/gmp-freestanding.6.1.2-2/opam
  packages/gmp-freestanding/gmp-freestanding.6.2.0/opam
  packages/gmp-freestanding/gmp-freestanding.6.2.1/opam
  packages/ocaml-freestanding-cross-aarch64/ocaml-freestanding-cross-aarch64.0.7.0/opam
  packages/ocaml-freestanding/ocaml-freestanding.0.7.0/opam
  packages/zarith-freestanding/zarith-freestanding.1.10/opam
  packages/zarith-freestanding/zarith-freestanding.1.11/opam
  packages/zarith-freestanding/zarith-freestanding.1.12/opam
  packages/zarith-freestanding/zarith-freestanding.1.7-1/opam
  packages/zarith-freestanding/zarith-freestanding.1.7-2/opam
  packages/zarith-freestanding/zarith-freestanding.1.9.1/opam
Labels: consider for merge

#20392 [new release] reddit_api_kernel and reddit_api_async (0.2.1)
  packages/reddit_api_async/reddit_api_async.0.2.1/opam
  packages/reddit_api_kernel/reddit_api_kernel.0.2.1/opam
Labels: consider for merge

#20410 Package ocolor.1.3.0
  packages/ocolor/ocolor.1.3.0/opam
Labels: consider for merge

#20415 3 packages from gitlab.com/nomadic-labs/json-data-encoding/-/archive/0.11/json-data-encoding-0.11.tar.gz
  packages/json-data-encoding-browser/json-data-encoding-browser.0.11/opam
  packages/json-data-encoding-bson/json-data-encoding-bson.0.11/opam
  packages/json-data-encoding/json-data-encoding.0.11/opam
Labels: consider for merge

#20419 Package ubase.0.05
  packages/ubase/ubase.0.05/opam
Labels: consider for merge

#20418 Package xdg-basedir.0.0.4
  packages/ocaml-xdg-basedir/ocaml-xdg-basedir.transition/opam
  packages/xdg-basedir/xdg-basedir.0.0.4/opam
Labels: consider for merge

#20422 [new release] irmin & all (2.9.1)
  packages/irmin-bench/irmin-bench.2.9.1/opam
  packages/irmin-chunk/irmin-chunk.2.9.1/opam
  packages/irmin-containers/irmin-containers.2.9.1/opam
  packages/irmin-fs/irmin-fs.2.9.1/opam
  packages/irmin-git/irmin-git.2.9.1/opam
  packages/irmin-graphql/irmin-graphql.2.9.1/opam
  packages/irmin-http/irmin-http.2.9.1/opam
  packages/irmin-layers/irmin-layers.2.9.1/opam
  packages/irmin-mirage-git/irmin-mirage-git.2.9.1/opam
  packages/irmin-mirage-graphql/irmin-mirage-graphql.2.9.1/opam
  packages/irmin-mirage/irmin-mirage.2.9.1/opam
  packages/irmin-pack/irmin-pack.2.9.1/opam
  packages/irmin-test/irmin-test.2.9.1/opam
  packages/irmin-tezos/irmin-tezos.2.9.1/opam
  packages/irmin-unix/irmin-unix.2.9.1/opam
  packages/irmin/irmin.2.9.1/opam
  packages/ppx_irmin/ppx_irmin.2.9.1/opam
Labels: consider for merge

#20431 [new release] happy-eyeballs, happy-eyeballs-mirage and happy-eyeballs-lwt (0.1.3)
  packages/happy-eyeballs-lwt/happy-eyeballs-lwt.0.1.3/opam
  packages/happy-eyeballs-mirage/happy-eyeballs-mirage.0.1.3/opam
  packages/happy-eyeballs/happy-eyeballs.0.1.3/opam
Labels: consider for merge

#20435 package parsexp.v0.14.2
  packages/parsexp/parsexp.v0.14.2/opam
Labels: consider for merge

#20443 Dune3: add implicit "result" dependencies
  packages/dispatch/dispatch.0.5.0/opam
  packages/lsp/lsp.1.9.1/opam
  packages/rpclib/rpclib.8.1.1/opam
Labels: consider for merge

#20438 release lambdapi-2.1.0
  packages/lambdapi/lambdapi.2.1.0/opam
Labels: question

#20445 [new release] links, links-postgresql, links-sqlite3 and links-mysql (0.9.5)
  packages/links-mysql/links-mysql.0.9.5/opam
  packages/links-postgresql/links-postgresql.0.9.5/opam
  packages/links-sqlite3/links-sqlite3.0.9.5/opam
  packages/links/links.0.9.5/opam
Labels: consider for merge

#20470 [new release] lambdapi (2.1.0)
  packages/lambdapi/lambdapi.2.1.0/opam
Labels: consider for merge

#20437 bls12-381.1.0.2 and bls12-381-unix.1.0.2 - Support s390x for 1.0.x
  packages/bls12-381-unix/bls12-381-unix.1.0.2/opam
  packages/bls12-381/bls12-381.1.0.2/opam
Labels: consider for merge

#20429 + farmhash 0.4
  packages/farmhash/farmhash.0.4/opam
Labels: needs reporter action

#20503 fix: add ocaml < 5.00.
  packages/fix/fix.20181206/opam
  packages/fix/fix.20200131/opam
  packages/fix/fix.20201120/opam
  packages/fix/fix.20211125/opam
  packages/fix/fix.20211231/opam
  packages/menhir/menhir.20211125/opam
  packages/menhir/menhir.20211128/opam
  packages/menhir/menhir.20211230/opam
Labels: consider for merge

#20473 [new release] bechamel, bechamel-js, bechamel-notty and bechamel-perf (0.2.0)
  packages/bechamel-js/bechamel-js.0.2.0/opam
  packages/bechamel-notty/bechamel-notty.0.2.0/opam
  packages/bechamel-perf/bechamel-perf.0.2.0/opam
  packages/bechamel/bechamel.0.2.0/opam
Labels: consider for merge

#20516 Package unionFind.20220122
  packages/unionFind/unionFind.20220122/opam
Labels: consider for merge

#20517 sigaltstack patch for ocaml-secondary-compiler
  packages/ocaml-secondary-compiler/ocaml-secondary-compiler.4.08.1-1/opam
  packages/ocaml-secondary-compiler/ocaml-secondary-compiler.4.08.1/opam
Labels: consider for merge

#20515 Package camlp4.4.14+1
  packages/camlp4/camlp4.4.14+1/opam
Labels: consider for merge

#20497 [new release] raylib (0.5.1)
  packages/raylib/raylib.0.5.1/opam
Labels: consider for merge

#20518 Add ocaml-src.4.14.dev
  packages/ocaml-src/ocaml-src.4.14.dev/files/META
  packages/ocaml-src/ocaml-src.4.14.dev/opam
Labels: consider for merge

#20532 Mark ssl incompatible with any compilers requiring no-naked-pointers
  packages/ssl/ssl.0.4.6/opam
  packages/ssl/ssl.0.4.6a/opam
  packages/ssl/ssl.0.4.7/opam
  packages/ssl/ssl.0.5.0/opam
  packages/ssl/ssl.0.5.10/opam
  packages/ssl/ssl.0.5.2/opam
  packages/ssl/ssl.0.5.3/opam
  packages/ssl/ssl.0.5.4/opam
  packages/ssl/ssl.0.5.5/opam
  packages/ssl/ssl.0.5.6/opam
  packages/ssl/ssl.0.5.7/opam
  packages/ssl/ssl.0.5.8/opam
  packages/ssl/ssl.0.5.9/opam
Labels: consider for merge

#20531 release ocamlfind-1.9.3
  packages/ocamlfind/ocamlfind.1.9.3/opam
Labels: consider for merge

#20284 Bump satyrographos.0.0.2.11's version constraints on opam
  packages/satyrographos/satyrographos.0.0.2.11/opam
Labels: question

#20549 Add coq-of-ocaml.2.5.2
  packages/coq-of-ocaml/coq-of-ocaml.2.5.2+4.12/opam
  packages/coq-of-ocaml/coq-of-ocaml.2.5.2+4.13/opam
Labels: consider for merge

#20529 2 packages from OCamlPro/ocp-index at 1.3.3
  packages/ocp-browser/ocp-browser.1.3.3/opam
  packages/ocp-index/ocp-index.1.3.3/opam
Labels: consider for merge

#20538 Package batteries.3.5.0
  packages/batteries/batteries.3.5.0/opam
Labels: consider for merge

#20539 Package opam-grep.0.3.0
  packages/opam-grep/opam-grep.0.3.0/opam
Labels: consider for merge

#20553 [new release] bigarray-compat (1.1.0)
  packages/bigarray-compat/bigarray-compat.1.1.0/opam
Labels: consider for merge

#20480 3 packages from c-cube/printbox at 0.6
  packages/printbox-html/printbox-html.0.6/opam
  packages/printbox-text/printbox-text.0.6/opam
  packages/printbox/printbox.0.6/opam
Labels: consider for merge

#20543 tezos-stdlib-unix < 10: Add missing conflicts
  packages/tezos-error-monad/tezos-error-monad.8.0/opam
  packages/tezos-error-monad/tezos-error-monad.8.1/opam
  packages/tezos-error-monad/tezos-error-monad.8.2/opam
  packages/tezos-error-monad/tezos-error-monad.8.3/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.8.0/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.8.1/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.8.2/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.8.3/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.9.2/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.9.3/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.9.4/opam
  packages/tezos-stdlib-unix/tezos-stdlib-unix.9.7/opam
Labels: consider for merge

#20555 [new release] ppx_deriving_hash (0.1.1)
  packages/ppx_deriving_hash/ppx_deriving_hash.0.1.1/opam
Labels: consider for merge

#20496 F* 2022.01.15
  packages/fstar/fstar.2022.01.15/opam
Labels: consider for merge

#20560 Add a preview package for ppxlib with OCaml 5.00
  packages/ppxlib/ppxlib.0.25.0~5.00preview/opam
Labels: consider for merge

#20557 [new release] mirage-block-unix (2.13.0)
  packages/fat-filesystem/fat-filesystem.0.15.0/opam
  packages/mirage-block-unix/mirage-block-unix.2.13.0/opam
  packages/qcow-tool/qcow-tool.0.11.0/opam
  packages/qcow/qcow.0.11.0/opam
  packages/shared-block-ring/shared-block-ring.3.0.0/opam
Labels: needs reporter action

#20576 Add the preview package for ocaml-lsp-server on OCaml 4.14
  packages/ocaml-lsp-server/ocaml-lsp-server.1.9.2~4.14preview/opam
Labels: consider for merge

#20580 Package mlbdd.0.7.3
  packages/mlbdd/mlbdd.0.7.3/opam
Labels: consider for merge

#20574 Package mm.0.7.4
  packages/mm/mm.0.7.4/opam
Labels: consider for merge

#20421 hacl-star and hacl-star-raw (0.4.5)
  packages/hacl-star-raw/hacl-star-raw.0.4.5/opam
  packages/hacl-star/hacl-star.0.4.5/opam
Labels: consider for merge

#20598 Add: brr.0.0.3
  packages/brr/brr.0.0.3/opam
Labels: consider for merge

#20599 Release of `mirage.4.0.0~beta2`
  packages/functoria-runtime/functoria-runtime.4.0.0~beta2/opam
  packages/functoria/functoria.4.0.0~beta2/opam
  packages/mirage-runtime/mirage-runtime.4.0.0~beta2/opam
  packages/mirage/mirage.4.0.0~beta2/opam
Labels: consider for merge

#20603 [new release] mirage-xen (7.0.0)
  packages/mirage-xen/mirage-xen.7.0.0/opam
Labels: consider for merge

#20600 [new release] mirage-solo5 (0.7.0)
  packages/mirage-solo5/mirage-solo5.0.7.0/opam
Labels: consider for merge
