Repository ocaml/opam-repository, pull requests merged in 2022-10, with the labels that each got.

#22192 [new release] checkseum (0.4.0)
  packages/checkseum/checkseum.0.4.0/opam
Labels: consider for merge

#22182 Package ocamlbuild.0.14.2
  packages/ocamlbuild/ocamlbuild.0.14.2/opam
Labels: consider for merge

#22187 [new release] paf, paf-le and paf-cohttp (0.2.0)
  packages/git-paf/git-paf.3.7.0/opam
  packages/git-paf/git-paf.3.7.1/opam
  packages/git-paf/git-paf.3.8.0/opam
  packages/git-paf/git-paf.3.8.1/opam
  packages/git-paf/git-paf.3.9.0/opam
  packages/git-paf/git-paf.3.9.1/opam
  packages/paf-cohttp/paf-cohttp.0.2.0/opam
  packages/paf-le/paf-le.0.2.0/opam
  packages/paf/paf.0.2.0/opam
Labels: consider for merge

#22183 [new release] wayland (1.1)
  packages/wayland/wayland.1.1/opam
Labels: consider for merge

#22220 Remove bounds on dune version on drom dependencies
  packages/ez_config/ez_config.0.2.0/opam
  packages/ez_file/ez_file.0.3.0/opam
  packages/ocplib_stuff/ocplib_stuff.0.3.0/opam
Labels: consider for merge

#22236 [new release] domainslib (0.5.0)
  packages/domainslib/domainslib.0.5.0/opam
Labels: consider for merge

#22229 Update conf-libxcb*
  packages/conf-libxcb-image/conf-libxcb-image.1/opam
  packages/conf-libxcb-keysyms/conf-libxcb-keysyms.1/opam
  packages/conf-libxcb-shm/conf-libxcb-shm.1/opam
  packages/conf-libxcb-xkb/conf-libxcb-xkb.1/opam
  packages/conf-libxcb/conf-libxcb.1/opam
Labels: question, do not merge

#22212 Add jasmin.2022.09.0
  packages/jasmin/jasmin.2022.09.0/opam
Labels: consider for merge

#22139 Release caqti-driver-postgresql 1.9.1.
  packages/caqti-driver-postgresql/caqti-driver-postgresql.1.9.1/opam
Labels: consider for merge

#22101 9 packages from savonet/ocaml-posix at 2.0.1
  packages/posix-base/posix-base.2.0.1/opam
  packages/posix-bindings/posix-bindings.2.0.1/opam
  packages/posix-getopt/posix-getopt.2.0.1/opam
  packages/posix-signal/posix-signal.2.0.1/opam
  packages/posix-socket-unix/posix-socket-unix.2.0.1/opam
  packages/posix-socket/posix-socket.2.0.1/opam
  packages/posix-time2/posix-time2.2.0.1/opam
  packages/posix-types/posix-types.2.0.1/opam
  packages/posix-uname/posix-uname.2.0.1/opam
Labels: consider for merge

#21796 Package: fswatch.11-0.1.1
  packages/fswatch/fswatch.11-0.1.1/opam
Labels: consider for merge

#22259 Add the 0.15 version of ocaml-torch.
  packages/torch/torch.0.15/opam
Labels: consider for merge

#22021 Package ppx_system.1.0
  packages/ppx_system/ppx_system.1.0/opam
Labels: consider for merge

#21982 Remove conf-libsamplerate in favor of conf-samplerate.
  packages/bjack/bjack.0.1.6/opam
  packages/conf-libsamplerate/conf-libsamplerate.2/opam
  packages/samplerate/samplerate.0.1.5/opam
Labels: needs reporter action

#22279 [new release] stdint (0.7.1)
  packages/stdint/stdint.0.7.1/opam
Labels: consider for merge

#22275 incr_dom.v0.15.1
  packages/incr_dom/incr_dom.v0.15.1/opam
Labels: consider for merge

#22286 [new release] OCADml (0.1.0)
  packages/OCADml/OCADml.0.1.0/opam
Labels: consider for merge

#22283 [new release] melange-compiler-libs (0.0.1-414)
  packages/melange-compiler-libs/melange-compiler-libs.0.0.1-414/opam
Labels: consider for merge

#22311 [new release] stdint (0.7.2)
  packages/stdint/stdint.0.7.2/opam
Labels: consider for merge

#22290 Remove old unused travis scripts
  .travis-ci-install.sh
  .travis-ci.sh
Labels: consider for merge

#22319 [new release] mirage-xen (8.0.1)
  packages/mirage-xen/mirage-xen.8.0.1/opam
Labels: consider for merge

#22330 [new release] digestif (1.1.3)
  packages/digestif/digestif.1.1.3/opam
Labels: consider for merge

#22320 [new release] carton, carton-lwt and carton-git (0.6.0)
  packages/carton-git/carton-git.0.6.0/opam
  packages/carton-lwt/carton-lwt.0.6.0/opam
  packages/carton/carton.0.6.0/opam
Labels: consider for merge

#22316 [new release] mirage-solo5 (0.9.1)
  packages/mirage-solo5/mirage-solo5.0.9.1/opam
Labels: consider for merge

#22250 Package ip2location.8.0.0
  packages/ip2location/ip2location.8.0.0/opam
Labels: consider for merge

#22332 [new release] git, git-paf, git-mirage and git-unix (3.10.0)
  packages/git-mirage/git-mirage.3.10.0/opam
  packages/git-paf/git-paf.3.10.0/opam
  packages/git-unix/git-unix.3.10.0/opam
  packages/git/git.3.10.0/opam
Labels: consider for merge

#22367 [new release] lru (0.3.1)
  packages/lru/lru.0.3.1/opam
Labels: consider for merge

#22366 [new release] tls-eio (0.15.5)
  packages/tls-eio/tls-eio.0.15.5/opam
Labels: consider for merge

#22341 [new release] eio-ssl (0.1.0)
  packages/eio-ssl/eio-ssl.0.1.0/opam
Labels: consider for merge

#22374 [new release] plateau (0.1)
  packages/plateau/plateau.0.1/opam
Labels: consider for merge

#22323 [new release] ppx_deriving_cad (0.1.0)
  packages/ppx_deriving_cad/ppx_deriving_cad.0.1.0/opam
Labels: consider for merge

#22373 [new release] pgx_value_ptime, pgx_value_core, pgx_unix, pgx_lwt_unix, pgx_lwt_mirage, pgx_lwt, pgx_async and pgx (2.2)
  packages/pgx/pgx.2.2/opam
  packages/pgx_async/pgx_async.2.2/opam
  packages/pgx_lwt/pgx_lwt.2.2/opam
  packages/pgx_lwt_mirage/pgx_lwt_mirage.2.2/opam
  packages/pgx_lwt_unix/pgx_lwt_unix.2.2/opam
  packages/pgx_unix/pgx_unix.2.2/opam
  packages/pgx_value_core/pgx_value_core.2.2/opam
  packages/pgx_value_ptime/pgx_value_ptime.2.2/opam
Labels: consider for merge

#22348 3 packages from dialohq/ocaml-grpc at 0.1.0
  packages/grpc-async/grpc-async.0.1.0/opam
  packages/grpc-lwt/grpc-lwt.0.1.0/opam
  packages/grpc/grpc.0.1.0/opam
Labels: consider for merge

#22389 Package treeprint.2.3.0
  packages/treeprint/treeprint.2.3.0/opam
Labels: consider for merge

#22379 Package rdbg.1.199.0
  packages/lutils/lutils.1.44/opam
  packages/lutils/lutils.1.49.5/opam
  packages/lutils/lutils.1.51.2/opam
  packages/rdbg/rdbg.1.199.0/opam
Labels: needs reporter action

#22400 codept 0.11: extend compatibility to 5.0
  packages/codept/codept.0.11.1/opam
Labels: consider for merge

#22410 [new release] build_path_prefix_map 0.3
  packages/build_path_prefix_map/build_path_prefix_map.0.2/opam
  packages/build_path_prefix_map/build_path_prefix_map.0.3/opam
Labels: consider for merge

#22405 [new release] phantom-algebra (1.0.1)
  packages/phantom-algebra/phantom-algebra.1.0.1/opam
Labels: consider for merge
