Repository ocaml/opam-repository, pull requests merged in 2022-09, with the labels that each got.

#22061 [new release] tyxml-lwd, nottui, nottui-pretty, nottui-lwt, lwd and brr-lwd (0.3)
  packages/brr-lwd/brr-lwd.0.3/opam
  packages/lwd/lwd.0.3/opam
  packages/nottui-lwt/nottui-lwt.0.3/opam
  packages/nottui-pretty/nottui-pretty.0.3/opam
  packages/nottui/nottui.0.3/opam
  packages/tyxml-lwd/tyxml-lwd.0.3/opam
Labels: consider for merge

#22067 Package blake3.0.3
  packages/blake3/blake3.0.3/opam
Labels: question

#22098 fix linking problems with z3_tptp program
  packages/z3_tptp/z3_tptp.4.8.13/opam
  packages/z3_tptp/z3_tptp.4.8.14/opam
Labels: consider for merge

#22109 Package gitlab_pipeline_notifier.0.1
  packages/gitlab_pipeline_notifier/gitlab_pipeline_notifier.0.1/opam
Labels: needs reporter action

#22116 Add: uucd.15.0.0, uucp.15.0.0, uunf.15.0.0, uuseg.15.0.0
  packages/uucd/uucd.15.0.0/opam
  packages/uucp/uucp.15.0.0/opam
  packages/uunf/uunf.15.0.0/opam
  packages/uuseg/uuseg.15.0.0/opam
Labels: consider for merge

#22130 Release of Esperanto v0.0.1
  packages/esperanto-cosmopolitan/esperanto-cosmopolitan.0.0.1/opam
  packages/esperanto/esperanto.0.0.1/opam
Labels: consider for merge

#22157 Package globlon.1.0
  packages/globlon/globlon.1.0/opam
Labels: consider for merge

#22170 3 packages from gitlab.com/nomadic-labs/ringo/-/archive/v1.0.0/ringo-v1.0.0.tar.gz
  packages/aches-lwt/aches-lwt.1.0.0/opam
  packages/aches/aches.1.0.0/opam
  packages/ringo/ringo.1.0.0/opam
  packages/tezos-crypto/tezos-crypto.14.0/opam
  packages/tezos-p2p/tezos-p2p.14.0/opam
  packages/tezos-protocol-environment/tezos-protocol-environment.14.0/opam
  packages/tezos-proxy/tezos-proxy.14.0/opam
  packages/tezos-stdlib/tezos-stdlib.14.0/opam
  packages/tezos-workers/tezos-workers.14.0/opam
Labels: consider for merge
