Repository ocaml/opam-repository, pull requests merged in 2022-03, with the labels that each got.

#20808 Package bindlib.6.0.0
  packages/bindlib/bindlib.6.0.0/opam
  packages/catala/catala.0.2.0/opam
  packages/catala/catala.0.3.0/opam
  packages/catala/catala.0.5.0/opam
  packages/lambdapi/lambdapi.1.0/opam
  packages/lambdapi/lambdapi.2.0.0/opam
  packages/lambdapi/lambdapi.2.1.0/opam
Labels: consider for merge

#20823 Release ocaml-jupyter kernel 2.7.7
  packages/jupyter/jupyter.2.7.7/opam
Labels: consider for merge

#20828 Add: ttweetnacl.0.1.0
  packages/ttweetnacl/ttweetnacl.0.1.0/opam
Labels: consider for merge

#20833 [new release] vchan, vchan-xen and vchan-unix (6.0.1)
  packages/vchan-unix/vchan-unix.6.0.1/opam
  packages/vchan-xen/vchan-xen.6.0.1/opam
  packages/vchan/vchan.6.0.1/opam
Labels: consider for merge

#20837 [new release] ledgerwallet and ledgerwallet-tezos (0.2.0)
  packages/ledgerwallet-tezos/ledgerwallet-tezos.0.2.0/opam
  packages/ledgerwallet/ledgerwallet.0.2.0/opam
  packages/tezos-signer-backends/tezos-signer-backends.11.0/opam
  packages/tezos-signer-backends/tezos-signer-backends.11.1/opam
Labels: needs reporter action

#20815 Fix memtrace_viewer with dune 3.0.0
  packages/memtrace_viewer/memtrace_viewer.v0.14.0/opam
  packages/memtrace_viewer/memtrace_viewer.v0.14.1/opam
Labels: needs reporter action

#20844 Package crowbar v0.2.1
  packages/crowbar/crowbar.0.2.1/opam
Labels: consider for merge

#20838 [new release] chamelon and chamelon-unix (0.0.7)
  packages/chamelon-unix/chamelon-unix.0.0.7/opam
  packages/chamelon/chamelon.0.0.7/opam
Labels: consider for merge

#20781 Lambdapi: update dependencies
  packages/lambdapi/lambdapi.2.1.0/opam
Labels: consider for merge

#20854 Add conf-libfontconfig
  packages/conf-libfontconfig/conf-libfontconfig.1/opam
Labels: consider for merge

#20861 Package catala.0.6.0
  packages/catala/catala.0.6.0/opam
Labels: consider for merge

#20843 Package ocaml-protoc.2.1
  packages/ocaml-protoc/ocaml-protoc.2.1/opam
Labels: consider for merge

#20845 [new release] macaddr, macaddr-sexp, macaddr-cstruct, ipaddr, ipaddr-sexp and ipaddr-cstruct (5.3.0)
  packages/ipaddr-cstruct/ipaddr-cstruct.5.3.0/opam
  packages/ipaddr-sexp/ipaddr-sexp.5.3.0/opam
  packages/ipaddr/ipaddr.5.3.0/opam
  packages/macaddr-cstruct/macaddr-cstruct.5.3.0/opam
  packages/macaddr-sexp/macaddr-sexp.5.3.0/opam
  packages/macaddr/macaddr.5.3.0/opam
Labels: consider for merge

#20868 [new release] reason and rtop (3.8.0)
  packages/reason/reason.3.8.0/opam
  packages/rtop/rtop.3.8.0/opam
Labels: consider for merge

#20872 [new release] tar, tar-unix and tar-mirage (2.0.1)
  packages/tar-mirage/tar-mirage.2.0.1/opam
  packages/tar-unix/tar-unix.2.0.1/opam
  packages/tar/tar.2.0.1/opam
Labels: consider for merge

#20928 [new release] mirage-net-unix (3.0.0)
  packages/mirage-net-unix/mirage-net-unix.3.0.0/opam
Labels: consider for merge

#20915 Package bogue.20220314
  packages/bogue/bogue.20220314/opam
Labels: consider for merge

#20939 odoc.2.0.0 is not compatible with OCaml 4.14
  packages/odoc/odoc.2.0.0/opam
Labels: consider for merge

#20937 Mark the solo5-kernel-* packages as deprecated
  packages/solo5-kernel-muen/solo5-kernel-muen.0.3.0/opam
  packages/solo5-kernel-muen/solo5-kernel-muen.0.3.1/opam
  packages/solo5-kernel-ukvm/solo5-kernel-ukvm.0.1.1/opam
  packages/solo5-kernel-ukvm/solo5-kernel-ukvm.0.2.1/opam
  packages/solo5-kernel-ukvm/solo5-kernel-ukvm.0.2.2-1/opam
  packages/solo5-kernel-ukvm/solo5-kernel-ukvm.0.2.2/opam
  packages/solo5-kernel-ukvm/solo5-kernel-ukvm.0.3.0/opam
  packages/solo5-kernel-ukvm/solo5-kernel-ukvm.0.3.1/opam
  packages/solo5-kernel-virtio/solo5-kernel-virtio.0.1.1/opam
  packages/solo5-kernel-virtio/solo5-kernel-virtio.0.2.1/opam
  packages/solo5-kernel-virtio/solo5-kernel-virtio.0.2.2-1/opam
  packages/solo5-kernel-virtio/solo5-kernel-virtio.0.2.2/opam
  packages/solo5-kernel-virtio/solo5-kernel-virtio.0.3.0/opam
  packages/solo5-kernel-virtio/solo5-kernel-virtio.0.3.1/opam
Labels: consider for merge

#20909 Package mm.0.8.0
  packages/liquidsoap/liquidsoap.2.0.0/opam
  packages/liquidsoap/liquidsoap.2.0.0~rc1/opam
  packages/liquidsoap/liquidsoap.2.0.1/opam
  packages/liquidsoap/liquidsoap.2.0.2-1/opam
  packages/liquidsoap/liquidsoap.2.0.2/opam
  packages/liquidsoap/liquidsoap.2.0.3-1/opam
  packages/liquidsoap/liquidsoap.2.0.3/opam
  packages/mkaudio/mkaudio.1.1.2/opam
  packages/mm/mm.0.8.0/opam
Labels: consider for merge

#20954 [new release] phylogenetics (0.1.0)
  packages/phylogenetics/phylogenetics.0.1.0/opam
Labels: needs reporter action

#20959 Add ocaml jupyter kernel 2.7.8
  packages/jupyter/jupyter.2.7.8/opam
Labels: question

#20955 Sundials/ML v6.1.1p1
  packages/sundialsml/sundialsml.6.1.1p1/opam
Labels: question

#20970 add missing cohttp and conduit upper bounds
  packages/ez_api/ez_api.0.1.0/opam
  packages/gremlin/gremlin.0.1.1/opam
Labels: consider for merge

#20979 Package pyml_bindgen.0.3.0
  packages/pyml_bindgen/pyml_bindgen.0.3.0/opam
Labels: consider for merge

#20988 Release of Solo5 0.7.1
  packages/solo5-cross-aarch64/solo5-cross-aarch64.0.7.1/opam
  packages/solo5/solo5.0.7.1/opam
Labels: consider for merge

#20996 Package data-encoding.0.5.3
  packages/data-encoding/data-encoding.0.5.3/opam
Labels: consider for merge

#20995 Package pyml_bindgen.0.3.1
  packages/pyml_bindgen/pyml_bindgen.0.3.1/opam
Labels: consider for merge

#20997 [new release] tcpip (7.1.0)
  packages/tcpip/tcpip.7.1.0/opam
Labels: consider for merge

#19776 Update package overview of camlp5 to move from GForge to GitHub
  packages/camlp5/camlp5.6.12/opam
  packages/camlp5/camlp5.6.13/opam
  packages/camlp5/camlp5.6.14/opam
  packages/camlp5/camlp5.6.15/opam
  packages/camlp5/camlp5.6.16/opam
Labels: missing upstream archive

#20852 [new release] dump_ocamlformat (0.2.2)
  packages/dump_ocamlformat/dump_ocamlformat.0.2.2/opam
Labels: consider for merge

#21004 Add: cmdliner.1.1.1
  packages/cmdliner/cmdliner.1.1.1/opam
Labels: consider for merge

#20974 mirage-crypto-rng 0.7.0: mark unavailable (to reduce revdeps)
  packages/mirage-crypto-rng/mirage-crypto-rng.0.7.0/opam
Labels: needs reporter action

#20913 Package unison.2.52.0
  packages/unison/unison.2.52.0/opam
Labels: consider for merge

#21035 [new release] aifad (2.3.0)
  packages/aifad/aifad.2.3.0/opam
Labels: consider for merge

#21011 Fix various bounds
  packages/ez_cmdliner/ez_cmdliner.0.4.3/opam
  packages/index-bench/index-bench.1.6.0/opam
  packages/index/index.1.3.0/opam
  packages/index/index.1.3.1/opam
  packages/index/index.1.3.2/opam
  packages/index/index.1.3.3/opam
  packages/index/index.1.4.0/opam
  packages/index/index.1.4.1/opam
  packages/index/index.1.4.2/opam
  packages/index/index.1.5.0/opam
  packages/index/index.1.6.0/opam
  packages/js_of_ocaml-webgpu/js_of_ocaml-webgpu.0.1/opam
  packages/ppx_yojson/ppx_yojson.1.1.0/opam
  packages/ppx_yojson/ppx_yojson.1.2.0/opam
  packages/webidl/webidl.1.0/opam
  packages/webidl/webidl.1.1/opam
  packages/webidl/webidl.1.2/opam
Labels: consider for merge

#21046 ocaml-manual: 4.14 manual
  packages/ocaml-manual/ocaml-manual.4.14.0/opam
Labels: consider for merge

#20971 Package atomic.0.1
  packages/atomic/atomic.0.1/opam
  packages/atomic/atomic.base/files/META.atomic
  packages/atomic/atomic.base/files/atomic.install
  packages/atomic/atomic.base/opam
Labels: consider for merge

#21045 Package sedlex.2.6
  packages/sedlex/sedlex.2.6/opam
Labels: consider for merge
