Repository ocaml/opam-repository, pull requests merged in 2022-05, with the labels that each got.

#21300 OCanren, GT 0.3.0 (non alpha)
  packages/GT/GT.0.5.1/opam
  packages/OCanren-ppx/OCanren-ppx.0.3.0/opam
  packages/OCanren/OCanren.0.3.0/opam
  packages/noCanren/noCanren.0.3.0/opam
Labels: consider for merge

#21316 [new release] mirage, mirage-runtime, functoria and functoria-runtime (4.1.0)
  packages/functoria-runtime/functoria-runtime.4.1.0/opam
  packages/functoria/functoria.4.1.0/opam
  packages/mirage-runtime/mirage-runtime.4.1.0/opam
  packages/mirage/mirage.4.1.0/opam
Labels: needs reporter action

#21338 [new release] biocaml (0.11.2)
  packages/biocaml/biocaml.0.11.2/opam
Labels: consider for merge

#21344 `EndianBytes` exists since ocplib-endian 0.6
  packages/afl-persistent/afl-persistent.1.1/opam
  packages/cohttp/cohttp.5.0.0/opam
  packages/crowbar/crowbar.0.1/opam
  packages/crowbar/crowbar.0.2.1/opam
  packages/crowbar/crowbar.0.2/opam
  packages/optint/optint.0.0.3/opam
  packages/optint/optint.0.0.4/opam
  packages/tezos-stdlib/tezos-stdlib.8.0/opam
  packages/tezos-stdlib/tezos-stdlib.8.1/opam
  packages/tezos-stdlib/tezos-stdlib.8.2/opam
  packages/tezos-stdlib/tezos-stdlib.8.3/opam
  packages/tezos-stdlib/tezos-stdlib.9.0/opam
  packages/tezos-stdlib/tezos-stdlib.9.1/opam
  packages/tezos-stdlib/tezos-stdlib.9.2/opam
  packages/tezos-stdlib/tezos-stdlib.9.3/opam
  packages/tezos-stdlib/tezos-stdlib.9.4/opam
  packages/tezos-stdlib/tezos-stdlib.9.7/opam
Labels: consider for merge

#21359 [new release] decoders, decoders-yojson, decoders-sexplib, decoders-msgpck, decoders-jsonm, decoders-ezjsonm, decoders-cbor and decoders-bencode (0.7.0)
  packages/decoders-bencode/decoders-bencode.0.7.0/opam
  packages/decoders-cbor/decoders-cbor.0.7.0/opam
  packages/decoders-ezjsonm/decoders-ezjsonm.0.7.0/opam
  packages/decoders-jsonm/decoders-jsonm.0.7.0/opam
  packages/decoders-msgpck/decoders-msgpck.0.7.0/opam
  packages/decoders-sexplib/decoders-sexplib.0.7.0/opam
  packages/decoders-yojson/decoders-yojson.0.7.0/opam
  packages/decoders/decoders.0.7.0/opam
Labels: consider for merge

#21374 [new release] albatross (1.5.0)
  packages/albatross/albatross.1.5.0/opam
Labels: consider for merge

#21399 2 packages from ocaml-community/cppo at 1.6.9
  packages/cppo/cppo.1.6.9/opam
  packages/cppo_ocamlbuild/cppo_ocamlbuild.1.6.9/opam
Labels: consider for merge

#21402 3 packages from OCamlPro/alt-ergo at 2.3.3
  packages/alt-ergo-free/alt-ergo-free.2.3.3/opam
  packages/alt-ergo-lib-free/alt-ergo-lib-free.2.3.3/opam
  packages/alt-ergo-parsers-free/alt-ergo-parsers-free.2.3.3/opam
Labels: consider for merge

#21395 Package class_group_vdf.0.0.1
  packages/class_group_vdf/class_group_vdf.0.0.1/opam
Labels: do not merge
