Repository ocaml/opam-repository, pull requests merged in 2023-05, with the labels that each got.

#23735 Package records.1.0.0
  packages/records/records.1.0.0/opam
Labels: consider for merge

#23733 [new release] js_of_ocaml, js_of_ocaml-tyxml, js_of_ocaml-toplevel, js_of_ocaml-ppx_deriving_json, js_of_ocaml-ppx, js_of_ocaml-lwt and js_of_ocaml-compiler (5.2.0)
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.5.2.0/opam
  packages/js_of_ocaml-lwt/js_of_ocaml-lwt.5.2.0/opam
  packages/js_of_ocaml-ppx/js_of_ocaml-ppx.5.2.0/opam
  packages/js_of_ocaml-ppx_deriving_json/js_of_ocaml-ppx_deriving_json.5.2.0/opam
  packages/js_of_ocaml-toplevel/js_of_ocaml-toplevel.5.2.0/opam
  packages/js_of_ocaml-tyxml/js_of_ocaml-tyxml.5.2.0/opam
  packages/js_of_ocaml/js_of_ocaml.5.2.0/opam
Labels: consider for merge

#23714 Release of Solo5.0.8.0
  packages/solo5-cross-aarch64/solo5-cross-aarch64.0.8.0/opam
  packages/solo5/solo5.0.8.0/opam
Labels: consider for merge

#23739 [new release] md2mld (0.7.0)
  packages/md2mld/md2mld.0.7.0/opam
Labels: consider for merge

#23737 [new release] cohttp-async, cohttp-curl-async, cohttp-curl-lwt, cohttp-curl, cohttp-eio, cohttp-lwt-jsoo, cohttp-lwt-unix, cohttp-lwt, cohttp-mirage, cohttp-server-lwt-unix, cohttp-top, cohttp and http (6.0.0~alpha1)
  packages/cohttp-async/cohttp-async.6.0.0~alpha1/opam
  packages/cohttp-curl-async/cohttp-curl-async.6.0.0~alpha1/opam
  packages/cohttp-curl-lwt/cohttp-curl-lwt.6.0.0~alpha1/opam
  packages/cohttp-curl/cohttp-curl.6.0.0~alpha1/opam
  packages/cohttp-eio/cohttp-eio.6.0.0~alpha1/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.6.0.0~alpha1/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.6.0.0~alpha1/opam
  packages/cohttp-lwt/cohttp-lwt.6.0.0~alpha1/opam
  packages/cohttp-mirage/cohttp-mirage.6.0.0~alpha1/opam
  packages/cohttp-server-lwt-unix/cohttp-server-lwt-unix.6.0.0~alpha1/opam
  packages/cohttp-top/cohttp-top.6.0.0~alpha1/opam
  packages/cohttp/cohttp.6.0.0~alpha1/opam
  packages/http/http.6.0.0~alpha1/opam
Labels: consider for merge

#23813 Package afl-persistent.1.4
  packages/afl-persistent/afl-persistent.1.4/opam
Labels: consider for merge

#23808 Package yuujinchou.5.0.0
  packages/yuujinchou/yuujinchou.5.0.0/opam
Labels: consider for merge

#23728 Add ocamlfuse.2.7.1-cvs8
  packages/ocamlfuse/ocamlfuse.2.7.1-cvs8/opam
Labels: temporarily do not merge

#23817 Package tezos-rust-libs 1.6
  packages/tezos-rust-libs/tezos-rust-libs.1.6/opam
Labels: consider for merge

#23821 [new release] ppx_lun and lun (0.0.1)
  packages/lun/lun.0.0.1/opam
  packages/ppx_lun/ppx_lun.0.0.1/opam
Labels: needs maintainer action

#23420 opam-file-format < 2.1.5 is not compatible with OCaml 5.0
  packages/opam-file-format/opam-file-format.2.0.0/opam
  packages/opam-file-format/opam-file-format.2.0.0~beta/opam
  packages/opam-file-format/opam-file-format.2.0.0~beta3/opam
  packages/opam-file-format/opam-file-format.2.0.0~beta5/opam
  packages/opam-file-format/opam-file-format.2.0.0~rc2/opam
  packages/opam-file-format/opam-file-format.2.0~alpha5/opam
  packages/opam-file-format/opam-file-format.2.1.0/opam
  packages/opam-file-format/opam-file-format.2.1.2/opam
  packages/opam-file-format/opam-file-format.2.1.3/opam
  packages/opam-file-format/opam-file-format.2.1.4/opam
Labels: consider for merge

#23834 Release v0.16 of Base
  packages/base/base.v0.16.0/opam
  packages/sexplib0/sexplib0.v0.16.0/opam
Labels: consider for merge

#23824 Prevent install ocamlformat-rpc using a dummy package
  packages/ocamlformat-rpc/ocamlformat-rpc.removed/opam
Labels: question

#23736 Remove constraints on package versions in conflicts, it's unsupported
  packages/ocaml-options-vanilla/ocaml-options-vanilla.1/opam
Labels: consider for merge

#23842 document the ocaml-option-nnpchecker package
  packages/ocaml-option-nnpchecker/ocaml-option-nnpchecker.1/opam
Labels: consider for merge

#23844 mesh-triangle is not compatible with ocaml 5
  packages/mesh-triangle/mesh-triangle.0.9.5/opam
Labels: consider for merge
