Repository ocaml/opam-repository, pull requests merged in 2023-02, with the labels that each got.

#23020 [new release] curly (0.3.0)
  packages/curly/curly.0.3.0/opam
Labels: consider for merge

#23175 release fmlib 0.5.2
  packages/fmlib/fmlib.0.5.2/opam
  packages/fmlib_js/fmlib_js.0.5.2/opam
  packages/fmlib_parse/fmlib_parse.0.5.2/opam
  packages/fmlib_pretty/fmlib_pretty.0.5.2/opam
  packages/fmlib_std/fmlib_std.0.5.2/opam
Labels: consider for merge

#23183 Package soupault.4.4.0
  packages/soupault/soupault.4.4.0/opam
Labels: consider for merge

#23217 Package bio_io.0.6.0
  packages/bio_io/bio_io.0.6.0/opam
Labels: consider for merge

#23211 [new release] http-mirage-client (0.0.2)
  packages/http-mirage-client/http-mirage-client.0.0.2/opam
Labels: consider for merge

#23220 [new release] http-lwt-client (0.2.1)
  packages/http-lwt-client/http-lwt-client.0.2.1/opam
Labels: consider for merge

#23191 Do not run qcheck tests on OCaml 5
  packages/qcheck-alcotest/qcheck-alcotest.0.18.1/opam
  packages/qcheck-alcotest/qcheck-alcotest.0.18/opam
  packages/qcheck-alcotest/qcheck-alcotest.0.19/opam
  packages/qcheck-core/qcheck-core.0.18.1/opam
  packages/qcheck-core/qcheck-core.0.18/opam
  packages/qcheck-core/qcheck-core.0.19/opam
  packages/qcheck-ounit/qcheck-ounit.0.18.1/opam
  packages/qcheck-ounit/qcheck-ounit.0.18/opam
  packages/qcheck-ounit/qcheck-ounit.0.19/opam
  packages/qcheck/qcheck.0.18.1/opam
  packages/qcheck/qcheck.0.18/opam
  packages/qcheck/qcheck.0.19/opam
Labels: question, consider for merge

#23039 Package letters.0.3.2
  packages/letters/letters.0.3.2/opam
Labels: question

#23017 Mark topkg as incompatible with the bytecode-only mode
  packages/topkg/topkg.0.7.5/opam
  packages/topkg/topkg.0.7.6/opam
  packages/topkg/topkg.0.7.7/opam
  packages/topkg/topkg.0.7.8/opam
  packages/topkg/topkg.0.7.9/opam
  packages/topkg/topkg.0.8.0/opam
  packages/topkg/topkg.0.8.1/opam
  packages/topkg/topkg.0.9.0/opam
  packages/topkg/topkg.0.9.1/opam
  packages/topkg/topkg.1.0.0/opam
  packages/topkg/topkg.1.0.1/opam
  packages/topkg/topkg.1.0.2/opam
  packages/topkg/topkg.1.0.3/opam
  packages/topkg/topkg.1.0.4/opam
  packages/topkg/topkg.1.0.5/opam
  packages/topkg/topkg.1.0.6/opam
Labels: consider for merge

#22870 Package ppx_deriving_madcast.0.2
  packages/ppx_deriving_madcast/ppx_deriving_madcast.0.2/opam
Labels: consider for merge

#23236 [new release] eio_main, eio_luv, eio_linux and eio (0.8.1)
  packages/eio/eio.0.8.1/opam
  packages/eio_linux/eio_linux.0.8.1/opam
  packages/eio_luv/eio_luv.0.8.1/opam
  packages/eio_main/eio_main.0.8.1/opam
Labels: consider for merge

#23198 3 packages from ocaml-multicore/multicoretests at 0.1.1
  packages/qcheck-lin/qcheck-lin.0.1.1/opam
  packages/qcheck-multicoretests-util/qcheck-multicoretests-util.0.1.1/opam
  packages/qcheck-stm/qcheck-stm.0.1.1/opam
Labels: consider for merge

#23221 [new release] lab, gitlab, gitlab-unix and gitlab-jsoo (0.1.7)
  packages/gitlab-jsoo/gitlab-jsoo.0.1.7/opam
  packages/gitlab-unix/gitlab-unix.0.1.7/opam
  packages/gitlab/gitlab.0.1.7/opam
  packages/lab/lab.0.1.7/opam
Labels: consider for merge

#23274 paf-cohttp 0.4.0 is not compatible with cohttp 6
  packages/paf-cohttp/paf-cohttp.0.4.0/opam
Labels: consider for merge

#23275 webmachine 0.4.0 requires ocamlbuild
  packages/webmachine/webmachine.0.4.0/opam
  packages/webmachine/webmachine.0.5.0/opam
Labels: consider for merge

#23254 conf-expat upgrade: more distributions considered
  packages/conf-expat/conf-expat.1/opam
Labels: consider for merge

#23278 Package tezos-rust-libs.1.4
  packages/tezos-rust-libs/tezos-rust-libs.1.4/opam
Labels: consider for merge

#23233 [new release] camyll (0.4.2)
  packages/camyll/camyll.0.4.2/opam
Labels: consider for merge

#23267 9 packages from savonet/ocaml-posix at 2.0.2
  packages/posix-base/posix-base.2.0.2/opam
  packages/posix-bindings/posix-bindings.2.0.2/opam
  packages/posix-getopt/posix-getopt.2.0.2/opam
  packages/posix-signal/posix-signal.2.0.2/opam
  packages/posix-socket-unix/posix-socket-unix.2.0.2/opam
  packages/posix-socket/posix-socket.2.0.2/opam
  packages/posix-time2/posix-time2.2.0.2/opam
  packages/posix-types/posix-types.2.0.2/opam
  packages/posix-uname/posix-uname.2.0.2/opam
Labels: consider for merge

#23050 ccbg.0.1
  packages/ccbg/ccbg.0.1/opam
Labels: needs reporter action

#23140 [new release] biotk (0.2.0)
  packages/biotk/biotk.0.2.0/opam
Labels: consider for merge

#23052 gotd.0.1
  packages/gotd/gotd.0.1/opam
Labels: needs reporter action

#23292 [new release] gluten, gluten-mirage, gluten-lwt, gluten-lwt-unix, gluten-eio and gluten-async (0.4.0)
  packages/gluten-async/gluten-async.0.4.0/opam
  packages/gluten-eio/gluten-eio.0.4.0/opam
  packages/gluten-lwt-unix/gluten-lwt-unix.0.4.0/opam
  packages/gluten-lwt/gluten-lwt.0.4.0/opam
  packages/gluten-mirage/gluten-mirage.0.4.0/opam
  packages/gluten/gluten.0.4.0/opam
Labels: consider for merge

#23247 [new release] ppxlib (0.29.0)
  packages/ppx_bench/ppx_bench.v0.14.1/opam
  packages/ppx_bench/ppx_bench.v0.15.0/opam
  packages/ppx_inline_test/ppx_inline_test.v0.14.1/opam
  packages/ppx_inline_test/ppx_inline_test.v0.15.0/opam
  packages/ppxlib/ppxlib.0.29.0/opam
Labels: consider for merge

#23213 [new release] dolmen_type, dolmen_model, dolmen_lsp, dolmen_loop, dolmen_bin and dolmen (0.8.1)
  packages/dolmen/dolmen.0.8.1/opam
  packages/dolmen_bin/dolmen_bin.0.8.1/opam
  packages/dolmen_loop/dolmen_loop.0.8.1/opam
  packages/dolmen_lsp/dolmen_lsp.0.8.1/opam
  packages/dolmen_model/dolmen_model.0.8.1/opam
  packages/dolmen_type/dolmen_type.0.8.1/opam
Labels: needs reporter action

#23306 [new release] git, git-mirage, git-paf and git-unix (3.12.0)
  packages/git-mirage/git-mirage.3.12.0/opam
  packages/git-paf/git-paf.3.12.0/opam
  packages/git-unix/git-unix.3.12.0/opam
  packages/git/git.3.12.0/opam
Labels: consider for merge

#23322 paf-cohttp.0.{0,2,3,4}.0 and paf-cohttp.0.0.{6,7,8,8-1,9} are incompatible with mirage-crypto-rng.0.11.0
  packages/git-unix/git-unix.2.1.3/opam
  packages/paf-cohttp/paf-cohttp.0.0.6/opam
  packages/paf-cohttp/paf-cohttp.0.0.7/opam
  packages/paf-cohttp/paf-cohttp.0.0.8-1/opam
  packages/paf-cohttp/paf-cohttp.0.0.8/opam
  packages/paf-cohttp/paf-cohttp.0.0.9/opam
  packages/paf-cohttp/paf-cohttp.0.2.0/opam
  packages/paf-cohttp/paf-cohttp.0.3.0/opam
  packages/paf-cohttp/paf-cohttp.0.4.0/opam
Labels: consider for merge

#23299 Package getopt.20230213
  packages/getopt/getopt.20230213/opam
Labels: consider for merge

#23326 [new release] albatross (1.5.5)
  packages/albatross/albatross.1.5.5/opam
  packages/current-albatross-deployer/current-albatross-deployer.1.0.0/opam
Labels: consider for merge

#23333 [new release] awa, awa-mirage and awa-lwt (0.1.2)
  packages/awa-lwt/awa-lwt.0.1.2/opam
  packages/awa-mirage/awa-mirage.0.1.2/opam
  packages/awa/awa.0.1.2/opam
Labels: consider for merge

#23336 [new release] mirage-block-ccm (2.0.0)
  packages/mirage-block-ccm/mirage-block-ccm.2.0.0/opam
Labels: consider for merge

#23341 [new release] ssh-agent and ssh-agent-unix (0.4.1)
  packages/ssh-agent-unix/ssh-agent-unix.0.4.1/opam
  packages/ssh-agent/ssh-agent.0.4.1/opam
Labels: consider for merge

#23342 [new release] http-lwt-client (0.2.2)
  packages/http-lwt-client/http-lwt-client.0.2.2/opam
Labels: consider for merge

#23362 Release ocaml-jupyter kernel v2.8.2
  packages/jupyter/jupyter.2.8.2/opam
Labels: consider for merge

#23369 Add `build` field to XML-Light 2.4
  packages/xml-light/xml-light.2.4/opam
Labels: consider for merge

#23354 [new release] iomux (0.1)
  packages/iomux/iomux.0.1/opam
Labels: consider for merge

#23351 Fix equinoxe 0.1.0 deps
  packages/equinoxe/equinoxe.0.1.0/opam
Labels: consider for merge

#23348 [new release] logs-syslog (0.3.2)
  packages/logs-syslog/logs-syslog.0.3.2/opam
Labels: consider for merge

#23344 [new release] conduit, conduit-mirage, conduit-lwt, conduit-lwt-unix and conduit-async (6.2.0)
  packages/conduit-async/conduit-async.6.2.0/opam
  packages/conduit-lwt-unix/conduit-lwt-unix.6.2.0/opam
  packages/conduit-lwt/conduit-lwt.6.2.0/opam
  packages/conduit-mirage/conduit-mirage.6.2.0/opam
  packages/conduit/conduit.6.2.0/opam
Labels: consider for merge

#23381 [new release] kcas (0.2.1)
  packages/kcas/kcas.0.2.1/opam
Labels: consider for merge

#23375 [new release] colombe, sendmail and sendmail-lwt (0.8.0)
  packages/colombe/colombe.0.8.0/opam
  packages/sendmail-lwt/sendmail-lwt.0.8.0/opam
  packages/sendmail/sendmail.0.8.0/opam
Labels: consider for merge

#23264 Package opine.0.1.3
  packages/opine/opine.0.1.3/opam
Labels: consider for merge

#23399 conex 0.9.2 is not compatible with ocaml5 (uses Pervasives)
  packages/conex/conex.0.9.2/opam
Labels: consider for merge

#23377 [capnp-rcp-unix] Add upper bound for mirage-crypto-rng
  packages/capnp-rpc-net/capnp-rpc-net.1.1/opam
  packages/capnp-rpc-net/capnp-rpc-net.1.2/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.0.9.0/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.1.0/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.1.1/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.1.2.1/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.1.2/opam
Labels: consider for merge

#23402 [new release] capnp-rpc, capnp-rpc-unix, capnp-rpc-net, capnp-rpc-mirage and capnp-rpc-lwt (1.2.3)
  packages/capnp-rpc-lwt/capnp-rpc-lwt.1.2.3/opam
  packages/capnp-rpc-mirage/capnp-rpc-mirage.1.2.3/opam
  packages/capnp-rpc-net/capnp-rpc-net.1.2.3/opam
  packages/capnp-rpc-unix/capnp-rpc-unix.1.2.3/opam
  packages/capnp-rpc/capnp-rpc.1.2.3/opam
Labels: consider for merge

#23404 [new release] checkseum (0.5.0)
  packages/checkseum/checkseum.0.5.0/opam
Labels: consider for merge

#22986 ahrocksdb: ignore CI failures
  packages/ahrocksdb/ahrocksdb.0.2.0/opam
  packages/ahrocksdb/ahrocksdb.0.2.1/opam
Labels: consider for merge

#23380 Add irc-client.0.7.1
  packages/irc-client-lwt-ssl/irc-client-lwt-ssl.0.7.1/opam
  packages/irc-client-lwt/irc-client-lwt.0.7.1/opam
  packages/irc-client-tls/irc-client-tls.0.7.1/opam
  packages/irc-client-unix/irc-client-unix.0.7.1/opam
  packages/irc-client/irc-client.0.7.1/opam
Labels: consider for merge

#23411 Release merlin and merlin-lib v4.8-{500,414}
  packages/gopcaml-mode/gopcaml-mode.0.0.6/opam
  packages/merlin-lib/merlin-lib.4.8-414/opam
  packages/merlin-lib/merlin-lib.4.8-500/opam
  packages/merlin/merlin.4.8-414/opam
  packages/merlin/merlin.4.8-500/opam
Labels: consider for merge
