Repository ocaml/opam-repository, pull requests merged in 2023-12, with the labels that each got.

#24816 Use clang on macOS for tsan support
  packages/ocaml-variants/ocaml-variants.5.1.0+tsan/opam
  packages/ocaml-variants/ocaml-variants.5.1.0~rc3+tsan/opam
  packages/ocaml-variants/ocaml-variants.5.2.0+trunk/opam
Labels: consider for merge

#24845 Add ocaml-option-no-compression to 5.1.1+trunk
  packages/ocaml-variants/ocaml-variants.5.1.1+trunk/opam
Labels: consider for merge

#24873 4 packages from c-cube/qcheck at 0.21.3
  packages/qcheck-alcotest/qcheck-alcotest.0.21.3/opam
  packages/qcheck-core/qcheck-core.0.21.3/opam
  packages/qcheck-ounit/qcheck-ounit.0.21.3/opam
  packages/qcheck/qcheck.0.21.3/opam
Labels: consider for merge

#24906 Disable tsdl-ttf's < 0.5 tests (infinit loop)
  packages/tsdl-ttf/tsdl-ttf.0.2/opam
  packages/tsdl-ttf/tsdl-ttf.0.3.2/opam
  packages/tsdl-ttf/tsdl-ttf.0.3/opam
  packages/tsdl-ttf/tsdl-ttf.0.4/opam
Labels: consider for merge

#24881 [new release] elpi (1.18.1)
  packages/elpi/elpi.1.18.1/opam
Labels: consider for merge

#24887 new file: packages/batteries/batteries.3.7.2/opam
  packages/batteries/batteries.3.7.2/opam
Labels: consider for merge

#24917 Release of OCaml 5.1.1
  packages/ocaml-base-compiler/ocaml-base-compiler.5.1.1/files/ocaml-base-compiler.install
  packages/ocaml-base-compiler/ocaml-base-compiler.5.1.1/opam
  packages/ocaml-src/ocaml-src.5.1.1/files/META
  packages/ocaml-src/ocaml-src.5.1.1/opam
  packages/ocaml-system/ocaml-system.5.1.1/files/gen_ocaml_config.ml.in
  packages/ocaml-system/ocaml-system.5.1.1/opam
  packages/ocaml-variants/ocaml-variants.5.1.1+options/files/ocaml-variants.install
  packages/ocaml-variants/ocaml-variants.5.1.1+options/opam
  packages/ocaml-variants/ocaml-variants.5.1.1+trunk/opam
  packages/ocaml-variants/ocaml-variants.5.1.2+trunk/opam
  packages/ocaml/ocaml.5.1.2/opam
Labels: consider for merge

#24900 [new release] trace (2 packages) (0.5)
  packages/trace-tef/trace-tef.0.5/opam
  packages/trace/trace.0.5/opam
Labels: do not merge

#24863 [new release] ocaml-protoc (4 packages) (3.0.0)
  packages/kinetic-client/kinetic-client.0.0.11/opam
  packages/ocaml-protoc/ocaml-protoc.3.0.0/opam
  packages/opentelemetry/opentelemetry.0.2/opam
  packages/opentelemetry/opentelemetry.0.3/opam
  packages/opentelemetry/opentelemetry.0.4/opam
  packages/opentelemetry/opentelemetry.0.5/opam
  packages/opentelemetry/opentelemetry.0.6/opam
  packages/pbrt/pbrt.3.0.0/opam
  packages/pbrt_services/pbrt_services.3.0.0/opam
  packages/pbrt_yojson/pbrt_yojson.3.0.0/opam
Labels: consider for merge

#24937 mybuild: conflicts with bytecode only compilers
  packages/mybuild/mybuild.1/opam
  packages/mybuild/mybuild.2/opam
  packages/mybuild/mybuild.3/opam
  packages/mybuild/mybuild.5/opam
  packages/mybuild/mybuild.6/opam
Labels: consider for merge

#24897 Add Z3 4.12.3
  packages/z3/z3.4.12.3/files/optional-python-bytecode.patch
  packages/z3/z3.4.12.3/opam
Labels: consider for merge

#24939 Add Z3 4.12.4
  packages/z3/z3.4.12.4/files/optional-python-bytecode.patch
  packages/z3/z3.4.12.4/opam
Labels: consider for merge

#24936 Release cohttp v5.3.1
  packages/cohttp-async/cohttp-async.5.3.0/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.5.3.0/opam
  packages/cohttp-lwt/cohttp-lwt.5.3.0/opam
  packages/cohttp-mirage/cohttp-mirage.5.3.0/opam
  packages/cohttp-top/cohttp-top.5.3.0/opam
  packages/cohttp/cohttp.5.3.1/opam
Labels: consider for merge

#24950 [new release] grid (0.1.0)
  packages/grid/grid.0.1.0/opam
Labels: consider for merge

#24924 Package camlimages.5.0.5
  packages/camlimages/camlimages.5.0.5/opam
  packages/liquidsoap/liquidsoap.1.4.0/opam
  packages/liquidsoap/liquidsoap.1.4.1-1/opam
  packages/liquidsoap/liquidsoap.1.4.1-2/opam
  packages/liquidsoap/liquidsoap.1.4.1/opam
  packages/liquidsoap/liquidsoap.1.4.2/opam
  packages/liquidsoap/liquidsoap.1.4.3/opam
  packages/liquidsoap/liquidsoap.1.4.4/opam
  packages/liquidsoap/liquidsoap.2.0.0/opam
  packages/liquidsoap/liquidsoap.2.0.0~rc1/opam
  packages/liquidsoap/liquidsoap.2.0.1/opam
  packages/liquidsoap/liquidsoap.2.0.2-1/opam
  packages/liquidsoap/liquidsoap.2.0.2/opam
  packages/liquidsoap/liquidsoap.2.0.3-1/opam
  packages/liquidsoap/liquidsoap.2.0.3/opam
  packages/liquidsoap/liquidsoap.2.0.4-1/opam
  packages/liquidsoap/liquidsoap.2.0.4-2/opam
  packages/liquidsoap/liquidsoap.2.0.4/opam
  packages/liquidsoap/liquidsoap.2.0.5/opam
  packages/liquidsoap/liquidsoap.2.0.6/opam
  packages/liquidsoap/liquidsoap.2.0.7/opam
Labels: consider for merge

#24957 [new release] lsp (3 packages) (1.17.0)
  packages/jsonrpc/jsonrpc.1.17.0/opam
  packages/lsp/lsp.1.17.0/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.17.0/opam
Labels: consider for merge

#24958 [new release] merlin and merlin-lib (4.13-500)
  packages/merlin-lib/merlin-lib.4.13-500/opam
  packages/merlin/merlin.4.13-500/opam
Labels: new opam-repository maintainer question

#24956 Old soupault packages need a lower bound on re
  packages/soupault/soupault.1.10.0/opam
  packages/soupault/soupault.1.11.0/opam
  packages/soupault/soupault.1.12.0/opam
  packages/soupault/soupault.1.13.0/opam
  packages/soupault/soupault.1.6/opam
  packages/soupault/soupault.1.7.0/opam
  packages/soupault/soupault.1.8.0/opam
  packages/soupault/soupault.1.9.0/opam
  packages/soupault/soupault.2.0.0/opam
  packages/soupault/soupault.2.1.0/opam
  packages/soupault/soupault.2.2.0/opam
  packages/soupault/soupault.2.3.0/opam
  packages/soupault/soupault.2.3.1/opam
  packages/soupault/soupault.2.4.0/opam
  packages/soupault/soupault.2.5.0/opam
  packages/soupault/soupault.2.6.0/opam
  packages/soupault/soupault.2.7.0/opam
  packages/soupault/soupault.2.8.0/opam
  packages/soupault/soupault.3.0.0/opam
  packages/soupault/soupault.3.1.0/opam
Labels: consider for merge

#24942 ott: fix for building on Windows (without symlink)
  packages/ott/ott.0.32/opam
  packages/ott/ott.0.33/opam
Labels: consider for merge

#24963 Ledgerwallet.0.4.0
  packages/conf-secp256k1/conf-secp256k1.2/opam
  packages/ledgerwallet-tezos/ledgerwallet-tezos.0.4.0/opam
  packages/ledgerwallet/ledgerwallet.0.4.0/opam
  packages/octez-shell-libs/octez-shell-libs.18.0/opam
  packages/octez-shell-libs/octez-shell-libs.18.1/opam
  packages/tezos-signer-backends/tezos-signer-backends.16.0/opam
  packages/tezos-signer-backends/tezos-signer-backends.16.1/opam
  packages/tezos-signer-backends/tezos-signer-backends.17.1/opam
  packages/tezos-signer-backends/tezos-signer-backends.17.2/opam
  packages/tezos-signer-backends/tezos-signer-backends.17.3/opam
Labels: consider for merge

#24982 [new release] dune-compiledb (0.6.0)
  packages/dune-compiledb/dune-compiledb.0.6.0/opam
Labels: consider for merge

#24980 Add new version 3.0 for the E-prover automatic theorem prover
  packages/eprover/eprover.3.0/opam
Labels: consider for merge

#24994 [new release] castore (0.0.2)
  packages/castore/castore.0.0.2/opam
Labels: consider for merge

#24961 Mark let-if and ssh-agent-unix unavailable
  packages/let-if/let-if.0.1.0/opam
  packages/let-if/let-if.0.2.0/opam
  packages/let-if/let-if.0.3.0/opam
  packages/ssh-agent-unix/ssh-agent-unix.0.2.0/opam
  packages/ssh-agent-unix/ssh-agent-unix.0.2.1/opam
  packages/ssh-agent-unix/ssh-agent-unix.0.3.0/opam
  packages/ssh-agent-unix/ssh-agent-unix.0.3.1/opam
  packages/ssh-agent-unix/ssh-agent-unix.0.4.0/opam
  packages/ssh-agent-unix/ssh-agent-unix.0.4.1/opam
Labels: consider for merge
