Repository ocaml/opam-repository, pull requests merged in 2023-03, with the labels that each got.

#23409 release omake-0.10.6
  packages/omake/omake.0.10.6/opam
Labels: consider for merge

#23401 ulex-camlp5 1.3: point to upstream tarball
  packages/ulex-camlp5/ulex-camlp5.1.3/opam
Labels: consider for merge

#23430 [new release] tls, tls-mirage, tls-lwt, tls-eio and tls-async (0.17.0)
  packages/conduit-mirage/conduit-mirage.6.2.0/opam
  packages/mehari/mehari.0.1/opam
  packages/mehari/mehari.0.2/opam
  packages/tls-async/tls-async.0.17.0/opam
  packages/tls-eio/tls-eio.0.17.0/opam
  packages/tls-lwt/tls-lwt.0.17.0/opam
  packages/tls-mirage/tls-mirage.0.17.0/opam
  packages/tls/tls.0.17.0/opam
Labels: consider for merge

#23429 [new release] mrmime (0.6.0)
  packages/mrmime/mrmime.0.6.0/opam
Labels: consider for merge

#23442 Package sedlex.3.1
  packages/sedlex/sedlex.3.1/opam
Labels: consider for merge

#23459 [new release] mirage-monitoring (0.0.4)
  packages/mirage-monitoring/mirage-monitoring.0.0.4/opam
Labels: consider for merge

#23468 [new release] received (0.5.2)
  packages/received/received.0.5.2/opam
Labels: consider for merge

#21050 Add new version 3.9 for conf-python-3
  packages/conf-python-3/conf-python-3.9.0.0/files/test.py
  packages/conf-python-3/conf-python-3.9.0.0/opam
Labels: do not merge

#22851 Fix lowerbound for ocamlfind.1.9.5
  packages/ocamlfind/ocamlfind.1.9.5/opam
Labels: question

#23473 Release of esperanto.0.0.3
  packages/esperanto-cosmopolitan/esperanto-cosmopolitan.0.0.3/opam
  packages/esperanto/esperanto.0.0.3/opam
Labels: consider for merge

#23480 Fix ocamlfind.1.9.6 upgrade
  packages/ocamlfind/ocamlfind.1.9.6/files/0001-Harden-test-for-OCaml-5.patch
  packages/ocamlfind/ocamlfind.1.9.6/opam
Labels: consider for merge

#23499 [new release] ethernet (3.2.0)
  packages/ethernet/ethernet.3.2.0/opam
Labels: consider for merge

#23488 2 packages from LexiFi/gen_js_api at 1.1.2
  packages/gen_js_api/gen_js_api.1.1.2/opam
  packages/ojs/ojs.1.1.2/opam
Labels: consider for merge

#23482 [new release] uspf, uspf-unix and uspf-lwt (0.0.3)
  packages/uspf-lwt/uspf-lwt.0.0.3/opam
  packages/uspf-unix/uspf-unix.0.0.3/opam
  packages/uspf/uspf.0.0.3/opam
Labels: consider for merge

#23374 [new release] ppx_cstruct, cstruct, cstruct-unix, cstruct-sexp, cstruct-lwt and cstruct-async (6.2.0)
  packages/cstruct-async/cstruct-async.6.2.0/opam
  packages/cstruct-lwt/cstruct-lwt.6.2.0/opam
  packages/cstruct-sexp/cstruct-sexp.6.2.0/opam
  packages/cstruct-unix/cstruct-unix.6.2.0/opam
  packages/cstruct/cstruct.6.2.0/opam
  packages/ppx_cstruct/ppx_cstruct.6.2.0/opam
Labels: consider for merge

#23470 [new release] irmin project (3.6.1)
  packages/irmin-bench/irmin-bench.3.6.1/opam
  packages/irmin-chunk/irmin-chunk.3.6.1/opam
  packages/irmin-cli/irmin-cli.3.6.1/opam
  packages/irmin-containers/irmin-containers.3.6.1/opam
  packages/irmin-fs/irmin-fs.3.6.1/opam
  packages/irmin-git/irmin-git.3.6.1/opam
  packages/irmin-graphql/irmin-graphql.3.6.1/opam
  packages/irmin-http/irmin-http.3.6.1/opam
  packages/irmin-mirage-git/irmin-mirage-git.3.6.1/opam
  packages/irmin-mirage-graphql/irmin-mirage-graphql.3.6.1/opam
  packages/irmin-mirage/irmin-mirage.3.6.1/opam
  packages/irmin-pack/irmin-pack.3.6.1/opam
  packages/irmin-test/irmin-test.3.6.1/opam
  packages/irmin-tezos-utils/irmin-tezos-utils.3.6.1/opam
  packages/irmin-tezos/irmin-tezos.3.6.1/opam
  packages/irmin/irmin.3.6.1/opam
  packages/libirmin/libirmin.3.6.1/opam
  packages/ppx_irmin/ppx_irmin.3.6.1/opam
Labels: consider for merge

#23503 Packages conf-protoc.4.4.0 and ocaml-protoc-plugin.4.4.0
  packages/conf-protoc/conf-protoc.4.4.0/opam
  packages/ocaml-protoc-plugin/ocaml-protoc-plugin.4.4.0/opam
Labels: consider for merge

#23455 Add gapi-ocaml 0.4.4
  packages/gapi-ocaml/gapi-ocaml.0.4.4/opam
Labels: consider for merge

#23510 [new release] camyll (0.4.3)
  packages/camyll/camyll.0.4.3/opam
Labels: consider for merge

#23502 [new release] lambdapi (2.3.1)
  packages/lambdapi/lambdapi.2.3.1/opam
Labels: consider for merge

#23529 [new release] kcas (0.2.2)
  packages/kcas/kcas.0.2.2/opam
Labels: consider for merge

#23522 Package errpy.0.0.7
  packages/errpy/errpy.0.0.7/opam
Labels: consider for merge

#23531 Package randii.1.0.0
  packages/randii/randii.1.0.0/opam
Labels: question

#23519 [new release] piece_rope (0.9.0)
  packages/piece_rope/piece_rope.0.9.0/opam
Labels: needs reporter action

#23357 Add ctypes 0.20.2
  packages/ctypes/ctypes.0.20.2/opam
Labels: needs reporter action

#23544 [new release] unix-errno (0.6.2)
  packages/unix-errno/unix-errno.0.6.2/opam
Labels: consider for merge

#23457 add constraint on mtime for logtk
  packages/logtk/logtk.2.1/opam
Labels: needs reporter action

#23512 conf-protoc: fix license
  packages/conf-protoc/conf-protoc.1.0.0/opam
Labels: consider for merge

#23526 [new release] ezxenstore (0.4.3)
  packages/ezxenstore/ezxenstore.0.4.3/opam
Labels: needs reporter action

#23524 Package guardian.0.1.0
  packages/guardian/guardian.0.1.0/opam
Labels: needs reporter action

#23555 Package zanuda.1.0.0
  packages/zanuda/zanuda.1.0.0/opam
Labels: consider for merge

#23573 cca: add missing dependency on num
  packages/cca/cca.0.1/opam
  packages/cca/cca.0.2/opam
  packages/cca/cca.0.4/opam
  packages/cca/cca.0.5/opam
  packages/cca/cca.0.6.2/opam
Labels: consider for merge

#23577 Package bogue-tutorials.0.1.0
  packages/bogue-tutorials/bogue-tutorials.0.1.0/opam
Labels: consider for merge

#23590 Add libtorch 2.0.0
  packages/libtorch/libtorch.2.0.0+linux-x86_64/opam
  packages/libtorch/libtorch.2.0.0+macos-x86_64/opam
Labels: consider for merge

#23586 Add HOMEBREW_NO_AUTO_UPDATE=1 to homebrew packages
  packages/conf-bison/conf-bison.2/opam
  packages/conf-flex/conf-flex.2/opam
  packages/conf-libclang/conf-libclang.1.0.0/opam
  packages/conf-libclang/conf-libclang.10/opam
  packages/conf-libclang/conf-libclang.11/opam
  packages/conf-libclang/conf-libclang.12/opam
  packages/conf-libclang/conf-libclang.13/opam
  packages/conf-libclang/conf-libclang.14/opam
  packages/conf-libclang/conf-libclang.15/opam
  packages/conf-libssl/conf-libssl.1/opam
  packages/conf-libssl/conf-libssl.2/opam
  packages/conf-libssl/conf-libssl.3/opam
  packages/conf-libssl/conf-libssl.4/opam
  packages/conf-qt/conf-qt.5.2.1/opam
Labels: consider for merge

#23584 add coq-core.8.17.0, coq-stdlib.8.17.0, coq-server.8.17.0, coq.8.17.0
  packages/coq-core/coq-core.8.17.0/opam
  packages/coq-of-ocaml/coq-of-ocaml.2.5.3+4.14/opam
  packages/coq-stdlib/coq-stdlib.8.17.0/opam
  packages/coq/coq.8.17.0/opam
  packages/coqide-server/coqide-server.8.17.0/opam
  packages/zenon/zenon.0.8.4/opam
  packages/zenon/zenon.0.8.5/opam
Labels: consider for merge

#23568 cca v0.7
  packages/cca/cca.0.7/files/cca.install
  packages/cca/cca.0.7/opam
Labels: question
