Repository ocaml/opam-repository, pull requests merged in 2023-08, with the labels that each got.

#24178 [new release] conf-diffutils 1.1
  packages/conf-diffutils/conf-diffutils.1.1/opam
Labels: consider for merge

#24222 2 packages from OCamlPro/ocp-index at 1.3.5
  packages/ocp-browser/ocp-browser.1.3.5/opam
  packages/ocp-index/ocp-index.1.3.5/opam
Labels: consider for merge

#24229 Fix lowerbounds check on acgtk's mtime dep
  packages/acgtk/acgtk.1.5.1/opam
  packages/acgtk/acgtk.1.5.2/opam
Labels: consider for merge

#24241 [new release] dream-html (1.0.0)
  packages/dream-html/dream-html.1.0.0/opam
Labels: consider for merge

#24105 conf-postgresql - update depexts package name for macos + homebrew (#23912)
  packages/conf-postgresql/conf-postgresql.1/opam
Labels: question

#24240 [new release] trace (2 packages) (0.3)
  packages/opentelemetry/opentelemetry.0.5/opam
  packages/trace-tef/trace-tef.0.3/opam
  packages/trace/trace.0.3/opam
  packages/tracy-client/tracy-client.0.1/opam
Labels: consider for merge

#24262 CamlPDF v2.6
  packages/camlpdf/camlpdf.2.6/opam
Labels: consider for merge

#24260 Package par_incr.0.1
  packages/par_incr/par_incr.0.1/opam
Labels: consider for merge

#24234 [new release] http, cohttp, cohttp-top, cohttp-server-lwt-unix, cohttp-mirage, cohttp-lwt, cohttp-lwt-unix, cohttp-lwt-jsoo, cohttp-eio, cohttp-curl, cohttp-curl-lwt, cohttp-curl-async and cohttp-async (6.0.0~alpha2)
  packages/cohttp-async/cohttp-async.6.0.0~alpha2/opam
  packages/cohttp-curl-async/cohttp-curl-async.6.0.0~alpha2/opam
  packages/cohttp-curl-lwt/cohttp-curl-lwt.6.0.0~alpha2/opam
  packages/cohttp-curl/cohttp-curl.6.0.0~alpha2/opam
  packages/cohttp-eio/cohttp-eio.6.0.0~alpha2/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.6.0.0~alpha2/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.6.0.0~alpha2/opam
  packages/cohttp-lwt/cohttp-lwt.6.0.0~alpha2/opam
  packages/cohttp-mirage/cohttp-mirage.6.0.0~alpha2/opam
  packages/cohttp-server-lwt-unix/cohttp-server-lwt-unix.6.0.0~alpha2/opam
  packages/cohttp-top/cohttp-top.6.0.0~alpha2/opam
  packages/cohttp/cohttp.6.0.0~alpha2/opam
  packages/http/http.6.0.0~alpha2/opam
Labels: consider for merge

#24090 Package apron.v0.9.14~beta.2
  packages/apron/apron.v0.9.14~beta.2/opam
Labels: consider for merge

#24196 [new release] repr (4 packages) (0.7.0)
  packages/ppx_repr/ppx_repr.0.7.0/opam
  packages/repr-bench/repr-bench.0.7.0/opam
  packages/repr-fuzz/repr-fuzz.0.7.0/opam
  packages/repr/repr.0.7.0/opam
Labels: consider for merge

#24277 Package cpdf.2.6
  packages/cpdf/cpdf.2.6/files/cpdf.install
  packages/cpdf/cpdf.2.6/opam
Labels: consider for merge

#24275 Package opam-ed.0.4
  packages/opam-ed/opam-ed.0.4/opam
Labels: consider for merge

#24265 [new release] qmp (0.20.0)
  packages/qmp/qmp.0.20.0/opam
Labels: consider for merge

#24213 Package lwt.5.7.0
  packages/lwt/lwt.5.7.0/opam
Labels: consider for merge

#24288 [new release] rtree (0.1.1)
  packages/rtree/rtree.0.1.1/opam
Labels: consider for merge

#24218 Package errpy.0.0.9
  packages/errpy/errpy.0.0.9/opam
Labels: consider for merge

#24290 Package quick_print.0.11
  packages/quick_print/quick_print.0.11/opam
Labels: consider for merge

#24293 Package bwd.2.2.0
  packages/bwd/bwd.2.2.0/opam
Labels: consider for merge

#24294 [new release] earlybird (1.2.1)
  packages/earlybird/earlybird.1.2.1/opam
Labels: consider for merge

#24303 [new release] ocamlregextkit (1.0.0)
  packages/ocamlregextkit/ocamlregextkit.1.0.0/opam
Labels: consider for merge

#24251 [new release] opam-check-npm-deps (1.0.0)
  packages/opam-check-npm-deps/opam-check-npm-deps.1.0.0/opam
Labels: consider for merge

#24286 Add a Github Action that removes the "needs reporter action" label when the issue or PR has been commented on
  .github/workflows/unlabel.yml
Labels: needs opam-repository maintainer action, consider for merge

#24296 [new release] re (1.11.0)
  packages/re/re.1.11.0/opam
Labels: consider for merge

#24311 2 packages from extism/extism at 0.4.0
  packages/extism-manifest/extism-manifest.0.4.0/opam
  packages/extism/extism.0.4.0/opam
Labels: consider for merge

#24310 Release merlin v4.10-414 and v4.10-500
  packages/merlin-lib/merlin-lib.4.10-414/opam
  packages/merlin-lib/merlin-lib.4.10-500/opam
  packages/merlin/merlin.4.10-414/opam
  packages/merlin/merlin.4.10-500/opam
Labels: consider for merge

#23793 Fix bad SHAs for ezjs_fetch package
  packages/ezjs_fetch/ezjs_fetch.0.1/opam
Labels: missing upstream archive

#24328 [new release] eio (5 packages) (0.12)
  packages/SZXX/SZXX.4.0.0/opam
  packages/caqti-eio/caqti-eio.2.0.1/opam
  packages/carbon/carbon.0.1.0/opam
  packages/cohttp-eio/cohttp-eio.6.0.0~alpha1/opam
  packages/cohttp-eio/cohttp-eio.6.0.0~alpha2/opam
  packages/eio-ssl/eio-ssl.0.2.0/opam
  packages/eio/eio.0.12/opam
  packages/eio_linux/eio_linux.0.12/opam
  packages/eio_main/eio_main.0.12/opam
  packages/eio_posix/eio_posix.0.12/opam
  packages/eio_windows/eio_windows.0.12/opam
  packages/forester/forester.2.3/opam
  packages/geojsone/geojsone.0.1.1/opam
  packages/gluten-eio/gluten-eio.0.4.0/opam
  packages/gluten-eio/gluten-eio.0.4.1/opam
  packages/lwt_eio/lwt_eio.0.4/opam
  packages/mehari-eio-unix/mehari-eio-unix.0.1/opam
  packages/mehari-eio/mehari-eio.0.1/opam
  packages/mehari-eio/mehari-eio.0.2/opam
  packages/mehari-eio/mehari-eio.0.3/opam
  packages/mirage-crypto-rng-eio/mirage-crypto-rng-eio.0.10.7/opam
  packages/mirage-crypto-rng-eio/mirage-crypto-rng-eio.0.11.0/opam
  packages/mirage-crypto-rng-eio/mirage-crypto-rng-eio.0.11.1/opam
  packages/nloge/nloge.0.0.1/opam
  packages/nloge/nloge.0.0.2/opam
  packages/plist-xml/plist-xml.0.4.0/opam
  packages/plist-xml/plist-xml.0.5.0/opam
  packages/tls-eio/tls-eio.0.16.0/opam
  packages/tls-eio/tls-eio.0.17.0/opam
  packages/tls-eio/tls-eio.0.17.1/opam
Labels: consider for merge

#24306 [new release] moonpool (0.4)
  packages/moonpool/moonpool.0.4/opam
Labels: consider for merge

#24332 Constrain Links.0.9.7
  packages/links/links.0.9.7/opam
Labels: consider for merge

#24335 [new release] lwt_eio (0.5)
  packages/lwt_eio/lwt_eio.0.5/opam
Labels: consider for merge

#24336 re2.v0.16.0: does not compile on arm32
  packages/re2/re2.v0.16.0/opam
Labels: consider for merge

#24340 [new release] stringCodepointSplitter (0.0.2)
  packages/stringCodepointSplitter/stringCodepointSplitter.0.0.2/opam
Labels: consider for merge
