Repository ocaml/opam-repository, pull requests merged in 2023-06, with the labels that each got.

#23832 ocamlbuild: add patch to work on windows from fdopen
  packages/ocamlbuild/ocamlbuild.0.14.2+win/opam
Labels: consider for merge

#23852 Fix for building capnproto on opensuse-tumbleweed.
  packages/conf-capnproto/conf-capnproto.2/opam
Labels: consider for merge

#23856 Relax metrics-unix constraint on mtime
  packages/metrics-unix/metrics-unix.0.4.0/opam
Labels: consider for merge

#23846 Add jasmin.2022.09.3
  packages/jasmin/jasmin.2022.09.3/opam
Labels: consider for merge

#23864 [new release] eio_windows, eio_posix, eio_main, eio_linux and eio (0.10)
  packages/eio-ssl/eio-ssl.0.1.1/opam
  packages/eio/eio.0.10/opam
  packages/eio_linux/eio_linux.0.10/opam
  packages/eio_main/eio_main.0.10/opam
  packages/eio_posix/eio_posix.0.10/opam
  packages/eio_windows/eio_windows.0.10/opam
  packages/geojsone/geojsone.0.1.0/opam
  packages/lwt_eio/lwt_eio.0.1/opam
  packages/rawlink-eio/rawlink-eio.2.1/opam
  packages/tls-eio/tls-eio.0.15.4/opam
  packages/tls-eio/tls-eio.0.15.5/opam
  packages/topojsone/topojsone.0.1.0/opam
Labels: consider for merge

#23847 [new release] sel (0.2.0)
  packages/sel/sel.0.2.0/opam
Labels: consider for merge

#23869 [new release] ssl (0.6.0)
  packages/ssl/ssl.0.6.0/opam
Labels: consider for merge

#23865 add tezt.3.1.1
  packages/tezt/tezt.3.1.1/opam
Labels: consider for merge

#23886 [new release] tar, tar-unix and tar-mirage (2.5.0)
  packages/tar-mirage/tar-mirage.2.5.0/opam
  packages/tar-unix/tar-unix.2.5.0/opam
  packages/tar/tar.2.5.0/opam
Labels: consider for merge

#23893 Exclude `mtime.1.4.0` for `metrics-unix`
  packages/metrics-unix/metrics-unix.0.4.0/opam
Labels: consider for merge

#23890 [new release] fiber and fiber-lwt (3.7.0)
  packages/fiber-lwt/fiber-lwt.3.7.0/opam
  packages/fiber/fiber.3.7.0/opam
Labels: needs reporter action

#23899 Resto-cohttp-server is incompatible with cohttp-lwt.5.1.0
  packages/resto-cohttp-server/resto-cohttp-server.0.10/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.2/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.3/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.4/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.5/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.6.1/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.6/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.7/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.8/opam
  packages/resto-cohttp-server/resto-cohttp-server.0.9/opam
  packages/resto-cohttp-server/resto-cohttp-server.1.0/opam
  packages/resto-cohttp-server/resto-cohttp-server.1.1/opam
Labels: consider for merge

#23896 Fix compiler constraint in the base-metaocaml-ocamlfind native check
  packages/base-metaocaml-ocamlfind/base-metaocaml-ocamlfind.base/opam
Labels: consider for merge

#23904 [new release] nloge (0.0.2)
  packages/nloge/nloge.0.0.2/opam
Labels: consider for merge

#23905 [new release] domain-local-await (0.2.0)
  packages/domain-local-await/domain-local-await.0.2.0/opam
Labels: consider for merge

#23757 Package cb-check.0.1
  packages/cb-check/cb-check.0.1/opam
Labels: needs reporter action

#23894 3 packages from gitlab.inria.fr/fpottier/menhir/-/archive/20230608/archive.tar.gz
  packages/liquidsoap/liquidsoap.2.0.6/opam
  packages/menhir/menhir.20230608/opam
  packages/menhirLib/menhirLib.20230608/opam
  packages/menhirSdk/menhirSdk.20230608/opam
Labels: consider for merge

#23922 [new release] minisat (0.6)
  packages/minisat/minisat.0.6/opam
  packages/touist/touist.3.0.0/opam
  packages/touist/touist.3.1.0/opam
  packages/touist/touist.3.2.0/opam
  packages/touist/touist.3.2.1/opam
  packages/touist/touist.3.4.0/opam
  packages/touist/touist.3.4.1/opam
  packages/touist/touist.3.5.0/opam
Labels: consider for merge

#23927 [new release] rangeSet (0.2.1)
  packages/rangeSet/rangeSet.0.2.1/opam
Labels: consider for merge

#23889 Base.v.16.0 doesn't build on windows
  packages/base/base.v0.16.0/opam
Labels: do not merge

#23930 [new release] trace and trace-tef (0.2)
  packages/trace-tef/trace-tef.0.2/opam
  packages/trace/trace.0.2/opam
Labels: needs reporter action

#23934 Package base.v0.16.1
  packages/base/base.v0.16.1/opam
Labels: consider for merge

#23929 [new release] trampoline (0.1.0)
  packages/trampoline/trampoline.0.1.0/opam
Labels: consider for merge

#23939 [new release] moonpool (0.2)
  packages/moonpool/moonpool.0.2/opam
Labels: needs reporter action

#22836 Add ocamlfind-secondary.1.9.6
  packages/ocamlfind-secondary/ocamlfind-secondary.1.9.6/files/META.in
  packages/ocamlfind-secondary/ocamlfind-secondary.1.9.6/files/ocaml-secondary-compiler.conf.in
  packages/ocamlfind-secondary/ocamlfind-secondary.1.9.6/opam
Labels: consider for merge

#23944 [new release] shuttle_http (0.10.0)
  packages/shuttle_http/shuttle_http.0.10.0/opam
Labels: consider for merge

#23937 Frama-C: new release (27.0-Cobalt)
  packages/frama-c/frama-c.27.0/opam
Labels: consider for merge

#23958 cohttp-async requires JS < 0.16
  packages/cohttp-async/cohttp-async.2.5.8/opam
  packages/cohttp-async/cohttp-async.6.0.0~alpha1/opam
Labels: consider for merge

#23946 Fix various Windows `depends`/`available` fields
  packages/eio_main/eio_main.0.10/opam
  packages/eio_main/eio_main.0.9/opam
  packages/parany/parany.12.2.2/opam
  packages/parany/parany.14.0.0/opam
Labels: consider for merge

#23964 Add afl-2.57b package.
  packages/afl/afl.2.57b/files/add-uninstall-target.patch
  packages/afl/afl.2.57b/opam
Labels: consider for merge

#23965 [new release] ppxlib and ppxlib-bench (0.30.0)
  packages/ppxlib/ppxlib.0.30.0/opam
Labels: consider for merge

#23977 irmin-test: old versions require old verion of mtime
  packages/irmin-test/irmin-test.2.2.0/opam
Labels: consider for merge

#23990 [new release] duff (0.5)
  packages/duff/duff.0.5/opam
Labels: needs reporter action

#23960 Package picasso.0.4.0
  packages/absolute/absolute.0.1/opam
  packages/absolute/absolute.0.2/opam
  packages/picasso/picasso.0.4.0/opam
Labels: consider for merge

#23975 [new release] caisar, caisar-ovo, caisar-onnx, caisar-nnet, caisar-xgboost and caisar-ir (0.2)
  packages/caisar-ir/caisar-ir.0.2/opam
  packages/caisar-nnet/caisar-nnet.0.2/opam
  packages/caisar-onnx/caisar-onnx.0.2/opam
  packages/caisar-ovo/caisar-ovo.0.2/opam
  packages/caisar-xgboost/caisar-xgboost.0.2/opam
  packages/caisar/caisar.0.2/opam
Labels: consider for merge

#24007 [new release] dune (15 packages) (3.8.3)
  packages/chrome-trace/chrome-trace.3.8.3/opam
  packages/dune-action-plugin/dune-action-plugin.3.8.3/opam
  packages/dune-build-info/dune-build-info.3.8.3/opam
  packages/dune-configurator/dune-configurator.3.8.3/opam
  packages/dune-glob/dune-glob.3.8.3/opam
  packages/dune-private-libs/dune-private-libs.3.8.3/opam
  packages/dune-rpc-lwt/dune-rpc-lwt.3.8.3/opam
  packages/dune-rpc/dune-rpc.3.8.3/opam
  packages/dune-site/dune-site.3.8.3/opam
  packages/dune/dune.3.8.3/opam
  packages/dyn/dyn.3.8.3/opam
  packages/ocamlc-loc/ocamlc-loc.3.8.3/opam
  packages/ordering/ordering.3.8.3/opam
  packages/stdune/stdune.3.8.3/opam
  packages/xdg/xdg.3.8.3/opam
Labels: consider for merge

#24012 Package plotly.1.0.0
  packages/plotly/plotly.1.0.0/opam
Labels: consider for merge

#24028 alt-ergo 0.99.1 uses autoconf
  packages/alt-ergo/alt-ergo.0.99.1/opam
Labels: consider for merge
