Repository ocaml/opam-repository, pull requests merged in 2023-09, with the labels that each got.

#24343 [new release] bitwuzla-cxx (0.2.0)
  packages/bitwuzla-cxx/bitwuzla-cxx.0.2.0/opam
Labels: consider for merge

#24342 Alpine pandoc package changed name in 3.18
  packages/conf-pandoc/conf-pandoc.0.1/opam
Labels: consider for merge

#24316 DkSDKFFIOCaml_Std +Export-linux_x86_64 1.0.0~1
  packages/DkSDKFFIOCaml_Std/DkSDKFFIOCaml_Std.1.0.0~1/opam
  packages/DkSDKFFIOCaml_StdExport-linux_x86_64/DkSDKFFIOCaml_StdExport-linux_x86_64.1.0.0~1/opam
Labels: question

#24357 [new release] lintcstubs-arity (0.2.1)
  packages/lintcstubs-arity/lintcstubs-arity.0.2.1/opam
Labels: consider for merge

#24367 reason-react: add upper bound to `reason` dep
  packages/melange/melange.1.0.0/opam
  packages/reason-react/reason-react.0.11.0/opam
Labels: consider for merge

#24370 Batteries 3.7 upper bounds
  packages/acpc/acpc.1.0/opam
  packages/acpc/acpc.1.1.1/opam
  packages/acpc/acpc.1.1/opam
  packages/acpc/acpc.1.2.1/opam
  packages/acpc/acpc.1.2.2/opam
  packages/acpc/acpc.1.2.3/opam
  packages/acpc/acpc.1.2/opam
  packages/cpm/cpm.1.0.0/opam
  packages/cpm/cpm.2.0.0/opam
  packages/cpm/cpm.3.0.0/opam
  packages/daft/daft.0.0.2/opam
  packages/daft/daft.0.0.3/opam
  packages/get_line/get_line.1.0.0/opam
  packages/get_line/get_line.2.1.0/opam
  packages/get_line/get_line.2.1.1/opam
  packages/get_line/get_line.3.0.0/opam
  packages/pb-plugin/pb-plugin.1.0.0/opam
Labels: consider for merge

#24373 [new release] semver (0.2.1)
  packages/semver/semver.0.2.1/opam
Labels: consider for merge

#24400 [new release] goblint-cil (2.0.2)
  packages/goblint-cil/goblint-cil.2.0.2/opam
  packages/goblint/goblint.2.0.0/opam
  packages/goblint/goblint.2.0.1/opam
  packages/goblint/goblint.2.1.0/opam
Labels: consider for merge

#24375 conf-unwind.1 with a fix for os-family=ubuntu
  packages/conf-unwind/conf-unwind.0/opam
Labels: consider for merge

#24390 4 packages from igarnier/prbnmcn-dagger at 0.0.4
  packages/prbnmcn-dagger-gsl/prbnmcn-dagger-gsl.0.0.4/opam
  packages/prbnmcn-dagger-stats/prbnmcn-dagger-stats.0.0.4/opam
  packages/prbnmcn-dagger-test/prbnmcn-dagger-test.0.0.4/opam
  packages/prbnmcn-dagger/prbnmcn-dagger.0.0.4/opam
Labels: consider for merge

#24362 [new release] alt-ergo (4 packages) (2.5.0)
  packages/alt-ergo-lib/alt-ergo-lib.2.5.0/opam
  packages/alt-ergo-parsers/alt-ergo-parsers.2.5.0/opam
  packages/alt-ergo-plugin-ab-why3/alt-ergo-plugin-ab-why3.2.5.0/opam
  packages/alt-ergo/alt-ergo.2.5.0/opam
Labels: consider for merge

#24364 Package conf-readline.1
  packages/conf-readline/conf-readline.1/opam
Labels: consider for merge

#24406 [new release] lintcstubs (2 packages) (0.4.7)
  packages/goblint/goblint.2.0.0/files/0001-Fix-deprecated-File.exists-in-update_suite.rb.patch
  packages/goblint/goblint.2.0.0/opam
  packages/goblint/goblint.2.0.1/files/0001-Fix-deprecated-File.exists-in-update_suite.rb.patch
  packages/goblint/goblint.2.0.1/opam
  packages/goblint/goblint.2.1.0/files/0001-Fix-deprecated-File.exists-in-update_suite.rb.patch
  packages/goblint/goblint.2.1.0/opam
  packages/lintcstubs-gen/lintcstubs-gen.0.4.7/opam
  packages/lintcstubs/lintcstubs.0.4.7/opam
Labels: consider for merge

#24411 Package azure-cosmos-db.0.2.3
  packages/azure-cosmos-db/azure-cosmos-db.0.2.3/opam
Labels: consider for merge

#24378 5 packages from coq/coq at 8.18.0
  packages/coq-core/coq-core.8.18.0/opam
  packages/coq-stdlib/coq-stdlib.8.18.0/opam
  packages/coq/coq.8.18.0/opam
  packages/coqide-server/coqide-server.8.18.0/opam
  packages/coqide/coqide.8.18.0/opam
Labels: consider for merge

#24379 Patch ocaml-variants.5.1.0~rc3+tsan with ocaml/ocaml#12541
  packages/ocaml-variants/ocaml-variants.5.1.0~rc3+tsan/opam
Labels: consider for merge

#24424 Added FreeBSD depext to conf-libX11.1
  packages/conf-libX11/conf-libX11.1/opam
Labels: consider for merge

#24422 [new release] reason-react and reason-react-ppx (0.12.0)
  packages/reason-react-ppx/reason-react-ppx.0.12.0/opam
  packages/reason-react/reason-react.0.12.0/opam
Labels: consider for merge

#24446 [new release] pp (1.2.0)
  packages/pp/pp.1.2.0/opam
Labels: consider for merge

#24431 [new release] knights_tour (0.0.5)
  packages/knights_tour/knights_tour.0.0.5/opam
Labels: consider for merge

#24414 batteries-3.7.1
  packages/batteries/batteries.3.7.1/opam
Labels: consider for merge

#24472 [new release] decompress (2 packages) (1.5.3)
  packages/decompress/decompress.1.5.3/opam
  packages/rfc1951/rfc1951.1.5.3/opam
Labels: consider for merge

#24465 + camlp4 5.0
  packages/camlp4/camlp4.5.0/opam
Labels: consider for merge

#22902 Add dkml-base-compiler to ocaml.4.14.1 & ocaml.5.0.0
  packages/ocaml/ocaml.4.14.1/opam
  packages/ocaml/ocaml.5.0.0/opam
Labels: consider closing

#24470 [new release] melange-numeral (0.0.1)
  packages/melange-numeral/melange-numeral.0.0.1/opam
Labels: consider for merge

#24427 Added FreeBSD depext for emacs
  packages/conf-emacs/conf-emacs.1/opam
Labels: consider for merge

#24467 higher-bound constraint on ocaml version for mdx packages
  packages/mdx/mdx.1.11.1/opam
  packages/mdx/mdx.2.0.0/opam
  packages/mdx/mdx.2.1.0/opam
  packages/mdx/mdx.2.2.0/opam
  packages/mdx/mdx.2.2.1/opam
Labels: consider for merge

#24485 [new release] reason-react (2 packages) (0.13.0)
  packages/reason-react-ppx/reason-react-ppx.0.13.0/opam
  packages/reason-react/reason-react.0.13.0/opam
Labels: consider for merge

#24458 3 packages from mefyl/timmy at 1.0.4
  packages/timmy-jsoo/timmy-jsoo.1.0.4/opam
  packages/timmy-unix/timmy-unix.1.0.4/opam
  packages/timmy/timmy.1.0.4/opam
Labels: consider for merge

#24506 Add bounds for removed dune ctypes 0.1 extension
  packages/colibrics/colibrics.0.3.3/opam
  packages/colibrics/colibrics.0.4/opam
  packages/colibrilib/colibrilib.0.3.3/opam
  packages/colibrilib/colibrilib.0.4/opam
  packages/flint/flint.0.1.5/opam
  packages/flint/flint.0.2.3/opam
  packages/flint/flint.0.3/opam
  packages/monocypher/monocypher.0.1.0/opam
  packages/octez-alcotezt/octez-alcotezt.17.3/opam
  packages/octez-bls12-381-hash/octez-bls12-381-hash.17.3/opam
  packages/octez-bls12-381-polynomial/octez-bls12-381-polynomial.17.3/opam
  packages/octez-bls12-381-signature/octez-bls12-381-signature.17.3/opam
  packages/octez-distributed-internal/octez-distributed-internal.17.3/opam
  packages/octez-mec/octez-mec.17.3/opam
  packages/octez-polynomial/octez-polynomial.17.3/opam
  packages/tezos-hacl/tezos-hacl.15.0/opam
  packages/tezos-hacl/tezos-hacl.15.1/opam
  packages/tezos-hacl/tezos-hacl.16.0/opam
  packages/tezos-hacl/tezos-hacl.16.1/opam
  packages/tezos-hacl/tezos-hacl.17.3/opam
  packages/tezos-lwt-result-stdlib/tezos-lwt-result-stdlib.15.0/opam
  packages/tezos-lwt-result-stdlib/tezos-lwt-result-stdlib.15.1/opam
  packages/tezos-lwt-result-stdlib/tezos-lwt-result-stdlib.16.0/opam
  packages/tezos-lwt-result-stdlib/tezos-lwt-result-stdlib.16.1/opam
  packages/tezos-lwt-result-stdlib/tezos-lwt-result-stdlib.17.3/opam
  packages/tezos-stdlib/tezos-stdlib.15.0/opam
  packages/tezos-stdlib/tezos-stdlib.15.1/opam
  packages/tezos-stdlib/tezos-stdlib.16.0/opam
  packages/tezos-stdlib/tezos-stdlib.16.1/opam
  packages/tezos-stdlib/tezos-stdlib.17.3/opam
  packages/tezos-test-helpers/tezos-test-helpers.15.0/opam
  packages/tezos-test-helpers/tezos-test-helpers.15.1/opam
  packages/tezos-test-helpers/tezos-test-helpers.16.0/opam
  packages/tezos-test-helpers/tezos-test-helpers.16.1/opam
  packages/tezos-test-helpers/tezos-test-helpers.17.3/opam
  packages/tezos-wasmer/tezos-wasmer.16.0/opam
  packages/tezos-wasmer/tezos-wasmer.16.1/opam
  packages/tezos-wasmer/tezos-wasmer.17.3/opam
  packages/tezt-performance-regression/tezt-performance-regression.17.1/opam
  packages/tezt-performance-regression/tezt-performance-regression.17.2/opam
  packages/tezt-performance-regression/tezt-performance-regression.17.3/opam
Labels: consider for merge

#24493 goblint-cil build patch to detect more recent gcc
  packages/goblint-cil/goblint-cil.2.0.0/files/realGccConfigure.patch
  packages/goblint-cil/goblint-cil.2.0.0/opam
  packages/goblint-cil/goblint-cil.2.0.1/files/realGccConfigure.patch
  packages/goblint-cil/goblint-cil.2.0.1/opam
Labels: consider for merge

#24526 Updated conf-libgsasl
  packages/conf-libgsasl/conf-libgsasl.1/files/test.c
  packages/conf-libgsasl/conf-libgsasl.1/opam
Labels: consider for merge

#24423 [new release] goblint (2.2.1)
  packages/goblint/goblint.2.2.1/opam
  packages/lintcstubs/lintcstubs.0.4.7/opam
Labels: consider for merge

#24474 [new release] caisar (0.2.1)
  packages/caisar/caisar.0.2.1/opam
Labels: consider for merge

#24482 [new release] elpi (1.17.3)
  packages/elpi/elpi.1.17.3/opam
Labels: consider for merge

#24511 2 packages from darioteixeira/pgocaml at 4.4.0
  packages/macaque/macaque.0.7.2/opam
  packages/macaque/macaque.0.7.4/opam
  packages/macaque/macaque.0.8/opam
  packages/pgocaml/pgocaml.4.4.0/opam
  packages/pgocaml_ppx/pgocaml_ppx.4.4.0/opam
Labels: consider for merge

#24522 [new release] uri, uri-sexp, uri-re and uri-bench (4.4.0)
  packages/uri-bench/uri-bench.4.4.0/opam
  packages/uri-re/uri-re.4.4.0/opam
  packages/uri-sexp/uri-sexp.4.4.0/opam
  packages/uri/uri.4.4.0/opam
Labels: consider for merge

#24518 [new release] opam-check-npm-deps (2.0.0)
  packages/opam-check-npm-deps/opam-check-npm-deps.2.0.0/opam
Labels: consider for merge

#24541 [new release] carton, carton-lwt and carton-git (v0.7.0)
  packages/carton-git/carton-git.0.7.0/opam
  packages/carton-lwt/carton-lwt.0.7.0/opam
  packages/carton/carton.0.7.0/opam
Labels: consider for merge
