Repository ocaml/opam-repository, pull requests merged in 2024-03, with the labels that each got.

#25405 Package jsonschema2atd.0.0.2
  packages/jsonschema2atd/jsonschema2atd.0.0.2/opam
Labels: consider for merge

#25402 [new release] quickjs (0.1.0)
  packages/quickjs/quickjs.0.1.0/opam
Labels: consider for merge

#25453 Update ppxlib.0.32.1~5.2preview
  packages/ppxlib/ppxlib.0.32.1~5.2preview/opam
Labels: priority for next OCaml release

#25481 lablgl: Add dependency on camlp5
  packages/lablgl/lablgl.1.06/opam
  packages/lablgl/lablgl.1.07/opam
Labels: consider for merge

#25505 opam packages for OCaml 4.14.2 packages
  packages/ocaml-base-compiler/ocaml-base-compiler.4.14.2/files/ocaml-base-compiler.install
  packages/ocaml-base-compiler/ocaml-base-compiler.4.14.2/opam
  packages/ocaml-src/ocaml-src.4.14.2/files/META
  packages/ocaml-src/ocaml-src.4.14.2/opam
  packages/ocaml-system/ocaml-system.4.14.2/files/gen_ocaml_config.ml.in
  packages/ocaml-system/ocaml-system.4.14.2/opam
  packages/ocaml-variants/ocaml-variants.4.14.2+options/files/ocaml-variants.install
  packages/ocaml-variants/ocaml-variants.4.14.2+options/opam
  packages/ocaml-variants/ocaml-variants.4.14.2+trunk/opam
  packages/ocaml-variants/ocaml-variants.4.14.3+trunk/opam
  packages/ocaml/ocaml.4.14.3/opam
Labels: consider for merge

#25516 Rewrite CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: consider for merge

#25512 Add flexdll.0.35-flexdll.0.43 and winpthreads.20240209-1
  packages/flexdll/flexdll.0.35/opam
  packages/flexdll/flexdll.0.36/opam
  packages/flexdll/flexdll.0.37/opam
  packages/flexdll/flexdll.0.38/opam
  packages/flexdll/flexdll.0.39/opam
  packages/flexdll/flexdll.0.40/opam
  packages/flexdll/flexdll.0.41/opam
  packages/flexdll/flexdll.0.42/opam
  packages/flexdll/flexdll.0.43/opam
  packages/winpthreads/winpthreads.20240209-1/opam
Labels: consider for merge, priority for windows support

#25519 Package cry.1.0.3
  packages/cry/cry.1.0.3/opam
Labels: consider for merge

#25518 Package typeid.1.0.1
  packages/typeid/typeid.1.0.1/opam
Labels: consider for merge

#25484 Mark old dune releases as not compatible with windows
  packages/dune/dune.3.0.2/opam
  packages/dune/dune.3.0.3/opam
  packages/dune/dune.3.1.0/opam
  packages/dune/dune.3.1.1/opam
  packages/dune/dune.3.10.0/opam
  packages/dune/dune.3.11.0/opam
  packages/dune/dune.3.11.1/opam
  packages/dune/dune.3.12.1/opam
  packages/dune/dune.3.12.2/opam
  packages/dune/dune.3.13.0/opam
  packages/dune/dune.3.13.1/opam
  packages/dune/dune.3.14.0/opam
  packages/dune/dune.3.2.0/opam
  packages/dune/dune.3.3.0/opam
  packages/dune/dune.3.3.1/opam
  packages/dune/dune.3.4.0/opam
  packages/dune/dune.3.4.1/opam
  packages/dune/dune.3.5.0/opam
  packages/dune/dune.3.6.0/opam
  packages/dune/dune.3.6.1/opam
  packages/dune/dune.3.6.2/opam
  packages/dune/dune.3.7.0/opam
  packages/dune/dune.3.7.1/opam
  packages/dune/dune.3.8.0/opam
  packages/dune/dune.3.8.1/opam
  packages/dune/dune.3.8.2/opam
  packages/dune/dune.3.8.3/opam
  packages/dune/dune.3.9.0/opam
  packages/dune/dune.3.9.1/opam
  packages/dune/dune.3.9.2/opam
  packages/dune/dune.3.9.3/opam
Labels: consider for merge

#24678 4 packages from gitlab.com/nomadic-labs/data-encoding/-/archive/v1.0.1/data-encoding-v1.0.1.tar.gz
  packages/data-encoding/data-encoding.1.0.1/opam
  packages/json-data-encoding-browser/json-data-encoding-browser.1.0.1/opam
  packages/json-data-encoding-bson/json-data-encoding-bson.1.0.1/opam
  packages/json-data-encoding/json-data-encoding.1.0.1/opam
Labels: consider for merge

#25528 Package soupault.4.9.0
  packages/soupault/soupault.4.9.0/opam
Labels: consider for merge

#25589 Update ppxlib.0.32.1~5.2preview
  packages/ppxlib/ppxlib.0.32.1~5.2preview/opam
Labels: priority for next OCaml release

#25599 Add: omod.0.0.4
  packages/omod/omod.0.0.4/opam
Labels: consider for merge
