Repository ocaml/opam-repository, pull requests merged in 2024-10, with the labels that each got.

#26652 Package ppx_mica.0.1.0
  packages/ppx_mica/ppx_mica.0.1.0/opam
Labels: consider for merge

#26670 [new release] ppx_deriving (6.0.3)
  packages/ppx_deriving/ppx_deriving.6.0.3/opam
Labels: priority for next OCaml release

#26662 Package mazeppa.0.3.3
  packages/mazeppa/mazeppa.0.3.3/opam
Labels: needs opam-repository maintainer action

#26685 [new release] albatross (2.3.0)
  packages/albatross/albatross.2.3.0/opam
Labels: consider for merge

#26690 [new release] mirage (2 packages) (4.8.0)
  packages/mirage-runtime/mirage-runtime.4.8.0/opam
  packages/mirage/mirage.4.8.0/opam
Labels: consider for merge

#26728 [new release] rust-staticlib-gen (3 packages) (0.1.0)
  packages/dune-cargo-build/dune-cargo-build.0.1.0/opam
  packages/rust-staticlib-gen/rust-staticlib-gen.0.1.0/opam
  packages/rust-staticlib-virtual/rust-staticlib-virtual.0.1.0/opam
Labels: consider for merge

#26741 [new release] mirage (2 packages) (4.8.1)
  packages/mirage-runtime/mirage-runtime.4.8.1/opam
  packages/mirage/mirage.4.8.1/opam
Labels: consider for merge

#26682 [new release] catt (3 packages) (1.0)
  packages/catt/catt.1.0/opam
  packages/coq-catt-plugin/coq-catt-plugin.1.0/opam
Labels: consider for merge

#26746 [new release] colombe, sendmail, sendmail-lwt, sendmail-mirage and sendmail-miou-unix (0.10.0)
  packages/colombe/colombe.0.10.0/opam
  packages/sendmail-lwt/sendmail-lwt.0.10.0/opam
  packages/sendmail-miou-unix/sendmail-miou-unix.0.10.0/opam
  packages/sendmail-mirage/sendmail-mirage.0.10.0/opam
  packages/sendmail/sendmail.0.10.0/opam
Labels: consider for merge

#26753 [new release] opam-0install (0.5)
  packages/opam-0install/opam-0install.0.5/opam
Labels: consider for merge

#26758 [new release] multicore-bench (0.1.7)
  packages/multicore-bench/multicore-bench.0.1.7/opam
Labels: consider for merge

#26763 Package mazeppa.0.4.2
  packages/mazeppa/mazeppa.0.4.2/opam
Labels: consider for merge

#26762 [new release] ppx_deriving_jsonschema (0.0.3)
  packages/ppx_deriving_jsonschema/ppx_deriving_jsonschema.0.0.3/opam
Labels: consider for merge

#26726 Add Z3 4.13.2
  packages/z3/z3.4.13.2/opam
Labels: question, consider for merge

#26736 Package yosqlite.0.2
  packages/yosqlite/yosqlite.0.2/opam
Labels: needs reporter action

#26772 [new release] trs (1.0.0)
  packages/trs/trs.1.0.0/opam
Labels: consider for merge

#26730 Add climate.0.1.0
  packages/climate/climate.0.1.0/opam
Labels: consider for merge

#26761 Package ppx_minidebug.2.0.2
  packages/ppx_minidebug/ppx_minidebug.2.0.2/opam
Labels: consider for merge

#26779 Package adelfa.0.1
  packages/adelfa/adelfa.0.1/opam
Labels: consider for merge

#26789 [new release] colombe (6 packages) (0.11.0)
  packages/colombe/colombe.0.11.0/opam
  packages/received/received.0.11.0/opam
  packages/sendmail-lwt/sendmail-lwt.0.11.0/opam
  packages/sendmail-miou-unix/sendmail-miou-unix.0.11.0/opam
  packages/sendmail-mirage/sendmail-mirage.0.11.0/opam
  packages/sendmail/sendmail.0.11.0/opam
Labels: consider for merge

#26790 [new release] uspf (4 packages) (0.0.4)
  packages/uspf-lwt/uspf-lwt.0.0.4/opam
  packages/uspf-mirage/uspf-mirage.0.0.4/opam
  packages/uspf-unix/uspf-unix.0.0.4/opam
  packages/uspf/uspf.0.0.4/opam
Labels: consider for merge

#26807 Package theora.0.4.1
  packages/theora/theora.0.4.1/opam
Labels: consider for merge

#26805 Package sedlex.3.3
  packages/sedlex/sedlex.3.3/opam
Labels: consider for merge

#26806 8 packages from savonet/ocaml-ffmpeg at 1.2.1
  packages/ffmpeg-av/ffmpeg-av.1.2.1/opam
  packages/ffmpeg-avcodec/ffmpeg-avcodec.1.2.1/opam
  packages/ffmpeg-avdevice/ffmpeg-avdevice.1.2.1/opam
  packages/ffmpeg-avfilter/ffmpeg-avfilter.1.2.1/opam
  packages/ffmpeg-avutil/ffmpeg-avutil.1.2.1/opam
  packages/ffmpeg-swresample/ffmpeg-swresample.1.2.1/opam
  packages/ffmpeg-swscale/ffmpeg-swscale.1.2.1/opam
  packages/ffmpeg/ffmpeg.1.2.1/opam
Labels: question

#26817 3 packages from ocurrent/ocaml-dockerfile at 8.2.3
  packages/dockerfile-cmd/dockerfile-cmd.8.2.3/opam
  packages/dockerfile-opam/dockerfile-opam.8.2.3/opam
  packages/dockerfile/dockerfile.8.2.3/opam
Labels: consider for merge
