Repository ocaml/opam-repository, pull requests merged in 2024-07, with the labels that each got.

#26171 8 packages from ocaml/opam at 2.2.0 and opam-publish 2.3.1
  packages/opam-client/opam-client.2.2.0/opam
  packages/opam-core/opam-core.2.2.0/opam
  packages/opam-devel/opam-devel.2.2.0/opam
  packages/opam-format/opam-format.2.2.0/opam
  packages/opam-installer/opam-installer.2.2.0/opam
  packages/opam-publish/opam-publish.2.3.1/opam
  packages/opam-repository/opam-repository.2.2.0/opam
  packages/opam-solver/opam-solver.2.2.0/opam
  packages/opam-state/opam-state.2.2.0/opam
Labels: consider for merge

#22843 new file: packages/orf/orf.1.0.1/opam
  packages/orf/orf.1.0.1/opam
Labels: consider for merge

#26173 [new release] shuttle_http (2 packages) (0.12.0)
  packages/shuttle_http/shuttle_http.0.12.0/opam
  packages/shuttle_websocket/shuttle_websocket.0.12.0/opam
Labels: consider for merge

#26108 [new release] pyre-ast (0.1.10)
  packages/pyre-ast/pyre-ast.0.1.10/opam
Labels: consider for merge

#25863 conf-cuda: CUDA libraries -- configure installation path, offer install tips, validate
  packages/conf-cuda-config/conf-cuda-config.1/opam
  packages/conf-cuda/conf-cuda.1/opam
Labels: question

#26118 Release of LTest for Frama-C 29.0 (Copper)
  packages/frama-c-lannotate/frama-c-lannotate.0.2.3/opam
  packages/frama-c-luncov/frama-c-luncov.0.2.1/opam
  packages/lreplay/lreplay.0.1.1/opam
Labels: consider for merge

#26182 Package obelisk.0.7.0
  packages/obelisk/obelisk.0.7.0/opam
Labels: consider for merge

#26164 OCamlbuild.0.15.0
  packages/ocamlbuild/ocamlbuild.0.15.0/opam
Labels: priority for windows support

#26214 [new release] phylogenetics (0.3.0)
  packages/phylogenetics/phylogenetics.0.3.0/opam
Labels: consider for merge

#25936 Package imguiml.v1.90.6
  packages/imguiml/imguiml.v1.90.6/opam
Labels: consider for merge

#26178 Install `num.1.5` in findlib directory as well as stdlib
  packages/num/num.1.5-1/opam
Labels: consider for merge

#26231 DBM version 1.4
  packages/dbm/dbm.1.4/opam
Labels: consider for merge

#26230 [new release] http-mirage-client (0.0.6)
  packages/http-mirage-client/http-mirage-client.0.0.6/opam
Labels: consider for merge

#26141 Package torch.v0.17.0
  packages/torch/torch.v0.17.0/opam
Labels: question

#26253 ctypes prior to 0.4.0 doesn't support Windows
  packages/ctypes/ctypes.0.1.1/opam
  packages/ctypes/ctypes.0.2.3/opam
  packages/ctypes/ctypes.0.3.4/opam
Labels: consider for merge

#26256 [new release] docteur (3 packages) (0.0.7)
  packages/docteur-solo5/docteur-solo5.0.0.7/opam
  packages/docteur-unix/docteur-unix.0.0.7/opam
  packages/docteur/docteur.0.0.7/opam
Labels: consider for merge

#26268 Upper-bound `cudajit` for arrayjit 0.3.3
  packages/arrayjit/arrayjit.0.3.3/opam
Labels: consider for merge

#26221 camllib.1.3.3: update availability range
  packages/camllib/camllib.1.3.3/opam
Labels: consider for merge

#26257 [new release] quickjs (0.1.2)
  packages/quickjs/quickjs.0.1.2/opam
  packages/server-reason-react/server-reason-react.0.2.0/opam
Labels: consider for merge

#26265 Package cudajit.0.4.0
  packages/cudajit/cudajit.0.4.0/opam
Labels: consider for merge

#26266 [new release] beluga (1.1.2)
  packages/beluga/beluga.1.1.2/opam
Labels: consider for merge

#26267 Release of x509.1.0.0
  packages/ca-certs-nss/ca-certs-nss.3.101/opam
  packages/ca-certs-nss/ca-certs-nss.3.71.0.1/opam
  packages/ca-certs-nss/ca-certs-nss.3.74/opam
  packages/ca-certs-nss/ca-certs-nss.3.77/opam
  packages/ca-certs-nss/ca-certs-nss.3.80/opam
  packages/ca-certs-nss/ca-certs-nss.3.83/opam
  packages/ca-certs-nss/ca-certs-nss.3.86/opam
  packages/ca-certs-nss/ca-certs-nss.3.89.1/opam
  packages/ca-certs-nss/ca-certs-nss.3.92/opam
  packages/ca-certs-nss/ca-certs-nss.3.95/opam
  packages/ca-certs-nss/ca-certs-nss.3.98/opam
  packages/x509/x509.1.0.0/opam
Labels: consider for merge

#26274 [new release] spotify_ml (push)
  packages/spotify_ml/spotify_ml.push/opam
Labels: needs reporter action

#26272 processor.0.2
  packages/processor/processor.0.2/opam
Labels: consider for merge

#26271 [new release] reason (2 packages) (3.12.0)
  packages/reason/reason.3.12.0/opam
  packages/rtop/rtop.3.12.0/opam
Labels: do not merge

#26301 disable melange 4.0.0-52
  packages/melange/melange.4.0.0-52/opam
Labels: consider for merge

#26304 [new release] ppx_deriving_yojson (3.9.0)
  packages/ppx_deriving_yojson/ppx_deriving_yojson.3.9.0/opam
Labels: consider for merge
