Repository ocaml/opam-repository, pull requests merged in 2024-05, with the labels that each got.

#25788 opam packages for OCaml 5.2.0~rc1
  packages/ocaml-base-compiler/ocaml-base-compiler.5.2.0~rc1/files/ocaml-base-compiler.install
  packages/ocaml-base-compiler/ocaml-base-compiler.5.2.0~rc1/opam
  packages/ocaml-variants/ocaml-variants.5.2.0~rc1+options/files/ocaml-variants.install
  packages/ocaml-variants/ocaml-variants.5.2.0~rc1+options/opam
Labels: priority for next OCaml release

#25795 Package checked_oint.0.1.1
  packages/checked_oint/checked_oint.0.1.1/opam
Labels: consider for merge

#25808 [new release] paf (2 packages) (0.6.0)
  packages/git-mirage/git-mirage.3.13.0/opam
  packages/git-mirage/git-mirage.3.14.0/opam
  packages/git-mirage/git-mirage.3.15.0/opam
  packages/paf-cohttp/paf-cohttp.0.6.0/opam
  packages/paf/paf.0.6.0/opam
Labels: consider for merge

#25804 Add conf-libblake3 virtual package.
  packages/conf-libblake3/conf-libblake3.1.5.1/opam
Labels: consider for merge

#25811 Add conf-libmd package.
  packages/conf-libmd/conf-libmd.1.0.0/opam
Labels: consider for merge

#25865 OCaml 5.2.0 released: compiler and source packages
  packages/ocaml-base-compiler/ocaml-base-compiler.5.2.0/files/ocaml-base-compiler.install
  packages/ocaml-base-compiler/ocaml-base-compiler.5.2.0/opam
  packages/ocaml-src/ocaml-src.5.2.0/files/META
  packages/ocaml-src/ocaml-src.5.2.0/opam
  packages/ocaml-system/ocaml-system.5.2.0/files/gen_ocaml_config.ml.in
  packages/ocaml-system/ocaml-system.5.2.0/opam
  packages/ocaml-variants/ocaml-variants.5.2.0+options/files/ocaml-variants.install
  packages/ocaml-variants/ocaml-variants.5.2.0+options/opam
  packages/ocaml-variants/ocaml-variants.5.2.0+trunk/opam
  packages/ocaml-variants/ocaml-variants.5.2.1+trunk/opam
  packages/ocaml/ocaml.5.2.1/opam
Labels: priority for next OCaml release

#25796 [new release] js_of_ocaml (7 packages) (5.8.1)
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.5.8.1/opam
  packages/js_of_ocaml-lwt/js_of_ocaml-lwt.5.8.1/opam
  packages/js_of_ocaml-ppx/js_of_ocaml-ppx.5.8.1/opam
  packages/js_of_ocaml-ppx_deriving_json/js_of_ocaml-ppx_deriving_json.5.8.1/opam
  packages/js_of_ocaml-toplevel/js_of_ocaml-toplevel.5.8.1/opam
  packages/js_of_ocaml-tyxml/js_of_ocaml-tyxml.5.8.1/opam
  packages/js_of_ocaml/js_of_ocaml.5.8.1/opam
Labels: consider for merge

#25864 [new release] bam (3 packages) (0.2)
  packages/bam-ppx/bam-ppx.0.2/opam
  packages/bam/bam.0.2/opam
  packages/tezt-bam/tezt-bam.0.2/opam
Labels: consider for merge

#25866 [new release] alt-ergo (4 packages) (2.5.4)
  packages/alt-ergo-lib/alt-ergo-lib.2.5.4/opam
  packages/alt-ergo-parsers/alt-ergo-parsers.2.5.4/opam
  packages/alt-ergo-plugin-ab-why3/alt-ergo-plugin-ab-why3.2.5.4/opam
  packages/alt-ergo/alt-ergo.2.5.4/opam
Labels: consider for merge

#25885 [new-release] melange (4.0.0)
  packages/melange/melange.4.0.0-414/opam
  packages/melange/melange.4.0.0-51/opam
  packages/melange/melange.4.0.0-52/opam
Labels: priority for next OCaml release

#25902 [new release] merlin (3 packages) (5.0-502)
  packages/dot-merlin-reader/dot-merlin-reader.5.0-502/opam
  packages/merlin-lib/merlin-lib.5.0-502/opam
  packages/merlin/merlin.5.0-502/opam
Labels: consider for merge

#25900 [new release] wcwidth (1.0.1)
  packages/wcwidth/wcwidth.1.0.1/opam
Labels: consider for merge

#25903 Package speed.0.2.0
  packages/speed/speed.0.2.0/opam
Labels: consider for merge

#25895 Package dates_calc.0.0.6
  packages/dates_calc/dates_calc.0.0.6/opam
Labels: consider for merge

#25904 Package bitv.2.0
  packages/bitv/bitv.2.0/opam
Labels: consider for merge

#25911 Add ocaml-variants.5.2.0+statmemprof
  packages/ocaml-variants/ocaml-variants.5.2.0+statmemprof/files/ocaml-variants.install
  packages/ocaml-variants/ocaml-variants.5.2.0+statmemprof/opam
Labels: consider for merge

#25813 Retry release camlp5 8.03.00 for ocaml 5.2.0 compat
  packages/camlp5/camlp5.8.03.00/opam
Labels: priority for next OCaml release

#25891 8 packages from ocaml/opam at 2.1.6
  packages/opam-client/opam-client.2.1.6/opam
  packages/opam-core/opam-core.2.1.6/opam
  packages/opam-devel/opam-devel.2.1.6/opam
  packages/opam-format/opam-format.2.1.6/opam
  packages/opam-installer/opam-installer.2.1.6/opam
  packages/opam-repository/opam-repository.2.1.6/opam
  packages/opam-solver/opam-solver.2.1.6/opam
  packages/opam-state/opam-state.2.1.6/opam
Labels: consider for merge

#25927 ocaml-lsp-server.1.18.0~5.2preview: fix breakage after the merge of merlin 5.0 and removal of the merlin preview
  packages/ocaml-lsp-server/ocaml-lsp-server.1.18.0~5.2preview/opam
Labels: important

#25926 mirage/functoria: restrict to cmdliner < 1.3.0 for tests:
  packages/functoria/functoria.4.4.0/opam
  packages/functoria/functoria.4.4.1/opam
  packages/functoria/functoria.4.4.2/opam
  packages/mirage/mirage.4.4.0/opam
  packages/mirage/mirage.4.4.1/opam
  packages/mirage/mirage.4.4.2/opam
  packages/mirage/mirage.4.5.0/opam
  packages/mirage/mirage.4.5.1/opam
Labels: consider for merge

#25924 Add: cmdliner.1.3.0
  packages/cmdliner/cmdliner.1.3.0/opam
Labels: consider for merge

#25892 Update the 'out-of-date warning' after the release of opam 2.1.6
  repo
Labels: consider for merge

#25919 [new release] ipaddr (6 packages) (5.6.0)
  packages/ipaddr-cstruct/ipaddr-cstruct.5.6.0/opam
  packages/ipaddr-sexp/ipaddr-sexp.5.6.0/opam
  packages/ipaddr/ipaddr.5.6.0/opam
  packages/macaddr-cstruct/macaddr-cstruct.5.6.0/opam
  packages/macaddr-sexp/macaddr-sexp.5.6.0/opam
  packages/macaddr/macaddr.5.6.0/opam
Labels: consider for merge

#25905 [new release] multicore-bench (0.1.3)
  packages/multicore-bench/multicore-bench.0.1.3/opam
Labels: consider for merge

#25923 Package kind2.2.2.0
  packages/kind2/kind2.2.2.0/opam
Labels: consider for merge

#25894 [new release] git-kv (0.0.5)
  packages/git-kv/git-kv.0.0.5/opam
Labels: consider for merge

#25945 [new release] semv (1.0.0)
  packages/semv/semv.1.0.0/opam
Labels: consider for merge

#25910 Release camlkit v0.1.1-alpha
  packages/camlkit-base/camlkit-base.0.1.1/opam
  packages/camlkit-gui/camlkit-gui.0.1.1/opam
  packages/camlkit/camlkit.0.1.1/opam
  packages/conf-gnustep-base/conf-gnustep-base.1/opam
  packages/conf-gnustep-gui/conf-gnustep-gui.1/opam
  packages/conf-libobjc2/conf-libobjc2.1/opam
Labels: consider for merge

#25941 Package reanalyze.2.25.0
  packages/reanalyze/reanalyze.2.25.0/opam
Labels: consider for merge
