Repository ocaml/opam-repository, pull requests merged in 2024-04, with the labels that each got.

#25607 Package azure-cosmos-db.0.2.4
  packages/azure-cosmos-db/azure-cosmos-db.0.2.4/opam
Labels: consider for merge

#25598 [new release] coccinelle (1.2)
  packages/coccinelle/coccinelle.1.2/opam
Labels: consider for merge

#25596 Package lastfm.0.3.4
  packages/lastfm/lastfm.0.3.4/opam
Labels: consider for merge

#24314 [new release] argon2 (1.0.2)
  packages/argon2/argon2.1.0.2/opam
Labels: question, consider for merge

#25613 [new release] iostream (2 packages) (0.2.2)
  packages/iostream-camlzip/iostream-camlzip.0.2.2/opam
  packages/iostream/iostream.0.2.2/opam
Labels: consider for merge

#25592 Provides path to lib and include dirs for homebrew distribution.
  packages/conf-ppl/conf-ppl.1/opam
Labels: consider for merge

#25618 [new release] js_of_ocaml (7 packages) (5.7.2)
  packages/js_of_ocaml-compiler/js_of_ocaml-compiler.5.7.2/opam
  packages/js_of_ocaml-lwt/js_of_ocaml-lwt.5.7.2/opam
  packages/js_of_ocaml-ppx/js_of_ocaml-ppx.5.7.2/opam
  packages/js_of_ocaml-ppx_deriving_json/js_of_ocaml-ppx_deriving_json.5.7.2/opam
  packages/js_of_ocaml-toplevel/js_of_ocaml-toplevel.5.7.2/opam
  packages/js_of_ocaml-tyxml/js_of_ocaml-tyxml.5.7.2/opam
  packages/js_of_ocaml/js_of_ocaml.5.7.2/opam
Labels: priority for next OCaml release

#25617 [new release] miou (0.1.0)
  packages/miou/miou.0.1.0/opam
Labels: consider for merge

#25621 [new release] mimic (2 packages) (0.0.7)
  packages/gpt/gpt.1.0.0/opam
  packages/mimic-happy-eyeballs/mimic-happy-eyeballs.0.0.7/opam
  packages/mimic/mimic.0.0.7/opam
  packages/paf/paf.0.1.0/opam
  packages/paf/paf.0.2.0/opam
  packages/paf/paf.0.3.0/opam
  packages/paf/paf.0.4.0/opam
  packages/paf/paf.0.5.0/opam
Labels: consider for merge

#25606 [new release] zstd (0.4)
  packages/zstd/zstd.0.4/opam
Labels: consider for merge

#25129 Package universal-portal.0.1
  packages/universal-portal/universal-portal.0.1/opam
Labels: consider for merge

#25647 8 packages from ocaml/opam at 2.2.0~beta2
  packages/opam-client/opam-client.2.2.0~beta2/opam
  packages/opam-core/opam-core.2.2.0~beta2/opam
  packages/opam-devel/opam-devel.2.2.0~beta2/opam
  packages/opam-format/opam-format.2.2.0~beta2/opam
  packages/opam-installer/opam-installer.2.2.0~beta2/opam
  packages/opam-repository/opam-repository.2.2.0~beta2/opam
  packages/opam-solver/opam-solver.2.2.0~beta2/opam
  packages/opam-state/opam-state.2.2.0~beta2/opam
Labels: consider for merge

#25651 [new release] mirage (2 packages) (4.5.0)
  packages/mirage-runtime/mirage-runtime.4.5.0/opam
  packages/mirage/mirage.4.5.0/opam
Labels: consider for merge

#25653 Package universal-portal.0.2.0
  packages/universal-portal/universal-portal.0.2.0/opam
Labels: consider for merge

#25655 [new release] gluon (0.0.9)
  packages/gluon/gluon.0.0.9/opam
Labels: consider for merge

#25657 [new release] serde (3 packages) (0.0.2)
  packages/serde/serde.0.0.2/opam
  packages/serde_derive/serde_derive.0.0.2/opam
  packages/serde_json/serde_json.0.0.2/opam
Labels: consider for merge

#25671 [new release] progress (2 packages) (0.3.0)
  packages/progress/progress.0.3.0/opam
  packages/terminal/terminal.0.3.0/opam
Labels: consider for merge

#25669 [new release] multipart_form (4 packages) (0.6.0)
  packages/multipart_form-cohttp-lwt/multipart_form-cohttp-lwt.0.6.0/opam
  packages/multipart_form-eio/multipart_form-eio.0.6.0/opam
  packages/multipart_form-lwt/multipart_form-lwt.0.6.0/opam
  packages/multipart_form/multipart_form.0.6.0/opam
Labels: consider for merge

#25656 [new release] atacama (0.0.5)
  packages/atacama/atacama.0.0.5/opam
Labels: consider for merge

#25681 [new release] smtlib-utils (0.5)
  packages/smtlib-utils/smtlib-utils.0.5/opam
Labels: consider for merge

#25673 [new release] Four Ortac packages 0.2.0
  packages/ortac-core/ortac-core.0.2.0/opam
  packages/ortac-qcheck-stm/ortac-qcheck-stm.0.2.0/opam
  packages/ortac-runtime-qcheck-stm/ortac-runtime-qcheck-stm.0.2.0/opam
  packages/ortac-runtime/ortac-runtime.0.2.0/opam
Labels: consider for merge

#25672 Package fred.0.1.0
  packages/fred/fred.0.1.0/opam
Labels: consider for merge

#25662 [new release] server-reason-react (0.2.0)
  packages/server-reason-react/server-reason-react.0.2.0/opam
  packages/universal-portal/universal-portal.0.1/opam
  packages/universal-portal/universal-portal.0.2.0/opam
Labels: consider for merge

#25697 [new release] patricia-tree (0.9.0)
  packages/patricia-tree/patricia-tree.0.9.0/opam
Labels: needs reporter action

#25726 [new release] git-kv (0.0.4)
  packages/git-kv/git-kv.0.0.4/opam
Labels: consider for merge

#25710 [new release] colombe (4 packages) (0.8.1)
  packages/colombe/colombe.0.8.1/opam
  packages/received/received.0.8.1/opam
  packages/sendmail-lwt/sendmail-lwt.0.8.1/opam
  packages/sendmail/sendmail.0.8.1/opam
Labels: consider for merge

#25663 [new release] styled-ppx (0.56.0)
  packages/styled-ppx/styled-ppx.0.56.0/opam
Labels: consider for merge

#25749 [new release] html_of_jsx (0.0.2)
  packages/html_of_jsx/html_of_jsx.0.0.2/opam
Labels: needs reporter action

#25744 Update merlin.4.14-502~preview
  packages/dot-merlin-reader/dot-merlin-reader.4.14-502~preview/opam
  packages/merlin-lib/merlin-lib.4.14-502~preview/opam
  packages/merlin/merlin.4.14-502~preview/opam
Labels: consider for merge, priority for next OCaml release

#25762 [new release] odoc and odoc-parser (2.4.2)
  packages/odoc-parser/odoc-parser.2.4.2/opam
  packages/odoc/odoc.2.4.2/opam
Labels: consider for merge
