Repository ocaml/opam-repository, pull requests merged in 2024-11, with the labels that each got.

#26823 Older datalog versions FTBFS on newer OCaml
  packages/datalog/datalog.0.1/opam
  packages/datalog/datalog.0.2/opam
  packages/datalog/datalog.0.3.1/opam
  packages/datalog/datalog.0.3/opam
Labels: consider for merge

#26814 M4 on Cygwin
  packages/conf-m4/conf-m4.1/opam
Labels: consider for merge

#26819 Mingw support for gnutls and nettle
  packages/conf-gnutls/conf-gnutls.1/opam
  packages/conf-mingw-w64-gnutls-i686/conf-mingw-w64-gnutls-i686.1/opam
  packages/conf-mingw-w64-gnutls-x86_64/conf-mingw-w64-gnutls-x86_64.1/opam
  packages/conf-mingw-w64-nettle-i686/conf-mingw-w64-nettle-i686.1/opam
  packages/conf-mingw-w64-nettle-x86_64/conf-mingw-w64-nettle-x86_64.1/opam
Labels: consider for merge

#26816 [new release] dune (15 packages) (3.16.1)
  packages/chrome-trace/chrome-trace.3.16.1/opam
  packages/dune-action-plugin/dune-action-plugin.3.16.1/opam
  packages/dune-build-info/dune-build-info.3.16.1/opam
  packages/dune-configurator/dune-configurator.3.16.1/opam
  packages/dune-glob/dune-glob.3.16.1/opam
  packages/dune-private-libs/dune-private-libs.3.16.1/opam
  packages/dune-rpc-lwt/dune-rpc-lwt.3.16.1/opam
  packages/dune-rpc/dune-rpc.3.16.1/opam
  packages/dune-site/dune-site.3.16.1/opam
  packages/dune/dune.3.16.1/opam
  packages/dyn/dyn.3.16.1/opam
  packages/ocamlc-loc/ocamlc-loc.3.16.1/opam
  packages/ordering/ordering.3.16.1/opam
  packages/stdune/stdune.3.16.1/opam
  packages/xdg/xdg.3.16.1/opam
Labels: consider for merge, priority for next OCaml release

#26822 compiler packages for the OCaml 5.3.0~beta1
  packages/ocaml-base-compiler/ocaml-base-compiler.5.3.0~beta1/opam
  packages/ocaml-compiler/ocaml-compiler.5.3.0~beta1/opam
  packages/ocaml-variants/ocaml-variants.5.3.0~beta1+options/opam
Labels: new opam-repository maintainer question, priority for next OCaml release

#26838 [new release] postgresql (5.1.0)
  packages/conf-mingw-w64-postgresql-i686/conf-mingw-w64-postgresql-i686.1/opam
  packages/conf-mingw-w64-postgresql-x86_64/conf-mingw-w64-postgresql-x86_64.1/opam
  packages/conf-postgresql/conf-postgresql.2/opam
  packages/postgresql/postgresql.5.1.0/opam
Labels: consider for merge

#26831 Re-enable a few packages for OCaml 5.3
  packages/MlFront_Cli/MlFront_Cli.0.4.0~prerel7/opam
  packages/caisar-onnx/caisar-onnx.0.2/opam
  packages/caisar/caisar.0.1/opam
  packages/caisar/caisar.0.2.1/opam
  packages/caisar/caisar.0.2/opam
  packages/caisar/caisar.1.0/opam
  packages/caisar/caisar.2.0/opam
  packages/caisar/caisar.2.1/opam
  packages/coq-core/coq-core.8.17.0/opam
  packages/coq-core/coq-core.8.17.1/opam
  packages/coq-core/coq-core.8.18.0/opam
  packages/coq-core/coq-core.8.19.0/opam
  packages/coq-core/coq-core.8.19.1/opam
  packages/mock/mock.1.0.0/opam
  packages/mopsa/mopsa.1.0/opam
  packages/omake/omake.0.10.6/opam
  packages/prbnmcn-dagger/prbnmcn-dagger.0.0.2/opam
  packages/prbnmcn-dagger/prbnmcn-dagger.0.0.3/opam
  packages/prbnmcn-dagger/prbnmcn-dagger.0.0.4/opam
  packages/prbnmcn-dagger/prbnmcn-dagger.0.0.5/opam
  packages/why3/why3.1.6.0/opam
  packages/why3/why3.1.7.0/opam
  packages/why3/why3.1.7.1/opam
  packages/why3/why3.1.7.2/opam
  packages/yocaml/yocaml.1.0.0/opam
Labels: consider for merge

#26851 Package catala-format.0.1.0
  packages/catala-format/catala-format.0.1.0/opam
Labels: consider for merge

#26877 2 packages from ocsigen/lwt at 5.9.0
  packages/lwt/lwt.5.9.0/opam
  packages/lwt_retry/lwt_retry.5.9.0/opam
Labels: consider for merge

#26875 Fix PostgreSQL on Cygwin
  packages/conf-mingw-w64-postgresql-i686/conf-mingw-w64-postgresql-i686.1/opam
  packages/conf-mingw-w64-postgresql-x86_64/conf-mingw-w64-postgresql-x86_64.1/opam
Labels: question

#26898 [new release] containers (2 packages) (3.15)
  packages/containers-data/containers-data.3.15/opam
  packages/containers/containers.3.15/opam
Labels: question

#26886 Patch to fix async_ssl build
  packages/async_ssl/async_ssl.v0.16.0-1/opam
  packages/async_ssl/async_ssl.v0.16.1-1/opam
  packages/async_ssl/async_ssl.v0.17.0-1/opam
Labels: consider for merge

#26895 Package ppxlib_jane.v0.17.2
  packages/ppxlib_jane/ppxlib_jane.v0.17.2/opam
Labels: consider for merge, priority for next OCaml release

#26916 [new release] provider (0.0.11)
  packages/provider/provider.0.0.11/opam
Labels: consider for merge

#26927 New version of package color: 0.3.0
  packages/color/color.0.3.0/opam
Labels: question

#26950 Cohttp6 upper bounds
  packages/caldav/caldav.0.1.0/opam
  packages/caldav/caldav.0.1.1/opam
  packages/caldav/caldav.0.2.0/opam
  packages/caldav/caldav.0.2.2/opam
  packages/caldav/caldav.0.2.3/opam
  packages/graphql-cohttp/graphql-cohttp.0.9.0/opam
  packages/h1_parser/h1_parser.0.0.2/opam
  packages/picos_io_cohttp/picos_io_cohttp.0.5.0/opam
  packages/picos_io_cohttp/picos_io_cohttp.0.6.0/opam
  packages/tidy_email_mailgun/tidy_email_mailgun.0.0.1/opam
  packages/websocket-async/websocket-async.2.17/opam
Labels: consider for merge

#26946 [new release] gsl (1.25.1)
  packages/gsl/gsl.1.25.1/opam
Labels: consider for merge

#26952 [new release] utop (2.15.0)
  packages/utop/utop.2.15.0/opam
Labels: priority for next OCaml release

#26925 [new release] cohttp (14 packages) (6.0.0)
  packages/cohttp-async/cohttp-async.6.0.0/opam
  packages/cohttp-bench/cohttp-bench.6.0.0/opam
  packages/cohttp-curl-async/cohttp-curl-async.6.0.0/opam
  packages/cohttp-curl-lwt/cohttp-curl-lwt.6.0.0/opam
  packages/cohttp-curl/cohttp-curl.6.0.0/opam
  packages/cohttp-eio/cohttp-eio.6.0.0/opam
  packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.6.0.0/opam
  packages/cohttp-lwt-unix/cohttp-lwt-unix.6.0.0/opam
  packages/cohttp-lwt/cohttp-lwt.6.0.0/opam
  packages/cohttp-mirage/cohttp-mirage.6.0.0/opam
  packages/cohttp-server-lwt-unix/cohttp-server-lwt-unix.6.0.0/opam
  packages/cohttp-top/cohttp-top.6.0.0/opam
  packages/cohttp/cohttp.6.0.0/opam
  packages/http/http.6.0.0/opam
Labels: consider for merge

#26963 [new release] passage (0.1.5)
  packages/passage/passage.0.1.5/opam
Labels: consider for merge

#26989 Second beta release of OCaml 5.3.0
  packages/ocaml-base-compiler/ocaml-base-compiler.5.3.0~beta2/opam
  packages/ocaml-compiler/ocaml-compiler.5.3.0~beta2/opam
  packages/ocaml-variants/ocaml-variants.5.3.0~beta2+options/opam
Labels: priority for next OCaml release

#26980 Update js_of_ocaml upper bounds in preparation to release 6.0.0
  packages/eliom/eliom.10.4.0/opam
  packages/eliom/eliom.10.4.1/opam
  packages/eliom/eliom.11.0.0/opam
  packages/eliom/eliom.11.0.1/opam
  packages/eliom/eliom.11.1.0/opam
  packages/ezjs_blockies/ezjs_blockies.0.1.1/opam
  packages/fmlib_js/fmlib_js.0.2.0/opam
  packages/fmlib_js/fmlib_js.0.3.0/opam
  packages/fmlib_js/fmlib_js.0.3.1/opam
  packages/fmlib_js/fmlib_js.0.4.0/opam
  packages/fmlib_js/fmlib_js.0.5.0/opam
  packages/fmlib_js/fmlib_js.0.5.1/opam
  packages/fmlib_js/fmlib_js.0.5.2/opam
  packages/fmlib_js/fmlib_js.0.5.3/opam
  packages/fmlib_js/fmlib_js.0.5.4/opam
  packages/fmlib_js/fmlib_js.0.5.5/opam
  packages/fmlib_js/fmlib_js.0.5.6/opam
  packages/fmlib_js/fmlib_js.0.5.7/opam
  packages/fmlib_js/fmlib_js.0.5.8/opam
  packages/fmlib_js/fmlib_js.0.5.9/opam
  packages/graphv_webgl_impl/graphv_webgl_impl.0.1.1/opam
  packages/incr_dom/incr_dom.v0.15.1/opam
  packages/incr_dom/incr_dom.v0.16.0/opam
  packages/ocsigen-start/ocsigen-start.7.0.0/opam
  packages/ocsigen-toolkit/ocsigen-toolkit.3.3.1/opam
  packages/ocsigen-toolkit/ocsigen-toolkit.3.3.4/opam
  packages/ocsigen-toolkit/ocsigen-toolkit.4.0.0/opam
  packages/ocsigen-toolkit/ocsigen-toolkit.4.1.0/opam
  packages/ojs_base/ojs_base.0.7.0/opam
  packages/timmy-jsoo/timmy-jsoo.1.0.0/opam
  packages/timmy-jsoo/timmy-jsoo.1.0.4/opam
  packages/vg/vg.0.9.4/opam
Labels: consider for merge

#26990 Add: bytesrw.0.1.0
  packages/bytesrw/bytesrw.0.1.0/opam
Labels: consider for merge

#26972 Ocaml src updates
  packages/ocaml-src/ocaml-src.3.12.1/opam
  packages/ocaml-src/ocaml-src.4.00.0/opam
  packages/ocaml-src/ocaml-src.4.00.1/opam
  packages/ocaml-src/ocaml-src.4.01.0/opam
  packages/ocaml-src/ocaml-src.4.02.0/opam
  packages/ocaml-src/ocaml-src.4.02.1/opam
  packages/ocaml-src/ocaml-src.4.02.2/opam
  packages/ocaml-src/ocaml-src.4.02.3/opam
  packages/ocaml-src/ocaml-src.4.03.0/opam
  packages/ocaml-src/ocaml-src.4.04.0/opam
  packages/ocaml-src/ocaml-src.4.04.1/opam
  packages/ocaml-src/ocaml-src.4.04.2/opam
  packages/ocaml-src/ocaml-src.4.05.0/opam
  packages/ocaml-src/ocaml-src.4.06.0/opam
  packages/ocaml-src/ocaml-src.4.06.1/opam
  packages/ocaml-src/ocaml-src.4.07.0/opam
  packages/ocaml-src/ocaml-src.4.07.1/opam
  packages/ocaml-src/ocaml-src.4.08.0/opam
  packages/ocaml-src/ocaml-src.4.08.1/opam
  packages/ocaml-src/ocaml-src.4.09.0/opam
  packages/ocaml-src/ocaml-src.4.09.1-1/opam
  packages/ocaml-src/ocaml-src.4.09.1/opam
  packages/ocaml-src/ocaml-src.4.10.0/opam
  packages/ocaml-src/ocaml-src.4.10.1/opam
  packages/ocaml-src/ocaml-src.4.10.2/opam
  packages/ocaml-src/ocaml-src.4.11.0/opam
  packages/ocaml-src/ocaml-src.4.11.1/opam
  packages/ocaml-src/ocaml-src.4.11.2/opam
  packages/ocaml-src/ocaml-src.4.12.0/opam
  packages/ocaml-src/ocaml-src.4.12.1/opam
  packages/ocaml-src/ocaml-src.4.13.0/opam
  packages/ocaml-src/ocaml-src.4.13.1/opam
  packages/ocaml-src/ocaml-src.4.13.dev/opam
  packages/ocaml-src/ocaml-src.4.14.0/opam
  packages/ocaml-src/ocaml-src.4.14.1/opam
  packages/ocaml-src/ocaml-src.4.14.2/opam
  packages/ocaml-src/ocaml-src.4.14.dev/opam
  packages/ocaml-src/ocaml-src.5.0.0/opam
  packages/ocaml-src/ocaml-src.5.0.dev/opam
  packages/ocaml-src/ocaml-src.5.1.0/opam
  packages/ocaml-src/ocaml-src.5.1.1/opam
  packages/ocaml-src/ocaml-src.5.2.0/opam
Labels: consider for merge

#26947 add ocaml-src 5.2.1
  packages/ocaml-src/ocaml-src.5.2.1/opam
Labels: consider for merge

#26997 rml: update tarballs to opam-source-archives
  packages/rml/rml.1.08.04/opam
  packages/rml/rml.1.08.05/opam
  packages/rml/rml.1.08.06/opam
  packages/rml/rml.1.09.00/opam
  packages/rml/rml.1.09.01/opam
  packages/rml/rml.1.09.02/opam
  packages/rml/rml.1.09.03/opam
  packages/rml/rml.1.09.04/opam
  packages/rml/rml.1.09.05/opam
  packages/rml/rml.1.09.06/opam
  packages/rml/rml.1.09.07/opam
Labels: consider for merge
