Repository ocaml/opam-repository, pull requests merged in 2024-08, with the labels that each got.

#26317 [new release] dockerfile, dockerfile-opam, dockerfile-cmd (8.2.2)
  packages/dockerfile-cmd/dockerfile-cmd.8.2.2/opam
  packages/dockerfile-opam/dockerfile-opam.8.2.2/opam
  packages/dockerfile/dockerfile.8.2.2/opam
Labels: consider for merge

#26308 [new release] elpi (1.19.5)
  packages/elpi/elpi.1.19.5/opam
Labels: consider for merge

#26307 [new release] goblint-cil (2.0.4)
  packages/goblint-cil/goblint-cil.2.0.4/opam
  packages/goblint/goblint.2.2.1/opam
  packages/goblint/goblint.2.3.0/opam
Labels: question

#26320 Package ldap.2.5.1
  packages/ldap/ldap.2.5.1/opam
Labels: consider for merge

#26037 Package cvc5.1.1.3-unreleased
  packages/conf-python3-pyparsing/conf-python3-pyparsing.1/opam
  packages/conf-python3-tomli/conf-python3-tomli.1/opam
  packages/cvc5/cvc5.1.1.3~unreleased/opam
Labels: consider for merge

#26327 [new release] goblint (2.4.0)
  packages/goblint/goblint.2.4.0/opam
Labels: consider for merge

#26321 [new release] sqlite3 (5.2.0)
  packages/sqlite3/sqlite3.5.2.0/opam
Labels: consider for merge

#26314 [new release] uring-trace (2 packages) (0.1.0)
  packages/conf-liburing/conf-liburing.0.1.0/opam
  packages/uring-trace/uring-trace.0.1.0/opam
Labels: consider for merge

#26309 [new release] GT (0.5.3)
  packages/GT/GT.0.5.3/opam
Labels: consider for merge

#26330 [new release] tar (4 packages) (3.0.0)
  packages/tar-eio/tar-eio.3.0.0/opam
  packages/tar-mirage/tar-mirage.3.0.0/opam
  packages/tar-unix/tar-unix.3.0.0/opam
  packages/tar/tar.3.0.0/opam
Labels: consider for merge

#26146 Update conf-sqlite3 for mingw-w64 ports
  packages/conf-mingw-w64-sqlite3-i686/conf-mingw-w64-sqlite3-i686.1/opam
  packages/conf-mingw-w64-sqlite3-x86_64/conf-mingw-w64-sqlite3-x86_64.1/opam
  packages/conf-sqlite3/conf-sqlite3.1/opam
Labels: needs reporter action

#26074 Update bitstring sources
  packages/bitstring/bitstring.2.1.0/opam
  packages/bitstring/bitstring.2.1.1/opam
  packages/bitstring/bitstring.3.0.0/opam
  packages/bitstring/bitstring.3.1.0/opam
  packages/bitstring/bitstring.3.1.1/opam
Labels: consider for merge

#25958 [new release] lzo (0.0.3)
  packages/lzo/lzo.0.0.3/opam
Labels: needs reporter action

#26332 [new release] sail (12 packages) (0.18)
  packages/libsail/libsail.0.18/opam
  packages/sail/sail.0.18/opam
  packages/sail_c_backend/sail_c_backend.0.18/opam
  packages/sail_coq_backend/sail_coq_backend.0.18/opam
  packages/sail_doc_backend/sail_doc_backend.0.18/opam
  packages/sail_latex_backend/sail_latex_backend.0.18/opam
  packages/sail_lem_backend/sail_lem_backend.0.18/opam
  packages/sail_manifest/sail_manifest.0.18/opam
  packages/sail_ocaml_backend/sail_ocaml_backend.0.18/opam
  packages/sail_output/sail_output.0.18/opam
  packages/sail_smt_backend/sail_smt_backend.0.18/opam
  packages/sail_sv_backend/sail_sv_backend.0.18/opam
Labels: needs reporter action

#26339 Add m4 rule for macos
  packages/conf-m4/conf-m4.1/opam
Labels: do not merge

#26351 Release of esperanto 0.0.6
  packages/aarch64-esperanto/aarch64-esperanto.0.0.6/opam
  packages/esperanto-cosmopolitan/esperanto-cosmopolitan.0.0.6/opam
  packages/x86_64-esperanto/x86_64-esperanto.0.0.6/opam
Labels: consider for merge

#26323 Add -mno-outline-atomics to fix static build on Ubuntu arm64
  packages/ocaml-variants/ocaml-variants.5.0.0+options/opam
  packages/ocaml-variants/ocaml-variants.5.1.1+options/opam
  packages/ocaml-variants/ocaml-variants.5.2.0+options/opam
Labels: needs opam-repository maintainer action

#26389 [new release] miou (0.3.0)
  packages/miou/miou.0.3.0/opam
Labels: consider for merge

#25979 conf-opencc1_1: add Ubuntu-family support
  packages/conf-opencc1_1/conf-opencc1_1.1/opam
Labels: consider for merge

#25980 conf-openjdk: add Ubuntu-family support
  packages/conf-openjdk/conf-openjdk.1/opam
Labels: consider for merge

#26390 [new release] tcpip (8.2.0)
  packages/tcpip/tcpip.8.2.0/opam
Labels: consider for merge

#26395 Package forester.4.3.0
  packages/forester/forester.4.3.0/opam
Labels: consider for merge

#26388 Lambda Soup 1.1.0: HTML scraping with CSS
  packages/lambdasoup/lambdasoup.1.1.0/opam
Labels: consider for merge

#26368 [new release] corosync (0.1.0)
  packages/conf-libcorosync/conf-libcorosync.3/opam
  packages/corosync/corosync.0.1.0/opam
Labels: consider for merge

#26376 [new release] reason-react (2 packages) (0.15.0)
  packages/reason-react-ppx/reason-react-ppx.0.15.0/opam
  packages/reason-react/reason-react.0.15.0/opam
Labels: consider for merge

#26375 + mldonkey 3.2.1
  packages/mldonkey/mldonkey.3.2.1/opam
Labels: consider for merge

#26400 [new release] dream-html (2 packages) (3.6.1)
  packages/dream-html/dream-html.3.6.1/opam
  packages/pure-html/pure-html.3.6.1/opam
Labels: consider for merge

#26398 [new release] happy-eyeballs (4 packages) (1.2.0)
  packages/happy-eyeballs-lwt/happy-eyeballs-lwt.1.2.0/opam
  packages/happy-eyeballs-miou-unix/happy-eyeballs-miou-unix.1.2.0/opam
  packages/happy-eyeballs-mirage/happy-eyeballs-mirage.1.2.0/opam
  packages/happy-eyeballs/happy-eyeballs.1.2.0/opam
Labels: consider for merge

#26420 [new release] h1 (2 packages) (1.0.0)
  packages/h1-lwt-unix/h1-lwt-unix.1.0.0/opam
  packages/h1/h1.1.0.0/opam
Labels: consider for merge

#26429 [new release] dns (13 packages) (9.0.0)
  packages/dns-certify/dns-certify.9.0.0/opam
  packages/dns-cli/dns-cli.9.0.0/opam
  packages/dns-client-lwt/dns-client-lwt.9.0.0/opam
  packages/dns-client-miou-unix/dns-client-miou-unix.9.0.0/opam
  packages/dns-client-mirage/dns-client-mirage.9.0.0/opam
  packages/dns-client/dns-client.9.0.0/opam
  packages/dns-mirage/dns-mirage.9.0.0/opam
  packages/dns-resolver/dns-resolver.9.0.0/opam
  packages/dns-server/dns-server.9.0.0/opam
  packages/dns-stub/dns-stub.9.0.0/opam
  packages/dns-tsig/dns-tsig.9.0.0/opam
  packages/dns/dns.9.0.0/opam
  packages/dnssec/dnssec.9.0.0/opam
Labels: consider for merge

#26377 [new release] elpi (1.19.6)
  packages/elpi/elpi.1.19.6/opam
Labels: consider for merge

#26452 [new release] awa (2 packages) (0.4.0)
  packages/awa-mirage/awa-mirage.0.4.0/opam
  packages/awa/awa.0.4.0/opam
Labels: consider for merge
