Repository ocaml/opam-repository, pull requests merged in 2024-12, with the labels that each got.

#27005 Dream 1.0.0~alpha8: tidy Web framework
  packages/dream-httpaf/dream-httpaf.1.0.0~alpha4/opam
  packages/dream/dream.1.0.0~alpha8/opam
Labels: consider for merge, priority for next OCaml release

#27031 mark solo5 packages that use -Werror as avoid-version
  packages/solo5/solo5.0.7.0/opam
  packages/solo5/solo5.0.7.1/opam
  packages/solo5/solo5.0.7.2/opam
  packages/solo5/solo5.0.7.3/opam
  packages/solo5/solo5.0.7.4/opam
  packages/solo5/solo5.0.7.5/opam
  packages/solo5/solo5.0.8.0/opam
Labels: consider for merge

#27040 Add: jsont.0.1.1
  packages/jsont/jsont.0.1.1/opam
Labels: consider for merge

#27057 [new release] lacaml (11.1.1)
  packages/lacaml/lacaml.11.1.1/opam
Labels: question

#27076 liquidsoap-core: fix unnecessarily restrictive upper bound
  packages/liquidsoap-core/liquidsoap-core.2.3.0/opam
Labels: consider for merge

#27074 [new release] irmin (19 packages) (3.10.0)
  packages/irmin-bench/irmin-bench.3.10.0/opam
  packages/irmin-chunk/irmin-chunk.3.10.0/opam
  packages/irmin-cli/irmin-cli.3.10.0/opam
  packages/irmin-client/irmin-client.3.10.0/opam
  packages/irmin-containers/irmin-containers.3.10.0/opam
  packages/irmin-fs/irmin-fs.3.10.0/opam
  packages/irmin-git/irmin-git.3.10.0/opam
  packages/irmin-graphql/irmin-graphql.3.10.0/opam
  packages/irmin-mirage-git/irmin-mirage-git.3.10.0/opam
  packages/irmin-mirage-graphql/irmin-mirage-graphql.3.10.0/opam
  packages/irmin-mirage/irmin-mirage.3.10.0/opam
  packages/irmin-pack-tools/irmin-pack-tools.3.10.0/opam
  packages/irmin-pack/irmin-pack.3.10.0/opam
  packages/irmin-server/irmin-server.3.10.0/opam
  packages/irmin-test/irmin-test.3.10.0/opam
  packages/irmin-tezos/irmin-tezos.3.10.0/opam
  packages/irmin/irmin.3.10.0/opam
  packages/libirmin/libirmin.3.10.0/opam
  packages/ppx_irmin/ppx_irmin.3.10.0/opam
Labels: priority for next OCaml release

#27089 ezjs_d3pie is not compatible with OCaml 5.3
  packages/ezjs_d3pie/ezjs_d3pie.0.1/opam
Labels: priority for next OCaml release

#27072 Why3 1.8.0
  packages/caisar/caisar.2.1/opam
  packages/colibrics/colibrics.0.3.3/opam
  packages/colibrics/colibrics.0.4/opam
  packages/frama-c/frama-c.28.0/opam
  packages/frama-c/frama-c.28.1/opam
  packages/frama-c/frama-c.29.0/opam
  packages/frama-c/frama-c.29.0~beta/opam
  packages/frama-c/frama-c.30.0~beta/opam
  packages/why3-coq/why3-coq.1.8.0/opam
  packages/why3-ide/why3-ide.1.8.0/opam
  packages/why3/why3.1.8.0/opam
Labels: consider for merge

#27087 archetype is not compatible with OCaml 5.3
  packages/archetype/archetype.0.1.10/opam
  packages/archetype/archetype.0.1.11/opam
  packages/archetype/archetype.0.1.12/opam
  packages/archetype/archetype.0.1.13/opam
  packages/archetype/archetype.0.1.14/opam
  packages/archetype/archetype.0.1.3/opam
  packages/archetype/archetype.0.1.4/opam
  packages/archetype/archetype.0.1.5/opam
  packages/archetype/archetype.0.1.6/opam
  packages/archetype/archetype.0.1.8/opam
  packages/archetype/archetype.0.1.9/opam
  packages/archetype/archetype.1.0.0/opam
  packages/archetype/archetype.1.1.0/opam
  packages/archetype/archetype.1.1.1/opam
  packages/archetype/archetype.1.1.2/opam
  packages/archetype/archetype.1.2.0/opam
  packages/archetype/archetype.1.2.1/opam
  packages/archetype/archetype.1.2.10/opam
  packages/archetype/archetype.1.2.11/opam
  packages/archetype/archetype.1.2.12/opam
  packages/archetype/archetype.1.2.13/opam
  packages/archetype/archetype.1.2.14/opam
  packages/archetype/archetype.1.2.15/opam
  packages/archetype/archetype.1.2.16/opam
  packages/archetype/archetype.1.2.2/opam
  packages/archetype/archetype.1.2.3/opam
  packages/archetype/archetype.1.2.4/opam
  packages/archetype/archetype.1.2.5/opam
  packages/archetype/archetype.1.2.6/opam
  packages/archetype/archetype.1.2.7/opam
  packages/archetype/archetype.1.2.8/opam
  packages/archetype/archetype.1.2.9/opam
  packages/archetype/archetype.1.3.0/opam
  packages/archetype/archetype.1.3.1/opam
  packages/archetype/archetype.1.3.2/opam
  packages/archetype/archetype.1.3.3/opam
  packages/archetype/archetype.1.3.4/opam
  packages/archetype/archetype.1.3.5/opam
  packages/archetype/archetype.1.3.6/opam
  packages/archetype/archetype.1.4.0/opam
  packages/archetype/archetype.1.4.1/opam
  packages/archetype/archetype.1.4.2/opam
  packages/archetype/archetype.1.4.3/opam
  packages/archetype/archetype.1.5.0/opam
  packages/archetype/archetype.1.5.1/opam
  packages/archetype/archetype.1.5.2/opam
Labels: priority for next OCaml release

#27101 some packages forgot the 'v' in their ppx_expect bounds
  packages/camelot/camelot.1.3.0/opam
  packages/camelot/camelot.1.4.0/opam
  packages/camelot/camelot.1.4.1/opam
  packages/functoria/functoria.4.4.1/opam
  packages/lsp/lsp.1.19.0/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.19.0/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.20.0-4.14/opam
  packages/ocaml-lsp-server/ocaml-lsp-server.1.20.1-4.14/opam
  packages/salsa20/salsa20.1.0.0/opam
Labels: consider for merge

#27106 [new release] yocaml (12 packages) (2.1.0)
  packages/yocaml/yocaml.2.1.0/opam
  packages/yocaml_cmarkit/yocaml_cmarkit.2.1.0/opam
  packages/yocaml_eio/yocaml_eio.2.1.0/opam
  packages/yocaml_git/yocaml_git.2.1.0/opam
  packages/yocaml_jingoo/yocaml_jingoo.2.1.0/opam
  packages/yocaml_mustache/yocaml_mustache.2.1.0/opam
  packages/yocaml_omd/yocaml_omd.2.1.0/opam
  packages/yocaml_otoml/yocaml_otoml.2.1.0/opam
  packages/yocaml_runtime/yocaml_runtime.2.1.0/opam
  packages/yocaml_syndication/yocaml_syndication.2.1.0/opam
  packages/yocaml_unix/yocaml_unix.2.1.0/opam
  packages/yocaml_yaml/yocaml_yaml.2.1.0/opam
Labels: priority for next OCaml release

#27102 fix constraints of the form "with-test >= Y" to "with-test & >= Y"
  packages/conjury/conjury.2.0.1/opam
  packages/conjury/conjury.2.1.1/opam
  packages/conjury/conjury.2.1/opam
  packages/gobba/gobba.0.4.1/opam
  packages/lsp/lsp.1.11.3/opam
  packages/lsp/lsp.1.11.4/opam
  packages/lsp/lsp.1.11.5/opam
  packages/lsp/lsp.1.11.6/opam
  packages/lsp/lsp.1.12.0/opam
  packages/lsp/lsp.1.12.1/opam
  packages/minicaml/minicaml.0.3.3/opam
  packages/minicaml/minicaml.0.4/opam
  packages/pa_ppx/pa_ppx.0.09/opam
  packages/pratter/pratter.3.0.0/opam
  packages/tls-eio/tls-eio.1.0.0/opam
  packages/tls-eio/tls-eio.1.0.2/opam
  packages/tls-eio/tls-eio.1.0.4/opam
Labels: consider for merge

#27136 mark packages deprecated that are no longer maintained
  packages/arp-mirage/arp-mirage.1.0.0/opam
  packages/arp-mirage/arp-mirage.2.0.0/opam
  packages/arp-mirage/arp-mirage.2.1.0/opam
  packages/arp-mirage/arp-mirage.2.2.0/opam
  packages/arp-mirage/arp-mirage.2.2.1/opam
  packages/awa-lwt/awa-lwt.0.0.1/opam
  packages/awa-lwt/awa-lwt.0.0.2/opam
  packages/awa-lwt/awa-lwt.0.0.3/opam
  packages/awa-lwt/awa-lwt.0.0.4/opam
  packages/awa-lwt/awa-lwt.0.0.5/opam
  packages/awa-lwt/awa-lwt.0.1.0/opam
  packages/awa-lwt/awa-lwt.0.1.1/opam
  packages/awa-lwt/awa-lwt.0.1.2/opam
  packages/awa-lwt/awa-lwt.0.2.0/opam
  packages/conex-nocrypto/conex-nocrypto.0.10.0/opam
  packages/conex-nocrypto/conex-nocrypto.0.10.1/opam
  packages/conex-nocrypto/conex-nocrypto.0.11.0/opam
  packages/dns-async/dns-async.1.0.0/opam
  packages/dns-async/dns-async.1.0.1/opam
  packages/dns-async/dns-async.1.1.0/opam
  packages/dns-async/dns-async.1.1.1/opam
  packages/dns-async/dns-async.1.1.3/opam
  packages/dns-lwt-unix/dns-lwt-unix.1.0.0/opam
  packages/dns-lwt-unix/dns-lwt-unix.1.0.1/opam
  packages/dns-lwt-unix/dns-lwt-unix.1.1.0/opam
  packages/dns-lwt-unix/dns-lwt-unix.1.1.1/opam
  packages/dns-lwt-unix/dns-lwt-unix.1.1.3/opam
  packages/dns-lwt/dns-lwt.1.0.0/opam
  packages/dns-lwt/dns-lwt.1.0.1/opam
  packages/dns-lwt/dns-lwt.1.1.0/opam
  packages/dns-lwt/dns-lwt.1.1.1/opam
  packages/dns-lwt/dns-lwt.1.1.3/opam
  packages/hkdf/hkdf.1.0.0/opam
  packages/hkdf/hkdf.1.0.1/opam
  packages/hkdf/hkdf.1.0.2/opam
  packages/hkdf/hkdf.1.0.3/opam
  packages/hkdf/hkdf.1.0.4/opam
  packages/hkdf/hkdf.2.0.0/opam
  packages/mirage-crypto-entropy/mirage-crypto-entropy.0.6.0/opam
  packages/mirage-crypto-entropy/mirage-crypto-entropy.0.6.1/opam
  packages/mirage-crypto-entropy/mirage-crypto-entropy.0.6.2/opam
Labels: consider for merge

#27092 release pa_ppx.0.16 to support ocaml 5.3.0 syntax changes
  packages/pa_ppx/pa_ppx.0.16/opam
  packages/pa_ppx_migrate/pa_ppx_migrate.0.11/opam
  packages/pa_ppx_q_ast/pa_ppx_q_ast.0.12/opam
  packages/pa_ppx_regexp/pa_ppx_regexp.0.03/opam
Labels: consider for merge

#27134 new release: ocaml-solo5 1.0.1
  packages/ocaml-solo5-cross-aarch64/ocaml-solo5-cross-aarch64.1.0.1/opam
  packages/ocaml-solo5/ocaml-solo5.1.0.1/opam
Labels: consider for merge

#27143 rdf, ojs-base, lwt-parallel: use archives from opam-source-archives
  packages/lwt-parallel/lwt-parallel.0.1.0/opam
  packages/lwt-parallel/lwt-parallel.0.1.1/opam
  packages/lwt-parallel/lwt-parallel.0.1.2/opam
  packages/ojs-base/ojs-base.0.2.0/opam
  packages/ojs-base/ojs-base.0.3.0/opam
  packages/ojs-base/ojs-base.0.4.0/opam
  packages/ojs-base/ojs-base.0.5.0/opam
  packages/rdf/rdf.0.2/opam
  packages/rdf/rdf.0.3/opam
  packages/rdf/rdf.0.4/opam
  packages/rdf/rdf.0.5/opam
Labels: consider for merge

#27144 Package why3find.1.1.0
  packages/why3find/why3find.1.1.0/opam
Labels: consider for merge

#27161 melange is not compatible with OCaml 5.3
  packages/melange/melange.4.0.0-52/opam
  packages/melange/melange.4.0.1-52/opam
Labels: priority for next OCaml release

#27162 Package camlp4.5.3
  packages/camlp4/camlp4.5.3/opam
Labels: priority for next OCaml release

#27171 conf-perl: add OS dep for cygwin
  packages/conf-perl/conf-perl.2/opam
Labels: consider for merge

#27170 [new release] junit (3 packages) (2.1.0)
  packages/junit/junit.2.1.0/opam
  packages/junit_alcotest/junit_alcotest.2.1.0/opam
  packages/junit_ounit/junit_ounit.2.1.0/opam
Labels: needs reporter action

#27182 [new release] cachet (3 packages) (0.0.1)
  packages/cachet-lwt/cachet-lwt.0.0.1/opam
  packages/cachet-solo5/cachet-solo5.0.0.1/opam
  packages/cachet/cachet.0.0.1/opam
Labels: consider for merge
