Repository ocaml/opam-repository, pull requests merged in 2025-06, with the labels that each got.

#27997 Add: tgls.0.9.0
  packages/tgls/tgls.0.9.0/opam
Labels: consider for merge

#28003 Package opam-ci-check-lint.0.1
  packages/opam-ci-check-lint/opam-ci-check-lint.0.1/opam
Labels: consider for merge

#27999 Add conf-hg
  packages/conf-hg/conf-hg.1.0/opam
Labels: consider for merge

#28013 9 packages from mbarbin/vcs at 0.0.18
  packages/volgo-base/volgo-base.0.0.18/opam
  packages/volgo-git-backend/volgo-git-backend.0.0.18/opam
  packages/volgo-git-eio/volgo-git-eio.0.0.18/opam
  packages/volgo-git-unix/volgo-git-unix.0.0.18/opam
  packages/volgo-hg-backend/volgo-hg-backend.0.0.18/opam
  packages/volgo-hg-eio/volgo-hg-eio.0.0.18/opam
  packages/volgo-hg-unix/volgo-hg-unix.0.0.18/opam
  packages/volgo-vcs/volgo-vcs.0.0.18/opam
  packages/volgo/volgo.0.0.18/opam
Labels: consider for merge

#28004 [new release] sail (13 packages) (0.19.1)
  packages/libsail/libsail.0.19.1/opam
  packages/sail/sail.0.19.1/opam
  packages/sail_c_backend/sail_c_backend.0.19.1/opam
  packages/sail_coq_backend/sail_coq_backend.0.19.1/opam
  packages/sail_doc_backend/sail_doc_backend.0.19.1/opam
  packages/sail_latex_backend/sail_latex_backend.0.19.1/opam
  packages/sail_lean_backend/sail_lean_backend.0.19.1/opam
  packages/sail_lem_backend/sail_lem_backend.0.19.1/opam
  packages/sail_manifest/sail_manifest.0.19.1/opam
  packages/sail_ocaml_backend/sail_ocaml_backend.0.19.1/opam
  packages/sail_output/sail_output.0.19.1/opam
  packages/sail_smt_backend/sail_smt_backend.0.19.1/opam
  packages/sail_sv_backend/sail_sv_backend.0.19.1/opam
Labels: consider for merge

#28002 [new release] fast_bitvector (0.1.0.1)
  packages/fast_bitvector/fast_bitvector.0.1.0.1/opam
Labels: consider for merge

#28045 ppxlib upper bound related changes for ppx_minidebug
  packages/arrayjit/arrayjit.0.5.2/opam
  packages/neural_nets_lib/neural_nets_lib.0.5.2/opam
  packages/ppx_minidebug/ppx_minidebug.2.2.0/opam
Labels: consider for merge

#28042 release with fixes for line directives
  packages/camlp5/camlp5.8.03.05/opam
  packages/pa_ppx/pa_ppx.0.18/opam
Labels: consider for merge

#28041 [new release] git-kv (2 packages) (0.2.0)
  packages/git-kv/git-kv.0.2.0/opam
  packages/git-net/git-net.0.2.0/opam
Labels: consider for merge

#28052 [new release] ppx_deriving_yaml (2 packages) (0.4.1)
  packages/ppx_deriving_ezjsonm/ppx_deriving_ezjsonm.0.4.1/opam
  packages/ppx_deriving_yaml/ppx_deriving_yaml.0.4.1/opam
Labels: question

#28072 [new release] bstr (3 packages) (0.0.2)
  packages/bin/bin.0.0.2/opam
  packages/bstr/bstr.0.0.2/opam
  packages/slice/slice.0.0.2/opam
Labels: consider for merge

#28073 Allow ocaml-option-fp on arm64 starting with OCaml 5.4
  packages/ocaml-option-fp/ocaml-option-fp.1/opam
Labels: priority for next OCaml release

#28066 [new release] lp (0.5.0)
  packages/lp-glpk-js/lp-glpk-js.0.5.0/opam
  packages/lp-glpk/lp-glpk.0.5.0/opam
  packages/lp-gurobi/lp-gurobi.0.5.0/opam
  packages/lp-highs/lp-highs.0.5.0/opam
  packages/lp/lp.0.5.0/opam
Labels: consider for merge

#27965 [new release] ancient (0.10.0)
  packages/ancient/ancient.0.10.0/opam
Labels: consider for merge

#28053 [new release] CAISAR (4.0)
  packages/caisar/caisar.4.0/opam
Labels: consider for merge

#28099 Attempt to fix nuscr 2.0.0 cram tests
  packages/nuscr/nuscr.2.0.0/opam
Labels: consider for merge

#28094 [new release] jsonschema (0.1.0)
  packages/jsonschema/jsonschema.0.1.0/opam
Labels: consider for merge

#28106 Package stringx.0.2.0
  packages/stringx/stringx.0.2.0/opam
Labels: consider for merge

#28107 [new release] plplot (5.12.1)
  packages/plplot/plplot.5.12.1/opam
Labels: consider for merge
