Repository ocaml/opam-repository, pull requests merged in 2025-09, with the labels that each got.

#28418 [new package] ocue: 0.1.0
  packages/ocue/ocue.0.1.0/opam
Labels: needs admin action

#28416 update: chess_com_api, lichess_api, pgn_parser 1.0.1
  packages/chess_com_api/chess_com_api.1.0.1/opam
  packages/lichess_api/lichess_api.1.0.1/opam
  packages/pgn_parser/pgn_parser.1.0.1/opam
Labels: consider for merge

#28417 Package dead_code_analyzer.1.0.0
  packages/dead_code_analyzer/dead_code_analyzer.1.0.0/opam
Labels: consider for merge

#28483 OCaml 5.4.0: second beta release
  packages/ocaml-base-compiler/ocaml-base-compiler.5.4.0~beta2/opam
  packages/ocaml-compiler/ocaml-compiler.5.4.0~beta2/opam
  packages/ocaml-variants/ocaml-variants.5.4.0~beta2+options/opam
Labels: priority for next OCaml release

#28454 2 packages from kit-ty-kate/opam-build at 0.2.6
  packages/opam-build/opam-build.0.2.6/opam
  packages/opam-test/opam-test.0.2.6/opam
Labels: question, consider for merge

#28456 [new release] tinyfiledialogs (1.0)
  packages/tinyfiledialogs/tinyfiledialogs.1.0/opam
Labels: consider for merge

#28508 4 packages from gitlab.inria.fr/fpottier/menhir/-/archive/20250912/archive.tar.gz
  packages/menhir/menhir.20250912/opam
  packages/menhirCST/menhirCST.20250912/opam
  packages/menhirLib/menhirLib.20250912/opam
  packages/menhirSdk/menhirSdk.20250912/opam
Labels: consider for merge

#28520 Add an lwt_ppx upper bound for dream.1.0.0~alpha{1,2,3}
  packages/dream/dream.1.0.0~alpha1/opam
  packages/dream/dream.1.0.0~alpha2/opam
  packages/dream/dream.1.0.0~alpha3/opam
Labels: consider for merge

#28525 3 packages from ocurrent/ocaml-dockerfile at 8.3.1
  packages/dockerfile-cmd/dockerfile-cmd.8.3.1/opam
  packages/dockerfile-opam/dockerfile-opam.8.3.1/opam
  packages/dockerfile/dockerfile.8.3.1/opam
Labels: consider for merge

#28546 archiving.md: fix typos
  governance/policies/archiving.md
Labels: consider for merge

#28535 [new release] iomux (0.4)
  packages/iomux/iomux.0.4/opam
Labels: question

#28540 mark conf-gmp.1 as avoid version
  packages/conf-gmp/conf-gmp.1/opam
Labels: consider for merge

#28543 [new release] yocaml (13 packages) (2.5.0)
  packages/yocaml/yocaml.2.5.0/opam
  packages/yocaml_cmarkit/yocaml_cmarkit.2.5.0/opam
  packages/yocaml_eio/yocaml_eio.2.5.0/opam
  packages/yocaml_git/yocaml_git.2.5.0/opam
  packages/yocaml_jingoo/yocaml_jingoo.2.5.0/opam
  packages/yocaml_markdown/yocaml_markdown.2.5.0/opam
  packages/yocaml_mustache/yocaml_mustache.2.5.0/opam
  packages/yocaml_omd/yocaml_omd.2.5.0/opam
  packages/yocaml_otoml/yocaml_otoml.2.5.0/opam
  packages/yocaml_runtime/yocaml_runtime.2.5.0/opam
  packages/yocaml_syndication/yocaml_syndication.2.5.0/opam
  packages/yocaml_unix/yocaml_unix.2.5.0/opam
  packages/yocaml_yaml/yocaml_yaml.2.5.0/opam
Labels: consider for merge

#28547 [new release] fd-send-recv (2.0.3)
  packages/fd-send-recv/fd-send-recv.2.0.3/opam
Labels: consider for merge

#28539 Package proton.1.0.16
  packages/proton/proton.1.0.16/opam
Labels: consider for merge

#28537 [new release] zanuda (2.0.0)
  packages/zanuda/zanuda.2.0.0/opam
Labels: consider for merge

#28531 Package portmidi.0.4
  packages/portmidi/portmidi.0.4/opam
Labels: consider for merge

#28553 [new release] base64 (3.5.2)
  packages/base64/base64.3.5.2/opam
Labels: consider for merge

#28548 Frama c.31.0 plugins MetAcsl and Frama-Clang
  packages/frama-c-metacsl/frama-c-metacsl.0.9/opam
  packages/frama-clang/frama-clang.0.0.18/opam
Labels: consider for merge

#28564 Package catala.1.0.0~alpha
  packages/catala/catala.1.0.0~alpha/opam
Labels: question

#28569 [new release] progress (2 packages) (0.5.0)
  packages/progress/progress.0.5.0/opam
  packages/terminal/terminal.0.5.0/opam
Labels: consider for merge

#28565 Package monolith.20250922
  packages/monolith/monolith.20250922/opam
Labels: consider for merge

#28598 Add a Windows MSys2 MinGW workflow
  .github/workflows/windows.yml
Labels: github_actions

#28571 [new release] yocaml (13 packages) (2.6.0)
  packages/yocaml/yocaml.2.6.0/opam
  packages/yocaml_cmarkit/yocaml_cmarkit.2.6.0/opam
  packages/yocaml_eio/yocaml_eio.2.6.0/opam
  packages/yocaml_git/yocaml_git.2.6.0/opam
  packages/yocaml_jingoo/yocaml_jingoo.2.6.0/opam
  packages/yocaml_markdown/yocaml_markdown.2.6.0/opam
  packages/yocaml_mustache/yocaml_mustache.2.6.0/opam
  packages/yocaml_omd/yocaml_omd.2.6.0/opam
  packages/yocaml_otoml/yocaml_otoml.2.6.0/opam
  packages/yocaml_runtime/yocaml_runtime.2.6.0/opam
  packages/yocaml_syndication/yocaml_syndication.2.6.0/opam
  packages/yocaml_unix/yocaml_unix.2.6.0/opam
  packages/yocaml_yaml/yocaml_yaml.2.6.0/opam
Labels: consider for merge

#28606 Hopefully last round of cmdliner.2.0.0 constraints
  packages/alcotest/alcotest.1.7.0/opam
  packages/alcotest/alcotest.1.8.0/opam
  packages/alcotest/alcotest.1.9.0/opam
  packages/forester/forester.2.3/opam
  packages/forester/forester.2.4.1/opam
  packages/forester/forester.2.4/opam
  packages/forester/forester.2.5.1/opam
  packages/forester/forester.2.5/opam
  packages/forester/forester.3.0.0/opam
  packages/forester/forester.3.1.0/opam
  packages/forester/forester.4.0.0/opam
  packages/forester/forester.4.0.1/opam
  packages/forester/forester.4.1.0/opam
  packages/forester/forester.4.2.0/opam
  packages/forester/forester.4.3.0/opam
  packages/forester/forester.4.3.1/opam
  packages/mustache-cli/mustache-cli.3.3.0/opam
  packages/omigrate/omigrate.0.1.0/opam
  packages/omigrate/omigrate.0.1.1/opam
  packages/opam-compiler/opam-compiler.0.2.0/opam
  packages/opam-compiler/opam-compiler.0.2.1/opam
Labels: consider for merge

#28607 Add cmdliner constraint on mirage-runtime.4.0.0
  packages/mirage-runtime/mirage-runtime.4.0.0/opam
Labels: consider for merge

#28614 GHA: Handle symlinks on MSys2
  .github/workflows/windows.yml
Labels: consider for merge, github_actions

#28613 Make opam library packages require a stable version of patch
  packages/opam-core/opam-core.2.4.0/opam
  packages/opam-core/opam-core.2.4.0~alpha2/opam
  packages/opam-core/opam-core.2.4.0~beta1/opam
  packages/opam-core/opam-core.2.4.0~rc1/opam
  packages/opam-core/opam-core.2.4.1/opam
  packages/opam-repository/opam-repository.2.4.0/opam
  packages/opam-repository/opam-repository.2.4.0~alpha2/opam
  packages/opam-repository/opam-repository.2.4.0~beta1/opam
  packages/opam-repository/opam-repository.2.4.0~rc1/opam
  packages/opam-repository/opam-repository.2.4.1/opam
Labels: consider for merge

#28622 OCaml 5.4.0: first release candidate
  packages/ocaml-base-compiler/ocaml-base-compiler.5.4.0~rc1/opam
  packages/ocaml-compiler/ocaml-compiler.5.4.0~rc1/opam
  packages/ocaml-variants/ocaml-variants.5.4.0~rc1+options/opam
Labels: consider for merge
