Repository ocaml/opam-repository, pull requests merged in 2025-02, with the labels that each got.

#27268 UPDATE pds and hll
  packages/hll/hll.4.3/opam
  packages/pds/pds.5.42/opam
Labels: needs reporter action

#27334 [new release] benchmark (1.7)
  packages/benchmark/benchmark.1.7/opam
Labels: consider for merge

#27364 [new release] arg-complete (0.2.1)
  packages/arg-complete/arg-complete.0.2.1/opam
Labels: consider for merge

#27357 [new release] ansifmt (0.2.0)
  packages/ansifmt/ansifmt.0.2.0/opam
Labels: consider for merge

#27337 Package srt.0.3.3
  packages/srt/srt.0.3.3/opam
Labels: consider for merge

#27367 Topiary v0.6.0
  packages/topiary/topiary.0.6.0/opam
Labels: consider for merge

#27389 [new release] tls (6 packages) (2.0.0)
  packages/capnp-rpc-unix/capnp-rpc-unix.2.0/opam
  packages/tls-async/tls-async.2.0.0/opam
  packages/tls-eio/tls-eio.2.0.0/opam
  packages/tls-lwt/tls-lwt.2.0.0/opam
  packages/tls-miou-unix/tls-miou-unix.2.0.0/opam
  packages/tls-mirage/tls-mirage.2.0.0/opam
  packages/tls/tls.2.0.0/opam
Labels: consider for merge

#27426 Add missing field to ocaml.5.2.1 and ocaml.5.2.2
  packages/ocaml/ocaml.5.2.1/opam
  packages/ocaml/ocaml.5.2.2/opam
Labels: bug, priority for windows support, important

#27421 [new release] albatross (2.4.1)
  packages/albatross/albatross.2.4.1/opam
Labels: consider for merge

#27424 [new release] charrua (4 packages) (2.0.0)
  packages/charrua-client/charrua-client.2.0.0/opam
  packages/charrua-server/charrua-server.2.0.0/opam
  packages/charrua-unix/charrua-unix.2.0.0/opam
  packages/charrua/charrua.2.0.0/opam
Labels: consider for merge

#27423 logs-syslog is not compatible with tcpip >= 9.0.0
  packages/logs-syslog/logs-syslog.0.3.1/opam
  packages/logs-syslog/logs-syslog.0.3.2/opam
  packages/logs-syslog/logs-syslog.0.4.0/opam
  packages/logs-syslog/logs-syslog.0.4.1/opam
Labels: consider for merge

#27375 vlt.0.2 added
  packages/vlt/vlt.0.2.4/opam
Labels: consider for merge

#27441 ppx_inline_test_nobase: decrease lower bound on sexplib
  packages/ppx_inline_test_nobase/ppx_inline_test_nobase.v0.17.0/opam
Labels: consider for merge

#27467 [new release] paf (2 packages) (0.8.0)
  packages/git-paf/git-paf.3.10.0/opam
  packages/git-paf/git-paf.3.10.1/opam
  packages/git-paf/git-paf.3.11.0/opam
  packages/git-paf/git-paf.3.12.0/opam
  packages/git-paf/git-paf.3.13.0/opam
  packages/git-paf/git-paf.3.14.0/opam
  packages/git-paf/git-paf.3.15.0/opam
  packages/git-paf/git-paf.3.16.0/opam
  packages/git-paf/git-paf.3.16.1/opam
  packages/git-paf/git-paf.3.17.0/opam
  packages/git-paf/git-paf.3.5.0/opam
  packages/git-paf/git-paf.3.6.0/opam
  packages/http-mirage-client/http-mirage-client.0.0.1/opam
  packages/http-mirage-client/http-mirage-client.0.0.2/opam
  packages/http-mirage-client/http-mirage-client.0.0.3/opam
  packages/http-mirage-client/http-mirage-client.0.0.4/opam
  packages/http-mirage-client/http-mirage-client.0.0.5/opam
  packages/http-mirage-client/http-mirage-client.0.0.7/opam
  packages/http-mirage-client/http-mirage-client.0.0.8/opam
  packages/letsencrypt-mirage/letsencrypt-mirage.0.5.0/opam
  packages/letsencrypt-mirage/letsencrypt-mirage.0.5.1/opam
  packages/letsencrypt-mirage/letsencrypt-mirage.1.0.0/opam
  packages/paf-cohttp/paf-cohttp.0.8.0/opam
  packages/paf/paf.0.8.0/opam
Labels: consider for merge

#27457 [new release] binsec (0.10.0)
  packages/binsec/binsec.0.10.0/opam
Labels: consider for merge

#27381 add some conf packages
  packages/conf-lld/conf-lld.1/opam
  packages/conf-rust-llvm/conf-rust-llvm.1/opam
  packages/conf-rust-wasm/conf-rust-wasm.1/opam
Labels: consider for merge

#27455 release ocamlbuild 0.16.1
  packages/ocamlbuild/ocamlbuild.0.16.1/opam
Labels: needs opam-repository maintainer action

#27489 Disable runtest for bytestring on 5.2.0+
  packages/bytestring/bytestring.0.0.8/opam
Labels: consider for merge

#27469 [new release] git (4 packages) (3.18.0)
  packages/git-mirage/git-mirage.3.18.0/opam
  packages/git-paf/git-paf.3.18.0/opam
  packages/git-unix/git-unix.3.18.0/opam
  packages/git/git.3.18.0/opam
Labels: consider for merge
