Repository ocaml/opam-repository, pull requests merged in 2025-01, with the labels that each got.

#27201 frama-c < 30.0 didn't support OCaml 5.3
  packages/frama-c/frama-c.11.0/opam
  packages/frama-c/frama-c.12.1/opam
  packages/frama-c/frama-c.13.1/opam
  packages/frama-c/frama-c.14.0/opam
  packages/frama-c/frama-c.15.0/opam
  packages/frama-c/frama-c.19.1/opam
  packages/frama-c/frama-c.20.0/opam
  packages/frama-c/frama-c.21.0/opam
  packages/frama-c/frama-c.21.1/opam
  packages/frama-c/frama-c.22.0/opam
  packages/frama-c/frama-c.24.0/opam
  packages/frama-c/frama-c.25.0/opam
  packages/frama-c/frama-c.25.0~beta/opam
  packages/frama-c/frama-c.26.0/opam
  packages/frama-c/frama-c.26.0~beta/opam
  packages/frama-c/frama-c.26.1/opam
  packages/frama-c/frama-c.27.0/opam
  packages/frama-c/frama-c.27.0~beta/opam
  packages/frama-c/frama-c.27.1/opam
  packages/frama-c/frama-c.28.0~beta/opam
Labels: priority for next OCaml release

#27200 miou < 0.2.0 didn't support OCaml 5.3
  packages/miou/miou.0.0.1~beta1/opam
  packages/miou/miou.0.0.1~beta2/opam
  packages/miou/miou.0.1.0/opam
Labels: priority for next OCaml release

#27199 riot is not compatible with OCaml 5.3
  packages/riot/riot.0.0.2/opam
  packages/riot/riot.0.0.3/opam
  packages/riot/riot.0.0.4/opam
  packages/riot/riot.0.0.5/opam
  packages/riot/riot.0.0.7/opam
  packages/riot/riot.0.0.8/opam
  packages/riot/riot.0.0.9/opam
Labels: priority for next OCaml release

#27197 2 packages from OCamlPro/ocp-index at 1.3.7
  packages/ocp-browser/ocp-browser.1.3.7/opam
  packages/ocp-index/ocp-index.1.3.7/opam
Labels: consider for merge, priority for next OCaml release

#27231 release of OCaml 5.3.0
  packages/ocaml-base-compiler/ocaml-base-compiler.5.3.0/opam
  packages/ocaml-compiler/ocaml-compiler.5.3.0/opam
  packages/ocaml-manual/ocaml-manual.5.3.0/opam
  packages/ocaml-src/ocaml-src.5.3.0/opam
  packages/ocaml-system/ocaml-system.5.3.0/opam
  packages/ocaml-variants/ocaml-variants.5.3.0+options/opam
  packages/ocaml-variants/ocaml-variants.5.3.1+trunk/opam
  packages/ocaml/ocaml.5.3.1/opam
Labels: priority for next OCaml release

#27213 mark io-page-unix as deprecated (part of io-page)
  packages/io-page-unix/io-page-unix.0.1.0/opam
  packages/io-page-unix/io-page-unix.0.9.9/opam
  packages/io-page-unix/io-page-unix.2.0.0/opam
  packages/io-page-unix/io-page-unix.2.0.1/opam
  packages/io-page-unix/io-page-unix.2.1.0/opam
  packages/io-page-unix/io-page-unix.2.2.0/opam
  packages/io-page-unix/io-page-unix.2.3.0/opam
Labels: consider for merge

#27215 charrua-client-{lwt,mirage}: deprecate
  packages/charrua-client-lwt/charrua-client-lwt.0.10/opam
  packages/charrua-client-lwt/charrua-client-lwt.0.11.0/opam
  packages/charrua-client-lwt/charrua-client-lwt.0.11.1/opam
  packages/charrua-client-lwt/charrua-client-lwt.0.11.2/opam
  packages/charrua-client-lwt/charrua-client-lwt.0.12.0/opam
  packages/charrua-client-lwt/charrua-client-lwt.0.9/opam
  packages/charrua-client-lwt/charrua-client-lwt.1.0.0/opam
  packages/charrua-client-lwt/charrua-client-lwt.1.1.0/opam
  packages/charrua-client-lwt/charrua-client-lwt.1.2.0/opam
  packages/charrua-client-lwt/charrua-client-lwt.1.2.1/opam
  packages/charrua-client-lwt/charrua-client-lwt.1.2.2/opam
  packages/charrua-client-mirage/charrua-client-mirage.0.10/opam
  packages/charrua-client-mirage/charrua-client-mirage.0.11.0/opam
  packages/charrua-client-mirage/charrua-client-mirage.0.11.1/opam
  packages/charrua-client-mirage/charrua-client-mirage.0.11.2/opam
  packages/charrua-client-mirage/charrua-client-mirage.0.12.0/opam
  packages/charrua-client-mirage/charrua-client-mirage.0.9/opam
  packages/charrua-client-mirage/charrua-client-mirage.1.0.0/opam
  packages/charrua-client-mirage/charrua-client-mirage.1.1.0/opam
  packages/charrua-client-mirage/charrua-client-mirage.1.2.0/opam
  packages/charrua-client-mirage/charrua-client-mirage.1.2.1/opam
  packages/charrua-client-mirage/charrua-client-mirage.1.2.2/opam
Labels: consider for merge

#27223 git-cohttp/git-http/git-cohttp-unix/git-cohttp-mirage: deprecate
  packages/git-cohttp-mirage/git-cohttp-mirage.3.0.0/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.1.0/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.1.1/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.2.0/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.0/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.1/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.2/opam
  packages/git-cohttp-mirage/git-cohttp-mirage.3.3.3/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.0.0/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.1.0/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.1.1/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.2.0/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.3.0/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.3.1/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.3.2/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.3.3/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.4.0/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.5.0/opam
  packages/git-cohttp-unix/git-cohttp-unix.3.6.0/opam
  packages/git-cohttp/git-cohttp.3.0.0/opam
  packages/git-cohttp/git-cohttp.3.1.0/opam
  packages/git-cohttp/git-cohttp.3.1.1/opam
  packages/git-cohttp/git-cohttp.3.2.0/opam
  packages/git-cohttp/git-cohttp.3.3.0/opam
  packages/git-cohttp/git-cohttp.3.3.1/opam
  packages/git-cohttp/git-cohttp.3.3.2/opam
  packages/git-cohttp/git-cohttp.3.3.3/opam
  packages/git-cohttp/git-cohttp.3.4.0/opam
  packages/git-cohttp/git-cohttp.3.5.0/opam
  packages/git-cohttp/git-cohttp.3.6.0/opam
  packages/git-http/git-http.1.10.0/opam
  packages/git-http/git-http.1.11.0/opam
  packages/git-http/git-http.1.11.2/opam
  packages/git-http/git-http.1.11.4/opam
  packages/git-http/git-http.2.0.0/opam
  packages/git-http/git-http.2.1.0/opam
  packages/git-http/git-http.2.1.1/opam
  packages/git-http/git-http.2.1.2/opam
  packages/git-http/git-http.2.1.3/opam
Labels: consider for merge

#27226 paf-le: deprecate. this is no longer part of the upstream paf repository
  packages/paf-le/paf-le.0.0.4/opam
  packages/paf-le/paf-le.0.0.5/opam
  packages/paf-le/paf-le.0.0.6/opam
  packages/paf-le/paf-le.0.0.7/opam
  packages/paf-le/paf-le.0.0.8-1/opam
  packages/paf-le/paf-le.0.0.8/opam
  packages/paf-le/paf-le.0.0.9/opam
  packages/paf-le/paf-le.0.1.0/opam
  packages/paf-le/paf-le.0.2.0/opam
  packages/paf-le/paf-le.0.3.0/opam
  packages/paf-le/paf-le.0.4.0/opam
Labels: consider for merge

#27210 [new release] ansifmt (0.1.3)
  packages/ansifmt/ansifmt.0.1.3/opam
Labels: consider for merge

#27208 result < 1.5: mark as available only with ocaml < 4.08
  packages/result/result.1.0/opam
  packages/result/result.1.1/opam
  packages/result/result.1.2/opam
  packages/result/result.1.3/opam
  packages/result/result.1.4/opam
Labels: consider for merge

#27256 Mark all jbuilder packages as depracted
  packages/jbuilder/jbuilder.1.0+beta1/opam
  packages/jbuilder/jbuilder.1.0+beta10/opam
  packages/jbuilder/jbuilder.1.0+beta11/opam
  packages/jbuilder/jbuilder.1.0+beta12/opam
  packages/jbuilder/jbuilder.1.0+beta13/opam
  packages/jbuilder/jbuilder.1.0+beta14/opam
  packages/jbuilder/jbuilder.1.0+beta15/opam
  packages/jbuilder/jbuilder.1.0+beta16/opam
  packages/jbuilder/jbuilder.1.0+beta17/opam
  packages/jbuilder/jbuilder.1.0+beta18.1/opam
  packages/jbuilder/jbuilder.1.0+beta18/opam
  packages/jbuilder/jbuilder.1.0+beta19.1/opam
  packages/jbuilder/jbuilder.1.0+beta19/opam
  packages/jbuilder/jbuilder.1.0+beta2/opam
  packages/jbuilder/jbuilder.1.0+beta20.1/opam
  packages/jbuilder/jbuilder.1.0+beta20.2/opam
  packages/jbuilder/jbuilder.1.0+beta20/opam
  packages/jbuilder/jbuilder.1.0+beta3/opam
  packages/jbuilder/jbuilder.1.0+beta4/opam
  packages/jbuilder/jbuilder.1.0+beta5/opam
  packages/jbuilder/jbuilder.1.0+beta6/opam
  packages/jbuilder/jbuilder.1.0+beta7/opam
  packages/jbuilder/jbuilder.1.0+beta8/opam
  packages/jbuilder/jbuilder.1.0+beta9/opam
  packages/jbuilder/jbuilder.transition/opam
Labels: consider for merge

#27246 [new release] linol (3 packages) (0.8)
  packages/linol-eio/linol-eio.0.8/opam
  packages/linol-lwt/linol-lwt.0.8/opam
  packages/linol/linol.0.8/opam
Labels: consider for merge

#27255 [new release] miou (0.3.1)
  packages/miou/miou.0.3.1/opam
Labels: consider for merge

#27269 Package camlgpc.1.1
  packages/camlgpc/camlgpc.1.1/opam
Labels: consider for merge

#27202 Try fixing dream lower bound breakage
  packages/dream-httpaf/dream-httpaf.1.0.0~alpha4/opam
Labels: needs opam-repository maintainer action

#26917 pkg-config: attempt to mitigate issue on github runners
  packages/conf-pkg-config/conf-pkg-config.4/opam
Labels: consider for merge

#27275 Add x-maintenance-intent field for agrep, camlidl, camlp-streams, camlzip, cryptokit, dbm, graphics, num, mpi, pringo, zarith
  packages/agrep/agrep.1.0/opam
  packages/camlidl/camlidl.1.12/opam
  packages/camlp-streams/camlp-streams.5.0.1/opam
  packages/camlzip/camlzip.1.13/opam
  packages/cryptokit/cryptokit.1.20/opam
  packages/dbm/dbm.1.4/opam
  packages/graphics/graphics.5.1.2/opam
  packages/mpi/mpi.1.06/opam
  packages/num/num.1.5-1/opam
  packages/pringo/pringo.1.4/opam
  packages/zarith/zarith.1.14/opam
Labels: consider for merge

#27283 Mark Why3 + Stackify as incompatible with OCaml < 4.12.
  packages/why3/why3.1.7.0/opam
  packages/why3/why3.1.7.1/opam
  packages/why3/why3.1.7.2/opam
  packages/why3/why3.1.8.0/opam
Labels: consider for merge

#27287 Prepare release carton.1.0.0 (add some bouds with incompatible packages
  packages/docteur-solo5/docteur-solo5.0.0.2/opam
  packages/docteur-solo5/docteur-solo5.0.0.3/opam
  packages/docteur-solo5/docteur-solo5.0.0.4/opam
  packages/docteur-solo5/docteur-solo5.0.0.5/opam
  packages/docteur-solo5/docteur-solo5.0.0.6/opam
  packages/docteur-solo5/docteur-solo5.0.0.7/opam
  packages/docteur-unix/docteur-unix.0.0.2/opam
  packages/docteur-unix/docteur-unix.0.0.3/opam
  packages/docteur-unix/docteur-unix.0.0.4/opam
  packages/docteur-unix/docteur-unix.0.0.5/opam
  packages/docteur-unix/docteur-unix.0.0.6/opam
  packages/docteur-unix/docteur-unix.0.0.7/opam
  packages/docteur/docteur.0.0.1/opam
  packages/docteur/docteur.0.0.2/opam
  packages/docteur/docteur.0.0.3/opam
  packages/docteur/docteur.0.0.4/opam
  packages/docteur/docteur.0.0.5/opam
  packages/docteur/docteur.0.0.6/opam
  packages/docteur/docteur.0.0.7/opam
  packages/git-kv/git-kv.0.0.1/opam
  packages/git-kv/git-kv.0.0.2/opam
  packages/git-kv/git-kv.0.0.3/opam
  packages/git-kv/git-kv.0.0.4/opam
  packages/git-kv/git-kv.0.0.5/opam
  packages/git-kv/git-kv.0.1.0/opam
  packages/git-kv/git-kv.0.1.1/opam
  packages/git-kv/git-kv.0.1.2/opam
  packages/git-unix/git-unix.3.16.1/opam
  packages/git-unix/git-unix.3.17.0/opam
  packages/git/git.3.10.0/opam
  packages/git/git.3.10.1/opam
  packages/git/git.3.11.0/opam
  packages/git/git.3.12.0/opam
  packages/git/git.3.13.0/opam
  packages/git/git.3.14.0/opam
  packages/git/git.3.15.0/opam
  packages/git/git.3.16.0/opam
  packages/git/git.3.16.1/opam
  packages/git/git.3.17.0/opam
  packages/git/git.3.2.0/opam
  packages/git/git.3.4.0/opam
  packages/git/git.3.5.0/opam
  packages/git/git.3.6.0/opam
  packages/git/git.3.7.0/opam
  packages/git/git.3.8.0/opam
  packages/git/git.3.9.0/opam
  packages/git/git.3.9.1/opam
Labels: consider for merge

#27227 Flag every versions of the ocaml package that haven't been released yet with avoid-version
  packages/ocaml/ocaml.4.02.4/opam
  packages/ocaml/ocaml.4.03.1/opam
  packages/ocaml/ocaml.4.04.3/opam
  packages/ocaml/ocaml.4.05.1/opam
  packages/ocaml/ocaml.4.06.2/opam
  packages/ocaml/ocaml.4.07.2/opam
  packages/ocaml/ocaml.4.08.2/opam
  packages/ocaml/ocaml.4.09.2/opam
  packages/ocaml/ocaml.4.10.3/opam
  packages/ocaml/ocaml.4.11.3/opam
  packages/ocaml/ocaml.4.12.2/opam
  packages/ocaml/ocaml.4.13.2/opam
  packages/ocaml/ocaml.4.14.3/opam
  packages/ocaml/ocaml.5.0.1/opam
  packages/ocaml/ocaml.5.1.2/opam
  packages/ocaml/ocaml.5.2.2/opam
  packages/ocaml/ocaml.5.3.1/opam
  packages/ocaml/ocaml.5.4.0/opam
Labels: important

#27299 Package ip2proxy.3.0.0
  packages/ip2proxy/ip2proxy.3.0.0/opam
Labels: consider for merge

#27266 Package letters.0.4.0
  packages/letters/letters.0.4.0/opam
Labels: needs reporter action

#27263 2 packages from lexifi/landmarks at 1.5
  packages/landmarks-ppx/landmarks-ppx.1.5/opam
  packages/landmarks/landmarks.1.5/opam
Labels: needs reporter action

#27291 Package mem_usage.0.1.2
  packages/conf-sysinfo/conf-sysinfo.1/opam
  packages/mem_usage/mem_usage.0.1.2/opam
Labels: needs opam-repository maintainer action

#27262 [new release] carton (4 packages) (1.0.0)
  packages/carton-git-lwt/carton-git-lwt.1.0.0/opam
  packages/carton-lwt/carton-lwt.1.0.0/opam
  packages/carton-miou-unix/carton-miou-unix.1.0.0/opam
  packages/carton/carton.1.0.0/opam
Labels: needs reporter action

#27239 utop 2.15.0: switch to the archive with the substituted version number
  packages/utop/utop.2.15.0-1/opam
Labels: consider for merge

#27220 add Tezt 4.2.0
  packages/tezt/tezt.4.2.0/opam
Labels: consider for merge

#27328 directories.0.6
  packages/bogue/bogue.20231209/opam
  packages/catapult-sqlite/catapult-sqlite.0.1.1/opam
  packages/catapult-sqlite/catapult-sqlite.0.1/opam
  packages/catapult-sqlite/catapult-sqlite.0.2/opam
  packages/ccbg/ccbg.0.1/opam
  packages/directories/directories.0.6/opam
  packages/drom_lib/drom_lib.0.2.0/opam
  packages/drom_lib/drom_lib.0.3.0/opam
  packages/drom_lib/drom_lib.0.6.0/opam
  packages/drom_lib/drom_lib.0.6.1/opam
  packages/drom_lib/drom_lib.0.8.0/opam
  packages/gotd/gotd.0.1/opam
  packages/sun/sun.0.1/opam
Labels: consider for merge
