Repository ocaml/opam-repository, pull requests merged in 2025-03, with the labels that each got.

#27178 Prepare for LLVM 18, link to local repo for scripts and patches
  packages/conf-llvm-shared/conf-llvm-shared.18/opam
  packages/conf-llvm-static/conf-llvm-static.18/opam
  packages/llvm/llvm.18-shared/opam
  packages/llvm/llvm.18-static/opam
Labels: consider for merge

#27578 Raylib and Raygui are not compatible with patch 3.0
  packages/raygui/raygui.1.3.1/opam
  packages/raygui/raygui.1.4.0/opam
  packages/raylib/raylib.1.3.1/opam
  packages/raylib/raylib.1.4.0/opam
Labels: consider for merge

#27458 [new release] gettext (3 packages) (0.5.0)
  packages/gettext-camomile/gettext-camomile.0.5.0/opam
  packages/gettext-stub/gettext-stub.0.5.0/opam
  packages/gettext/gettext.0.5.0/opam
Labels: needs reporter action

#27577 Package patch.3.0.0~alpha1
  packages/patch/patch.3.0.0~alpha1/opam
Labels: consider for merge

#27581 [new release] ez_dune_describe (0.1)
  packages/ez_dune_describe/ez_dune_describe.0.1/opam
Labels: consider for merge

#27590 [new release] obelisk (0.8.0)
  packages/obelisk/obelisk.0.8.0/opam
Labels: consider for merge

#27599 Add: uutf.1.0.4
  packages/uutf/uutf.1.0.4/opam
Labels: consider for merge

#27601 [new release] mrmime (0.7.0)
  packages/mrmime/mrmime.0.7.0/opam
Labels: consider for merge

#27600 Add: uuidm.0.9.10
  packages/uuidm/uuidm.0.9.10/opam
Labels: consider for merge

#27603 Add: webbrowser.0.6.2
  packages/webbrowser/webbrowser.0.6.2/opam
Labels: consider for merge

#27604 Add: topkg.1.0.8, topkg-care.1.0.8
  packages/topkg-care/topkg-care.1.0.8/opam
  packages/topkg/topkg.1.0.8/opam
Labels: consider for merge

#27611 Package dynamic_gc.0.1.0
  packages/dynamic_gc/dynamic_gc.0.1.0/opam
Labels: consider for merge

#27605 Update of the opam file for ACGtk 2.1.0.
  packages/acgtk/acgtk.2.1.0/opam
Labels: consider for merge

#27622 Constrain failing packages for #27602.
  packages/current/current.0.4/opam
  packages/current/current.0.5/opam
  packages/git/git.3.0.0/opam
  packages/git/git.3.1.0/opam
  packages/git/git.3.1.1/opam
  packages/index/index.1.6.1/opam
  packages/index/index.1.6.2/opam
Labels: consider for merge

#27629 More constraints for failing packages for #27602
  packages/acgtk/acgtk.1.5.0/opam
  packages/acgtk/acgtk.2.0.0/opam
  packages/current/current.0.2/opam
  packages/current/current.0.3/opam
  packages/ocluster/ocluster.0.1/opam
Labels: consider for merge

#27625 Add missing ppxlib.0.36.0 upper bounds
  packages/elpi/elpi.1.11.0/opam
  packages/elpi/elpi.1.11.1/opam
  packages/elpi/elpi.1.11.2/opam
  packages/elpi/elpi.1.13.2/opam
  packages/elpi/elpi.1.13.4/opam
  packages/elpi/elpi.1.13.5/opam
  packages/elpi/elpi.1.13.6/opam
  packages/elpi/elpi.1.13.7/opam
  packages/elpi/elpi.1.13.8/opam
  packages/elpi/elpi.1.14.0/opam
  packages/elpi/elpi.1.14.1/opam
  packages/elpi/elpi.1.14.3/opam
  packages/elpi/elpi.1.15.0/opam
  packages/elpi/elpi.1.15.2/opam
  packages/elpi/elpi.1.16.1/opam
  packages/elpi/elpi.1.16.10/opam
  packages/elpi/elpi.1.16.3/opam
  packages/elpi/elpi.1.16.4/opam
  packages/elpi/elpi.1.16.5/opam
  packages/elpi/elpi.1.16.7/opam
  packages/elpi/elpi.1.16.8/opam
  packages/elpi/elpi.1.16.9/opam
  packages/elpi/elpi.1.17.0/opam
  packages/elpi/elpi.1.17.3/opam
  packages/elpi/elpi.1.17.4/opam
  packages/elpi/elpi.1.18.0/opam
  packages/elpi/elpi.1.18.1/opam
  packages/elpi/elpi.1.18.2/opam
  packages/elpi/elpi.1.19.0/opam
  packages/elpi/elpi.1.19.1/opam
  packages/elpi/elpi.1.19.2/opam
  packages/elpi/elpi.1.19.3/opam
  packages/elpi/elpi.1.19.4/opam
  packages/elpi/elpi.1.19.5/opam
  packages/elpi/elpi.1.19.6/opam
  packages/elpi/elpi.1.20.0/opam
  packages/ppx_deriving_qcheck/ppx_deriving_qcheck.0.1.0/opam
  packages/ppx_deriving_qcheck/ppx_deriving_qcheck.0.2.0/opam
  packages/ppx_deriving_qcheck/ppx_deriving_qcheck.0.3.0/opam
  packages/ppx_deriving_qcheck/ppx_deriving_qcheck.0.4.0/opam
  packages/ppx_deriving_qcheck/ppx_deriving_qcheck.0.4.1/opam
  packages/ppx_deriving_qcheck/ppx_deriving_qcheck.0.5/opam
  packages/ppx_deriving_qcheck/ppx_deriving_qcheck.0.6/opam
  packages/ppx_rapper/ppx_rapper.0.9.2/opam
  packages/ppx_rapper/ppx_rapper.1.0.1/opam
  packages/ppx_rapper/ppx_rapper.1.0.2/opam
  packages/ppx_rapper/ppx_rapper.1.1.0/opam
  packages/ppx_rapper/ppx_rapper.1.1.1/opam
  packages/ppx_rapper/ppx_rapper.1.2.0/opam
  packages/ppx_rapper/ppx_rapper.2.0.0/opam
  packages/ppx_rapper/ppx_rapper.3.0.0/opam
  packages/ppx_rapper/ppx_rapper.3.1.0/opam
Labels: consider for merge

#27619 Package lem.2025-03-13
  packages/lem/lem.2025-03-13/opam
Labels: consider for merge

#27618 ocamlfind 1.9.5 is not compatible with ocaml 5 (while 1.9.8 is fine)
  packages/ocamlfind/ocamlfind.1.9.5/opam
Labels: consider for merge

#27602 Add: logs.0.8.0
  packages/logs/logs.0.8.0/opam
Labels: consider for merge

#27617 [new release] alcotest (5 packages) (1.9.0)
  packages/alcotest-async/alcotest-async.1.9.0/opam
  packages/alcotest-js/alcotest-js.1.9.0/opam
  packages/alcotest-lwt/alcotest-lwt.1.9.0/opam
  packages/alcotest-mirage/alcotest-mirage.1.9.0/opam
  packages/alcotest/alcotest.1.9.0/opam
Labels: consider for merge

#27513 Release brisk-reconciler.1.0.0~alpha1
  packages/brisk-reconciler/brisk-reconciler.1.0.0~alpha1/opam
Labels: needs opam-repository maintainer action

#27641 [new release] odoc (5 packages) (3.0.0)
  packages/odoc-driver/odoc-driver.3.0.0/opam
  packages/odoc-md/odoc-md.3.0.0/opam
  packages/odoc-parser/odoc-parser.3.0.0/opam
  packages/odoc/odoc.3.0.0/opam
  packages/sherlodoc/sherlodoc.3.0.0/opam
Labels: consider for merge

#27645 Package dtools.0.4.6
  packages/dtools/dtools.0.4.6/opam
Labels: consider for merge

#27639 [new release] codept and codept-lib (0.12.1)
  packages/codept-lib/codept-lib.0.12.1/opam
  packages/codept/codept.0.12.1/opam
Labels: consider for merge

#27614 Rocqide 9.0 release
  packages/rocqide/rocqide.9.0.0/opam
Labels: consider for merge

#27179 [new release] junit (3 packages) (2.2.0)
  packages/junit/junit.2.2.0/opam
  packages/junit_alcotest/junit_alcotest.2.2.0/opam
  packages/junit_ounit/junit_ounit.2.2.0/opam
Labels: needs reporter action

#27651 Package ppx_minidebug.2.1.0
  packages/ppx_minidebug/ppx_minidebug.2.1.0/opam
Labels: consider for merge

#27607 Use `-p` instead of `--release` in Dune builds
  packages/aws-config/aws-config.0.0.1/opam
  packages/frama-c/frama-c.26.0/opam
  packages/frama-c/frama-c.26.0~beta/opam
  packages/frama-c/frama-c.26.1/opam
  packages/frama-c/frama-c.27.0/opam
  packages/frama-c/frama-c.27.0~beta/opam
  packages/frama-c/frama-c.27.1/opam
  packages/frama-c/frama-c.28.0/opam
  packages/frama-c/frama-c.28.0~beta/opam
  packages/frama-c/frama-c.28.1/opam
  packages/frama-c/frama-c.29.0/opam
  packages/frama-c/frama-c.29.0~beta/opam
  packages/frama-c/frama-c.30.0/opam
  packages/frama-c/frama-c.30.0~beta/opam
  packages/opsian/opsian.0.1/opam
Labels: consider for merge

#27670 [new release] yocaml (12 packages) (2.2.0)
  packages/yocaml/yocaml.2.2.0/opam
  packages/yocaml_cmarkit/yocaml_cmarkit.2.2.0/opam
  packages/yocaml_eio/yocaml_eio.2.2.0/opam
  packages/yocaml_git/yocaml_git.2.2.0/opam
  packages/yocaml_jingoo/yocaml_jingoo.2.2.0/opam
  packages/yocaml_mustache/yocaml_mustache.2.2.0/opam
  packages/yocaml_omd/yocaml_omd.2.2.0/opam
  packages/yocaml_otoml/yocaml_otoml.2.2.0/opam
  packages/yocaml_runtime/yocaml_runtime.2.2.0/opam
  packages/yocaml_syndication/yocaml_syndication.2.2.0/opam
  packages/yocaml_unix/yocaml_unix.2.2.0/opam
  packages/yocaml_yaml/yocaml_yaml.2.2.0/opam
Labels: consider for merge

#27658 not-ocamlfind 0.14: windows bugfixes
  packages/frama-clang/frama-clang.0.0.14/opam
  packages/not-ocamlfind/not-ocamlfind.0.14/opam
Labels: consider for merge
