Repository ocaml/opam-repository, pull requests merged in 2025-08, with the labels that each got.

#28233 Adding giflib version v1.0.3 to opam
  packages/giflib/giflib.1.0.3/opam
Labels: needs reporter action

#28300 [new release] miou (0.4.0)
  packages/miou/miou.0.4.0/opam
Labels: consider for merge

#28309 [new release] doi2bib (2 packages) (0.7.7)
  packages/bibfmt/bibfmt.0.7.7/opam
  packages/doi2bib/doi2bib.0.7.7/opam
Labels: consider for merge

#28322 [new release] httpcats (0.1.0)
  packages/httpcats/httpcats.0.1.0/opam
Labels: consider for merge

#28336 [new release] ppx_jsobject_conv (0.21.1)
  packages/ppx_jsobject_conv/ppx_jsobject_conv.0.21.1/opam
Labels: consider for merge

#28361 Set up Dependabot
  .github/dependabot.yml
Labels: dependencies

#28402 Package coq-waterproof.3.0.0+8.17
  packages/coq-waterproof/coq-waterproof.3.0.0+8.17/opam
Labels: consider for merge

#28374 [new release] opam-compiler (0.2.1)
  packages/opam-compiler/opam-compiler.0.2.1/opam
Labels: needs reporter action

#27865 small fix for conf-mariadb.2
  packages/conf-mariadb/conf-mariadb.2/opam
Labels: needs reporter action
