Repository ocaml/opam-repository, pull requests merged in 2025-05, with the labels that each got.

#27837 [new release] ocamlmig (5.3-20250429)
  packages/ocamlmig/ocamlmig.5.3-20250429/opam
Labels: consider for merge

#27844 [new release] spurs (0.1.0)
  packages/spurs/spurs.0.1.0/opam
Labels: consider for merge

#27861 Package smtml.0.7.0
  packages/smtml/smtml.0.7.0/opam
Labels: consider for merge

#27558 ocaml-variants 4.00.1 +mirage+: mark as not maintained
  packages/ocaml-variants/ocaml-variants.4.00.1+mirage-unix/opam
  packages/ocaml-variants/ocaml-variants.4.00.1+mirage-xen/opam
Labels: question

#27522 irmin: extend the x-maintenance-intent
  packages/irmin-http/irmin-http.3.8.0/opam
  packages/irmin-layers/irmin-layers.2.10.2/opam
  packages/irmin-mirage-git/irmin-mirage-git.3.10.0/opam
  packages/irmin-mirage-graphql/irmin-mirage-graphql.3.10.0/opam
  packages/libirmin/libirmin.3.10.0/opam
Labels: question

#27868 Mark iomux unavailable on Windows
  packages/iomux/iomux.0.1/opam
  packages/iomux/iomux.0.2/opam
  packages/iomux/iomux.0.3/opam
Labels: consider for merge

#27768 [new release] bitwuzla-cxx (0.7.0)
  packages/bitwuzla-cxx/bitwuzla-cxx.0.7.0/opam
Labels: consider for merge

#27874 [new release] curl (3 packages) (0.10.0)
  packages/curl/curl.0.10.0/opam
  packages/curl_lwt/curl_lwt.0.10.0/opam
  packages/ocurl/ocurl.transition/opam
Labels: question

#27869 release ledit with fixup for finding camlp-streams
  packages/ledit/ledit.2.07/opam
Labels: consider for merge

#27886 Add upper bounds to pgsolver for Tcsprojects/release tcslib v0.5
  packages/pgsolver/pgsolver.4.1/opam
  packages/pgsolver/pgsolver.4.3/opam
Labels: consider for merge

#27906 Package bdd.0.5
  packages/bdd/bdd.0.5/opam
Labels: consider for merge

#27910 [new release] dune (15 packages) (3.19.0)
  packages/chrome-trace/chrome-trace.3.19.0/opam
  packages/dune-action-plugin/dune-action-plugin.3.19.0/opam
  packages/dune-build-info/dune-build-info.3.19.0/opam
  packages/dune-configurator/dune-configurator.3.19.0/opam
  packages/dune-glob/dune-glob.3.19.0/opam
  packages/dune-private-libs/dune-private-libs.3.19.0/opam
  packages/dune-rpc-lwt/dune-rpc-lwt.3.19.0/opam
  packages/dune-rpc/dune-rpc.3.19.0/opam
  packages/dune-site/dune-site.3.19.0/opam
  packages/dune/dune.3.19.0/opam
  packages/dyn/dyn.3.19.0/opam
  packages/ocamlc-loc/ocamlc-loc.3.19.0/opam
  packages/ordering/ordering.3.19.0/opam
  packages/stdune/stdune.3.19.0/opam
  packages/xdg/xdg.3.19.0/opam
Labels: consider for merge

#27918 Package binary_tree.1.0
  packages/binary_tree/binary_tree.1.0/opam
Labels: needs reporter action

#27917 Extend conf-gnomecanvas support to MinGW and MSys2
  packages/conf-gnomecanvas/conf-gnomecanvas.2/opam
  packages/conf-mingw-w64-gnomecanvas-i686/conf-mingw-w64-gnomecanvas-i686.1/opam
  packages/conf-mingw-w64-gnomecanvas-x86_64/conf-mingw-w64-gnomecanvas-x86_64.1/opam
Labels: consider for merge

#27923 2 packages from mbarbin/fpath-base at 0.3.1
  packages/fpath-base/fpath-base.0.3.1/opam
  packages/fpath-sexp0/fpath-sexp0.0.3.1/opam
Labels: consider for merge

#27924 Package pplumbing.0.0.14
  packages/pplumbing/pplumbing.0.0.14/opam
Labels: consider for merge

#27926 8 packages from savonet/ocaml-ffmpeg at 1.2.5
  packages/ffmpeg-av/ffmpeg-av.1.2.5/opam
  packages/ffmpeg-avcodec/ffmpeg-avcodec.1.2.5/opam
  packages/ffmpeg-avdevice/ffmpeg-avdevice.1.2.5/opam
  packages/ffmpeg-avfilter/ffmpeg-avfilter.1.2.5/opam
  packages/ffmpeg-avutil/ffmpeg-avutil.1.2.5/opam
  packages/ffmpeg-swresample/ffmpeg-swresample.1.2.5/opam
  packages/ffmpeg-swscale/ffmpeg-swscale.1.2.5/opam
  packages/ffmpeg/ffmpeg.1.2.5/opam
Labels: consider for merge

#27921 [new release] yocaml (12 packages) (2.3.0)
  packages/yocaml/yocaml.2.3.0/opam
  packages/yocaml_cmarkit/yocaml_cmarkit.2.3.0/opam
  packages/yocaml_eio/yocaml_eio.2.3.0/opam
  packages/yocaml_git/yocaml_git.2.3.0/opam
  packages/yocaml_jingoo/yocaml_jingoo.2.3.0/opam
  packages/yocaml_mustache/yocaml_mustache.2.3.0/opam
  packages/yocaml_omd/yocaml_omd.2.3.0/opam
  packages/yocaml_otoml/yocaml_otoml.2.3.0/opam
  packages/yocaml_runtime/yocaml_runtime.2.3.0/opam
  packages/yocaml_syndication/yocaml_syndication.2.3.0/opam
  packages/yocaml_unix/yocaml_unix.2.3.0/opam
  packages/yocaml_yaml/yocaml_yaml.2.3.0/opam
Labels: consider for merge

#27867 Preview release of ppxlib.0.37.0 with 5.4 compat
  packages/ppxlib/ppxlib.0.37.0~5.4preview/opam
Labels: priority for next OCaml release

#27931 Add conf-qemu-img
  packages/conf-qemu-img/conf-qemu-img.1/opam
Labels: consider for merge
