Repository ocaml/opam-repository, pull requests merged in 2025-10, with the labels that each got.

#28567 Bug correction in dokeysto.4.0.2 impacting three packages
  packages/dokeysto/dokeysto.4.0.2/opam
  packages/dokeysto_camltc/dokeysto_camltc.4.0.2/opam
  packages/dokeysto_lz4/dokeysto_lz4.4.0.2/opam
Labels: consider for merge

#28624 [new release] icalendar (0.1.12)
  packages/icalendar/icalendar.0.1.12/opam
Labels: consider for merge

#28631 [new release] unisim_archisec (0.0.13)
  packages/unisim_archisec/unisim_archisec.0.0.13/opam
Labels: consider for merge

#28647 [new release] primavera (1.0.0)
  packages/primavera/primavera.1.0.0/opam
Labels: consider for merge

#28663 ppxlib 0.36.{0,1} needs avoid-version
  packages/ppxlib/ppxlib.0.36.0/opam
  packages/ppxlib/ppxlib.0.36.2/opam
Labels: consider for merge

#28659 Package camlp4.5.4
  packages/camlp4/camlp4.5.4/opam
Labels: priority for next OCaml release

#28664 3 packages from ocaml-multicore/multicoretests at 0.10
  packages/qcheck-lin/qcheck-lin.0.10/opam
  packages/qcheck-multicoretests-util/qcheck-multicoretests-util.0.10/opam
  packages/qcheck-stm/qcheck-stm.0.10/opam
Labels: consider for merge

#28642 synchronizer.0.1
  packages/synchronizer/synchronizer.0.1/opam
Labels: consider for merge

#28662 Package sedlex.3.7
  packages/sedlex/sedlex.3.7/opam
Labels: question

#28661 fstar.2025.10.06
  packages/fstar/fstar.2025.10.06/opam
Labels: question
